### ISSUE TITLE
digest use case: resume upload

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1005]
## I wish

to use `Digest` to implement resumeable uploads.

## Note

See https://cloud.google.com/storage/docs/hashes-etags:

- approach similar to digest 1

>  The checksum(s) returned when downloading data from Cloud Storage cover the complete object 
> content. Thus, if you specify a request range there's no way to detect data corruption for that byte 
> range alone. 

- approach similar to digest 2

> To protect against data corruption, Cloud Storage supports two types of hashes: CRC32C and 
> MD5 (described below). Google recommends that customers use CRC32C for all cases,

**Comment by LPardue** [comment]
I don't understand exactly what this issue is trying to track. In more human-readable terms are you suggesting that we make an editorial change to add a resumable upload use case

**Comment by ioggstream** [comment]
I wanted to track this use-case to see if digest can cover it. No changes are expected to the spec for now.

**Comment by LPardue** [comment]
Thanks for clarifying. We should be mindful of feature creep in this spec, for instance there is a difference in documenting how Digest **is used** today for a use case vs attempting to apply Digest to this use case that is satisfied already by other approaches.

That said, a survey of present approaches may be useful to help determine if/what the Digest header specification might chose to mention. So to that end, in the context of Google Cloud Storage, a better link would seem to be https://cloud.google.com/storage/docs/resumable-uploads 

> In addition, we recommend that you request an integrity check of the final uploaded object to be sure that it matches the source file. You can do this by calculating the MD5 digest of the source file and adding it to the Content-MD5 request header. Checking the integrity of the uploaded file is particularly important if you are uploading a large file over a long period of time, because there is an increased likelihood of the source file being modified over the course of the upload operation.

Similarly, AWS provides guidance such as 
 https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/

> To verify the MD5 checksum value of the object during its upload to Amazon S3, use the AWS Command Line Interface (AWS CLI) command aws s3api put-object and include the --content-md5 option. For the value of --content-md5, enter the base64-encoded MD5 checksum value that you calculated, similar to the following:
> 
> aws s3api put-object --bucket awsexamplebucket --key awsexampleobject.txt --body awsexampleobjectpath --content-md5 examplemd5value1234567==
> 
> Optionally, if you want to store the MD5 checksum value as metadata (custom HTTP header), you can also add the --metadata option in the command, similar to the following:
> 
> aws s3api put-object --bucket awsexamplebucket --key awsexampleobject.txt --body awsexampleobjectpath --content-md5 examplemd5value1234567== --metadata md5checksum=examplemd5value1234567==
> 
> If the checksum that Amazon S3 calculates during the upload doesn't match the value that you entered for --content-md5, Amazon S3 won't store the object. Instead, you receive an error message in response.

There is also the `tus` protocol which is described as a _"protocol provides a mechanism for resumable file uploads via HTTP/1.1 (RFC 7230) and HTTP/2 (RFC 7540)."_. For uploads it says  
https://tus.io/protocols/resumable-upload.html#checksum

> A Client MAY include the Upload-Checksum header in a PATCH request. Once the entire request has been received, the Server MUST verify the uploaded chunk against the provided checksum using the specified algorithm. Depending on the result the Server MAY respond with one of the following status code: 1) 400 Bad Request if the checksum algorithm is not supported by the server, 2) 460 Checksum Mismatch if the checksums mismatch or 3) 204 No Content if the checksums match and the processing of the data succeeded. In the first two cases the uploaded chunk MUST be discarded, and the upload and its offset MUST NOT be updated.
> 
> The Server MUST support at least the SHA1 checksum algorithm identified by sha1. The names of the checksum algorithms MUST only consist of ASCII characters with the modification that uppercase characters are excluded.
> 
> The Tus-Checksum-Algorithm header MUST be included in the response to an OPTIONS request.
> 
> If the hash cannot be calculated at the beginning of the upload, it MAY be included as a trailer. If the Server can handle trailers, this behavior MUST be announced by adding checksum-trailer to the Tus-Extension header. Trailers, also known as trailing headers, are headers which are sent after the request’s body has been transmitted already. Following RFC 7230 they MUST be announced using the Trailer header and are only allowed in chunked transfers.

**Comment by ioggstream** [comment]
Thanks @LPardue for the survey :D !

**Comment by ioggstream** [comment]
About feature creep:
- yes, we should not add features;
- but we must investigate how legitimate usage of digest can improve existing use cases.

This:
- will avoid spec proliferation;
- avoid usage of deprecated content-md5;

For example, the usage of content-md5 by CSP like goog and amz may be mitigated by their knowledge and architecture; it may not be the same for a generic implementor ( that's why http deprecated content-md5).

Hth, R

**Comment by ioggstream** [comment]
IIUC this is not the semantics of content-md5. Am I wrong? @LPardue 

> we recommend that you request an integrity check of the final uploaded object to be sure that it matches the source file. You can do this [..] adding it to the Content-MD5 request header

**Comment by LPardue** [comment]
Let's try to decide if we want to pursue this or not. @mnot my concern here is that we don't have IETF specs to link to wrt to resumable uploads, I'm wary about speculating on the applicability of digest to a use case that doesn't seem to use it. Someone could always follow up with a separate document that attempts to do this work.

**Comment by ioggstream** [comment]
I agree this shouldn't be a show stopper, and I can prepare a new I-D on using Digest for resuming upload if you suggest to do so.

**Comment by ioggstream** [comment]
I think the current wording allows developing this in a new I-D. Closing.
