### ISSUE TITLE
[SH] dictionary with default True value doesn't accept parameters

### ISSUE THREAD

**Issue by phluid61** [httpwg/http-extensions#1007]
In section **4.2.2 Parsing a Dictionary** step 2.4.2 initialises an empty set of parameters, but never parses any from input_string.  This corresponds with the ABNF rule `dict-member = member-name [ "=" member-value ]` where `member-value` includes the parameters.

This conflicts with a [recently-added test](https://github.com/httpwg/structured-header-tests/pull/24/files#diff-6976ba7e46d6978bde81530178302e1fR112-R118).

Related to #992

**Comment by mnot** [comment]
Nope, I just has a moment. Fixed.
