### ISSUE TITLE
Consider using "User Agent" and "Origin Server" instead of "end client"

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1016]
## I suggest

to replace the terms client and server with user-agent and origin server https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#operation when appropriate.

## because

IIUC  priority is an end-to-end header. 

## Note

I can provide a PR if this issue is correct.

**Comment by tfpauly** [comment]
Can we close this issue?

**Comment by ioggstream** [comment]
@tfpauly it's up to the authors to me.

**Comment by LPardue** [comment]
I've not seen much interest in doing this so I'm going to close with no action. If the topic comes up again,we can reopen this and say that Roberto was right all along.
