### ISSUE TITLE
451 Editorial Feedback

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#102]
From Julian.

### 1

> Feedback should occur on the ietf-http-wg@w3.org mailing list.

(This should go in the boilerplate, not the actual spec text; and yes, the RFC production center will catch it)

### 2

The example should use the link header field.

### 3

> 5.  Security Considerations

1) We don't need a nested subsection here. 
2) Avoid use of lowercased BCP14 terms...

### 4

We'll need the IANA considerations for the new link relation as well.

**Comment by timbray** [comment]
#1 I'll leave for rfc-ed
#2 added in -03
#3.1/2 added in -03
#4 added in -03
