### ISSUE TITLE
Deprecate sha-1

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1020]
## I expect

SHA-1 to be deprecated in `digest-headers` because of https://sha-mbles.github.io/

## Instead

It's NOT RECOMMENDED

## Notes

When we decided to NOT RECOMMEND sha-1, we knew that collisions were possible. 
Now researchers states that

```
We have computed the very first chosen-prefix collision for SHA-1. In a nutshell, this means a complete and practical break of the SHA-1 hash function, with dangerous practical implications if you are still using this hash function. To put it in another way: all attacks that are practical on MD5 are now also practical on SHA-1
```

The latest paper is here https://eprint.iacr.org/2020/014.pdf

**Comment by LPardue** [comment]
Some feedback I've had is that we should deprecate. I'd like to hear from the WG if there is any pushback to doing so.

**Comment by ioggstream** [comment]
I'm in favour of deprecation.

**Comment by LPardue** [comment]
3GPP TLS Profile 6 also makes SHA-1 a "must not" for TLS 1.2 [1]. 

[1] - https://github.com/EricssonResearch/CBOR-certificates/blob/master/3GPP%20TLS%20Profile%206%20march%202020.pdf
