### ISSUE TITLE
Coalescing intermediaries and fairness

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1022]
In [Section 7.1](https://httpwg.org/http-extensions/draft-ietf-httpbis-priority.html#coalescing-intermediaries) there is a rather firm recommendation to erase priorities at servers that are served by coalescing intermediaries:

> the server SHOULD prioritize the response as if it was assigned the priority of u=1, i=?1 (i.e. round-robin) 

This seems wrong to me.  The Priority header field provides information about what the User Agent thinks of priority.  This might be adjusted by intermediaries on the path, and it might not be globally consistent, but that does not mean the information should be discarded.  Instead, I would prefer that we say that when an intermediary coalesces requests from multiple clients, servers need to be aware of that and account for that in their processing.

The remainder of this text is fine in the sense that it identifies information the server can use to more fairly allocate resources to different requests, but - again - this is just information the server uses when making prioritization decisions.

The model we operate on should not assume be that Priority is an instruction to the server, but that it provides the server (or intermediary) clues about how it might decide to allocate resources.

**Comment by LPardue** [comment]
No one responded to this for a while, sorry. The text is mostly untouched but I did change the example to just `u=1,i`.

My read of this today, I'm concerned that the requirement is a bit specific. It's not clear if a server applying this would also discard any additional priority parameters. I don't know if @martinthomson's original point was along those lines or not, but I'll try to make a PR to address what I think needs fixing
