### ISSUE TITLE
"i=?1" -> "i"

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1025]
Changes in structured headers means that boolean parameter values are reduced to their parameter name:

> Parameters whose value is Boolean true MUST omit that value when serialised. 

-- https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#param

**Comment by ioggstream** [comment]
Q: should this be labeled `header-structure` ?

**Comment by LPardue** [comment]
No, this issue addresses the minor editorial problem that needs fixing in the priorities spec

https://tools.ietf.org/html/draft-kazuho-httpbis-priority-04#section-3.2
