### ISSUE TITLE
"Legal Demand"

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#103]
Amos raises:

"for use when a server operator has a received a legal demand to deny
access to a resource"

This is a lot more restrictive than what I understood was being agreed
to. This phrasing implies that a specific-URL DMCA type notice is
required before the status may be used.

It would be a lot more reasonable to also allow the status to be used
when a blanket law requirement was levelled on the operator. For example
schools following laws on porn fitering, or national level restrictions
on categories of traffic. In cases like these operators dont receive
per-resource demands, they often receive a one-off notice "law X applies
to you" and are then expected to censor proactively to the best of their
ability and face the court on overlooked URLs.

Probably this can be resolved with s/legal demand/legal requirement/.

There are other "legal demand" phrase uses elsewhere to keep in sync.

If "legal demand" is being used with a meaning other than a specific
warrant DMCA takedown etc. Then that definitely needs to be explained.

**Comment by mnot** [comment]
Suggestion from Ted:

"for use whenever a server operator has received a legal demand to deny access to a resource or to a set of resources which includes the requested resource."

**Comment by mnot** [comment]
Discussed on list, accept Ted's proposal.

**Comment by timbray** [comment]
Added in -03
