### ISSUE TITLE
Remove "MUST store last-access-time" for each cookie?

### ISSUE THREAD

**Issue by bagder** [httpwg/http-extensions#1032]
The original RFC 6265 as well as the current draft (-04) says that a user-agent **MUST** store last-access-time and then goes on to explain how to store a cookie... but never says how that access time would even be used.

I find no argument for saying it MUST be used. We can implement fully compliant cookie user-agents without storing that information.

**Comment by mikewest** [comment]
We use the time of last access in the eviction algorithm (way at the bottom of [Section 5.4](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-04#section-5.4) ("If two cookies have the same removal priority, the user agent MUST evict the cookie with the earliest last-access date first."; see e.g. https://cs.chromium.org/chromium/src/net/cookies/cookie_monster.cc?rcl=cc550e3a16febcdf45a861071ac901666298f579&l=1602), which seems pretty reasonable to want to do.

Would you suggest we drop that requirement as well? If so, which ordering would we use and why?

**Comment by bagder** [comment]
Ah, I missed that since it's not "last-access-time" there, it is "last-access date". I figured it was odd...

No, I don't think it should be removed. Maybe it could be updated to use the same name in section 5.4?

**Comment by johnwilander** [comment]
That’s a good enhancement. You won’t be the only one doing a text search. But we should also have an explicit reference in my opinion.
