### ISSUE TITLE
6265bis: "site.example" is not under "com" PSL!

### ISSUE THREAD

**Issue by bagder** [httpwg/http-extensions#1034]
Section 2.3 and section 5.4, step 5 say: 

> For example, "site.example"'s public suffix is "com".

(mistake from #1017 )

Also mentioned on the list: https://lists.w3.org/Archives/Public/ietf-http-wg/2020JanMar/0022.html

**Comment by mikewest** [comment]
Fixed in https://github.com/httpwg/http-extensions/commit/e170e90e7db369e2080166c4fbd5496eb2a67f68, thanks!
