### ISSUE TITLE
Support "Or" operator

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#104]
See: 
  https://github.com/mnot/I-D/issues/21

**Comment by martinthomson** [comment]
My suggestion is to have OR semantics for key-values of the same type, but AND for key-values of different types.  That would solve most of the sorts of problem that Ilya identified without a need to create operators, which complicate the grammar and implementation considerably.

So `s=a;s=b` means "a" or "b", but `s=c;m=d` means "c" and "d".

cc @igrigorik

**Comment by mnot** [comment]
@igrigorik please also have a look at discussion in #108. We need to figure out whether this hits the use cases, would appreciate your views.

**Comment by mnot** [comment]
Hey @igrigorik - the problem with defining an operator like that is that it pushes a LOT of complexity into the algorithm and its implementation. Right now, each parameter results in a string that can be written into the secondary cache key, so its processing is very simple. 

It's also not clear how some parameters would combine; e.g., what does `partition=20:30 and match=foo` mean? 

It would really help if we had some **concrete** examples of what people would want to do with OR.

**Comment by mnot** [comment]
Bleh. I meant `partition=20:30 OR match=foo`.

I'm starting to suspect that this is primarily about `substr`; I can totally see the use cases there (in UA). For `param`, the major use case is cookies, and like you say, the server can emit those to suit. For `match`, the major use case is "gzip", so I don't see strong cases here (yet). For `div` and `partition`, OR doesn't make any sense at all.

**Comment by igrigorik** [comment]
> I'm starting to suspect that this is primarily about substr. 

*nod*. I think it makes sense to scope this discussion substr in particular.

**Comment by mnot** [comment]
OK. If that's the case, does something like

> `Key: User-Agent;substr=mobi|android`

do the trick?

**Comment by igrigorik** [comment]
Yeah.. Except, what if I have a `|` in my substring? :P

**Comment by mnot** [comment]
Well, we can either escape it, or we can say that we don't think it's likely that the headers that Key will be targeting will contain that character.

I like the latter; IME developers often don't bother to implement escaping in performance-critical code.

**Comment by yoavweiss** [comment]
One CH use case for OR would be "serving low res version for both 1x as well as Save-Data users", which would potentially involve `partition` ("anything below 1.2x") on `DPR` as well as `match` on `Save-Data`.

**Comment by mnot** [comment]
> `Key: DPR;partition=1.2, Save-Data;match=1`

would create four potential cache entries:

1. `DPR` < 1.2, `Save-Data` = 1
2. `DPR` < 1.2, `Save-Data` != 1
3. `DPR` > 1.2, `Save-Data` = 1
4. `DPR` > 1.2, `Save-Data` != 1

It sounds like you want to collapse 1,2 and 3 into one cache entry, correct?

**Comment by yoavweiss** [comment]
That is correct

**Comment by mnot** [comment]
Hm. It seems like that's going to be hard to do, because `partition` isn't a boolean; it can create an arbitrary number of cache entries. This is the problem I mentioned above, e.g.,

> `Key: DPR;partition=1:2:3, Save-Data;match=1`

Even if we did have something that evaluated to truth (e.g., `lessthan`, `greaterthan`), we'd have to pretty fundamentally change the parsing model for the header to something more complex, and there's been good implementer feedback about the simplicity of what we have now.

So, I wonder if this is nice-to-have, or critical-for-success? Obviously, it will result in more cache misses, but does that make it unusable / uninteresting?

Also, if it's critical, is that for this specific use case, or as a general facility?

**Comment by yoavweiss** [comment]
I'd put this in the "nice-to-have" bucket. I don't think this is critical for success, and agree that it adds complexity.

**Comment by igrigorik** [comment]
Hmm, not sure if this is a deal breaker, but it's not a great outcome.. In effect, we're discouraging folks from reporting granular hints. With CH our goal is to get enable the UA/app to advertise any and all relevant hints to the server, each via its own header. However, with the model we have here, each and every key expands the cache space, with no ability to collapse it -- this, in effect, discourages use and deployment of new hints.

**Comment by mnot** [comment]
I think that's correct, _when the hints aren't completely orthogonal_. We see the problem above because there's overlap between the effect of the semantics of `DPR` and `Save-Data`.

Are there other examples where that might happen, or is it a one-off?

**Comment by igrigorik** [comment]
In a world with ServiceWorkers, where it's easy to mint new headers based on various UA-reported and app/user specific preference, I don't think it's a one-off. 

That said, I guess one solution to this is to have the client collapse some of those headers that interact with each other into a unique preference/header, or massagge reported values to effectively achieve the same grouping -- e.g. if Save-Data is present then override DPR header to always report 1.x, etc.

With that in mind, perhaps what we have here is sufficient?

**Comment by mnot** [comment]
Thinking about this a bit more. We could introduce limited operators. E.g., we could specify when another header's portion of the key should be discarded.

Taking the example above and adding the calculated secondary cache key:

`Key: DPR;partition=1.2, Save-Data;match=1`

* DPR < 1.2, Save-Data = 1	`0:1`
* DPR < 1.2, Save-Data != 1	`0:0`
* DPR > 1.2, Save-Data = 1	`1:1`
* DPR > 1.2, Save-Data != 1	`1:0`

We could at least make 1 and three equivalent like this:

`Key: DPR;partition=1.2, Save-Data;match=1;discard=1:DPR`

* DPR < 1.2, Save-Data = 1	`:1`
* DPR < 1.2, Save-Data != 1	`0:0`
* DPR > 1.2, Save-Data = 1	`:1`
* DPR > 1.2, Save-Data != 1	`1:0`

because `discard=1:DPR` tells us to discard the `DPR` portion of the key if `Save-Data`'s post-processing value is `1`.

This would need some massaging, of course, and it wouldn't be able to express all of the interdependencies between headers (notice that the second case is still a distinct cache entry). However, it would help avoid a complete combinetric cache explosion.

I'm torn as to whether this is a good idea; Ilya could be right that in complex situations, we'll just fiddle request header semantics and/or synthesise new headers with ServiceWorker (although it'd be a great pity to use SW just for that, I think). 

WDYT?

**Comment by yoavweiss** [comment]
> DPR < 1.2, Save-Data = 1 :1
> DPR < 1.2, Save-Data != 1 0:0
> DPR > 1.2, Save-Data = 1 :1
> DPR > 1.2, Save-Data != 1 1:0

That's better than before, but I suspect that for this use case the desired outcome is:
* DPR < 1.2, Save-Data = 1: 1x
* DPR < 1.2, Save-Data != 1: 1x
* DPR > 1.2, Save-Data = 1: 1x
* DPR > 1.2, Save-Data != 1: 2x

So, adding `discard` improves things and reduces unnecessary cache explosion, but doesn't eliminate it.

**Comment by mnot** [comment]
Yep. I don't see a reasonable way to get to that without starting over from scratch, and making it significantly more complex. Happy if someone else can, though.

**Comment by yoavweiss** [comment]
At least for this particular scenario, the browser is not likely to change DPR values, so the cache verbosity is likely to be at the cache servers. 

Cache servers could avoid storing multiple instances of the same resource by having a 2-step lookup, where lookup-name=>content-hash=>resource-contents so that multiple lookup-names can lead to the same resource-contents if they have the same content-hash.

So, if this is the only example we can come up with, maybe we should punt this issue until we see more usage in the wild and/or come up with more use cases?

**Comment by igrigorik** [comment]
> So, if this is the only example we can come up with, maybe we should punt this issue until we see more usage in the wild and/or come up with more use cases?

That's what I'm leaning towards as well. While not without own set of problems, I think folks can also combine these things into own headers via SW... see https://github.com/httpwg/http-extensions/issues/104#issuecomment-162656089.

**Comment by mnot** [comment]
That sounds reasonable to me, but I want to point out that if we punt on it and want to have another crack, we'll probably need to use another header name.

**Comment by igrigorik** [comment]
Yep. Let's cross that bridge when we get there.

**Comment by mnot** [comment]
Closing with no action (yet).

**Comment by igrigorik** [comment]
@mnot in https://github.com/httpwg/http-extensions/issues/104#issuecomment-187447282, I thought we were referring to the case of "orthogonal hints" (https://github.com/httpwg/http-extensions/issues/104#issuecomment-161842062). FWIW, I do think the earlier suggestion of substr (in https://github.com/httpwg/http-extensions/issues/104#issuecomment-157212831) is something we should support, as I've heard many requests for this -- e.g. the user-agent case, cookies, etc. That said, perhaps we should open a separate bug for that?
