### ISSUE TITLE
Decimal rounding

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1043]
... still isn't right, as Kari noticed. E.g., a value of `1.9998` won't get rounded to `2.0`.

**Comment by phluid61** [comment]
Step 1 of all serialisation algorithms could be related to sanitising/casting/failing-on noncanonical data.

1. Turn your random number into a Decimal, including rounding to three digits.
2. Fail if it's `>= 1e13` or `<= -1e13`
3. no worries from here on

Actually, Key, Integer, String, Token, Byte Sequence, and Boolean already do this, so Decimal is the only scalar type that doesn't.

**Comment by clelland** [comment]
With the current algorithm, if it is allowed as input, -0.0004 will get serialized as `-0.0`, rather than `0.0`.
#1044 corrects that as well.
