### ISSUE TITLE
Bad link in 6265bis samesite enforcement section

### ISSUE THREAD

**Issue by sbingler** [httpwg/http-extensions#1046]
In https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-04#section-5.3.7.1 under sub heading # 1 there is a paragraph, "Attackers can still pop up new windows or trigger...", which references section 2.1 for more information on that topic. However section 2.1 is "Conformance Criteria" so that doesn't seem the intended target.

**Comment by mikewest** [comment]
Thanks!
