### ISSUE TITLE
Policy for Key parameter registry

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#106]
See:
  https://github.com/mnot/I-D/issues/130

**Comment by mnot** [comment]
Random thoughts:

I know we usually try to keep the barrier low, but OTOH lots of uncoordinated extensions here means that cache hit rates could suffer (because unrecognised parameters means the entire header being keyed falls back to Vary behaviour).

So, IETF Review?

**Comment by martinthomson** [comment]
Standards Action even.

**Comment by mnot** [comment]
SGTM. Will confirm on list.

**Comment by mnot** [comment]
I think IETF Review is sufficient. Its purpose is "that the document and proposed assignment will be reviewed by the IESG and appropriate IETF WGs (or experts, if suitable working groups no longer exist) to ensure that the proposed assignment will not negatively impact interoperability or otherwise extend IETF protocols in an inappropriate or damaging manner."

... which sounds about right.
