### ISSUE TITLE
Binary delimiter (again)

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1067]
When preparing a talk the other night, I had an example like this:

~~~
Example-BinaryHdr: :cHJldGVuZCB0aGlzIGmFyeSBjb250ZW50Lg==:
~~~

... which made me wince a bit, since the `:` is used both as a delimiter between the field name and field line value, and to denote the start of binary content. We don't have an example like this in the spec, so it was the first time I saw it "for real."

It's syntactically valid in HTTP, and I don't think there are any security or interoperability issues, but I wanted to make sure folks were comfortable with this -- especially since someone came up right after the talk and pointed out the same thing :-/

If we changed this, I think a reasonable replacement would be `|`; e.g.,

~~~
Example-BinaryHdr: |cHJldGVuZCB0aGlzIGmFyeSBjb250ZW50Lg==|
~~~

What do folks think -- is this worth changing at this late stage?

Pinging @phluid61 @annevk and @clelland specifically.

**Comment by phluid61** [comment]
I'd love to see it in a H2 pseudo-header some time: `:path: :L2Zvby9iYXI=:`

At this point I think it's aesthetic. `:`, `|`, `$`, pretty sure any of them would work. Just depends what's easier on the eyes.  But I would suggest that once it's settled here, it's settled for good.

**Comment by evert** [comment]
I believe that most people interact with HTTP these days, *not* seeing headers like this. For the most part they'll see them through libraries to read/write them or they use GUI's where they are formatted as a table... so I *think* it doesn't really matter, but ymmv

**Comment by annevk** [comment]
I think it's fine for the "legacy" (currently also only, but hey) serialization. And yeah, most APIs deal with header names and values separately so it's not a big deal.

**Comment by mnot** [comment]
I'm not hearing folks being too concerned; closing with no action.

**Comment by clelland** [comment]
Agreed that this is probably fine, though its hard to say what older proxy servers will choke on. That said, colons appear everywhere in headers already, so I don't imagine any interop issues.
