### ISSUE TITLE
Default dictionary value with parameters

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1083]
Julian asked in e-mail why we can't have a dictionary with a default True value that is parameterised:

~~~
Example-Field: ;param=on-default-boolean

Parameter values are comparatively simpler, because they can't have any further substructure.

I don't quite get the example. In the spec I see:

 Example-DictHeader: a=?0, b, c=?1; foo=bar

If this would be instead:

 Example-DictHeader: a=?0, b, c; foo=bar

...what would break?
~~~

**Comment by mnot** [comment]
I think we could replace:

~~~
   3. Otherwise:
      1. Let value be Boolean true.
      2. Let parameters be an empty, ordered map.
      3. Let member be the tuple (value, parameters).
~~~

With:

~~~
   3. Otherwise:
      1. Let value be Boolean true.
      2. Let parameters be the result of running Parsing Parameters {{parse-param}} with input_string.
      3. Let member be the tuple (value, parameters).
~~~

**Comment by mnot** [comment]
@clelland @phluid61 @bsdphk thoughts?

**Comment by clelland** [comment]
Example-Field: ;param=on-default-boolean

Is this a dictionary? What is the key here? (I see that the value is supposed to be implicit true, but I'm not grokking the implied syntax)

If I ignore that (assuming I've misinterpreted something), I like the idea of allowing implicit True.

The serialization algorithm needs a bit more surgery to support this as the canonical form, probably replacing:

```
3. If member_value is not Boolean true or parameters is not empty:
   1. Append "=" to output.
      2. If member_value is an array, append the result of running Serialising an Inner List ({{ser-innerlist}}) with (member_value, parameters) to output.
      3. Otherwise, append the result of running Serializing an Item ({{ser-item}}) with (member_value, parameters) to output.
```

with something like:

```
3. If member_value is an array,
   1. Append "=" to output.
   2. Append the result of running Serialising an Inner List ({{ser-innerlist}}) with (member_value, parameters) to output.
4. Otherwise, if member_value is Boolean True,
    1. Append the result of running Serializing Parameters ({{ser-params}}) with parameters to output.
5. Otherwise,
   1. Append "=" to output.
   2. Append the result of running Serializing an Item ({{ser-item}}) with (member_value, parameters) to output.
```

(unless we also modify Serializing an Item to optionally omit True values, but we can't just do that unconditionally, or else a simple Item header would be empty if True.)

This is the same issue as https://github.com/httpwg/http-extensions/pull/993#discussion_r352982269, I think -- back in December you thought that it would take more drastic changes. If this is everything that it needs, though, it seems reasonable. None of the canonical tests break with this (except for a couple of serialization tests, which just need to be updated), and I don't see any obvious cases that would be parsed incorrectly.

**Comment by mnot** [comment]
> Example-Field: ;param=on-default-boolean

Sorry, that was unrelated, accidentally copied from the email. Ignore.

I'll work up a PR and see how it looks.

**Comment by reschke** [comment]
Awesome.

Now, how about also collapsing the "false" value a bit. So instead of having

    a=?0

just say

    !a

?

**Comment by ioggstream** [comment]
IMHO explicit is better than implicit:
- I am not sure that `!a` is a good choice. 
- I am not even sure that defaulting `a -> a=?1` is a good choice.
