### ISSUE TITLE
Bumping up decimal precision?

### ISSUE THREAD

**Issue by eeeps** [httpwg/http-extensions#1102]
I've been working on [integrating the Content-DPR header into HTML](https://github.com/whatwg/html/pull/5112). One of the [use cases](https://github.com/eeeps/content-dpr-explainer) is for downscaled "placeholder" images that have the same intrinsic size as the full-res image.

However, Content-DPR is spec'd as being either an sh-decimal or sh-integer, and the rounding errors that fall out of sh-decimal's definition (at most 3 fractional digits) end up causing intrinsic size differences > 1px, leading to noticeable visual jumps.

See a rough demo here: https://observablehq.com/@eeeps/content-dpr-placeholders-and-rounding-errors (Chrome-only, as that's the only browser that currently supports the header)

I'm sure this isn't the only use case that could benefit from a digit or two more on the right side of the dot. I'm also sure that this has been discussed, perhaps at length. So:

1. Is there anything that can be done from a structured-headers-spec perspective?
2. If not, is my best option to move to define Content-DPR as a string, with custom decimal parsing, instead?

**Comment by eeeps** [comment]
One more thought on this... even with perfect precision, the intrinsic size of the placeholder will almost always be off in one dimension or the other; the server must choose when setting Content-DPR. I suppose to eliminate layout jumps you'd usually want to lock in the exact height. Hm.

More precision would still be nice!

**Comment by mnot** [comment]
It looks like we need to give you at least two more digits of precision for that use case -- probably three, for future-proofing. 

When we discussed the precision before, the sentiment seemed to be that cases that needed more precise values could use two integers; e.g.,

> Content-DPR: int=1, frac=4432

Would that work for you? I know it's not pretty. If you used a string, you'd have to define your own parser, and we're trying to get folks out of that business.

Otherwise, we could discuss moving some digits from the integer to the fractional component; I think it's a reasonable argument that folks who need very large values probably don't want Decimal, so maybe we could do 10.5 or 9.6 rather than 12.3.

It's pretty late in the day, though; Working Group Last Call has already closed. Not that that's an argument against a change on its own; we just don't want to be polishing this thing in perpetuity... 

@martinthomson @phluid61 @clelland @bsdphk thoughts?

**Comment by martinthomson** [comment]
I have to ask why DPR is the weapon of choice here and not "I want an image of the following dimensions".  I saw the demo, and the round errors are clear, but the demo works fine if you pin down the width and that is already an accepted best practice.

That said, it seems possible that a fractional DPR could occur (2:3 ratios perhaps), which leads to some amount of error.  But in the end, that error will exist unless we effectively allow arbitrary precision.  So I'm of the view that we leave as-is and accept that some cases that need some sophistication will have to find ways to cope.  I don't think DPR makes that grade (though the change in height is definitely awkward.

**Comment by yoavweiss** [comment]
@martinthomson - the scenarios where `Content-DPR` is currently needed are ones where the markup is outside the control of the image optimization service.

A replacement to DPR that would do what you're suggesting while tackling those use cases would be e.g. `Width` and `Height` response headers.

**Comment by clelland** [comment]
The only applications I can think of for large numbers with extra decimal digits are high-precision timestamps for performance reporting, but those are often represented in two components anyway (epoch time in seconds + explicit micro/nanosecond offset), so we could probably borrow a digit or two for this.

Echoing @martinthomson, though, I'm not sure that even four or five digits would be enough to avoid all rounding errors, once you multiply by the arbitrarily large image or screen dimensions. If the underlying data is specifically a ratio, would expressing it as such be possible? A token like `2:3` or `1:40` is an exact representation of the real ratio. Or even `Content-DPR: w=2,h=3`, though a bit more verbose, doesn't require any custom parsing.

**Comment by phluid61** [comment]
The more I think about decimals, the more I convince myself they cause more harm than good.  They're a convenient hammer, if you want to approximate every solution with a nail. And they're so easy to accidentally break (`<?php header('Content-DPR: ' . $x/$y);` leads to occasional silent failure)
