### ISSUE TITLE
Splitting on ','

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#111]
See:
  https://github.com/mnot/I-D/issues/137

**Comment by reschke** [comment]
I'm not sure that this is editorial; it's caused by the lack of standardized header field syntax.

Even if the algorithm pays attention to quoted-string, it's still going to fail if the field syntax uses different quoting mechanisms, such as Link's coded-URL.

**Comment by mnot** [comment]
The original issue was regarding:

> 4. Create "key_list" by splitting "key_value" on "," characters.

... so this is limited to the Key response header itself, not the request headers its value is referring to.

**Comment by reschke** [comment]
That's not working. For instance if fails for "Link". It also requires that the processor understands the ABNF of the header field it processes.
