### ISSUE TITLE
Digest is a message field in the new parlance

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1137]
The phrase "header field" is no longer the accepted form.  The generic form is "message field".

This matters more for Digest, which is a good candidate for a trailer.

**Comment by mnot** [comment]
Just "field" actually.

**Comment by LPardue** [comment]
I'm sorry, I have no idea how to resolve this. Looking at core semantics I still see many instances of header field, so I don't think the solution is a global replace. Are there correct examples I can use to base a PR on?

**Comment by mnot** [comment]
If it's purposefully designed to only be used in a header section, "header field" is fine. If it might appear in trailers, use "field" or "header or trailer field" as appropriate.

**Comment by LPardue** [comment]
ok, does this require a change to the document title?

**Comment by martinthomson** [comment]
I recommend "The HTTP Digest Field"

**Comment by martinthomson** [comment]
Or "HTTP Digests"

**Comment by LPardue** [comment]
and as an aide memior, it seems we'll need to change registration details to overwrite the "digest" defintion that will get migrated to the new table https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.12.4

**Comment by ioggstream** [comment]
> I recommend "The HTTP Digest Field"

Sounds reasonable.
