### ISSUE TITLE
sum and cksum aren't cryptographic either

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1138]
Section 11.2 rightly acknowledges that MD5 and SHA-1 don't provide certain properties.  But `sum` and `cksum` provide even weaker guarantees.  It might pay to reframe this to say that the Digest field can provide cryptographic properties, but only if an algorithm with the desired properties is used.  I would be very happy to see MD5 in the same bucket as `sum`.

**Comment by LPardue** [comment]
Sounds fair, let's see if we can make a PR that captures your phrasing.

**Comment by ioggstream** [comment]
@LPardue PTAL

**Comment by ioggstream** [comment]
closed in favor of #1377
