### ISSUE TITLE
If ADLER32 isn't good enough, why is sum OK?

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1139]
Section 11.3 says that ADLER32 was removed because it fails to detect certain errors.  I realize that `cksum` might be better as it uses the well-regarded CRC32 (or is that CRC32c? I didn't check; the original CRC32 had weaknesses of its own...).  But the 16-bit `sum` is clearly woefully inadequate for anything other than a sanity check.

I'm not going to say that anything other than a good cryptographic algorithm is acceptable here, but I want to understand the rationale for inclusion.  Making `sum` obsolete would be an improvement; we almost get better guarantees from the TCP checksum.  I tend to think that `cksum` obsolete would also be a good choice.  Right now, both are 'standard'.

**Comment by LPardue** [comment]
I think the status quo is a side-effect of the discussion about ADLER32 in https://github.com/httpwg/http-extensions/issues/828. In particular, https://github.com/httpwg/http-extensions/issues/828#issuecomment-517095275

> ADLER32 and CRC32c are well-defined, standardised, algorithms. But there is no spec specifically registering them for use in the HTTP Digest header. My judgement at the time (as the designated expert for that IANA table of HTTP Digest Algs) was that it was sufficient for the algorithms to have specs, without demanding an extra spec just to added them to the table.
To answer the specific issue question, the status of algorithms is a result of importing the original algorithm list and "blocking" algorithms on request. This request seems reasonable.
...snip
I suggest adding ADLER32 and CRC32c to draft-ietf-httpbis-digest-headers. That tidies up the registration.

It sounds fair to obsolete these algorithms. Typically we've just cited somebody else's work to explain why that is the case, if there are no such references for `sum` then we might need more text than is present for other obsoleted algorithms.

**Comment by martinthomson** [comment]
It might be sufficient to rely on the absence of evidence of strength algorithms.  The question should be what the algorithm claims to provide.  By my reckoning:

* sum is at best a sanity check that is approximately as good as the one in TCP (it might be better)
* cksum is CRC32(c?) and is intended to catch bit-level errors in transmission (there are likely papers that state the bounds on this and where the weaknesses lie, but my understanding is that this is a pretty good algorithm for this purpose still)
* MD5 and SHA-1 are intended to be cryptographically secure in the sense that they provide collision, pre-image, and second pre-image resistance.  They are known to fail at the first and the other properties are in question.
* The SHA-2 family are widely regarded as being cryptographically sound in the aforementioned sense.

The https://tools.ietf.org/html/rfc3309 is a good reference for ADLER32, though I will note that the claim about deprecation isn't quite accurate.  That deprecation was specifically in relation to its use in SCTP.  I think that this document needs to effect the deprecation directly.

**Comment by ioggstream** [comment]
> Making sum obsolete would be an improvement; we almost get better guarantees from the TCP
> checksum.
> I tend to think that cksum obsolete would also be a good choice. Right now, both are 'standard'

If you don't want to change the status of `adler32` wdyt to rename this issue as `make sum and cksum obsolete`?

While your question is reasonable, Lucas explained our approach:

>  if there are no such references for sum then we might need more text than is present for other obsoleted algorithms.

Do you know of any implementors use-cases that is affected by that?

**Comment by ioggstream** [comment]
If there are no further comments I would close this.

**Comment by LPardue** [comment]
I'd like to try and address both of Martin's point that relate to sum/cksum (here and on #1138) in a single PR. So I vote for keeping this open until we merge some text.

**Comment by ioggstream** [comment]
closed in favor of #1377
