### ISSUE TITLE
Add example for Tokens?

### ISSUE THREAD

**Issue by tfpauly** [httpwg/http-extensions#1147]
In Section 3.3.4. Tokens, there isn't an example `Example-TokenHeader:`. It's pretty trivial for this case, but since other types all provide an example, it might be nice to include one here as well.

Also, on the topic of examples, the existing examples are inconsistent with naming it "Header" or "Hdr"

`Example-IntegerHeader`
`Example-DecimalHeader`
`Example-StringHeader`
`Example-BinaryHdr`
`Example-BoolHdr`

**Comment by mnot** [comment]
Argh, forgot to do this in -18; will consider this a LC comment and do it then. Sorry.
