### ISSUE TITLE
6265bis should not normatively depend on the Public Suffix List

### ISSUE THREAD

**Issue by sleevi** [httpwg/http-extensions#1159]
Within 6265bis, the use of the PSL is currently specified normatively:
https://github.com/httpwg/http-extensions/blob/5469d515d8876196900078806d07813765aa9a49/draft-ietf-httpbis-rfc6265bis.md#L104-L106

Concrete suggestion: Move this to an informative reference, instead, and update the text relying upon it to capture this. 

In 6265, this was effectively an informative reference, per [Section 5.3's](https://tools.ietf.org/html/rfc6265#section-5.3) note. This is somewhat related to https://github.com/httpwg/http-extensions/issues/1033 which moved it into terminology, instead of Section 5.4.

In terms of "rough consensus and running code", in terms of widely deployed clients, the algorithm specified in the Public Suffix List is not consistently implemented, the algorithm itself is ambiguous for edge cases, and perhaps most importantly, none of the major implementations ship the same version of the Public Suffix List. Several implementations, including Google Chrome, further fork and modify that list to support their implementation needs.

Thus, it's really more of an informative dependency, similar to how 6265 captured this problem. [SAC070](https://www.icann.org/en/system/files/files/sac-070-en.pdf) similarly called out and acknowledged there may be many static lists used by applications, of differing versions and algorithms.

**Comment by sleevi** [comment]
@mikewest Also editorial and related to 6265bis

**Comment by mikewest** [comment]
I don't think it's pedantically "editorial" since it removes a normative reference, but I'm fine with doing so. Do you have a proposal for new text? If not, I'll make something up.
