### ISSUE TITLE
rfc6562bis draft-6 section 4.1.1 syntax says US-ASCII but is not?

### ISSUE THREAD

**Issue by bagder** [httpwg/http-extensions#1161]
News in draft-06 is the %80-FF range added here:
~~~
cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E / %x80-FF
                      ; US-ASCII characters excluding CTLs,
                      ; whitespace DQUOTE, comma, semicolon,
                      ; and backslash
~~~
... so the text below the syntax define doesn't match the syntax description anymore, as %x80-FF is certainly not US-ASCII...

**Comment by reschke** [comment]
See https://github.com/httpwg/http-extensions/pull/1162

**Comment by mikewest** [comment]
Merged @reschke's PR. Thank you both!
