### ISSUE TITLE
document.cookie should not be able to access SameSite cookies in cross-site iframes

### ISSUE THREAD

**Issue by chlily1** [httpwg/http-extensions#1163]
[Per mikewest](https://crbug.com/1075610#c5): 

> No, cross-site frames should not be able to access `SameSite=AnythingButNone` cookies via `document.cookie`. The spec doesn't make this clear (you have to read between the lines of bullet 5 of step 1 of https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-06#section-5.5), so we should change the spec.

**Comment by bakulf** [comment]
I recently wrote this https://github.com/web-platform-tests/wpt/pull/23113 to cover the opposite of what you suggest but I'm happy to revert it as soon as we have consensus.

In particular, the reason why I wrote that PR is this:

1. A.com as an anchor element pointing to B.com
2. the user clicks on the link. The browser navigates to B.com
3. B.com runs: `document.cookie = 'a=b; sameSite=strict'; console.log(document.cookie);`
4. Should the console show 'a=b' or an empty string?

In theory, a=b should be shown only if the navigation is same-origin, but here we don't have navigation (document.cookie doesn't trigger navigation). And if we consider the document loading, this is not same-site (A.com -> B.com).

Chrome shows 'a=b'. Firefox before [bug 1627653](https://bugzilla.mozilla.org/show_bug.cgi?id=1627653) used to show an empty string.

A way to cover this scenario and what you suggest is to not expose `sameSite=AnythingButNone` cookies to iframed cross-origin documents.

**Comment by chlily1** [comment]
If I'm understanding correctly, the changes in https://bugzilla.mozilla.org/show_bug.cgi?id=1627653#c11 make it so that all SameSite cookies are exposed in `document.cookie` queries regardless of the ancestor frames' origins. The WPT change also seems to test this behavior. This is more permissive than just showing SameSite=Strict cookies in "laxly same-site" (i.e. all document ancestors are same-site) contexts regardless of navigation initiator, which is what Chrome does.

**Comment by bakulf** [comment]
> If I'm understanding correctly, ...

This is correct. And reading the spec, the firefox implementation seems to be the correct one, even if I prefer to have something more restrictive.

**Comment by chlily1** [comment]
I believe #1428 addresses this adequately.
