### ISSUE TITLE
Typo in alt-svc caching example

### ISSUE THREAD

**Issue by rjb1000** [httpwg/http-extensions#117]
https://tools.ietf.org/html/draft-ietf-httpbis-alt-svc-08#section-3.1

    For example, a response:

     HTTP/1.1 200 OK
     Content-Type: text/html
     Cache-Control: 600
     Age: 30
     Alt-Svc: h2c=":8000"; ma=60

Missing `max-age=` in `Cache-Control` header?

**Comment by reschke** [comment]
good catch
