### ISSUE TITLE
Redirect scope

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1170]
People using HTTP for non-browser cases seem to keep on assuming that redirects are 'sticky' -- i.e., that once I redirect a client, it will somehow magically know to redirect future requests (even with different URLs) to the updated server. We should clarify this specifically so there's text we can point these people to.

One could read the current specs as saying that a POST to URL A that permanently redirects to URL B should imply that future POSTs to URL A should automatically be sent to URL B. I think that's reasonable, but AFAICT it isn't implemented anywhere, so we should caution folks that it's only advisory and not widely implemented.

**Comment by ioggstream** [comment]
Is that related to the `ought`s I find in  https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#status.301 ?

**Comment by mnot** [comment]
Yes.
