### ISSUE TITLE
[Client-Hints] Impact assessment requested

### ISSUE THREAD

**Issue by jwrosewell** [httpwg/http-extensions#1174]
The current draft does a good job of explaining the implementation of HTTP Client Hints in engineering terms. It is a shame the [reservations expressed in the W3C](https://github.com/w3ctag/design-reviews/issues/467) relating to HTTP Client Hints do not appear to have surfaced in the debate or have not been considered worthy of a acknowledgement in the final draft.

The document does not recognise the wide adoption of HTTP User-Agent header value optimisations, the benefits they provide or the reliability of the techniques used. The justification for the existence of HTTP Client Hints is framed almost entirely from the singular position of privacy. The justification concerning improving performance is at best weak.

The document does not consider use cases that would be removed by adoption in practice, the impact to the open web of such removal, societal harms, or the competition issues that would result from web browser vendor implementations when considered alongside related proposals such as privacy budget.

Uses cases that will be removed include performance optimisation, the detection of fraud, and problem diagnosis as a few examples. 

Other use cases associated with knowledge of the user’s agent are tacitly acknowledged by a [browser vendor that implements the X-Client-Data](https://9to5google.com/2020/02/06/google-chrome-x-client-data-tracking/) specifically for the purpose of receiving such information on first request. The implementation of X-Client-Data limits this information to services operated by the browser vendor, happens by default and without user consent or knowledge. For the same browser vendor to support a proposal that seeks to remove such information from others is disingenuous.

Where mitigations have been suggested they would in practice depend on a related proposal concerning privacy budget. Whoever controls the privacy budget and the default settings will therefore control the realisation of such use cases.

Where existing standards for interoperability are used to deliver vital content to people the provider of such services will need to modify their service to support HTTP Client Hints. This will be the case for millions of websites currently utilising accurate information contained in the User-Agent HTTP header value. This will consume untold developer effort running two parallel solutions and will take them away from more productive activity. The problem will be particularly acute in societies where mobile devices dominate access to information and will be a particular concern for people whose only method of accessing information is via a mobile device.

Assuming it is not the role of this body to pick winners and losers I urge participants to consider a further review to engage a wide range of stakeholders to better understand fully the implications before progressing.

**Comment by mnot** [comment]
Spec already shipped, so this is too late.

Beyond that, the issue you reference and what you raise here is about migrating form UA to clint hints, which is not part of this document.
