### ISSUE TITLE
Lack of definition of keyId hurts interoperability

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1177]
The current text leaves the format and semantics of `keyId` completely up to the implementation.  This is primarily due to the fact that most implementers of Cavage have extensive investment in key distribution and management, and just need to plug an identifier into the header.  We should support those cases, but we also need to provide guidance for the developer that doesn't have that and just wants to know how to identify a key.  It may be enough to punt this to profiling specs, but this needs to be explored more.

**Comment by OR13** [comment]
I think its fine to leave the identifier constrained too valid utf-8 / strings / URIs... certainly there will be a profile for working with DIDs in the future, where keyId is a DID_URL.

**Comment by jricher** [comment]
keyid is now a string that needs to be known to the verifier, with no additional semantics layered on by this spec. Applications of this spec can add further constraints if they want to.
