### ISSUE TITLE
Algorithm Registry duplicates work of JWA

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1178]
RFC7518 already defines an IANA registry for cryptographic algorithms.  This wasn't used by Cavage out of concerns about complexity of JOSE, and issues with JWE and JWS being too flexible, leading to insecure combinations of options.  Using JWA's definitions does not need to mean we're using JOSE, however. We should look at if/how we can leverage JWA's work without introducing too many sharp edges for implementers.

In any use of JWS algorithms, this spec would define a way to create the JWS Signing Input string to be applied to the algorithm.  It should be noted that this is incompatible with JWS itself, which requires the inclusion of a structured header in the signature input.

A possible approach is to incorporate all elements of the JWA signature algorithm registry into this spec using a prefix or other marker, such as `jws-RS256` for the RSA 256 JSON Web Signature algorithm.

**Comment by OR13** [comment]
I would prefer a clean mapping to support for JWS, and not to reinvent yet another crypto registry... 

I am implemented support for https://www.iana.org/assignments/jose/jose.xhtml

In https://w3c-ccg.github.io/lds-jws2020/

JOSE is not complicated, and is reasonably well supported in many different languages (as is HTTP).... IMO, It would be a complete disaster not to start with support for it.

**Comment by OR13** [comment]
PROPOSAL: use IANA / JOSE + detached JWS.

**Comment by jricher** [comment]
+1 to having a way to using JWS algorithms and defining the mapping, as algorithm options at least. 

-1 to "just use JOSE": I've implemented several variants of detached JWS for signing general HTTP messages, and it's not a good fit for this.

**Comment by OR13** [comment]
@jricher assuming a vanilla JWS, what goes in the payload if its not detached?

**Comment by jricher** [comment]
Draft -03 includes instructions on how to use JWA defined algorithms with this draft -- specifically how to pipe the input and output of JWS and HTTP Message Signatures together.
