### ISSUE TITLE
Algorithm Registry should not be initialized with deprecated entries

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1179]
The initial entries in this document reflect those in Cavage.  The ones that are marked deprecated were done so because of the issue explained in #1176, with the possible exception of `rsa-sha1`.  We should probably just remove that one.

**Comment by OR13** [comment]
Why not just say we support https://www.iana.org/assignments/jose/jose.xhtml

and leave it to implementers to choose which algorithms to use?

**Comment by jricher** [comment]
Algorithms have been redefined in -03 and algorithm selection refined in -04, including use of JOSE algorithms.
