### ISSUE TITLE
alt-svc: consistency of alternative service(s) terminology and capitalisation

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#118]
The document uses terminology such as "Alternative Services", "alternative services" and "alternative service". There seems to be a distinction between terms (albeit minor) based on the capitilisation and pluralisation but this is not completely clear to me.

For example:

https://httpwg.github.io/http-extensions/alt-svc.html#rfc.abstract
> This document specifies "alternative services" for HTTP,

and  https://httpwg.github.io/http-extensions/alt-svc.html#introduction
> This specification defines a new concept in HTTP, "Alternative Services"

and https://httpwg.github.io/http-extensions/alt-svc.html#alternative
> This specification defines a new concept in HTTP, the "alternative service".

The capilisation elsewhere looks ok based on context (titles, start of sentence) but perhaps that is leading to my uncertainty in the first place.

**Comment by reschke** [comment]
FWIW, this is not intentional. I'll make sure that the quoted forms are consistent.
