### ISSUE TITLE
No percent-encoding normalization of path/query

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1180]
The canonicalization rules for `(request-target)` do not perform handle minor, semantically meaningless differences in percent-encoding, such that verification could fail if an intermediary normalizes the effective request URI prior to forwarding the message.  

At a minimum, they should be case and percent-encoding normalized as described in sections 6.2.2.1 and 6.2.2.2 of RFC3986.

See: [issue #26 in old Cavage repo](https://github.com/w3c-dvcg/http-signatures/issues/26)

**Comment by jricher** [comment]
The path, query, query-param fields are all properly encoded/decoded. Request-target is more iffy but is no longer required.
