### ISSUE TITLE
Multiple Set-Cookie headers are not well supported

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1183]
The Set-Cookie header can occur multiple times but does not adhere to the list syntax, and thus is not well supported by the header field value concatenation rules.

**Comment by jricher** [comment]
Tagging @sbingler for feedback and discussion.

**Comment by sbingler** [comment]
Thanks, just for clarification are you looking for immediate-ish feedback from me or is this more of an FYI for future discussions?
