### ISSUE TITLE
Max values, precision for Integer String and Decimal String not defined

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1185]
The definitions for Integer String and Decimal String do not specify a maximum value.  The definition for Decimal String (used to provide sub-second precision for Expiration Time) does not define minimum or maximum precision requirements.  It should set a reasonable requirement here (e.g., MUST support up to 3 decimal places and no more).

Better yet, are there existing definitions we can reference?

**Comment by ioggstream** [comment]
Maybe S-H draft can help.

imho we should just not mandate for subsecond precision and allow both `int` and `float`

**Comment by ioggstream** [comment]
@richanna we are using structured fields: can we close? :)

**Comment by jricher** [comment]
Draft no longer defines data types but uses structured field definitions.
