### ISSUE TITLE
Reconcile Date header and Creation Time

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1189]
The draft is missing guidance on if/how the Date header relates to signature Creation Time.  There are cases where they may be different, such as if a signature was pre-created.  Should Creation Time default to the value in the Date header if the `created` parameter is not specified?

**Comment by ioggstream** [comment]
Explicit is better than implicit :)

imho:
-  `created` MUST be always present
- relations between `Date` and `created` MAY not be explicited

**Comment by jricher** [comment]
Creation time is no longer an object model item and is independent from the Date header. We should still add some discussion about the relationship between the Date header and the signature creation timestamp.

**Comment by jricher** [comment]
Closed by #1599
