### ISSUE TITLE
alt-svc: use of "alternative-protocol" term

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#119]
https://httpwg.github.io/http-extensions/alt-svc.html#alternative

>  Each origin maps to a set of these routes — the default route is derived from the origin itself and the other routes are introduced based on alternative-protocol information. 

This looks like it may be a remnant from Alternate-Protocol. [Section 2.4](https://httpwg.github.io/http-extensions/alt-svc.html#switching) uses the phrase `alternative service protocol`, which seems a little clearer.

**Comment by reschke** [comment]
IMHO it really ought to be "alternative-service information".
