### ISSUE TITLE
Transformations to Via header field value break verification

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1192]
Intermediaries are permitted to strip comments from the `Via` header field value, and consolidate related sequences of entries.  The canonicalization rules do not account for these changes, and thus they cause signature verification to fail if the `Via` header is signed. At the very least, guidance on signing or not signing `Via` headers needs to be included.

**Comment by ioggstream** [comment]
Let's add a paragraph with some caveats and header examples.
