### ISSUE TITLE
Define more content identifiers

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1195]
It should be possible to independently include the following content and metadata properties in Covered Content:

- ~The signature's Algorithm~
- ~The signature's Covered Content~
- ~The value used for the `keyId` parameter~
- Request method
- Individual components of the effective request URI: scheme, authority, path, query
- Status code
- Request body (currently supported via Digest header RFC3230)

**Comment by ioggstream** [comment]
Covering the payload body is not trivial as the http semantics impact on that: that includes all representation metadata (content-type, content-encoding), partial responses (range-requests), empty payload body methods (HEAD) and status (No Content).

I suggest having a look at the [I-D.ietf-httpbis-digest-headers](https://github.com/httpwg/http-extensions/blob/master/draft-ietf-httpbis-digest-headers.md) to check all the possibilities.

**Comment by jricher** [comment]
As of -03 there are different places to put each of these: signature parameters and specialty fields.

**Comment by jricher** [comment]
Everything listed here can now be covered as of #1565 , except for request body which is still leaning on the Digest header.
