### ISSUE TITLE
Support for signing specific cookies

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1197]
A signer may only wish to sign one or a few cookies, for example if the website requires its authentication state cookie to be signed, but also sets other cookies (e.g., for analytics, ad tracking, etc.)

**Comment by jricher** [comment]
If cookies were to use structure fields then this could be easily accommodated by the sub-field indexing, but that's not likely. A cookie-flavored specialty field could be defined in core or in an extension, but I haven't seen a draw for this yet.

Should we close?

**Comment by jricher** [comment]
Tagging @sbingler for feedback and discussion.

**Comment by richanna** [comment]
I am comfortable with deferring individual cookie signing to a separate spec.

No browsers provide built-in support HTTP Message Signatures at this time, so anyone wishing to use HTTPSig from the browser has to implement it in JavaScript. That means any cookies an implementer wants to sign must be visible to JavaScript, which in turn means that the implementer could transmit those values via another header field (e.g., `Authorization`, or a proprietary header field). So there is a work around for anyone who wants to do this immediately.
