### ISSUE TITLE
Use Structured Headers

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#1198]
Redefine the Signature header field to use [Structured Headers](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html). This will simplify both the definition and the parsing of this header field value.

**Comment by Ousret** [comment]
Hi,

I recently made this lib for HTTP headers, https://github.com/Ousret/kiss-headers 
I think that it could help. What do you think about it?
