### ISSUE TITLE
Positive indicator of server understanding

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#12]
I'm not sure how this can be turned into something useful, but this seems pretty bad:

1. An HTTP/1.1 server doesn't check the scheme, but permits authority form requests for both `http` and `https` equally.  Scheme is instead inferred from the presence/absence of TLS in the stack.

2. Attacker sends an Alt-Svc header field to clients referencing the `https` endpoint on that server.  This can come from any resource on the `http` endpoint, so it might not require any MitM attack.

3. Clients now make `http` requests to the secure endpoint and now the content from the `https` origin is entered into the `http` origin.

Do we want to require an explicit indication from HTTP/1.1 servers so that clients can
be assured that this error did not occur?

This should not be a problem for HTTP/2.

**Comment by reschke** [comment]
Proposed text?

**Comment by martinthomson** [comment]
There is text in the opp-sec draft that might be used.  I see no good reason to create a circular dependency, so maybe just copy (and reword) it.

**Comment by mnot** [comment]
@martinthomson can you point @reschke in the right direction?

**Comment by martinthomson** [comment]
http://httpwg.github.io/http-extensions/encryption.html#confusion-regarding-request-scheme

> Many existing HTTP/1.1 implementations use the presence or absence of TLS in the stack to determine whether requests are for http or https resources. This is necessary in many cases because the most common form of an HTTP/1.1 request does not carry an explicit indication of the URI scheme.
>
> HTTP/1.1 MUST NOT be used for opportunistically secured requests.

I think that this document can alter the last statement.  I can't think of a good way to generically phrase the statement, but maybe:

> Alternative Services MUST NOT be advertised for a protocol that is not designed to carry the scheme.  In particular, HTTP/1.1 over TLS cannot carry safely requests for http resources.
