### ISSUE TITLE
Intermediaries altering content-coding

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1208]
## I expect

To clarify 

- [x] why Draft indicates protection against buggy compression, doesn't seem to actually do that as specified.
- [ ] that intermediaries MUST NOT alter Digest
- [x] protection from transforming proxies

## Notes

This is a good question and probably should be addressed explicitly in the spec, either in the FAQ or in a proper section or [here](https://github.com/httpwg/http-extensions/blob/master/draft-ietf-httpbis-digest-headers.md#digest-for-end-to-end-integrity).
Probably we can even refine the introduction.
Here's a general answer.

1- Digest protects the representation-data from a buggy transfer-coding; 

2- Digest was not originally designed to protect from a buggy content-coding (that could compress, encrypt or alter in any way the content-type bits) because the content-coding is a property of the representation;

3- If the content-coding changes, the representation-data changes and the Digest validation is supposed to fail;

4- In the new draft the introduction of the `id-sha-*` algorithms provide a mechanism that protects from buggy content-coding.

Infrastructures delegating content-coding to reverse proxies can delegate them the digest computation too; such a reverse proxy is probably seen as an Origin Server from an User Agent.

My opinion on integrity is that intermediaries should not generally alter the content-coding (nor the content-type :P): some considerations are expressed in Semantics https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#message.transformations  where there's a hint about `Cache-control: no-trasform`.

**Comment by ioggstream** [comment]
@wbl thanks for the question! I think we should address it better in the spec. I stubbed a bullet-point answer: if that works for you we'll try to integrate it in the spec.

**Comment by wbl** [comment]
That works for me. I think we also should mention that it does work for Transport-Encoding compression.

**Comment by LPardue** [comment]
I think this is a good issue but I have a concern that it is easy to go overboard on describing a case, Transfer-encoding compression, that in practice isn't used much. 

Validating that the Transport-Coding didn't mangle the Content-Coding only works when a full payload has been transferred. It won't work for a partial resource. So this is a subset of a subset. 

I'm more inclined to simply remove the mention of protecting against "buggy compression" and add some other prose. For example, in the Introduction where we say

> However, there are cases where relying on this alone is insufficient. An HTTP-level integrity mechanism that operates independent of transfer can be used to detect programming errors and/or corruption of data at rest, be used across multiple hops in order to provide end-to-end integrity guarantees, aid fault diagnosis across hops and system boundaries, and can be used to validate integrity when reconstructing a resource fetched using different HTTP connections.

We can augment that to say `An HTTP-level integrity mechanism that operates independent of transfer can be used to detect programming errors and/or corruption of data in flight or at rest`.

Then in the section `Digest for End-to-End Integrity` we might want to add some guidance about considerations for intermediaries that want to fiddle with content and/or content-coding. CDNs ability to modify content is one of their main value propositions - we see this where new compression schemes like brotli, or new formats like WebP. With other types of intermediary, I figure that they either care to respect end-to-end headers or they don't; there's not much to enactable write about here IMO.

**Comment by ioggstream** [comment]
> remove the mention of protecting against "buggy compression"
+1

> An HTTP-level integrity mechanism that operates independent of transfer 
> can be used to detect programming errors and/or corruption of data in flight or at rest
+1

> add some guidance about considerations for intermediaries that want to fiddle
> with content and/or content-coding
+1. 

About CDN altering content-type and content-coding, I found this [gcloud document](https://cloud.google.com/storage/docs/transcoding) containing a caveat about integrity checks and transcoding.
Probably it's the kind of caveat CDN implementors should include in their documentation when allowing users to configure those behaviors.

If the CDN does not care for integrity (eg. serving webp photos for a gallery) probably it's not needed though.

**Comment by LPardue** [comment]
> About CDN altering content-type and content-coding, I found this gcloud document containing a caveat about integrity checks and transcoding.
Probably it's the kind of caveat CDN implementors should include in their documentation when allowing users to configure those behaviors.

My intuition of the Google Cloud documentation is that this is a corner they've painted themselves into with the `x-goog-hash` header. Using Digest would actually be advantageous in such a scenario because a client can upload a compressed coding representation and include `id-sha-256`, any transcoding in the cloud won't invalidate this.

But that is tangential to the concerns of what the Digest specification needs to do.

**Comment by ioggstream** [comment]
I #1294 I replaced "buggy compression" with undesired Trasforming Proxies. As they are defined in {{SEMANTICS}} I think we can omit further explanations. WDYT?

**Comment by ioggstream** [comment]
Closed via #1294
