### ISSUE TITLE
alt-svc: Alt-Used security discussion

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#121]
[Section 5](https://httpwg.github.io/http-extensions/alt-svc.html#indicator) foreshadows a discussion about privacy 

> As the Alt-Used header field might be used by the server for tracking the client, a client MAY choose not to include it in its requests for protecting its privacy (see Section 9.4). 

However, Section 9.4 doesn't contain any mention of Alt-Used. Maybe all the information contained in the document is enough but this just struck me as a little odd.

**Comment by reschke** [comment]
This inconsistency was caused by the fix for https://github.com/httpwg/http-extensions/issues/36.

**Comment by mnot** [comment]
SGTM.
