### ISSUE TITLE
digest-algorithms SHOULD be lowercase (wrt structured headers)

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1211]
## I suggest

that digest-algorithms `SHOULD` be lowercase

## Note

digest-algorithms are currently case insensitive.
We won't break specs suggesting to express them in lowercase.
This could make it easy a future transition to S-H

**Comment by mnot** [comment]
The encoded digest output seems like it's often case-sensitive, but it's a token, so this header won't 'fit' into Structured Fields naturally anyway.

**Comment by ioggstream** [comment]
Ok, so I'll close sh-related issues, though I'm still in favor of suggesting `lowercase` digest-algorithms :)
