### ISSUE TITLE
Ensure Signatures is independent from HTTP/1.1 + use http-core 

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1214]
## I expect

The spec relies only on HTTP Semantics
and not on HTTP/1.1 messaging.

- [ ] improve wording #1310 
- [ ] switch to http-core

## Notes

Check all references to Messaging and consider replacing them using Semantic.

See https://github.com/httpwg/http-core/pull/362/files

**Comment by ioggstream** [comment]
@richanna @jricher @reschke I was re-reading the spec after the more recent filed issues, and I think that switching this draft to HTTP Core terminology (eg. I-D.ietf-httpbis-semantics ) we could have a more consistent background for taking the right decisions about things like transformations, intermediaries.

**Comment by jricher** [comment]
This should be taken care of with #1599 , @ioggstream please re-open with comment if there are more things to be done.
