### ISSUE TITLE
Ensure digest is independent from http/1.1

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1215]
## I expect

Digest to be indepentent from http/1.1 (messaging)

See https://github.com/httpwg/http-core/pull/362/files

**Comment by ioggstream** [comment]
@reschke iiuc the only MESSAGING-depending parts is:

- https://github.com/httpwg/http-extensions/blob/master/draft-ietf-httpbis-digest-headers.md#usage-in-trailers

The spec references the term "message body" 3 times too, which is defined in MESSAGING. Do you think we should replace it?

**Comment by reschke** [comment]
message body: this might be "payload" (https://greenbytes.de/tech/webdav/draft-ietf-httpbis-semantics-latest.html#payload)
