### ISSUE TITLE
Make it more clear what to do with read and write errors

### ISSUE THREAD

**Issue by mnot-fastly** [httpwg/http-extensions#1228]
Right now the likely candidates are `connection_terminated` and `http_incomplete_response`, but it's not obvious, and also this depends on the implementation knowing whether the response has started yet or not -- which may be difficult to retrofit onto an existing implementation.

**Comment by PiotrSikora** [comment]
Well, proxies must know that anyway, since if the response has already started and HTTP headers were already sent, then the only way to transmit this information in `Proxy-Status` is via HTTP trailers.

**Comment by mnot-fastly** [comment]
Ah, good point - never mind.
