### ISSUE TITLE
Proxy configuration error

### ISSUE THREAD

**Issue by mnot-fastly** [httpwg/http-extensions#1229]
Right now the only way to indicate bad configuration is `proxy_internal_error`, which isn't terribly helpful.

**Comment by PiotrSikora** [comment]
Could you elaborate on the use case here? I think `proxy_internal_error` should be fine for misconfiguration errors that we don't want to advertise (e.g. fleet-wide misconfiguration that broke the Internet), but perhaps we could use something else for customer-provided configuration that breaks proxying for a specific hostname? Is that what you had in mind?

**Comment by mnot-fastly** [comment]
Yes, exactly.
