### ISSUE TITLE
alt-svc: Question about parameters

### ISSUE THREAD

**Issue by rjb1000** [httpwg/http-extensions#123]
The Internet Draft specifies a syntax for parameters (Section 3), and an IANA registry to manage their name space (Section 7.3), but doesn't prescribe what parameters should be used for, except for the following fleeting reference:

> ## 7.3.  Alt-Svc Parameter Registry
> The HTTP Alt-Svc Parameter Registry defines the name space for the cache directives. ...

Is the intention that parameters should only be used as cache directives, as implied by the above sentence? The two parameters specified in the Draft ("ma" and "persist") are certainly of that flavour. Or is the intention that parameters could be used for other purposes as well?

If the latter, perhaps the language in section 7.3 could be softened, e.g.

> The HTTP Alt-Svc Parameter Registry defines the name space for parameter names. ...

The text at Section 3 currently launches into the following with no preamble:

> # 3.  The Alt-Svc HTTP Header Field
> ...
> This specification defines two parameters: "ma" and "persist", defined in Section 3.1.  Unknown parameters MUST be ignored, that is the values (alt-value) they appear in MUST be processed as if the unknown parameter was not present.
> New parameters can be defined in extension specifications (see Section 7.3 for registration details).
> ...

How about inserting a sentence along the following lines:

> Each "alt-value" MAY be followed by a semicolon-separated list of additional parameters, each such "parameter" comprising a name and a value. This specification defines two parameters...

Or, if you want to constrain the use of parameters in any way, you could do that here.

**Comment by reschke** [comment]
Good points.

(The first problem is simply a result of copying and pasting from <http://greenbytes.de/tech/webdav/rfc7234.html#cache.directive.registry>)

**Comment by rjb1000** [comment]
Thanks. You worded it much better than I did :-)
