### ISSUE TITLE
Specify how non-HTTP cookies should be exposed to sites

### ISSUE THREAD

**Issue by DCtheTall** [httpwg/http-extensions#1233]
Currently, 6265bis only really talks about storing cookies that come from non-HTTP sources (e.g. document.cookie, CookieStore), but there is nothing in the spec about what cookies should be included in non-HTTP reads except that HttpOnly cookies should be ignored.

This lack of guidance has led to some [disagreements between browsers](https://github.com/httpwg/http-extensions/issues/1163) about whether `SameSite=AnythingButNone` cookies should be accessible in cross-origin frames.

I am opening this issue to start a discussion about whether non-HTTP cookie access is in scope of 6265bis, and if so, what changes should be made to the spec.

**Comment by DCtheTall** [comment]
CC @mikewest

**Comment by mikewest** [comment]
It certainly needs to be defined somewhere. It might well make sense for HTML to define some filtering mechanism for the particular set of user agents that care about HTML (along with its definition of `document.cookie`), but I expect that definition to require some infrastructure in this document to support it.

**Comment by DCtheTall** [comment]
> but I expect that definition to require some infrastructure in this document to support it.

@mikewest can you clarify?

**Comment by chlily1** [comment]
Another consideration is that the definition in `5.2.  "Same-site" and "cross-site" Requests` applies to "requests" and is defined in terms of the "request's client", IIUC as defined in Fetch, which doesn't really cover cookie accesses from non-HTTP APIs. This part may also need to be reformulated to cover non-HTTP APIs.

**Comment by chlily1** [comment]
I believe #1428 addresses this adequately.
