### ISSUE TITLE
Inconsistent rules around whitespace

### ISSUE THREAD

**Issue by zcorpan** [httpwg/http-extensions#1251]
https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html

I found https://github.com/httpwg/http-extensions/pull/1173

The current grammar with both SP and OWS in different places. I don't quite understand the motivation for SP in some places instead of OWS everywhere. If OWS was allowed in some places for more robust parsing, wouldn't allowing OWS everywhere be more robust still?

Also, there are some places where no whitespace is allowed but maybe it should be. In particular, before the `;` in the parameters. Should whitespace be allowed there?

cc @mnot

**Comment by annevk** [comment]
cc @valenting

**Comment by reschke** [comment]
FWIW and AFAIR, "OWS" was needed because sender/recipient have no control about how other components rombine multiple field lines into one. The other places are actually intentionally strict.

**Comment by annevk** [comment]
So SP is used where you could not have whitespace as a result of combining? So basically whenever there's no possible comma adjacent to it?

(That would still leave the parameters thing.)

**Comment by reschke** [comment]
> (That would still leave the parameters thing.)

Yes, there are multiple questions here.

I would say that it really doesn't matter that much as long as it is well-defined and implementations agree on it (and there's a test suite for a reason). In which case the outcome IMHO should be not to make another change, given the fact that the spec is approved already.

**Comment by annevk** [comment]
Making this a bit more concrete, in `N: \tV` (assuming \t is HT) does `V` end up parsing as a structured value or not? If it does because HTTP removed the HT, why does SFV feel the need to remove SP in step 2 of https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#text-parse?

**Comment by reschke** [comment]
AFAIU, the invidual parsers (list, item, ...) assume that leading SP has already been consumed.

**Comment by annevk** [comment]
I'm not sure how that addresses the question. Are you saying \tV cannot parse as a structured field value? So if you defined a header value as "sometoken" (or case-sensitive variant) in the past it's not forward-compatible with SFV?

**Comment by reschke** [comment]
It parses, as the leading HTAB is part of the OWS that surrounds the field value. See <https://greenbytes.de/tech/webdav/rfc7230.html#header.fields>.

**Comment by annevk** [comment]
Okay and OWS includes SP, so why does https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#text-parse remove SP? How can there be SP at that point?

**Comment by reschke** [comment]
Good question.

**Comment by phluid61** [comment]
>  Are you saying \tV cannot parse as a structured field value?

It can't, but also it should never try to, because by the time the field value gets to the Structured Fields parser, the `\t` should have been eaten by the HTTP parser. So in a sane environment, step 2 is a noop. I guess we just forgot about that, because we've not been working in that sane environment (the test suite doesn't use any HTTP machinery, so there's no guarantee that what gets fed into `parse()` is even remotely sensible.)

I think it shouldn't be a problem to remove it.

For the parameters thing: there's a discussion in #954 (from October last year, so I can't remember precise details.) I think it was that the algorithm doesn't look ahead, so couldn't distinguish between `"x ;"` and `"x y"`, so it gobbled up the space after `x`, which broke the inner-list parser which expected a space character before the `y`.

**Comment by zcorpan** [comment]
Thanks for the clarifications. I think it would be helpful with a note in "Parsing Structured Fields" to clarify that leading and trailing OWS are "removed" per RFC7230. Also I suggest removing the (no-op) steps that skip SP.

**Comment by zcorpan** [comment]
@mnot Was this closed without change? https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#name-parsing-structured-fields step 2 still says "Discard any leading SP characters from input_string."

**Comment by mnot** [comment]
@zcorpan this discussion happened after the IESG approved the document.

**Comment by annevk** [comment]
@mnot should we not keep it open until we can file errata then? As per https://github.com/httpwg/http-extensions/issues/1251#issuecomment-675508724 I don't think it's a normative change, but it would make it clearer.
