### ISSUE TITLE
Buffering PRIORITY_UPDATES and early responses

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1260]
I think it might be better to say "SHOULD be buffered and be applied once the stream is opened."

The problem with current text is that it does deal with servers sending responses _while_ they receive requests (i.e. early response).

_Originally posted by @kazuho in https://github.com/httpwg/http-extensions/pull/1167#r484963926_

**Comment by LPardue** [comment]
It's interesting that serving early response with appropriate priority is not a use case anyone came up with in defence of PRIORITY_UPDATE frames. 

I think we can support an early response case but we need to make sure the language is precise. For example, the document says

> The signal carried by a PRIORITY_UPDATE frame overrides that carried by the
header field, even when the frame was received before the request headers.

What we're asking implementers to do with Kazuho's suggestion to ignore any Priority header that might be in the request if they choose to process headers after they started serving a response. I'd like implementers to confirm that they think this is a reasonable thing to do.

**Comment by MikeBishop** [comment]
In general, an early response is because the *headers* are sufficient to generate a response without processing the body of the request.  (POST somewhere that requires authentication you don't have, for example.)  Talking about an early response before you've processed the headers seems kind of nonsensical, unless *maybe* you're talking about a 404 once you've seen the URL.  Even then, I suspect most servers would simplify their processing by waiting until they see the end of the header section.

**Comment by LPardue** [comment]
Apologies. This issue would have been improved if GitHub included the text that Kazuho was speaking to. So here it is

> Request-stream variant PRIORITY_UPDATE frames (type=0xF0700) received before the
request or response has started SHOULD be buffered until the stream is opened
and applied immediately after the request message has been processed.

Kazuho was suggesting that we change this to

> Request-stream variant PRIORITY_UPDATE frames (type=0xF0700) received before the
request or response has started SHOULD be buffered and and applied once the stream is opened.

**Comment by kazuho** [comment]
If we want to be precise, I think the best way would be to change the model that we assume in the document.

The document (including the changes proposed in #1167, which I think we should merge and then try to adjust) assumes that the priority is carried by the priority header field, with PRIORITY_UPDATE frame updating the information. But as we know, PRIORITY_UPDATE frame can arrive before the stream is being created or before the request headers are received. And in theory, a server might start sending response before it receives the priority request header field (though that's rare as @MikeBishop points out).

We could instead say that the PRIORITY_UPDATE frame always carries the up-to-date signal, whereas the value of priority request header field is adopted only when a PRIORITY_UPDATE frame has not (yet) been received for that request.

**Comment by MikeBishop** [comment]
I think that's a reasonable way to frame it.  It is equivalent, of course, to simply state that the PRIORITY_UPDATE frame is an update which might race the initial value.  If the server knows it's an update, it can ignore the older message when it sees it.

**Comment by kazuho** [comment]
I agree that we can go either directions, being precise, or concisely stating that it is an update that replaces the value sent in the header field (if any).
