### ISSUE TITLE
"Within the stream limit" in HTTP/2?

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#1261]
What does "within the stream limit" mean in this case?  HTTP/2 specifies a maximum number of concurrently active streams, with streams which are either "open" or "half-open" counting toward the limit regardless of the ID.  I think what you're saying here is that you're modifying the definition of the limit to also include "idle" streams where priority information has been received.  However, you're not explicitly calling this out as a modification to the 7540 concurrency logic.

_Originally posted by @MikeBishop in https://github.com/httpwg/http-extensions/pull/1167#discussion_r485149756_

**Comment by LPardue** [comment]
PR #1262 moves some of the text around but the issue here still remains. In [review of PR #1262](https://github.com/httpwg/http-extensions/pull/1262/files#r485975868) Kazuho said 

> I think we should RECOMMEND servers to buffer the most recent PRIORITY_UPDATE frames it receives for all the unopened streams, provided that the stream ID being specified by the frame is within the concurrency window.

> Otherwise, the server will fail to prioritize the responses correctly when a client issues many requests at once (e.g., when finding lots of tags in a HTML document).
