### ISSUE TITLE
What happens if PRIORITY_UPDATE's PFV is not a valid SF?

### ISSUE THREAD

**Issue by dtikhonov** [httpwg/http-extensions#1268]
The `Priority` field's field value and the Priority Field Value carried in _PRIORITY_UPDATE_ frame may not be a well-structured Structured Field (i.e. it may fail to parse).  While ignoring unexpected parameters and values is discussed in the draft, handling unparseable Structured Fields is not.

**Comment by LPardue** [comment]
Good question.

I don't believe that Structured Fields spec has any guidance other than to fail parsing. I'm open to ideas on what to suggest. 

Fail closed seems quite harsh. My gut feeling is to suggest the treating as though default values were received.

**Comment by dtikhonov** [comment]
That may become an optimization: send invalid Dictionary to send default values.

Unlike HTTP Fields, the contents of the _PRIORITY_UPDATE_ frame are not expected to come directly from the user of the protocol.  We should at least ignore such frames.

**Comment by LPardue** [comment]
Omitting the parameters implies defaults, so omitting the header or sending a frame with empty value would work just as well as sending a malformed value.

Take for example Chrome which sends initial priority in PRIORITY_UPDATE. If that is malformed and it's ignored, how would a server prioritise things?

**Comment by kazuho** [comment]
+1 to using defaults. IMO, implementations can sent an Warning response header field if they want to be helpful, but I do not think we need to state that (as we do not make such statement in each of the HTTP-related specifications).

**Comment by martinthomson** [comment]
I wouldn't ignore a badly formed frame, I would generate a connection error.  Otherwise you are burying an error.

I'd be opposed to mandating that garbage be ignored.  I'm OK if people decide to ignore junk, but have a slight preference if they don't.  Ignoring junk has negative consequences for other protocol users.
