### ISSUE TITLE
Combined value across headers and footers

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1269]
The structured field definition of dictionaries [says](https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-19#section-3.2):

> Note that Dictionaries can have their members split across multiple
   lines inside a header or trailer section;

The priority work is debating updates to priorities, which can be piecemeal.  I could read this two ways:

1. The value of a field can be split within a field section.
2. The value of a field can be split across multiple field sections.

Though the "or" implies that it is more of the former than the latter.

The core spec says this of trailers:

> Trailer fields ought to be processed and stored separately from the fields in the header section to avoid contradicting message semantics known at the time the header section was complete. 

Which reinforces that view.

A simple fix might be to s/inside a header or trailer section/of the same header or trailer section/.

However, I couldn't find anything in the core spec about combining field lines.  It is a common practice that might be worth documenting/defining somehow.

**Comment by mnot** [comment]
Agreed WRT the suggestion. See [here](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field-order) in the core spec for what you're looking for.

**Comment by bsdphk** [comment]
agreed.

**Comment by mnot** [comment]
This has been discussed on list and there hasn't been any pushback, so proceeding with an instruction to the RPC in AUTH48.
