### ISSUE TITLE
bnf for dict-member

### ISSUE THREAD

**Issue by Jxck** [httpwg/http-extensions#1273]
according to the current spec, `dict-member` is defined as

```bnf
dict-member = member-name [ "=" member-value ]
```

but current test includes case like below as valid. [link to test](https://github.com/httpwg/structured-field-tests/blob/master/dictionary.json#L114-L117)

```json
    {
        "name": "missing value with params dictionary",
        "raw": ["a=1, b;foo=9, c=3"],
        "header_type": "dictionary",
        "expected": [["a", [1, []]], ["b", [true, [["foo", 9]]]], ["c", [3, []]]]
    }
```

`b` 's member-value's are omitted, so `b` is implicitly `true` and it **has parameters** `foo=9` too.

in my understand from BNF,  if `=` doesn't appear next to member-name, member name section are omitted.

so if its should valid, BNF should be seems like this.

```bnf
dict-member = member-name [ ( "=" member-value) / parameters ]
```

**Comment by phluid61** [comment]
Heh, when that test was added I logged #1007 for essentially the same reason. The prose text and the algorithm were updated in fa0d3b0ea2412154747b63736ad041b9177b2b50 but I guess the ABNF was overlooked.

@mnot this report seems right, but it's very late in the day and the ABNF is a second class citizen in this spec. Should it be fixed?

**Comment by Jxck** [comment]
I hope it should be fixed, because it can be cause an interim problem who implements based on ABNF.

**Comment by reschke** [comment]
This indeed looks like an oversight, and yes, the ABNF needs to be fixed.

**Comment by mnot** [comment]
Oh, that's very annoying; I remember seeing this, but I thought it was fixed.

People should not implemented based upon the ABNF, but yes, it should be fixed.

I think the right approach is:

~~~ abnf
dict-member    = member-name ( "=" member-value ) / parameters
~~~

**Comment by mnot** [comment]
ooh, Github knows ABNF, @reschke!

**Comment by bsdphk** [comment]
Agree to @mnots ABNF.

On a first quick reading it might give people the wrong idea, that parameters are only possible without a value, but the text (and the rest of the ABNF) clarifies that well.

**Comment by Jxck** [comment]
@mnot just a question
> People should not implemented based upon the ABNF
Why should not ? Which should I implement based upon ?

**Comment by phluid61** [comment]
> Oh, that's very annoying; I remember seeing this, but I thought it was fixed.
> 
> People should not implemented based upon the ABNF, but yes, it should be fixed.
> 
> I think the right approach is:
> 
> ```abnf
> dict-member    = member-name ( "=" member-value ) / parameters
> ```

Do you mean:

```abnf
dict-member    = member-name ( "=" member-value / parameters) 
```

?

**Comment by phluid61** [comment]
@Jxck 
> 
> Why should not ? What should I implement based upon ?

The algorithms. See Section 1.2: "When parsing from HTTP fields, implementations MUST have behavior that is indistinguishable from following the algorithms. If there is disagreement between the parsing algorithms and ABNF, the specified algorithms take precedence." Etc.

**Comment by dtikhonov** [comment]
> Implementations MUST have behavior that is indistinguishable from following the algorithms.

One way to parse it is that one can use ABNF as long as it produces the right answer...

**Comment by phluid61** [comment]
> 
> 
> > Implementations MUST have behavior that is indistinguishable from following the algorithms.
> 
> One way to parse it is that one can use ABNF as long as it produces the right answer...

Sure, if the ABNF is correct. Which it, apparently, isn't (currently).

**Comment by mnot** [comment]
@phluid61 no. RFC5234 s 3.5 recommends that grouping be used when an alternative consists of multiple rules or literals.

**Comment by martinthomson** [comment]
This is an area in which parentheses are critical.  In ABNF, concatenation (" ") has higher precedence than alternation ("/"), so @phluid61 is correct to say that...

```abnf
dict-member    = member-name ( "=" member-value / parameters ) 
```

... matches the tests.  This is what the other means:

```abnf
dict-member    = ( member-name "=" member-value ) / parameters
```

Of course, the original suggestion was probably even better in that it was more explicit.  Even though `[]` is unnecessary given that `parameters` can be empty.

**Comment by mnot** [comment]
3.10, directly below the text that describes operator precedence:

~~~
   Use of the alternative operator, freely mixed with concatenations,
   can be confusing.

      Again, it is recommended that the grouping operator be used to
      make explicit concatenation groups.
~~~

**Comment by Jxck** [comment]
> "When parsing from HTTP fields, implementations MUST have behavior that is indistinguishable from following the algorithms. If there is disagreement between the parsing algorithms and ABNF, the specified algorithms take precedence."

Oh I missed this section. but I think spec should have correct ABNF which is equivalent with algorithms and implementer could implement parser automatically from ABNF instead of saying "should not implement depend upon the ABNF".

**Comment by phluid61** [comment]
> 
> 
> @phluid61 no. RFC5234 s 3.5 recommends that grouping be used when an alternative consists of multiple rules or literals.

Oh, right, sorry I forgot that in ABNF concatenation has higher precedence than alternation. Ignore me.

**Comment by martinthomson** [comment]
Is the ABNF for production or consumption?  Because...

>  Note that this requirement is only on serialisation; parsers are still required to correctly handle the true Boolean value when it appears in Dictionary values. 

Would suggest that the grammar a parser uses might be:

```abnf
dict-member    = member-name ( [ "=" sf-boolean ] parameters /  "=" member-value )
```

Whereas it appears that serialization needs to use the simpler:

```abnf
dict-member    = member-name ( parameters /  "=" member-value )
```

**Comment by phluid61** [comment]
Yeah I'm confused again now. [RFC 5234, Section 3.5](https://tools.ietf.org/html/rfc5234#section-3.5) says:

~~~text
         elem (foo / bar) blat

   matches (elem foo blat) or (elem bar blat), and

         elem foo / bar blat

   matches (elem foo) or (bar blat).
~~~

Which means that

~~~abnf
dict-member = member-name ( "=" member-value ) / parameters
~~~

is equivalent to

~~~abnf
dict-member = ( member-name "=" member-value ) / parameters
~~~

Which is how I read it originally, and how I'm pretty sure every other ABNF I've seen does it. (Even RFC 7230's definition of `quoted-pair`)

**Comment by martinthomson** [comment]
That is a correct reading.  Hence my suggestion above (and the different ordering).

**Comment by phluid61** [comment]
Or if you really, really want the grouping operator for the concatenation group:

```abnf
dict-member    = member-name ( ( "=" member-value ) / parameters )
; OR
dict-member    = member-name ( parameters / ( "=" member-value ) )
```

**Comment by mnot** [comment]
To @martinthomson's question above:

> This document uses... the Augmented Backus-Naur Form (ABNF) notation of [RFC5234] to illustrate expected syntax in HTTP header fields.

> When parsing from HTTP fields, implementations MUST have behavior
   that is indistinguishable from following the algorithms.  If there is
   disagreement between the parsing algorithms and ABNF, the specified
   algorithms take precedence.

> For serialization to HTTP fields, the ABNF illustrates their expected
   wire representations, and the algorithms define the recommended way
   to produce them.  Implementations MAY vary from the specified
   behavior so long as the output is still correctly handled by the
   parsing algorithm.

 Regarding grouping: my reading of 5234 is that concatenated groups be explicitly delimited not for correctness, but to avoid likely reader confusion (since some people will assume precedence in a different order).

So, I think that leaves us with:

~~~ abnf
dict-member    = member-name ( parameters /  ( "=" member-value ) )
~~~

The small price of a bit more visual noise is well worth the clarity, IMO.

Comments? We're now in AUTH48, so I'd like to come to a decision.

**Comment by martinthomson** [comment]
I think that is right and good.  And yes, 5234 recommends parentheses for exactly this reason.  (You can drop the extra space I added after the '/'.)

**Comment by mnot** [comment]
@phluid61 @bsdphk @Jxck anybody else?

**Comment by bsdphk** [comment]
OK with me

**Comment by mnot** [comment]
AUTH48 request made.

**Comment by Jxck** [comment]
@mnot 
that doesn't works fine for me.

as parameters definition covers anything because of it's optional itself.

```bnf
dict-member    = member-name ( parameters /  ( "=" member-value ) )
parameters     =  *( ";" *SP parameter )
```

it matches `a=b` as "`a` with no parameters and rest of `=b`"

so It works better as defined below.

```bnf
dict-member    = member-name ( ( "=" member-value ) / parameters )
```

almost same with my first proposal and it **already running in my code**.
- https://github.com/Jxck/structured-field-values/blob/master/index.js#L507

**Comment by mnot** [comment]
@jxck I'm confused. What's the practical difference between them? Ordering of alternatives isn't significant.

**Comment by Jxck** [comment]
@mnot ah, reasonable. in that case, both are matched then How to determine which are intended ?

```
a=b
=> result: {member-name: a, parameters: {}} , rest: "=b"
=> result: {member-name: a, member=value: b, parameters: {}}, rest: ""
```

**Comment by Jxck** [comment]
If "parameters optional itself" could be fix.
then something like below works fine for here.
(but it required widely change...)

```
dict-member    = member-name ( (";" parameters) /  ( "=" member-value ) )
```

**Comment by martinthomson** [comment]
@Jxck it sounds like you want unique particle attribution, which was never promised. The second interpretation, where there is no remainder, is what the algorithm produces.
