### ISSUE TITLE
The priorities I-D draft refers to non-existent FRAME_ENCODING_ERROR

### ISSUE THREAD

**Issue by dtikhonov** [httpwg/http-extensions#1277]
The latest version of the draft states:

> Failure to parse the Priority Field Value MUST be treated as a connection error of type FRAME_ENCODING_ERROR.

There is no such error either in [the HTTP/3 draft](https://tools.ietf.org/html/draft-ietf-quic-http-31#section-11.2.3) or in [RFC7540](https://tools.ietf.org/html/rfc7540#section-7).

Perhaps HTTP/3's _H3_FRAME_ERROR_ was meant?

**Comment by LPardue** [comment]
Dang, I worked from memory and should've spent 2 minutes for checking. I'll get this fixed up thanks.
