### ISSUE TITLE
Default incremental value in the new http priority scheme

### ISSUE THREAD

**Issue by yangchi** [httpwg/http-extensions#1300]
Reading https://tools.ietf.org/html/draft-ietf-httpbis-priority-02, it has the following on defaults:

> When receiving an HTTP request that does not carry these priority parameters, a server SHOULD act as if their default values were specified.

> The default value of the incremental parameter is false ("0").

This creates a problem to services that's already running a different resourse allocation scheme, when adopting the new proposal. Suppose one has production traffic where streams in the same connections have been behaving equivalent to incremental = 1. Adopting this new http priority proposal means we need to add a priority header to every request our clients send, to let it specify incremental=1 explicitly. Worse, for older clients, this is impossible to fix.

Can the default incremental value be left for implementation to decide? To remove the ambiguity when there is no clear default, client can use a SETTING frame to communicate the default incremental it desires. Server can also use a SETTING frame to communicate the default Incremental it would use when it receives a request that don't have the priority header.

**Comment by LPardue** [comment]
There's no single correct answer here, hence the recommendation is SHOULD.

Some work to date has shown that for typical web workloads, serving resources as FIFO is a sensible choice hence why incremental is default to false. If you have a server that thinks it better to apply a default of true, then there's nothing stopping you implementing it that way. 

Defining no default introduces too many unknowns. And adding a dependency on SETTINGS complicates this specification. I'm not conviced that either is needed.

**Comment by yangchi** [comment]
That's fair. I guess I didn't pay enough attention to this being a "SHOULD". Then this is fine.
