### ISSUE TITLE
rfc6265bis: be consistent about "header field"

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#1301]

**Comment by miketaylr** [comment]
@reschke can you provide some more context to this issue? What is inconsistent?

**Comment by miketaylr** [comment]
Re-ping @reschke. It's not clear to me what this issue means.

**Comment by reschke** [comment]
The correct term is "field", or "header field" or "trailer field" when specific to header section or trailer section.

"header" on it's own is not correct.
