### ISSUE TITLE
signatures: expected behaviour on unrecognized signature header parameters

### ISSUE THREAD

**Issue by llorllale** [httpwg/http-extensions#1304]
The draft has no normative text on expected behaviour when an unrecognized signature header parameter is encountered. Suggest adding normative text indicating implementations MUST produce an error when an unrecognized parameter is encountered (ie. they are not in the registry: https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-00#section-5.2.2).

**Comment by richanna** [comment]
The Structured Fields draft discourages field specifications from declaring the presence of unknown parameters to be an error condition, as this hurts forward compatibility with future extensions. This might be best left to profiling specifications.

**Comment by llorllale** [comment]
I wasn't aware of PR #1297 before I opened this issue.

That said, we might have to revisit the Structured Fields draft's guidelines on ignoring unknown parameters if we are to factor in `Signature-Input` in the computation of the `Signature`. We'd have to specify a canonicalization algorithm on `Signature-Input`.

**Comment by richanna** [comment]
We do have to fill in any ambiguities in the Structured Fields serialization algorithms, but unknown parameters shouldn't really affect that. The verifier can parse and serialize the parameters, even if it doesn't know what they mean. It's only when interpreting the field value that it should ignore them.

**Comment by jricher** [comment]
This should be clear in current drafts from -02 onward
