### ISSUE TITLE
signatures: datatypes of (created) and (expires)

### ISSUE THREAD

**Issue by llorllale** [httpwg/http-extensions#1305]
The draft defines an odd asymmetry between the data types of `(created)` and `(expires)` (respectively: integer string and decimal string). The non-normative examples all show `(expires)` as an integer string. Suggest we have them both as integer strings as:

* it simplifies implementations
* if omission of nanoseconds is OK on `(created)` (yes, imo), then it should be OK as well for `(expires)` imo

**Comment by richanna** [comment]
If you are signing a request being sent over a high throughput link between systems with good clock synchronization, 1000ms is way more lifetime than necessary. That said, I'm hard pressed to think of a scenario that would be mitigated by an expiration time of +200ms but not by an expiration time of +1000ms.

**Comment by msporny** [comment]
Agree, created/expires should be an integer representing time from epoch with 1000ms resolution.

**Comment by jricher** [comment]
These fields have been removed and redefined as parameters.
