### ISSUE TITLE
remove redundant definitions after transitioning to structured fields

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1311]
## I expect

- [x] to reference sf-decimal and sf-integer. It is probably more readable to define the params first, and then reference them in the content-identifier section
- [x] use SF reference, use Unixtime reference #1313

**Comment by msporny** [comment]
+1, agree that we should refer to sf-integer. Where would we refer to sf-decimal in the spec?

**Comment by ioggstream** [comment]
> +1, agree that we should refer to sf-integer. Where would we refer to sf-decimal in the spec?

https://github.com/httpwg/http-extensions/pull/1312/files#diff-1d57bca6223a0fee3ef29148c2550c0f862e72f67a56cc7f57b5a72fbd8320e3R262
