### ISSUE TITLE
HTTP Message Signatures - expired draft, please refresh

### ISSUE THREAD

**Issue by msporny** [httpwg/http-extensions#1318]
I'm getting a large volume of private emails asking why the HTTP Message Signatures has been allowed to expire in an active WG.

https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-00

I'm trying to reassure those people that the spec is still very much alive. When can we expect a new publication of the spec?

**Comment by ioggstream** [comment]
@richanna @jricher could you please create a -01? It's about

- git tag
- git push
- check your email

**Comment by mnot** [comment]
Please use e-mail to the authors to ask about things like this.
