### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#133]
Get advice from CFRG on crypto choices.

**Comment by mnot** [comment]
@martinthomson I take it you're comfortable with the amount of consultation done to this point? If so, please close (doubtless we'll get more in WGLC and beyond).

**Comment by martinthomson** [comment]
Yes, this is not going to improve.  (Feedback was that ChaCha20-Poly1305 or 25519 were better, which might be true, but AES and P-256 were acceptable.)
