### ISSUE TITLE
Effect of overwriting ordered dictionary entries

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1330]
In AUTH48, @bsdphk noticed that while we specify Dictionaries and Parameters as ordered dictionaries, we don't say what the effect of overwriting a value does to ordering.

From a quick play with the Python and Node REPLs, it appears that they both exhibit the behaviour that PHK intuited - that an overwrite will subsume the ordered position of what it replaces. E.g.,

~~~ javascript
> var a = {}
undefined
> a['1'] = 1
1
> a['2'] = 2
2
> a['3'] = 3
3
> a['2'] = 4
4
> a
{ '1': 1, '2': 4, '3': 3 }
~~~

I'll work up a PR to call this out shortly, just wanted to make sure people saw it.

/cc @phluid61 @annevk @clelland

**Comment by annevk** [comment]
It seems to me this is already clear. You overwrite the value of the existing key. You don't (get to) move it. Might be worth adding an example though.

**Comment by reschke** [comment]
Would be good to have a test and see what our current implementations do...

**Comment by phluid61** [comment]
FWIW, there is a test: https://github.com/httpwg/structured-field-tests/blob/4ac52e6de31a1a164cd1de0563edd701081a5b7b/dictionary.json#L139

**Comment by clelland** [comment]
Yes, I remember dealing with this specifically in the Chrome implementation; there is [language](https://github.com/httpwg/http-extensions/pull/1019) (and [tests](https://github.com/httpwg/structured-field-tests/pull/36)) in the spec about how to handle encountering a duplicate key in a dictionary or parameter list, and @annevk's interpretation matches what we do.

The spec only deals with parsing and serializing, though, not mutating the underlying data structures. There's no way for another spec to say "parse the header as a dictionary, then add an item, and serialize the dictionary", and guarantee byte-for-byte consistent results across implementations. This spec would have to define those operations (although that might be way out of scope here).

**Comment by annevk** [comment]
Well, the dictionaries are ordered and the parsing algorithm relies on add to add at the end so I think it's mostly there, but you could argue that "add" is not precisely defined I suppose (but in that case it'd be a problem for the current specification).

**Comment by clelland** [comment]
Yeah, it's a "most implementations would probably do the same reasonable thing" situation. I don't think it's necessary to change anything, since the spec is really just about parsing and serializing, and those cases are covered.

**Comment by annevk** [comment]
I don't see how you can differentiate between another specification building up a SV dictionary and the parser in this specification doing that. How are they different?

**Comment by phluid61** [comment]
We (collectively) made the conscious decision to not define fully-fledged data types with operations and interfaces and stuff. I can't remember which issue/thread it was in, but it was explicit. There is no "add", but ["Members are ordered as serialized..."](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#section-3.2-5) so it's implied.

I guess we could flesh out §4.2.2, Step 2.4:

> Add name this_key with value member to dictionary. If dictionary already contains a name this_key (comparing character for character), overwrite its value, otherwise insert it at the end.

..or something. I don't know how necessary it is, even if it were to be held as an erratum for a future update.

**Comment by annevk** [comment]
(Using https://infra.spec.whatwg.org/ as backend would simplify this quite a bit and would make adoption in WHATWG/W3C easier, though we could also define a translation between the types I suppose.)

**Comment by mnot** [comment]
The current text for dictionaries is:

> 4. Add name this_key with value member to dictionary. If dictionary already contains a name this_key (comparing character for character), overwrite its value.

I think this is clearer:

> 4. If dictionary already contains a name this_key (comparing character for character), overwrite its value.
> 5. Otherwise, append name this_key with value member to dictionary. 

... with a similar change to Parameters.

Does that work for everyone?

**Comment by martinthomson** [comment]
The alternative, which changes the results, and likely changes implementations, but ensures that wire order is better reflected is:

> 4. If dictionary already contains a name this_key (comparing character for character), remove its value.
> 5. Append name this_key with value member to dictionary. 

I think that I would prefer this, but I realize that it might be disruptive.

**Comment by mnot** [comment]
@martinthomson that would not only be disruptive (requiring changes in tests and implementations), but as per above would be counter to how this data structure works in common language implementations, so I suspect it would lead to much confusion.

**Comment by martinthomson** [comment]
I don't think that it is counter to how the structure works.  I know that if you just do `x[y] = v` in most language that doesn't reorder `y`.  But `delete x[y]; x[y] = v` should produce the same outcome everywhere.

**Comment by mnot** [comment]
Anyone else with a preference for this?

**Comment by phluid61** [comment]
Given the situation, my preferences are:

1. no change to anything; it's not 100% clear, but the right answer can already be inferred
2. change the wording of the algorithm but keep the implementation the same; @mnot's https://github.com/httpwg/http-extensions/issues/1330#issuecomment-730696699 is okay

@martinthomson:
> I don't think that it is counter to how the structure works.

This issue only became relevant when we decided to let different parties emit the same field name in an unbuffered stream, and give preference to the later ones. (Originally we dropped the subsequent dupe, so first won.) If ordering matters _in that case_ we should be providing explicit reordering tools, so that the later entity can prepend/insert/delete/etc. But we don't. So the later entity either sucks up the fact that the earlier entities decide the ordering, or it buffers the fields and explicitly reorders them.

Aside from all that, we're making a whole lot of fairly substantive changes to a spec that's gone through all its last calls. If it's this wrong, should we pull it back and start over?

**Comment by annevk** [comment]
@martinthomson's suggestion was not considered in https://github.com/httpwg/http-extensions/issues/997#issuecomment-564861602, i.e., return `{ k2: v2, k1: v3 }`, but to me at least the status quo seems preferable. At least all such similar data structures that come to mind would either discard `k1=v3` or overwrite `k1`'s value, not remove `k1` and then append it again with the new value. @kazuho @LPardue thoughts?

@phluid61 I looked at https://github.com/httpwg/http-extensions/commits/master/draft-ietf-httpbis-header-structure.md and did not see any substantive changes. Could you please highlight them?

**Comment by phluid61** [comment]
#1273 and this ticket are more than just editorial 

#1322 is substantive, but I think it's being rejected (?) 

#1251 raised an issue that wasn't caught in any review but was rejected because it's in AUTH48 

That might not be 'a whole lot', seeing them listed out, but this has been an awfully long 48 hours, and I've not seen this many issues raised, or notes to the editor to make changes, at this stage before.

**Comment by clelland** [comment]
If dictionary and parameter order is important at all, and the spec currently implies that it is ("Field specifications can constrain the order of individual Dictionary members" and "Field specifications can constrain the order of individual parameters",) then I don't think that https://github.com/httpwg/http-extensions/issues/1330#issuecomment-730726050 is ideal.

Being able to overwrite individual parameter values could be useful, but less so if it also changes the ordering, when that ordering is constrained.

https://github.com/httpwg/http-extensions/issues/1330#issuecomment-730696699 is still clear, and matches my current understanding of the spec, the tests in place, and the existing Chromium implementation.

**Comment by bsdphk** [comment]
I prefer Marks clarification over Martins proposed change.

@phluid61  A lot of the AUTH48 duration has been XML/toolchain issues.

**Comment by Lukasa** [comment]
I also prefer Mark’s clarification to changing the behaviour of the specification at this late stage.

**Comment by mnot** [comment]
OK, we seem to have agreement; asking the RFC Editor for the change as outlined above (Barry may weigh in on whether this is OK).

Request is as follows:

1) In #parse-dictionary, replace:

   4. Add name this_key with value member to dictionary. If dictionary already contains a name this_key (comparing character for character), overwrite its value.

with:

   4.	If dictionary already contains a name this_key (comparing character for character), overwrite its value with member.
   5. Otherwise, append name this_key with value member to dictionary.

2) In #parse-param, replace:

   7. Append key param_name with value param_value to parameters. If parameters already contains a name param_name (comparing character for character), overwrite its value.

with:

   7.	If parameters already contains a name param_name (comparing character for character), overwrite its value with param_value.
   8. Otherwise, append name param_name with value param_value to parameters.

(note that I've added `with_member` and `with param_value` to clarify what they're being overwritten with)
