### ISSUE TITLE
[6265bis] Align on HTML terminology for origins

### ISSUE THREAD

**Issue by miketaylr** [httpwg/http-extensions#1337]
It seems desirable to align with HTML and use [tuple origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin-tuple) instead of "scheme/host/port triple" (from https://tools.ietf.org/html/rfc6454).

See https://github.com/httpwg/http-extensions/pull/1324/files#r530145898 and https://greenbytes.de/tech/webdav/draft-ietf-httpbis-semantics-12.html#origin for related discussion.

cf. https://github.com/mikewest/cookie-incrementalism/pull/3#discussion_r390775633

(edit: updated to point to multi-page version of HTML, apologies for linking the single-page one!)

**Comment by reschke** [comment]
Unless there's a problem with it, it might be better to use http-core's definition (*if* there is a problem with it, now would be a good time to raise an issue)

**Comment by royfielding** [comment]
The tuple origin concept is an extension (or limitation) of permissions associated with same origin beyond what is considered the origin. HTTP core only defines origin, which is consistent with the current text in WHATWG html, and would still be consistent if you refer to the html tuple concept in Cookies.

**Comment by miketaylr** [comment]
I think it would also be a win for clarity in 6265bis if in place of `globally unique identifier` we used HTML's [opaque origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin-opaque). AFAICT, http-core doesn't have a mechanism defined for this.

**Comment by miketaylr** [comment]
It sounds like there are no objections, so I will write a PR (once #1348 is merged, to avoid conflicts for some of the usage of "globally unique identifier".

**Comment by englehardt** [comment]
> It sounds like there are no objections, so I will write a PR (once #1348 is merged, to avoid conflicts for some of the usage of "globally unique identifier".

SGTM
