### ISSUE TITLE
Failed to publish a new draft of RFC6265bis.

### ISSUE THREAD

**Issue by mikewest** [httpwg/http-extensions#1338]
https://github.com/httpwg/http-extensions/runs/1509108501?check_suite_focus=true shows the log of a failure to publish `draft-ietf-httpbis-rfc6265-07`. The relevant snipped from the failed step ("Upload to Datatracker") is below:

```
/usr/bin/docker run --name ghcriomartinthomsonidtemplateactionlatest_8ad9cd --label 179394 --workdir /github/workspace --rm -e INPUT_MAKE -e INPUT_TOKEN -e GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/http-extensions/http-extensions":"/github/workspace" ghcr.io/martinthomson/i-d-template-action:latest  "upload"
git clone -q --depth 10  \
    -b main https://github.com/martinthomson/i-d-template lib
lib/main.mk:20: Forcing rebuild of .targets.mk
error: lib/default-branch.py unable to determine default branch
error: lib/default-branch.py unable to determine default branch
make: Nothing to be done for '.targets.mk'.
error: lib/default-branch.py unable to determine default branch
make: *** No rule to make target '.draft-ietf-httpbis-rfc6265-07.upload', needed by 'upload'.  Stop.
```

As in #1031, I'll generate the text manually and upload it via datatracker, but I'd appreciate some help in case I did something wrong here, or someone looking into the workflow in case I didn't. :)

**Comment by mikewest** [comment]
Erm. This is likely because I'm dumb and typed `rfc6265` instead of `rfc6265bis`. Trying again.

**Comment by martinthomson** [comment]
Oops.  Those error messages are pretty obtuse, but hard to defend against.  I guess that I could add to the existing pre-push hook for tags.  Not that everyone engages those hooks.

The default branch thing is down to GH being weird about its checkouts, for which an API token is needed just to get the branch name.  That can be fixed in this repo by providing a token.

**Comment by mikewest** [comment]
So, I still think this was my fault, but when I uploaded another (correctly-spelled) tag, it failed in exactly the same way (presumably because it's publishing everything it hasn't already published?). I then deleted the incorrect `draft-ietf-httpbis-rfc6265-07` tag from the GitHub repo, and uploaded the draft manually.

I think we can close this as me being dumb. Perhaps @mnot, et al would like to follow up on the API token bits at some point in the future, though?

**Comment by mnot** [comment]
Sure. @martinthomson what do we need to do?

**Comment by martinthomson** [comment]
The only real change for this repo would be to suppress the default branch warnings, but that isn't really going to help with Mike's problem.  I've opened https://github.com/martinthomson/i-d-template/issues/253 to track the usability issue.
