### ISSUE TITLE
[6265bis] Clarification on cookie size limits

### ISSUE THREAD

**Issue by miketaylr** [httpwg/http-extensions#1340]
https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-07#section-6.1 states:
>    Practical user agent implementations have limits on the number and
   size of cookies that they can store.  General-use user agents SHOULD
   provide each of the following minimum capabilities:
>      *   At least 4096 bytes per cookie (as measured by the sum of the
      length of the cookie's name, value, and attributes).

IMHO, the prose here is a little confusing. It's clearly talking about limits on size, but then says the "minimum capability should be at least 4096 bytes per cookie". That I think can be cleaned up.

In addition, it's worthwhile looking into the current situation of interop on these limits. @chlily1 pointed me at http://www.ruslog.com/tools/cookies.html which has some interesting (older) research on the topic.

Other related links: 

Chrome considers name, =, value, and attributes when checking the 4096 cap:
https://source.chromium.org/chromium/chromium/src/+/master:net/cookies/parsed_cookie.cc;drc=b35da1f38c91cbc8a3ec0f934b747360fa9a0f73;bpv=1;bpt=1;l=133

Firefox only looks at name and value when checking the 4096 cap, and not attributes.
https://searchfox.org/mozilla-central/rev/ffdb6a4d934b3f5294f18cf0e1df618109ccb36b/netwerk/cookie/CookieCommons.cpp#193-197

But, Firefox enforces a limit on the path attribute:
https://searchfox.org/mozilla-central/rev/ffdb6a4d934b3f5294f18cf0e1df618109ccb36b/netwerk/cookie/CookieCommons.cpp#189-191

So neither Firefox nor Chrome are strictly following 6.1 here (but yes, it's a SHOULD).

Need to look at what Safari and other clients do.

**Comment by miketaylr** [comment]
I forgot to note that interop here seems desirable to prevent using these differences as a browser fingerprinting mechanism.

**Comment by karlcow** [comment]
@miketaylr 

WebKit

https://github.com/WebKit/WebKit/blob/88278b55563e5ccdc0b3419c6c391c3becc19e40/Source/WebCore/platform/network/curl/CookieUtil.cpp#L143-L144

and MAX_COOKIE_LINE is `5000`

https://github.com/WebKit/WebKit/blob/88278b55563e5ccdc0b3419c6c391c3becc19e40/Source/WebCore/platform/network/curl/CookieUtil.cpp#L37-L49

and fwiw the MAX_NAME doesn't seem to be used in the code.

**Comment by miketaylr** [comment]
OK, to recap, the current the spec text states:

>  At least 4096 bytes per cookie (as measured by the sum of the length of the cookie's name, value, and attributes).

Browsers interpret that "at least" as "at most", so we should change that.

Here's what browsers are doing:

Firefox: sets `kMaxBytesPerCookie = 4096` and adds up the name and value lengths (minus the =), and does not consider attributes. however, it seems there are constraints on the path size (1024 bytes) that can cause a cookie to be rejected. But expires, for example, I believe can add an additional 8 bytes to the total cookie size. And then there's attribute names' length to consider.

Chrome: sets `kMaxCookieSize = 4096;`, and counts the entire cookie string length (that is, everything from `Set-Cookie:` to the first of `kTerminator[] = "\n\r\0";`)

Safari: sets `#define MAX_COOKIE_LINE 5000` and also counts the entire cookie string length (`if (cookieLine.length() >= MAX_COOKIE_LINE)`. But my tests show it only allows a total cookie length of 4096.

**Comment by miketaylr** [comment]
> MAX_COOKIE_LINE is `5000`
> 
> https://github.com/WebKit/WebKit/blob/88278b55563e5ccdc0b3419c6c391c3becc19e40/Source/WebCore/platform/network/curl/CookieUtil.cpp#L37-L49

I'm not really sure if Safari is using that (because I'm not super familiar with the WebKit codebase), but here is where that was added to curl, with a nice commit message: https://github.com/curl/curl/commit/2bc230de63bd7da197280a69d84972b61455cd18

**Comment by miketaylr** [comment]
My general thinking here is that we should set a minimum for name+value, as well as a limit on attribute values. Perhaps something like 1024 bytes for attributes, and 4096 for name+value (similar to what Firefox does).

We should have some metrics from Chrome to look at in a few weeks to help us determine if this is web-compatible. In theory a domain or path attribute could be much larger than 1024 bytes. Hopefully not in practice?

**Comment by miketaylr** [comment]
> Safari: sets `#define MAX_COOKIE_LINE 5000` and also counts the entire cookie string length (`if (cookieLine.length() >= MAX_COOKIE_LINE)`. But my tests show it only allows a total cookie length of 4096.

I've since learned this isn't true -- this is curl code that's inside WebKit. Safari seems to bound by the limitations of https://developer.apple.com/documentation/foundation/nshttpcookie which aren't well documented (at least, I can't find good documentation). You can make really, really large cookies because NSHttpCookie supports the Set-Cookie2 comment attribute (up to 28k just for the comment alone).

**Comment by chlily1** [comment]
Addressed by #1563
