### ISSUE TITLE
digest-headers: cites Section 3.4.5 of SRI but that section does not exist

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#1353]

**Comment by reschke** [comment]
There's also:

"... This allows for protection of distinct resources sharing a URL. However, this is a contrast to the design of representation digests, where multiple Digest field-values all protect the same representation."

Actually, if these resources share the same URI, they are (in HTTP terminology) representations of the same resource.

**Comment by LPardue** [comment]
That's a good observation. My intention was to link the following text in Section 3.3.5 of the SRI spec, with the concept of of representation digest here.

```
which would allow the user agent to accept two different content payloads, one of which matches the first SHA-384 hash value and the other matches the second SHA-384 hash value.
```

What is the best way to phrase this in HTTP terminology?
