### ISSUE TITLE
digest-headers: confusing section "Server Returns No Representation Data"

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#1357]
In 10.2 Server Returns No Representation Data:

- what does the Digest request header field on the HEAD request refer to, and what is the recipient supposed to do with it?
- there's only one digest in the response, but the prose talks about two

**Comment by ioggstream** [comment]
> In 10.2 Server Returns No Representation Data:
> 
> * what does the Digest request header field on the HEAD request refer to, 
Requests without payload data can still send a `Digest` field applying the digest-algorithm to an empty representation.

> and what is the recipient supposed to do with it?
The recipient can validate that the digest-value matches the one of an empty representation or not.

> * there's only one digest in the response, but the prose talks about two
True. this is confusing, should reference the previous example.:

```
the id-sha-256 digest value in the response is the same of the sha-256 digest value of the response in {{example-full-representation}}
```
