### ISSUE TITLE
digest-headers: support vs SRI

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#1363]
"There is a chance that a user agent supporting both mechanisms may find one validates successfully while the other fails. This document specifies no requirements or guidance for user agents that experience such cases."

This makes it sound almost as if it could be ok to ignore an error on one level if there's no error on the other level. I think the spec should say that a user agent supporting both mechanisms must implement all requirements of both specs, no matter what.

**Comment by LPardue** [comment]
Thanks Julian. I agree and will make a PR to tighten up the language.

**Comment by ioggstream** [comment]
@reschke  should we really specify what a SRI implementor should do? 

RFC3230 explicitly states that https://tools.ietf.org/html/rfc3230#section-4.3.2

>   A recipient MAY ignore any or all of the instance-digests in a Digest
>   header field.

and we are not changing this.
