### ISSUE TITLE
digest-headers: 10.9, Location field missing in response

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#1365]

**Comment by ioggstream** [comment]
§10.9 seems to me Digest with PATCH. Can you pls link the code?

 Why is Location needed? do you mean content-location?  

Thx++!

**Comment by reschke** [comment]
Sorry, "10.7. POST Response does not Reference the Request URI" in current editor's copy.

**Comment by ioggstream** [comment]
fixed in https://github.com/httpwg/http-extensions/commit/057476ebcd216958f610059a799310fbe519f042
