### ISSUE TITLE
Third-party cookies

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1372]
In [the current draft's privacy considerations](https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#name-third-party-cookies):

> Given this risk to user privacy, some user agents restrict how third-party cookies behave, and those restrictions vary widly. For instance, user agents might block third-party cookies entirely by refusing to send Cookie headers or process Set-Cookie headers during third-party requests. They might take a less draconian approach by partitioning cookies based on the first-party context, sending one set of cookies to a given third party in one first-party context, and another to the same third party in another.
>
> This document grants user agents wide latitude to experiment with third-party cookie policies that balance the privacy and compatibility needs of their users. However, this document does not endorse any particular third-party cookie policy.

Is this still true?

**Comment by chlily1** [comment]
Which part of it are you asking about, specifically?

The part about "grants user agents wide latitude" is certainly true. It allows UAs to [ignore Set-Cookie headers in their entirety](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-07#section-5.3) and [omit the Cookie header entirely](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-07#section-5.5). I suppose it does not technically allow for selectively withholding certain cookies from the Cookie header. (Maybe that should be allowed?)

The part about not endorsing any third-party cookie policy is probably also fine. It gives examples of a third-party cookie policy that drops Set-Cookie and Cookie headers entirely on third-party requests, but I don't think this constitutes an endorsement.

**Comment by chlily1** [comment]
@mnot Does that answer your question? Please reopen if not, or if you think there are any changes needed.

**Comment by mnot** [comment]
I was wondering if, given how much has changed in the intervening years, we could go a little further and say something about how third-party cookies cannot be relied upon to work by sites because they are abused, and current techniques for mitigating that abuse are not standardised.

Happy to write up a proposal if that would help.

**Comment by sbingler** [comment]
I don't feel strongly here but if you think some updated wording would help I'm happy to review a proposal.

**Comment by mnot** [comment]
See PR.

**Comment by annevk** [comment]
Given that the PR got merged, should this be closed?

There's agreement emerging to block cross-site cookies, but perhaps that's best covered in a new issue.

**Comment by jwrosewell** [comment]
@annevk There may be an agreement among browser vendors and a small number of others within the IETF however the distinction between first / third or cross-site is not recognised by a wider group of stakeholders including the UK Information Commissioner's Office (ICO) and the Competition and Markets Authority. See [their joint statement](https://ico.org.uk/media/about-the-ico/documents/2619797/cma-ico-public-statement-20210518.pdf) from May 2021.

> Data is sometimes categorised according to the relationship between the party collecting and processing it and the individual or circumstance it relates to:

> • First-party data: data that is collected by a business through direct interaction with an individual providing or generating the data. For example, data collected by an online retailer regarding purchases made by consumers on its site. 

> • Third-party data: data collected by a business not in direct interaction with the individual providing or generating the data, for example, through business partners. Digital firms that do not have a direct relationship with users frequently rely on third-party data.

> The boundaries between first and third-party data according to the above definition are not always clear, particularly when large companies own a variety of businesses, some of which have a relationship with the user and some of which do not.
Both first-party and third-party data as defined above can include personal and non personal data. Whether information is personal data depends on whether it relates to an identified or identifiable individual. There is no explicit reference to the distinction between first-party and third-party data in data protection law.

> The descriptions of ‘first party’ and ‘third party’ are also used (though with a different meaning) in the context of cookies and similar technologies,10 which collectively form the key means by which information (including personal data) is collected and disseminated in online advertising. A cookie is generally identified as being first-party if the domain of the cookie matches the domain of the page visited and as being third-party in instances where the domain of the cookie does not match the domain of the website. This is not a rigid distinction. Some functions typically delivered through third party cookies can be done via first party cookies, even if a third party’s code and associated service is still involved.

> The rules on the use of cookies and similar technologies are specified in Regulation 6 of the Privacy and Electronic Communications Regulations 2003 (as amended) (‘PECR’), and oversight of these rules is one of the ICO’s regulatory functions. PECR provides more specific rules than the UK GDPR in a number of areas such as cookie use. It is also important to note that PECR’s provisions in this area apply whether or not personal data is processed.

This debate in this group consists of browser vendor representatives and a small number of others, agreeing to work with each other to exclude other non browser vendors from the market.

**Comment by mnot** [comment]
*chair hat on*

@jwrosewell, in the comment above you characterise / assume others' motivations. That does not promote good-faith participation in the work, and can be harmful to the consensus process. It also is perceived as an ad hominem attack by some.  Please refrain from doing this in the future. 

Additionally, this document is a technical document -- it does not purport to state legal constraints, nor do we have the authority to do so. As such, it's off-topic, and so I'm hiding the comment.

**Comment by miketaylr** [comment]
> Given that the PR got merged, should this be closed?

It seems fair to close now, yes.
