### ISSUE TITLE
Support for Partial Hits

### ISSUE THREAD

**Issue by elithrar** [httpwg/http-extensions#1381]
Continuing a discussion with @mnot  - 

The current draft[1] of the `cache-status` header specifies that ""hit" and "fwd" are exclusive; only one of them should appear on each list member.". 

If a "downstream" (user-facing) cache has a partial hit - say, a 2MB chunk of a larger object, it is challenging to accurately map that representation in the cache-status header. 

For example:

1. The user requests a larger video file - say, an 8MB segment
2. The cache has this stored in 2MB (or smaller) chunks
3. The cache closest to the client has the first 6MB, but not the last 2MB, and needs to fetch that from an upstream cache (or the origin; it doesn't know) 
4. The last 2MB chunk is fulfilled by an upstream.

This would be naively represented as `x-cache-status: PARTIAL, HIT`. Without constraints, it could potentially be represented as `cache-status: ExampleCache; fwd=partial; hit`.

In the case the next tier of caching did not have the segment, then it would be `cache-status: ExampleCache; fwd=partial; fwd=miss; hit`. 

That is, a cache may be able to fulfill _part_ of the response, but not all, and this is useful to distinguish vs. a full hit - e.g. from a latency/performance perspective.

[1]: https://tools.ietf.org/id/draft-ietf-httpbis-cache-header-06.html

**Comment by mnot** [comment]
I think that `fwd=partial` makes sense, with the semantic that the cache had a partial, fresh response stored that could be used to satisfy part of the request, but not all of it, so the cache needed to go forward for that reason.

hit` and `fwd` in the same member of `Cache-Status` isn't allowed by the spec right now; allowing that would muddy what the meaning of `hit` is. I know that it's already muddy in existing headers and logs, but this is a good opportunity to crisp it up.

I'll try to clarify this a bit more in the spec.

**Comment by mnot** [comment]
@elithrar see commit above, as well as https://github.com/httpwg/http-extensions/commit/b581968fa0

**Comment by mnot** [comment]
(and many thanks for the suggestion!)
