### ISSUE TITLE
Digest: Invalid SFV format for Digest field

### ISSUE THREAD

**Issue by Jxck** [httpwg/http-extensions#1388]
https://tools.ietf.org/html/draft-ietf-httpbis-digest-headers-04#section-3

```http
Digest: id-sha-512=WZDPaVn/7XgHaAy8pmojAkGWoRx2UFChF41A2svX+TaPmAbwAgBWnrIiYllu7BNNyealdVLvRwE\nmTHWXvJwew==

Digest: sha-256=4REjxQ4yrqUVicfSKYNO/cF9zNj5ANbzgDZt3/h3Qxo=,
             id-sha-256=X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=
```

`=` for padding on base64 string is [invalid](https://jxck.github.io/structured-field-values/demo.html#c2hhLTI1Nj00UkVqeFE0eXJxVVZpY2ZTS1lOTy9jRjl6Tmo1QU5iemdEWnQzL2gzUXhvPSwgaWQtc2hhLTI1Nj1YNDhFOXFPb2txcXJ2ZHRzOG5PSlJKTjNPV0RVb3lXeEJmN2tidTlEQlBFPQo=) for Dict format on Structured Field Values.
if include base64 string value itself, it should be a string. or use Byte Sequence of signature binary and it will encoded in base64 in sfv way (padding with `:`).

```http
Digest: sha-256="4REjxQ4yrqUVicfSKYNO/cF9zNj5ANbzgDZt3/h3Qxo=", 
             id-sha-256="X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE="
```
[result](https://jxck.github.io/structured-field-values/demo.html#c2hhLTI1Nj0iNFJFanhRNHlycVVWaWNmU0tZTk8vY0Y5ek5qNUFOYnpnRFp0My9oM1F4bz0iLCBpZC1zaGEtMjU2PSJYNDhFOXFPb2txcXJ2ZHRzOG5PSlJKTjNPV0RVb3lXeEJmN2tidTlEQlBFPSI=)

or

```http
Digest: sha-256=:4REjxQ4yrqUVicfSKYNO/cF9zNj5ANbzgDZt3/h3Qxo=:,
             id-sha-256=:X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=:
```
[result](https://jxck.github.io/structured-field-values/demo.html#c2hhLTI1Nj06NFJFanhRNHlycVVWaWNmU0tZTk8vY0Y5ek5qNUFOYnpnRFp0My9oM1F4bz06LCBpZC1zaGEtMjU2PTpYNDhFOXFPb2txcXJ2ZHRzOG5PSlJKTjNPV0RVb3lXeEJmN2tidTlEQlBFPTo=)

**Comment by LPardue** [comment]
Thanks for the report. Digest is however not defined as a Structured Field. And since the document is an update to an existing RFC we have decided not to change definition.

**Comment by Jxck** [comment]
ah, my misreading. https://tools.ietf.org/html/draft-ietf-httpbis-digest-headers-04#appendix-B mentions only lowercased.

**Comment by LPardue** [comment]
No problem, it would be nice to support SFV but we discussed it and seems too disruptive disruptive change. That ship probably sailed 20 years ago 😀
