### ISSUE TITLE
digest-headers: refer to 6151/6194 for md5/sha1 deprecation

### ISSUE THREAD

**Issue by seanturner** [httpwg/http-extensions#1392]
In s12.2, should refer (informatively) to [RFCs 6151](https://datatracker.ietf.org/doc/rfc6151/) and [6194](https://datatracker.ietf.org/doc/rfc6194/) for IETF references that deprecate the use of md5 and sha1, respectively.

**Comment by LPardue** [comment]
Thanks for the pointers, sgtm
