### ISSUE TITLE
digest-headers: update HTTP Digest Algorithms Values registry reference

### ISSUE THREAD

**Issue by seanturner** [httpwg/http-extensions#1393]
Add instructions for IANA in s13.1 that addresses whether you would like the [HTTP Digest Algorithms Values](https://www.iana.org/assignments/http-dig-alg/http-dig-alg.xhtml) registry to also point to this RFC-to-be; I am sure they will ask during the IANA review stage so might as well state that now.

**Comment by LPardue** [comment]
Thanks for the tip, let's do this.

**Comment by reschke** [comment]
Isn't that self-evident given the fact that the document obsoles RFC 3230?

**Comment by seanturner** [comment]
I am not 100% sure of this, but I think IANA won't automatically replace the registry's "Reference" with the latest. Lots of times registries refer to the RFC that created the registry. For example, many of the TLS registries still refer to RFC 5246 despite RFC 8446 obsoleting it. It is best to be explicit about what you would like IANA to do. Something as simple as "IANA is also requested to update the "Reference" for this registry to refer to this document" is sufficient.

**Comment by reschke** [comment]
Ack; this well indeed help with that.

**Comment by ioggstream** [comment]
Do we need to  `updates: 5843` ?

**Comment by ioggstream** [comment]
@seanturner you are probably the best person to provide a PR on that ;) Do you think you can make an attempt?

**Comment by seanturner** [comment]
Will do.

**Comment by ioggstream** [comment]
see #1652 . Task moved to #1533
