### ISSUE TITLE
digest headers: HTTP Digest Algorithm Values registration rules

### ISSUE THREAD

**Issue by seanturner** [httpwg/http-extensions#1394]
When RFC 3230 was published the fashion was to require an RFC. But, RFC 3230 was ahead of it's time and allowed Specification Required. The current fashion seems to lowering bar to just Specification Required (e.g., TLS algorithm registries. Should the registration rules be changed to be just Specification Required?

**Comment by LPardue** [comment]
Given that the current registry has only two RFC-related algorithms I'm inclined to take the suggestion to relax the rules to Specification Required. 

I wonder what @manger thinks?

**Comment by ioggstream** [comment]
Reorganized to https://github.com/httpwg/http-extensions/issues/1394

**Comment by MikeBishop** [comment]
@ioggstream, I don't think #1522 is what you meant.
