### ISSUE TITLE
"Original-Content-Length" to indicate data savings

### ISSUE THREAD

**Issue by igrigorik** [httpwg/http-extensions#140]
This is not CH specific but the desire for such thing has come up a few times...

1. Client advertises some content/quality/etc preference to the server (e.g. `Save-Data`)
1. Server responds with an alternate response based on advertised preference (e.g. a "light" version of the page, an image with higher compression ratio, etc). 
  - In addition to the `Content-Length` of the response, the server wants to advertise the "Original content length" of the response that would have been provided if the preference was not there.

In the context of `Save-Data` this is to enable user-reporting for amount of bytes saved - e.g. since you've enabled this mode, the browser fetched 100MB, which is 40% less than if you had this disabled.

Popular proxies (e.g. Chrome's Data Saver) already do this via `X-Original-Content-Length`: the proxy reports the content length of before and after applying its optimization. Other popular proxy implementations offer similar functionality (Opera, Yandex, etc). It would be nice to have a standard way to do this, and to enable origins to report this as well. 

Related discussions: 
- https://github.com/igrigorik/http-client-hints/pull/42
- https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/alternate/blink-dev/lj7wSXPBPWE/fE5UGl_2y1QJ

**Comment by martinthomson** [comment]
That's a pretty long name.  Aren't you worried about negating the savings?

**Comment by igrigorik** [comment]
![hmm](http://49.media.tumblr.com/tumblr_m161dvVeAQ1r4ghkoo1_500.gif)

**Comment by igrigorik** [comment]
Not hearing a strong demand for this. Closing. We can reopen if and when that changes.
