### ISSUE TITLE
proxy-status: confused about extra parameters 

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1403]
I got deep linked into the proxy-status draft, read some lines and made a wrong assumption about what a valid Proxy-Status looks like. Luckily my mistake was pointed out and I can reason about most of the spec. However, I'm still confused by the extra parameters part in each error type definition. Are they being defined there? At they unique? Are they mandatory to appear? What if the wrong extra parameter appear on the wrong type? 

There seems to be quite a few extra parameters that look quite similar, this seems like a possible avenue for getting things wrong.

**Comment by mnot** [comment]
PTAL at the commit above; does that help?

**Comment by LPardue** [comment]
Partly. I think this sentence 

```
Proxy Error Types can also define any number of extra parameters for use with that type. Their use, like all parameters, is optional.
```

Is still ambiguous though. Does this mean it is optional to generate or parse or both? (This is probably covered by "use" but I'm a bit simple)

I'm also not sure it covers a pathological case like e.g. 

```
Proxy-Status: StupidProxy; error=http_request_denied; status-code=500
```

I'd presume that an implementation of Proxy-Status has code paths that cover all case in this document. So it would be reasonable for it handle `status-code` in the case of `http_request_error` but ignore it in `http_request_denied`. This implies it's not optional to ignore the extra parameter when it is not used in the correct context.

**Comment by mnot** [comment]
WRT generate vs parse -- both; there isn't a processing model for P-S, so I don't think the distinction is relevant (actual parse and serialise requirements are deferred to structured fields).

So, it's not so much a matter of 'handle' -- there is no handling.

**Comment by LPardue** [comment]
If there's no handling, then who does the advice "Unrecognised parameters SHOULD be ignored." apply to? the parser? 

Apologies for the basic question. I think I need to adjust my mental model that anyone can stick any param into the header and that its main use is for debugging stuff.

**Comment by mnot** [comment]
It applies to people who are confused about this headers' purpose :)

Can we do anything else to clarify this?

**Comment by LPardue** [comment]
If the answer is to go away and get better I can live with that. But I might suggest something explicit like 

```
Proxy Error Types can also define any number of extra parameters for use with that type. Their use, like all parameters, is optional. If an extra parameter is used with an Error Type for which is not defined, it MUST be ignored."

**Comment by mnot** [comment]
By definition, an extra parameter used without its paired PET is unrecognised, and therefore ignored (because they don't conflict in the registry, as per the recent addition). I can make this explicit if you feel it'll help.

**Comment by LPardue** [comment]
I am missing that nuance so text would help I think.

**Comment by mnot** [comment]
Done. I didn't make it a requirement.

**Comment by LPardue** [comment]
Thanks Httpwg/Http-Extensions!
