### ISSUE TITLE
digest in trailer, algorithm in header

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1407]
## I expect

In the case where the digest is included in the trailer (Section 10.11
[1]), it may be beneficial for the client to know *which* digest the
server plans to include in the trailer.  This way, the client, too, can
calculate it in the streaming manner.  I wonder whether this use case
has been considered.

thx @dtikhonov 

## Note

A new Header can be added, eg. Has-Digest: 1#digest-algorithm

```
GET /file.txt
Host: foo.example
Has-Digest: sha-256, id-sha-256
Trailer: Digest

Hello World

Digest: sha-256=YYYYYYY=, id-sha-256=XXXXXXXX=
```

## Bikeshed

- a new I-D (I can prepare it)
- a new Header in this I-D (only if you suggests to do so).

**Comment by LPardue** [comment]
The use case seems valid but I wonder if anyone really has any intent to implement such a thing. This seems to mainly require a digest algorithm that can be calculated in a streaming manner. I've not seen much evidence of those existing and used for digest.

Then we have to explain resource usage examples which predominantly only works when the entire selected representation is sent.

I don't see this discussion as a bikeshed. We need clear implementer intent to expend any effort on adding a new feature. Without that, I propose to close yhis issue on digest with no action.

**Comment by ioggstream** [comment]
@LPardue how can we track this issue? I think it's valuable.

**Comment by LPardue** [comment]
I don't know what needs to be tracked. This is a feature request, which as far as I can tell has no implementation experience. The ability to stream calculate a digest is mainly an optimisation IMO.  Is the use of digest performance sensitive? Is it really on the critical path? Given what I know about how client treat trailers and how they process responses, I'm dubious this feature can help realize the goals as I understand them. 

Sounds like something that can be explored in other work to me, to decide if there's any interest in standardising it.
