### ISSUE TITLE
Should CH headers be treated as simple headers?

### ISSUE THREAD

**Issue by igrigorik** [httpwg/http-extensions#141]
Migrating https://github.com/igrigorik/http-client-hints/issues/68. A quick summary:

1. CH headers should be seen by ServiceWorker
1. CH headers should not trigger CORS preflight if...
  1. Set by the UA and not modified by the developer? 
  1. Set by the UA _or_ the developer? That is, treat them as [simple headers](https://fetch.spec.whatwg.org/#simple-header).

**Comment by igrigorik** [comment]
Related Chromium issue for Save-Data: https://code.google.com/p/chromium/issues/detail?id=584889

**Comment by sicking** [comment]
I definitely agree with 1 and 2i. There's no reason to hide the header from SWs or to require preflight for UA-provided CH headers any more than UA-provided accept/user-agent/etc headers.

Regarding 2ii, is it expected that websites will override the CH headers commonly? What is the use case?

**Comment by martinthomson** [comment]
I expect that some service workers might either request full versions of resources because they want to provide the full experience offline, or leaner versions so that they can save space.

**Comment by sicking** [comment]
Fair enough. Yeah, I think it's fine to treat them as simple headers.

**Comment by igrigorik** [comment]
This was resolved in https://github.com/whatwg/fetch/commit/404dc3acfddb5e9870fdee333302f80ecff661dd, closing.
