### ISSUE TITLE
cache-status: 2-layer example is a little ambiguous

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1412]
There's an example that says:

> Going through two layers of caching, both of which were hits, and the second collapsed with other requests:
```
Cache-Status: OriginCache; hit; ttl=1100; collapsed,
              "CDN Company Here"; hit; ttl=545
```

After reading the draft I'm not sure if the two layer example is correct or not, which doesn't seem ideal. Perhaps this is just me being unfamiliar with caching.

Early in the draft, you say 

> The first member of the list represents the cache closest to the origin server, and the last member of the list represents the cache closest to the user

So the phrase "second collapses" is a bit lose - it relates to the first entry which is the second cache.

Further, later you say 

> "hit", when true, indicates that the request was satisfied by the cache; i.e., it was not forwarded, and the response was obtained from the cache.

So why did the first cache `CDN Company Here` pass on the request to `OriginCache`. Or is this documenting that the first cache stored `OriginCache's` `Cache-Status` header and then appended its own entry to the list when serving this response?

**Comment by mnot** [comment]
PTAL - does that help?

**Comment by LPardue** [comment]
Yes, thanks!
