### ISSUE TITLE
RFC6265bis Spec does not match Lax-Allowing-Unsafe behavior implemented in Chrome and Firefox

### ISSUE THREAD

**Issue by sbingler** [httpwg/http-extensions#1422]
Both Chrome and Firefox (perhaps others) implement the [Lax-Allowing-Unsafe](https://tools.ietf.org/html/draft-west-cookie-incrementalism-01#section-3.1.1) behavior specified in cookie incrementalism, but RFC6265bis does not specify this behavior.

I believe it should.

**Comment by chlily1** [comment]
Addressed by #1435
