### ISSUE TITLE
RFC6265bis Section 9.3 link broken

### ISSUE THREAD

**Issue by sbingler** [httpwg/http-extensions#1426]
The section titled "Cookie Attribute Registry" has a link to the attribute registry maintained by the IANA.
This link is broken.

Moreso, a cursory look through the IANA site doesn't turn up any similar pages suggesting that this section is obsolete.

**Comment by reschke** [comment]
The registry does not exist yet. The text about it was added in https://github.com/httpwg/http-extensions/pull/1060.

The prose should actually tell IANA that the registry needs to be *created*, not "updated".

**Comment by chlily1** [comment]
Addressed by #1516
