### ISSUE TITLE
Should priority provide a recommendation for prioritizing retransmissions

### ISSUE THREAD

**Issue by afrind** [httpwg/http-extensions#1429]
The QUIC applicability draft states:

> Priority handling of retransmissions can be implemented by the sender in the transport layer. [QUIC] recommends retransmitting lost data before new data, unless indicated differently by the application.

Should HTTP Priority provide a recommendation here, perhaps endorsing this default behavior or stating this is implementation dependent?

**Comment by LPardue** [comment]
I agree the HTTP/3 section is likely improved be improved by saying something. Fancy making a PR?

**Comment by LPardue** [comment]
@afrind since you raised the issue and your org said they've tried this out, do you have any text to offer?

**Comment by afrind** [comment]
Wow did I walk into that one.  We'll put our heads together and see what we can come up with.

**Comment by yangchi** [comment]
I can create a PR for this. One question: it's not clear to me how to add a new item to the reference list. Is there a pointer on how to do that?

**Comment by LPardue** [comment]
What are you trying to do? Feel free to ping me on email or via Slack and I can help

**Comment by yangchi** [comment]
Thank you @LPardue . I will send an email to you later today.
