### ISSUE TITLE
What is a format

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1432]
Inspired partly by Carsten's work on the terminology, I noted [this text](https://httpwg.org/http-extensions/draft-ietf-httpbis-bcp56bis.html#name-defining-message-payloads):

> There are many potential formats for payloads; for example, JSON [RFC8259], XML [XML], and CBOR [RFC7049]. Best practices for their use are out of scope for this document.
>
> Applications should register distinct media types for each format they define;

So, "formats" is simultaneously used for the generic syntax (like ASN.1+DER), and for the distinct instantiation with the application-defined schema.  I think that the first might instead be reworded as:

> There are a few options that might be used in defining the format for payloads; for example, JSON ...

**Comment by mnot** [comment]
PTAL

**Comment by martinthomson** [comment]
LGTM.  Thanks.
