### ISSUE TITLE
Typo in 3.2.2 of Signatures v 0.2

### ISSUE THREAD

**Issue by bblfish** [httpwg/http-extensions#1436]
The date in [Figure 1: Non-normative example Signature Input](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-02.html#section-3.2.2) has the date as Tuesday

```http
"date": Tue, 07 Jun 2014 20:51:35 GMT
```

But the input above had the date as Saturday

```http
Date: Sat, 07 Jun 2014 20:51:35 GMT
```

**Comment by jricher** [comment]
Dates should all be fixed in re-generated examples in -04
