### ISSUE TITLE
SEARCH spec shouldn't use text/query mime type

### ISSUE THREAD

**Issue by pimterry** [httpwg/http-extensions#1450]
Minor point, but this is a non-standard mime type (in fact when googling for `Content-Type: text/query` the HTTP SEARCH spec is the top result). That's not prohibited, but it seems like this spec shouldn't implicitly mint a new mime type for this query syntax, or encourage users to create their own custom mime types when it's not necessary.

The spec seems to use a SQL dialect: `select surname, givenname, email limit 10`. Given that, it seems like we could use `application/sql` instead (which [is standardized](https://www.iana.org/assignments/media-types/application/sql)).

**Comment by reschke** [comment]
It's just an example. We'll get to this later.
