### ISSUE TITLE
proxy-status unrecognised parameters

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1452]
Draft 04 says:

> Unrecognised parameters SHOULD be ignored.

and later on 

> Proxy Error Types can also define any number of extra parameters for use with that type. Their use, like all parameters, is optional. As a result, if an extra parameter is used with a Proxy Error Type for which it is not defined, it will be ignored.

I'm a little confused why the requirement is `SHOULD`. The later comment implies certainty. What happens if the a client decides not to ignore the unrecognised parameter?

**Comment by mnot** [comment]
so `s/SHOULD/MUST/`? I can get on board with that. Don't think it's editorial in the strictest sense though.

**Comment by LPardue** [comment]
Sorry for the editorial label, I think I was on autopilot setting that.

Yes I think changing to a MUST works here. If there is a good reason to keep SHOULD I'd want to understand that better.
