### ISSUE TITLE
Signature: Invalid space in Signature-Input field examples

### ISSUE THREAD

**Issue by bblfish** [httpwg/http-extensions#1456]
I am writing [a parser for RFC8941](https://github.com/co-operating-systems/Reactive-SoLiD/issues/13) in Scala, to implement the Signature spec. So I am looking very closely at both specs.

We find the following in [2.4.2](https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-03#section-2.4.2)

```http
# NOTE: '\' line wrapping per RFC 8792
   ("@request-target" "host" "date" "cache-control" "x-empty-header"
     "x-example"); keyid="test-key-a"; alg="rsa-pss-sha512"; \
     created=1402170695; expires=1402170995
```

in [§2.4.2.1](https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-03#section-2.4.2.1)

```http
"@signature-params": ("@request-target" "host" "date" "cache-control" \
   "x-empty-header" "x-example" "x-dictionary";key=b \
   "x-dictionary";key=a "x-list";prefix=3); keyid="test-key-a"; \
   alg="rsa-pss-sha512"; created=1402170695; expires=1402170995
```

in [§2.5](https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-03#section-2.5), and so on.

In each of these cases the attributes for the inner list have a white space after the semicolon. I.e. they have "; " instead of ";". The [Signatures Param](https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-03#section-2.5) section refers to [the inner list section of RFC8941](https://tools.ietf.org/html/rfc8941#section-4.1.1.1), but in that section and the next there is no mention of adding a whitespace.

I think the following text from that RFC supports my reading:

> Note that parameters are ordered as serialized, and parameter keys
   cannot contain uppercase letters.  A parameter is separated from its
   Item or Inner List and other parameters by a semicolon.  For example:
   
```http
   Example-List: abc;a=1;b=2; cde_456, (ghi;jk=4 l);q="9";r=w
```

**Comment by reschke** [comment]
ABNF (https://www.rfc-editor.org/rfc/rfc8941.html#section-3.1.2):

~~~
parameters    = *( ";" *SP parameter )
~~~

Also see the parsing algorithm (https://www.rfc-editor.org/rfc/rfc8941.html#section-4.2.3.2).

**Comment by bblfish** [comment]
@reschke yes, that is how I implemented the *parser*. (see [here](https://github.com/co-operating-systems/Reactive-SoLiD/blob/c5163ed8f3d135f87be0a5091caaed997b2a2522/src/main/scala/run/cosy/http/headers/Rfc8941.scala#L69)).

I am speaking here not about parsing, but about serialization, which is different. Parsing of headers must be lenient, but the output to be signed must be exactly the same for each client and server. So for example `*SP` does not make sense there, as that would not make it possible for servers to verify the signature.

**Comment by reschke** [comment]
<https://www.rfc-editor.org/rfc/rfc8941.html#section-1.2-4>

> For serialization to HTTP fields, the ABNF illustrates their expected wire representations, and the algorithms define the recommended way to produce them. Implementations MAY vary from the specified behavior so long as the output is still correctly handled by the parsing algorithm described in Section 4.2.

So you really can't rely on a specific serialization wrt optional whitespace.

That said, the Signatures spec can of course make additional requirements.

**Comment by bblfish** [comment]
> So you really can't rely on a specific serialization wrt optional whitespace.

The text I am speaking of is not sent over the wire.  It is calculated by the client and reconstituted by the server and has to be byte to byte identical in order for the signature verification to work.

>  the Signatures spec can of course make additional requirements.

yes, and it quite handily points to the serialization algorithms from RFC8941 for the generated header to be signed. 
That is nice because it saves implementors work: My [RFC8941 code has Serialization](https://github.com/co-operating-systems/Reactive-SoLiD/blob/c5163ed8f3d135f87be0a5091caaed997b2a2522/src/main/scala/run/cosy/http/headers/Rfc8941.scala#L115)  code, that I can use for "Signing HTTP Messages". 

There is no deep problem here. It just requires the examples to be fixed, and if the associated example signatures to be regenerated.

**Comment by jricher** [comment]
I have not re-generated any of the examples yet, we've been focusing on getting the requirements and syntax right. It doesn't surprised me that one or more of the example serializations is off, and I guarantee that the signatures will fail because they haven't been changed with regard to the new signature input string format, yet. Unfortunately that process isn't automated for our draft and I haven't had a chance to do that yet! :) 

With that in mind: the design constraints of the signature draft is to use the serialization algorithms exactly as specified in RFC8941 to provide a single deterministic process. This is why the signature-params specialty parameter value is declared to be re-serialized by verifiers, for example. 

The other consideration is that it's difficult to accurately portray examples that are both human-readable and machine-processable in the spec text which has limits on line width for displays.

**Comment by jricher** [comment]
Examples should all be fixed in -04
