### ISSUE TITLE
'Active' content

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1465]
[ from https://www.w3.org/mid/d8ccd882-dc9b-ac42-9ef5-9aa8967e4264@gmx.de ]

An example of a HTTP response from an application that does not intend for its content to be treated as active by browsers might look like this:

HTTP/1.1 200 OK
Content-Type: application/example+json
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none'
Cache-Control: max-age=3600
Referrer-Policy: no-referrer

[content]

If an application has browser compatibility as a goal, client interaction ought to be defined in terms

In the introduction to this example, what exactly does "active" mean?

Best regards, Julian

**Comment by mnot** [comment]
@annevk any thoughts here re: terminology we could use / refer to / etc.? See also [context](https://httpwg.org/http-extensions/draft-ietf-httpbis-bcp56bis.html#name-co-existing-with-web-browsi).

**Comment by annevk** [comment]
I think if you say "HTML or PDF (as they can execute script)" you'd have it covered, as per https://mimesniff.spec.whatwg.org/#identifying-a-resource-with-an-unknown-mime-type.
