### ISSUE TITLE
digest and etag

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1474]
## I expect 

to clarify the relation b/w digest and etag

## Note

- etags are opaque, while digests are transparent
- digest is closely related to strong etags
- though having different algorithms, a strong etag can be related to many digest
- given an algorithm, digest mechanism could be used to compute a strong etag

**Comment by LPardue** [comment]
Given that we just removed the section on the relationship to SRI, do we need to do anything here? In other words, is there any strong use case that requires us to describe normative behaviour on Digest/Content-Digest? If not, then I think we should close with no action.
