### ISSUE TITLE
Remove SRI mention from Digest

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1478]
@mnot notes that SRI is orthogonal to Digest, so it's not appropriate to include it in this document.

The section was added in response to https://github.com/httpwg/http-extensions/issues/868. We've iterated on it a bit in the meantime. I tend to agree this sticks out from the rest of the document. I wonder if @martinthomson has any opinion since he raised the original issue.

**Comment by ioggstream** [comment]
Hi @martinthomson ! PTAL :)

**Comment by martinthomson** [comment]
Let's drop it.  The two things are different, but this document doesn't have to explain that.

**Comment by LPardue** [comment]
Fine by me. I will write this as a blog post instead
