### ISSUE TITLE
About comprehensive examples.

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1483]
- [ ] * 3. I'm uncomfortable with relying on examples to specify how this spec works normatively; by their nature, examples are not 'comprehensive.' While this spec shouldn't re-specify HTTP, the header's definition should be clear enough that a reader doesn't have to dig around in the examples and other specs to understand what's going on.

**Comment by ioggstream** [comment]
@LPardue  correctly notes that

>The example sections have grown organically as people have asked for them or we've uncovered corner cases.
> They deal with how to apply Digest, not what Digest is. 

In these years working on `Digest` I struggled trying to explain to implementers concepts like "resource representation" and "content coding", or the difference b/w content-coding and transfer-coding: this is the reason I think examples are useful.

@mnot If you think that there are specific examples which are not needed, we can discuss that!

**Comment by ioggstream** [comment]
@mnot can we close? :)

**Comment by mnot** [comment]
This is an editorial issue, so you can close it when you like. I think the main thing here is that you're confident that all of the constraints / requirements on implementations are reflected in the normative text, not just the examples.

Personally, I'd be a bit more comfortable if the example sections were appendices rather than in the main body of the spec, but that's totally a judgement call that's up to you.

**Comment by ioggstream** [comment]
@LPardue we could try to address that in the editorial revision we are planning, if that doesn't break stuff around. wdyt?

**Comment by LPardue** [comment]
> This is an editorial issue, so you can close it when you like. I think the main thing here is that you're confident that all of the constraints / requirements on implementations are reflected in the normative text, not just the examples.

This is an excellent point. The main purpose of this rewrite was to make Digest consistent with HTTP as defined today. IMO a reader who follows the various HTTP references will have sufficient information to implement this spec.  Someone less familiar with HTTP might not immediately understand how to apply things. As stated before I'm resistant to importing text defined elsewhere. The examples in section 8 and 9 help to fill some gaps the appear when transitioning from theory to practice. The other examples are ABNF->Expanded example, which are immediately useful just to give an illustration of what a field looks like. 

So I think moving some things to the appendix is fine, I'll follow up with a PR.
