### ISSUE TITLE
The priority extension doesn't mention the CONNECT method

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#1495]
The CONNECT method is somewhat special in the sense that most of the data transmitted on the stream is not a request or response. If a server receives a PRIORITY_UPDATE frame that references an open client-initiated bidirectional stream on which a CONNECT request was previously received, what is the server supposed to do?

This line of reasoning came thanks to @ianswett and @LPardue on https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/issues/46

**Comment by LPardue** [comment]
Thanks David. 

As you point out, extensible priorities uses the subject "responses", and CONNECT ends the strict notion of response after 2xx.

I think we can agree that prioritizing the frames that come back on a CONNECT stream is something nice to have and is easily handled by an implementation of priorities. So the action item here is to add some wording that highlight that special case CONNECT behaves just like all the others.
