### ISSUE TITLE
RFC 6265bis should allow user agents to block a subset of cookies during third-party requests

### ISSUE THREAD

**Issue by cfredric** [httpwg/http-extensions#1508]
Currently, the relevant wording is:

Section 5.3:
> When a user agent receives a Set-Cookie header field in an HTTP
   response, the user agent MAY ignore the Set-Cookie header field in
   its entirety.  For example, the user agent might wish to block
   responses to "third-party" requests from setting cookies (see
   Section 7.1).

Section 5.5:
> A user agent MAY omit the Cookie header in its entirety.  For
   example, the user agent might wish to block sending cookies during
   "third-party" requests from setting cookies (see Section 7.1).

These indicate that a user agent can block setting/sending **all** cookies during third-party requests. This bakes in an assumption that the user agent considers all cookies to be "third-party" during such a request. Chrome is planning on breaking this assumption in the future (notably for https://github.com/cfredric/sameparty/issues/4): some cookies (those with the [SameParty](https://github.com/cfredric/sameparty) attribute) may be considered first-party, so will not be blocked in those cases.

Therefore, it would be nice if the spec indicated that user agents may block a _subset_ of cookies during third-party requests. Section 7.1 could also explicitly mention that user agents might wish to block a subset of cookies during third-party requests, as an alternative to refusing to send the Cookie header at all.

**Comment by chlily1** [comment]
There's also this text in section 6.1, which suggests that servers SHOULD be able to handle individual cookies being absent:
```
   Servers SHOULD gracefully degrade if the user agent fails to return
   one or more cookies in the Cookie header because the user agent might
   evict any cookie at any time on orders from the user.
```

**Comment by miketaylr** [comment]
Section 7.1 is pretty generous here; I don't think any changes would be required to ship a SameParty cookies experiment.

> This document grants user agents wide latitude to experiment with third-party cookie policies that balance the privacy and compatibility needs of their users.  However, this document does not endorse any particular third-party cookie policy.

But making things more clear doesn't hurt. I guess we could update 5.3 to say (emphasis just to show the diff):

> For example, the user agent might wish to block responses to **all** "third-party" requests from setting cookies, **or just a subset, depending on user agent policy or user preference**. (see Section 7.1).

And do something similar in Section 5.5.

I think that would better describe what other UAs are doing today, e.g., Firefox's Standard ETP setting which blocks cross-site tracking cookies vs Strict ETP which blocks all cross-site cookies.

**Comment by miketaylr** [comment]
Actually, https://github.com/httpwg/http-extensions/commit/1f7edb710db72cfc994ab84260334899fcf8aebc landed after this issue was filed, so I'll just add an example to the "Third Party Cookies" section and I think we're good.

**Comment by miketaylr** [comment]
@cfredric let me know if you think https://github.com/httpwg/http-extensions/pull/1665 addresses your concern, thanks
