### ISSUE TITLE
How to include Signature Parameters such as `created` & `alg` in signing string material?

### ISSUE THREAD

**Issue by aljones15** [httpwg/http-extensions#1511]
I've been going through the spec and getting a javascript implementation ready for the RFC's release.
Really enjoying the structured fields, but I can't seem to understand how I include signature parameters such as `created` or `expires` in the signing string itself. In version 12 of the Signing HTTP Signatures specification `created` was a pseudo-header and could be included the canconizalied signing string by using `(created)` in the `headers` parameter (now covered content) of the Signature field value. 

Example: `Signature: keyId="foo",headers="host (created) (request-target)",signature="bar",created="111"`

I've seen examples in the spec where `created` is a structured field parameter of a signature value such as:

`("@request-target" "host" "date" "cache-control" "x-empty-header" \
  "x-example");keyid="test-key-rsa-pss";alg="rsa-pss-sha512";\
  created=1618884475;expires=1618884775`

However it is not clear to me how to include `created` in the signing string. A lot of the confusion comes from that previously `(request-target)` was a pseudo-header and now it is `@request-target`. So do I use `@created` in the covered content list? Enjoying the spec a lot and it is a lot clearer than it used, but still a little foggy for me in [Section 2.4.2](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-04.html#name-signature-parameters)

If anyone has the time to double check prospective implementation details I have made an issue here in my library's repo: https://github.com/digitalbazaar/http-signature-header/issues/45

EDIT: if anyone else comes across this issue it looks like you just include all of the structured field params from the signature's entry in the Singature-Input dictionary in the `@signature-parameters` part of the signature string creation.

**Comment by aljones15** [comment]
> The `@created` field is no longer defined as this is now covered in the signature parameters. You include the `created` timestamp by including the parameter as part of `@signature-parameters` as shown in the examples.

That what I figured. Thanks for the reply and closing this.

**Comment by jricher** [comment]
An important note to anyone finding this issue later: the signature parameters are :always: covered by the signature. It's not optional anymore, and so no additional special pseudo-headers need to be listed for it.
