### ISSUE TITLE
RFC 6265bis should specify that no decoding of Set-Cookie line should occur

### ISSUE THREAD

**Issue by chlily1** [httpwg/http-extensions#1517]
UAs should not decode any URL-encoded (or otherwise encoded) characters while storing a cookie, e.g. a cookie such as `__%53ecure-foo=bar` should not be interpreted as a `__Secure-` cookie.

I landed some WPTs for this in https://github.com/web-platform-tests/wpt/pull/28066. Chrome, Edge, Firefox, and Safari [seem to](https://wpt.fyi/results/cookies/attributes/secure-non-secure.html?label=experimental&label=master&aligned) do the right thing.

I think this could just be a clarifying note in the parsing algorithm section.

**Comment by abeyad** [comment]
I'll take this one

**Comment by miketaylr** [comment]
Let's make sure we are consistent for names and attributes.
