### ISSUE TITLE
IANA registration

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#1520]
@b---c wrote:
> TODO: register the `Client-Cert` HTTP header field in the registry defined by
http-core.

This should be pretty simple to add, but for the purposes of having a clean PR pulling out the TODOs, I'm moving it to an issue for now anyway.

**Comment by bc-pi** [comment]
https://www.iana.org/assignments/http-fields/http-fields.xhtml points to draft-ietf-httpbis-semantics for this
