### ISSUE TITLE
Support for Raw Public Keys

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#1522]
@b---c wrote:
> TODO: It has also been suggested that maybe considerations for {{?RFC7250}} Raw
Public Keys is maybe worth considering. This too is this is an area for further
discussion and consideration should this draft progress.

**Comment by martinthomson** [comment]
My take: keep the scope of this narrow.  If raw keys are needed - or other certificate types for that matter - then we can define another field.

**Comment by b---c** [comment]
I concur with Martin's take. The TODO made its way into the individual draft (and subsequently became this issue) based largely on this brief suggestion in one part of an off-list email on the topic, "While I do not know of a use case yet, it might be worth keeping raw public keys in mind as a use case." Which is not unreasonable but I'm going to favor narrow scope here over speculative need.
