### ISSUE TITLE
RFC 6265bis: Truncating cookie values may enable attack

### ISSUE THREAD

**Issue by chlily1** [httpwg/http-extensions#1531]
In https://github.com/httpwg/http-extensions/pull/1420, RFC 6265bis was modified to specify truncation of set-cookie-lines at the first {CR, LF, NUL} byte. This is consistent with Chrome's current behavior.

@annevk [points out](https://github.com/web-platform-tests/wpt/pull/28290#issuecomment-818826795) that this may enable an attack where an attacker may inject a CR, LF, or NUL byte into a cookie value to cause its truncation, thus changing the value of the cookie.

Investigate interop/web compatibility and consider rejecting all cookies containing any control character (rather than truncating).

**Comment by chlily1** [comment]
Addressed by #1576 and #1589.

**Comment by annevk** [comment]
Thanks @chlily1! Do you know if tests have been updated as well and implementations bugs have been filed against browsers that do not do this (yet)?

**Comment by recvfrom** [comment]
@annevk I just submitted for review an update to the tests, and will soon file bugs based on the findings from running those. I'll post back here with links to any tickets I open.  Thanks for asking about this

**Comment by recvfrom** [comment]
@annevk FYI, here are the corresponding bugs:
 - https://bugzilla.mozilla.org/show_bug.cgi?id=1702031#c1
 - ​​https://bugs.webkit.org/show_bug.cgi?id=229088
 - https://bugs.chromium.org/p/chromium/issues/detail?id=1233602

**Comment by annevk** [comment]
Thanks @recvfrom for your work on this!
