### ISSUE TITLE
Registration policy for digest algorithm values

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1533]
This specification obsoletes 3230 and updates the IANA registry to point to it, but doesn't specify what the registration policy actually is.

**Comment by ioggstream** [comment]
Related to #1394

**Comment by ioggstream** [comment]
See #1567

**Comment by ioggstream** [comment]
@LPardue do we need `Values to be added to this registry require IETF Review (see Section 4.8 of {{!RFC8126}}).` ?

**Comment by LPardue** [comment]
I'm sure I made this comment somewhere but I've lost it. I don't think we should mandate RFC required, that a very high bar for algorithms (and their users) that most likely developed the algoithm elsewhere already. Instead [Specification Required](https://datatracker.ietf.org/doc/html/rfc8126#section-4.6) seem like a better option here

**Comment by ioggstream** [comment]
@LPardue imho

* registering new algos should be done via an RFC,
* this doesn't imply that those algorithms should be defined in an RFC.

While it is fair to delegate the registration to an external specification,
I think the approach of an RFC (eg  https://datatracker.ietf.org/doc/rfc5843/ )
is a lot more clean and improves the overall interoperability.

It is important to note that  any type of RFC is sufficient (currently
   Standards Track, BCP, Informational, Experimental, or Historic).

In any case, I don't think this should be a game-stopper, so if there's
general consensus on "Specification Required", that's ok.

**Comment by LPardue** [comment]
I don't think running an RFC process can provide any meaningful value to the registration requirements.

I mean, that's going to add like a year of overhead to something as simple as "use algorithm $foo with token `foo`, the output is encoded using base64".

**Comment by seanturner** [comment]
The key to Specification Required is the Designated Experts. If they do they job you basically get what you need. If there's any question from the DEs they can always kick it back out for further review.

**Comment by ioggstream** [comment]
@LPardue Ok then. Since it seems there's general agreement on Specification Required, it's fine to me. Move on :)
