### ISSUE TITLE
@request-target doesn't encode the request target

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1536]
I just noticed that only the path and query URI components are included.  If a request uses absolute form, then the scheme and authority is not included.

The specification does not strongly recommend the inclusion of `host`.  It probably should.  (Examples show it, which is good.) 

That would not be sufficient, however.  Both `:authority` (or authority form) and `host` can be present.  If both are present `host` is ignored.  But this specification provides no way to sign the authority that is used.

That means that the message that is signed is potentially different than the message that is processed.  That could be disastrous.

To be truly safe, everything that is implicit needs to be explicitly covered.  That means including the scheme also.

**Comment by jricher** [comment]
I agree that this is a hole in the spec. It's been proposed to look at "request-target" more directly already, and even replace it with a new structured value that would be more comprehensive. The current definition pre-dates the adoption of structured field values, and we want to get rid of the special string-based construction at the very least. We've played with separating out all the components into specialty fields (method, host, query, and now authority), or putting all these values into a structured dictionary object with keys for each field.

Do you have a proposal for a field definition?

**Comment by martinthomson** [comment]
If you want to do this right, encode the information as it is used.  Maybe you could crib pseudo-header fields from HTTP/2.  Or maybe you could have this information as implicit (and therefore non-optional).  I can think of many ways to solve the problem, but only you know the usage constraints that you would apply to deciding between the various options.

**Comment by ioggstream** [comment]
@martinthomson wrt http/2 pseudo-headers, I thought that there is no guarantee that the transport is preserved in multi-hops, so I'd stick to information available in semantics-latest. For example, :scheme and :authority control data do not seem to be conveyed in HTTP/1.1.

We can even find a way to convey a structured control data, and this could be done using identifiers like :scheme, :method, ... These should not theorethically be "pseudo-headers" but a way to represent control data though :)

 The gap b/w :scheme and semantics-latest probably remains though.

**Comment by martinthomson** [comment]
The reason I suggest pseudo-headers is not because they are everywhere, but because they are guaranteed to contain the information that the protocol endpoints use to make decisions.  As you say, the generic information you are looking for is in the "[Control Data](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#message.control.data)".

HTTP/1.1 does convey all the necessary information, but it might not do so explicitly, which is a real problem for signing.  Not sure  what you mean by a gap in semantics for `:scheme`.  HTTP/1.1 has a bit of a (deliberate) hole, but it should never be the case that a scheme is not available, it just might just be something that endpoints pull from configuration or context rather than the protocol.

No matter how this works out, feel free to convey control data in a different way, as long as it is unambiguous.

**Comment by ioggstream** [comment]
> not sure what you mean by a gap in semantics for :scheme

From semantics-latest:

> control data includes a request method (Section 9), request target (Section 7.1), and protocol version (Section 2.5). 
> Response message control data includes a status code (Section 15), optional reason phrase, and protocol version.

iiuc this does not include the scheme; am I missing something?
Similarly, since http version is conveyed only in http/1.1, it is probably not something that should be
mentioned in semantics... cc: @mnot 


I agree with you that we should include  some caveats 
wrt the "Host" header since 

>  An intermediary that converts an HTTP/2 request to HTTP/1.1 MUST
>     create a Host header field if one is not present in a request by
>     copying the value of the ":authority" pseudo-header field

My2¢, R.

**Comment by MikeBishop** [comment]
I'll second @martinthomson's suggestion to use pseudo-headers for encoding aspects of the request-line and similar.  They're immediately present in HTTP/2 and HTTP/3, fit well into the rest of your design that wants to act on headers, and can be synthesized from an HTTP/1.1 request as if it were being relayed into a different HTTP version.

**Comment by mnot** [comment]
Sorry, why are we thinking about doing this in a version-specific manner?

I think the term you're looking for is [target URI](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.7.1). Each version of the protocol should define how to derive it from what happens on the wire in a deterministic fashion.

**Comment by ioggstream** [comment]
> you're looking for is target URI

that could fit requests.

Is the status-code ok for responses?

**Comment by mnot** [comment]
Yes - including the status phrase doesn't make sense because there's no guarantee of end-to-end integrity for it, especially through HTTP/2 and 3.

**Comment by jricher** [comment]
An alternate set of identifiers has been proposed in #1565, please review.

**Comment by jricher** [comment]
Closed by #1565
