### ISSUE TITLE
Considerations for Client-Cert field and header compression

### ISSUE THREAD

**Issue by afrind** [httpwg/http-extensions#1548]
The size of the client-cert field could be very large, especially if the entire chain is added.  Whenever an intermediary injects a large header, there is a chance that it will increase the total request size beyond what the server can accept, causing the request to fail.  Both HTTP/2 and HTTP/3 allow the server to declare its maximum value so the intermediary can detect this case. 

Because the client-cert fields may be large, they might be good candidates for header compression between the intermediary and the origin server.  If the client sends multiple requests to the intermediary over the same mutually authenticated TLS connection, there could be substantial savings.  One caveat that the draft could address is that the header table size may need to be tuned larger than the default to effectively support this use case.

If the draft recommends compression, perhaps it should also touch on the sensitivity of compressing these headers -- much like Cookie or any other authentication field.

**Comment by martinthomson** [comment]
#1547 seems to be a duplicate of this one.  I think we both said the same things.

**Comment by afrind** [comment]
Hah, race condition.
