### ISSUE TITLE
Define `Accept-CH` more precisely

### ISSUE THREAD

**Issue by sicking** [httpwg/http-extensions#155]
The spec currently says that if a server sends `Accept-CH: DPR`, then the `DPR` header should be added "to all subsequent requests".

However it is (as far as I can tell) completely undefined what a "subsequent request" is. Does it affect only future requests to the server which sent the `Accept-CH` header? If the header is sent with the response during a document load, does it affect all requests coming from that document, no matter which server the request goes to?

Generally speaking, if a CDN which servers images has to send a `Accept-CH: DPR` header before it will receive any `DPR` headers, that means that the first image will have to be served without DPR information. This seems unfortunate since ideally the first image that a page loads is the most important image.

A better solution is that when a browser loads a "document" and receives a `Accept-CH` header in the response, that header would affect all the requests that are made from that document, no matter which server the request is going to. If desired, in the future we could add more complex syntax to `Accept-CH` which enables opting in to certain CH headers only for certain servers and/or only for certain resource types.

We could also add a header which enables a server to opt in to getting specific CH headers for all future requests to that same server. To for example allow an image server to opt in to certain headers even if the document-serving server has not yet adopted the `Accept-CH` header. But I'm not sure how popular such a solution would be given first-load the problem mentioned above.

**Comment by mnot** [comment]
@igrigorik, my understanding is that this is going to be addressed in Fetch and HTML (as discussed during B-A). Can this be closed from the perspective of our spec?

**Comment by igrigorik** [comment]
We have ~1/2 of the solution in https://github.com/whatwg/fetch/commit/404dc3acfddb5e9870fdee333302f80ecff661dd#diff-1feda49b40370635faef8b655f144f64R1489. 

The remaining bits are to define the "parse the header" algorithm (CH RFC, probably) and associate the policy with the environment settings object (HTML, probably.. see https://github.com/whatwg/fetch/commit/404dc3acfddb5e9870fdee333302f80ecff661dd#diff-1feda49b40370635faef8b655f144f64R900).

I'll track progress for both of the above in https://github.com/httpwg/http-extensions/issues/156. Let's close this and continue there.
