### ISSUE TITLE
How are DATAGRAM frames prioritized?

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1550]
Discussed at the interim 2021-06.  We need to decide whether DATAGRAM is included and - if so - how.  If not, then the document might describe that it doesn't cover DATAGRAM.

**Comment by LPardue** [comment]
In case anyone wonders how we resolved this, for reference, the following comment was made on the PR

```
Healthy discussion on list. On balance I'm merging this in the pursuit of progress.
```
