### ISSUE TITLE
[SIGNATURES] Clarify Host vs :authority in canonicalization

### ISSUE THREAD

**Issue by enygren** [httpwg/http-extensions#1554]
It would be good to specify how HTTP/1.1 "Host" vs H/2 ":authority" are canonicalized.
(ie, is H/2's ":authority" converted to "host" and then canonicalized there?)

**Comment by mnot** [comment]
This makes me wonder -- would it be useful/helpful to move canonicalisation into a separate draft? Just a thought.

**Comment by jricher** [comment]
@englehardt at the moment `Host` is treated as a plain header value and `:authority` isn't mentioned separately. If it makes sense, we could have a single at-prefixed "specialty identifier" to handle this field that pulls information from the appropriate place in the protocol, driven by the semantics. I'd personally rather not have to have things driven through HTTP/1.1 to make signatures work.

@mnot canonicalization is the biggest part of this draft right now, as it tells you how to create or re-create the input string. With that, I think it makes the most sense to keep it internal. But that said, if there are some general purpose canonicalization methods that would be useful for other specs outside of signing, then I'd be in favor of moving those out and having signatures refer to them as the values for the signature input string.

**Comment by jricher** [comment]
I took a first shot at this in #1565 by adding a new `authority` field, where we can talk about using that instead of the `Host` header directly, and how they relate to each other. I'd like to see if this direction could help.

**Comment by jricher** [comment]
Closed by #1565
