### ISSUE TITLE
Add guidance to implementors of `id-` digest algorithms

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1555]
## Consider

providing guidance to implementors of id- digest algoritms:

- [ ] currently `id-` is not a reserved prefix for digest-algorithms
- [ ] to decide whether computing the checksum before or after content-coding, the full algorithm name should be checked, eg.

the same apply to generic algorithms.

@LPardue do we need to specify that? 

```
# bad
if algo.lower().startswith("id-"):
  .. compute digest before encoding ...

# bad
if "sha" in algo.lower():
  ... load sha function ...
```

```
# good 
id_algorithms = ("id-sha256", "id-sha512")

if algo.lower() in id_algorithms:
  .. compute digest before encoding ..


# good
def sha256_b64(d):
  ...

algos = {
  "sha256": {"function": sha256_b64}
}
``

**Comment by LPardue** [comment]
Seems related to this issue https://github.com/httpwg/http-extensions/issues/885, which will probably drive the answer here.

**Comment by ioggstream** [comment]
moved to https://github.com/ioggstream/draft-polli-id-digest-algorithms
