### ISSUE TITLE
Overuse of backticks

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#1558]
Putting `text` in back-ticks produces quotes in the text output and in-line code rendering in the HTML.  In other documents, we've found that this gets a bit excessive when used with tokens such as field names.  (Note that neither Semantics nor HTTP/3 render field names as in-line code.)  With #1542, you're defining four fields in this document -- that's a *lot* of back-ticks if used consistently.  You also use back-ticks for things other than the field name, like `selected representation data`.

I'd suggest following the lead of other documents and just using the stand-alone name of the field except in actual ABNF.  This is something of a stylistic opinion, so feel free to close this with editorial discretion.

**Comment by martinthomson** [comment]
I've concluded something different. xml2rfc is wrong. It over decorates. Code units don't need scare quotes.

**Comment by LPardue** [comment]
I'm not so convinced the RFC text output is a good baseline. For instance, it no longer includes page numbers - https://www.rfc-editor.org/rfc/rfc9000.txt ;)

Is the HTML in-line code rendering useful to readers? If not, I'm not opposed to reducing formatting.

**Comment by martinthomson** [comment]
I think that having variables in fixed-width font is useful.  It helps distinguish them when reading HTML.  As you say text renderings can't deal with that subtlety, so maybe they shouldn't even try.  But that is a problem with the text renderer, not the source.

**Comment by martinthomson** [comment]
https://trac.ietf.org/trac/xml2rfc/ticket/647#ticket

**Comment by LPardue** [comment]
Thanks for filing the bug report. My intuition is to wait to see how that progresses before making any decision here.

**Comment by LPardue** [comment]
xml2rfc got updated to remove text quotin, I'm inclined to leave the backticks in the document.

**Comment by LPardue** [comment]
@ioggstream I think we should close this with no action, let me know if you disagree

**Comment by ioggstream** [comment]
Closed with no action.
