### ISSUE TITLE
AD review for cache-status

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1564]
- [x] 1. -----

FP: I think the draft should add a normative reference to the HTTP Caching and HTTP semantics documents, and add a sentence in the terminology stating that terms and concepts from those documents are used.

- [x] 2. -----

FP: I would also add a sentence in the terminology stating that ABNF definitions of data types used are found in RFC 8941 - right now there is only a reference for Lists, but other data types are used throughout the document.

- [x] 3. ----

>  "hit" and "fwd" are exclusive; only one of them should appear on each
>  list member.

FP: any reason why this is not a MUST?

- [x] 4. -----

>  The most specific reason that the cache is aware of SHOULD be used.

FP: you could be even more clear here and mention when it is acceptable that the most specific reason is not used (I take it as this is a SHOULD to leave some flexibilities to implementations, I think it would be good to explicitly state that). Also it might be good to specify what a "more specific" is, in this case. I can see that uri-miss is more specific than miss, but is there any way to evaluate specificity between, say, request and stale?

- [x] 5. -----

>  "stored" indicates whether the cache stored the response; a true
>  value indicates that it did.  Only meaningful when fwd is present.

FP: With this definition I would assume that "stored" would always be true with "hit". Would it be an error on the client if it received it with "hit"? Or even more general: if a parameter is not meaningless, what's the client behavior? I assume ignore, but again it might be good to spell this out.

- [x] 6. -----

>  *  Name: [a name for the Cache-Status Parameter that matches key]

FP: I am a bit confused by "that matches key".

**Comment by mnot** [comment]
> any reason why this is not a MUST?

That implies a conformance / interop requirement. To specify that properly, we'd need to put separate requirements on producers and consumers, which seems like a very heavyweight way to say 'these options don't make sense together'.

**Comment by mnot** [comment]
> Also it might be good to specify what a "more specific" is,

see in-place intro text:

> The following parameter values are defined to explain why the request went forward, from most specific to least

**Comment by mnot** [comment]
> FP: With this definition I would assume that "stored" would always be true with "hit". Would it be an error on the client if it received it with "hit"? Or even more general: if a parameter is not meaningless, what's the client behavior? I assume ignore, but again it might be good to spell this out.

This isn't a protocol in that sense -- it's debugging information, so it doesn't trigger any client behaviour.

**Comment by mnot** [comment]
@fpalombini thanks for the feedback! I think this is done; PTAL.

**Comment by fpalombini** [comment]
> > Also it might be good to specify what a "more specific" is,
> 
> see in-place intro text:
> 
> > The following parameter values are defined to explain why the request went forward, from most specific to least

Ah! I missed that. 

It all looks good, thank you!
