### ISSUE TITLE
AD review for proxy-status

### ISSUE THREAD

**Issue by fpalombini** [httpwg/http-extensions#1578]
- [x] 1. -----

2.1.3 next-protocol

FP: I would suggest explicitly stating that the only acceptable values are those from the "TLS Application-Layer Protocol Negotiation (ALPN) Protocol IDs" and possibly add a reference to https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids

- [x] 2. ------

2.3.9 Connection Timeout

FP: should this also contain a note as previous and following section, stating that 
"Responses with this error type might not have been
      generated by the intermediary."

- [x] 3. -----

3. IANA Considerations

FP: Might be overkill, but please consider explicitly stating that both registries have "Expert review" as registration policy. Also please consider if it would make sense to add a change controller and a contact field, as suggested by RFC8126.

**Comment by mnot** [comment]
> 2.3.9 Connection Timeout

No - this is a timeout for _opening_ the connection; if an error happens, there's no opportunity to get a response from upstream.

> 3. IANA Considerations

I switched to Expert Review, thanks. I don't think it's appropriate to list a change controller / contact, as these are not registrations of private values, they're publicly reused and therefore under control of the community (overseen by the expert).

**Comment by fpalombini** [comment]
Ok, thanks for the clarifications. For the connection timeout, I think I was surprised to see that note on the "connection read timeout" for example, but not on the "connection timeout".
