### ISSUE TITLE
Secdir review of proxy-status

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1580]
- [x] While the draft says it is both for CDN like things and outgoing reverse
proxies, it doesn't quite seem that way.  For example, Sec 2 the Proxy-Status
HTTP field says the order is first closest to the origin, and last closest to
the user-agent. Shouldn't it always be in the direction of travel?  The
example, shows "FooProxy, ExampleCDN", but the explanation doesn't fit if there
is an outbound proxy. Or maybe it's "FooProxy" is a proxy at the origin side? 
Either way, I think there's an ambiguity there that needs to be cleaned up.

- [x] Implied, but should be stated, as that when the request arrives at the origin,
any proxy-status headers should be removed before responding.

- [x] Sec 2.1.3 should maybe refer to the ALPN registry directly. All current values
are US-ASCII, and that seems unlikely to change.  Saying UTF-8 seems
contradictory since sf-string is ASCII-only.

- [x] Sec 2.1.4 talks about received status, which is "in the opposite direction"
from 2.1.3  Perhaps split this up into "common" "sender" "receiver" types of
status fields?

- [x] Sec 2.1.5 uses sf-string which doesn't allow utf8 localization or markers
thereof.  should it?

- [x] Sec 2.2 says "[a] specification document is appreciated, but not required." 
Then the Reference bullet item needs editing.  I prefer to make it spec
required.

- [x] Sec 2.3.3 says "destination not found"  It should have a forward link to 2.3.6 
Consider shuffling some of those error cases around so that they fall into
things like "proxy failures" "infrastructure failures" "next hop did something
bad"  And consider making three subsections for each class.

- [x] I think having both "connection_limit_reached" and "destination_ip_prohibited"
is too fine a grain, but not worth arguing about. (shades of 451 I guess)

- [ ] The TLS errors should have "alert number" as extra info.  (Not the
alert-message as mentioned in 2.3.15)

- [x] I am confused by 2.3.18 and 2.3.8 or even 2.3.10; maybe some guidance on when
to use each?

- [x] I think, again, splitting this section up is worthwhile.  Maybe add "http
errors" "tls errors" -- i.e., what layer in the IETF protocol model broke. 
That, or the traffic direction suggest above, might really help implementors.

- [x] 2.3.29 has no recommended http stauts code.

- [x] 2.4 says a specification is appreciated, but the registration form doesn't list
one.  Similar to the comments above about Sec 2.2

**Comment by mnot** [comment]
> While the draft says it is both for CDN like things and outgoing reverse
proxies, it doesn't quite seem that way. For example, Sec 2 the Proxy-Status
HTTP field says the order is first closest to the origin, and last closest to
the user-agent. Shouldn't it always be in the direction of travel?

What does "the direction of travel" mean? List-based HTTP header field values are appended from left to right, so the most recently added entry (without header rewriting) is the right-most member of the list.

> The example, shows "FooProxy, ExampleCDN", but the explanation doesn't fit if there
is an outbound proxy. Or maybe it's "FooProxy" is a proxy at the origin side?
Either way, I think there's an ambiguity there that needs to be cleaned up.

FooProxy is indeed a reverse proxy closer to the origin; this is a very common configuration. 

I've added a clarification for what the nature of FooProxy is.

**Comment by mnot** [comment]
>  Implied, but should be stated, as that when the request arrives at the origin,
any proxy-status headers should be removed before responding.

@richsalz what do you mean here? Request headers are never implicitly copied into a response, and this is a response header field only.

**Comment by mnot** [comment]
> Sec 2.1.3 should maybe refer to the ALPN registry directly. All current values
are US-ASCII, and that seems unlikely to change. Saying UTF-8 seems
contradictory since sf-string is ASCII-only.

Fixed in feedback from @fpalombini.

**Comment by mnot** [comment]
> Sec 2.1.4 talks about received status, which is "in the opposite direction"
from 2.1.3 Perhaps split this up into "common" "sender" "receiver" types of
status fields?

No, they're both talking about the forwards connection.

**Comment by mnot** [comment]
> Sec 2.1.5 uses sf-string which doesn't allow utf8 localization or markers
thereof. should it?

The only other option is sf-binary, which doesn't seem very usable for debugging information.

**Comment by mnot** [comment]
> Sec 2.3.3 says "destination not found" It should have a forward link to 2.3.6
Consider shuffling some of those error cases around so that they fall into
things like "proxy failures" "infrastructure failures" "next hop did something
bad" And consider making three subsections for each class.

The primary source is going to be the registry, so internal links aren't really doable. Also, that will be organised alphabetically.

**Comment by mnot** [comment]
> 2.3.29 has no recommended http stauts code.

Because it's up to the proxy; this is just a way of declaring that the response wasn't generated by the origin.

**Comment by mnot** [comment]
> The TLS errors should have "alert number" as extra info. (Not the alert-message as mentioned in 2.3.15)

Can you say why? Given that this is debugging information, the message seems more useful than the number, and it's guaranteed to be unique AIUI.

**Comment by mnot** [comment]
> I am confused by 2.3.18 and 2.3.8 or even 2.3.10; maybe some guidance on when
to use each?

The intent here is to give error types that map closely to existing error states in implementations; it's not the case that each implementation will use all of the error types.

**Comment by richsalz** [comment]
oi, all in one issue; ugh.  I will respond to your comments in chronological order and skip ones where you already made changes.

>"direction of travel"
>"proxy-status headers should be removed"
>"no, both talking about the forwards (sic) connection"

I missed that these are response headers only.  Ignore that. 

> Sec 2.1.5

If the I18N/L11N folks are fine, so am I.

>The primary source is going to be the registry, so internal links aren't really doable.

Within the document?  I think they aide readability.

> 2.3.29 has no recommended http stauts(sic) code

An explicit note saying it's up to the proxy would be helpful.

> TLS alert number vs text

I don't think the text is mandated, and seeing what was on the wire would be helpful.

> give error types that map closely to existing error states in implementations.

That's a reasonable call, and should be made explicit in the intro to the detailed error section.

Hope this helps.

**Comment by mnot** [comment]
Thanks for the feedback!
