### ISSUE TITLE
RFC 6265bis: Domain attribute '.' prefix handling only applies to Set-Cookie header parsing

### ISSUE THREAD

**Issue by recvfrom** [httpwg/http-extensions#1583]
RFC6265bis mentions that a preceding '.' character in a domain attribute should be removed when parsing Set-Cookie headers but doesn't mention this in the more general Storage Model section.

From chatting with @chlily1 about this, it'd be desirable to have this behavior listed in that section as well. Since there are other ways cookies can come in to the cookie store (Ex: Cookie Store API), having these constraints be enforced when adding cookies from any source to the cookie store would better ensure cookie format consistency.

**Comment by arichiv** [comment]
On it, more soon
