### ISSUE TITLE
Commit without same-host opt-in

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#160]
Kari raises in WGLC:

In [5.1. Opportunistic Commitment](https://tools.ietf.org/html/draft-ietf-httpbis-http2-encryption-04#section-5.1):

> An origin can reduce the risk of attacks on opportunistically secured connections by committing to provide an secured, authenticated alternative service.  This is done by including the optional "commit" member in the http-opportunistic well-known resource (see Section 6).

This does not make possible to specify "commit" without saying same time that  there is also reasonable assurance for alternative services for on same host which does not provide strong authentication.

There should be possible to give "commit" for authenticated alternatives WITHOUT giving also reasonable assurances for non-authenticated alternatives (on same host that origin).

`/.well-known/http-opportunistic` SHOULD include separate indication that for reasonable assurances. My suggestion for that parameter is same than for "Attacks from the same host".

**Comment by MikeBishop** [comment]
There's a fair bit of overlap with #161 -- likely the same ultimate text change to resolve -- but I think the points are slightly different.

**Comment by mnot** [comment]
Please review change above.
