### ISSUE TITLE
Erik Kline's COMMENT on bcp56bis

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1609]
- [x] S4.3, comment

* Are all the uses of "should" here deliberately lowercase?  I got
 the feeling some of them could well have been SHOULD, e.g.,
 "Applications using HTTP SHOULD specify that ... when HTTPS is used."

**Editors**: That's intentional, and resulting from discussion in the community; this is best practices for specifications, so we generally avoid placing interoperability requirements on things. 

---

- [x] S4.5.1, nit

* s/ought consider/ought to consider/, I suspect

**Editors**: I believe this is grammatical; will see what the RFC Editor says

---

- [x] S4.5.2, question

* Is it correct to say "OPTIONS is not the default GET method"?
 Should that be something like "not the default HTTP method"?

**Editors**: 5a787808

---

- [x] S4.10, question

* Might "ambient authority" benefit from a reference to RFC 6454
 section 8.3?

**Editors**: 5369076c

---

- [x] S4.13, nit

* "can execute script" -> "a script" or "scripts"?

**Editors**: 27d3ee48

**Comment by ekline** [comment]
LGTM, thanks!
