### ISSUE TITLE
Requirement to filter Alt-Svc header needs explicit normative text

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#161]
The resolution to #144 implies that the client can trust Alt-Svc headers from the server after finding a .well-known/http-opportunistic resource, but doesn't explain why that should be.

Logically, the attack described depended on the attacker's ability, from hosted content, to inject a value for the Alt-Svc header.  The original solution in the Alt-Svc draft, saying that servers just shouldn't allow this, placed a retroactive requirement on servers that don't support Alt-Svc.  This well-known URI represents a clear signal that the server *does* support Alt-Svc.

I suggest we add the requirement that servers which advertise the .well-known/http-opportunistic resource MUST prohibit setting the Alt-Svc from unprivileged content.  This is a reasonable implication from the current state of the text, but is not explicitly stated and could easily be missed by a server implementer.

**Comment by mnot** [comment]
Discussed in B-A; seemed uncontroversial.

**Comment by mnot** [comment]
@MikeBishop is this still necessary with 33041d7? I could see expanding the text a bit and suggesting it might be worth thinking about, but a MUST seems quite strong.

**Comment by MikeBishop** [comment]
I agree -- this warrants a recommendation, but assuming that an individual user can't control the .well-known resource and can't convince the server admin to change the values advertised, there's less harm in allowing user-controlled Alt-Svc headers.  Basically, the content owner can make the browser do extra work, trying to use an alternative that isn't valid, but can't actually make a compliant browser go there.  SHOULD?

**Comment by mnot** [comment]
When I try to write this, I'm having trouble justifying the SHOULD. Can you suggest some text (and where to put it)? Otherwise, I'm inclined to leave the text as-is.

**Comment by MikeBishop** [comment]
On vacation through 6/1; I can give this a stab when I get back.  Off the top of my head, I’d note in the Security Considerations something like “Because Alt-Svc is used to describe policies across an entire origin, servers SHOULD NOT permit user content to set or modify the value of this header.”
