### ISSUE TITLE
ARTart review of proxy-status

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1612]
## Substantive comment

- [x] Modifying the header

The third paragraph from the end of Section 2 says:

>  When adding a value to the Proxy-Status field, intermediaries SHOULD
  preserve the existing members of the field, to allow debugging of the
  entire chain of intermediaries handling the request.

Under what circumstances would an intermediary need to mess with existing
Proxy-Status entries? Please consider upgrading this requirement to a MUST, and
perhaps also require that the ordering of existing entries be preserved.

**Editors**: See b3dc10c4. The ordering of values is already preserved by HTTP.

## Minor comments

- [x] Notes on additional information

The descriptions of errors in sections 2.3.13, 2.3.14, 2.3.28, 2.3.30, and
2.3.31 all contain a paragraph saying, "Note that additional information...(as
is the case for all errors)." It isn't clear whether this text belongs in the
"Notes" column of the registry entry being created since it is separate from
the bulleted list describing the entry. Please consider removing this text in
these sections and instead including it as introductory text describing the
error parameter.

**Editors**: I'm inclined to leave it as-is, since it's there to act as a gentle reminder during initial adoption of the specification; for these specific error types, additional information is likely to be desirable. It doesn't belong in the Notes, and if that issue comes up with IANA, we can correct it with them during document processing.

---

- [x] generation flag

The Notes for the entries either are empty or contain the text, "Responses with
this error type might not have been generated by the intermediary." I wonder if
this might more efficiently be represented by a Boolean flag in the registry
entries, but probably preserving the Notes field in the registry for future use.

**Editors**: We were on the cusp of doing this earlier; thanks for the push :)  See 1f11cc36

---

- [x] towards / upstream

The introduction uses both the phrase "towards the origin server" and the term
"upstream". It might be helpful to some readers to make it clear that they're
synonymous, e.g., "towards the origin server (upstream)"

**Editors**: I've aligned with [core terminology](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#intermediaries); see 75d14422.

---

- [x] ABNF ref

Section 1.1 says that this specification uses ABNF, but I find only structured
fields. Consider removing the mention of ABNF and the informative reference to
RFC 5234.

**Editors**: It uses ABNF in Section 2, in the definition of `Proxy-Status`.

**Comment by jimfenton** [comment]
Nit on Modifying the header: s/to prevent internal network details to leak/to prevent internal network details from leaking/

On additional information: I still don't understand why some of the errors get this text and others don't. Is there something about these specific errors that warrants a specific mention of additional information?

Generation flag: thanks!

Towards/upstream: thanks!

ABNF: Yes, I guess that "Proxy-Status   = sf-list" line is actually ABNF, isn't it. This is the first specification I have read that uses structured fields; as a higher-level syntax, it would be nice if it was possible to use structured fields to abstract away from ABNF without actually using ABNF as well. But in any case you are correct in retaining the ABNF reference.

**Comment by mnot** [comment]
Regarding additional information -- they're ones where extra information is more likely to be available.
