### ISSUE TITLE
RFC6265bis: The Secure Attribute section may be incorrectly warning that a secure cookie can be overwritten by an insecure origin

### ISSUE THREAD

**Issue by sbingler** [httpwg/http-extensions#1627]
[Section-4.1.2.5](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-08#section-4.1.2.5) states "An active network attacker can overwrite Secure cookies from an insecure channel, disrupting their integrity".

This warning appears to be out of date since [Leave Secure Cookies Alone](https://datatracker.ietf.org/doc/html/draft-west-leave-secure-cookies-alone-05) updated the spec to disallow insecure origins (schemes) from overwriting Secure cookies set by secure origins.

If there is in fact some other mechanism in which an insecure origin can overwrite a Secure cookie set by a secure origin then section 8.6 should be updated to list it (ignoring any origins which the UA might consider trustworthy, such as localhost).

**Comment by recvfrom** [comment]
Another section that could be updated to make this more clear is the [The "__Secure-" Prefix](https://github.com/httpwg/http-extensions/blob/cedd1ceeb474468ced197f67a78f81b606184e11/draft-ietf-httpbis-rfc6265bis.md#the-__secure--prefix) section.  Currently it makes no mention of cookies needing to be set from a secure origin like the [The "__Host-" Prefix](https://github.com/httpwg/http-extensions/blob/cedd1ceeb474468ced197f67a78f81b606184e11/draft-ietf-httpbis-rfc6265bis.md#the-__host--prefix) section does.

**Comment by sbingler** [comment]
> If there is one, that seems like a bug to be fixed 
Indeed! I added that as an invitation for someone to add any techniques I'm unaware of.

**Comment by sbingler** [comment]
This is fixed.
