### ISSUE TITLE
Rename "digest-headers" -> "digest-fields"

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1632]
## Discussion

The "Digest Headers" document could be renamed to "Digest Fields" since they can be used in trailer sections.

The new name could take into account the fact that we're going to have two fields too:

- `Digest`
- `Content-Digest`

WDYT? @LPardue @mnot 

## Note

- by @LPardue 
> Given how similar Want-Digest and Want-Content-Digest are, and that they share the want-digest-value we can probably editorialize this a bit. But in order not to block this PR, we can do that work in a follow up. https://github.com/httpwg/http-extensions/pull/1543#discussion_r702818806

**Comment by LPardue** [comment]
Renaming the title of the doc is oberwhelmingly good in my mind, I hope the chairs agree

**Comment by LPardue** [comment]
The point I made about Want-* headers is tangential to the title, I'll follow up with a PR

**Comment by jricher** [comment]
I think this is a good idea.

**Comment by MikeBishop** [comment]
Title is reasonable; probably not worth changing the filename.

**Comment by mnot** [comment]
Sure, this seems obvious and good.
