### ISSUE TITLE
ALPN tokens and TLS usage

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#1645]
Spinoff from #1620, a question which I think still needs to be answered in the draft even if we don't add a `next-secure`.  ALPN tokens generally imply that TLS was used, e.g. `http/1.1` or `h2`, and the exceptions are generally called out explicitly (`h2c`).

Do we need language that says whether you can/can't infer the presence of TLS from a particular ALPN token?  If so, do we need to register `http/1.1c` or similar?

**Comment by mnot** [comment]
This was addressed with:

>  Note that the APLN identifier is being used here to identify the protocol in use; it may or may not have been actually used in the protocol negotiation.

**Comment by MikeBishop** [comment]
That's not quite the same thing, though.  *ALPN* might or might not actually have been used, as I read that statement.  And that's reasonable -- the token `http/1.1` is often the result of the origin not supporting ALPN, and returning that token even if the server did not accept ALPN (or the proxy didn't offer it) is the correct response.

What's unclear, and what this issue intended to capture, is whether the use of any ALPN token implies that TLS was used, regardless of whether ALPN was.  `h2c` explicitly disclaims the use of TLS, suggesting that the other entries in the registry *do* reflect the use of TLS.
