### ISSUE TITLE
Update CODEOWNERS

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1647]
The current file is a little out of date.

There is a tool that will generate a file in i-d-template, but it differs from what is currently in the repo:

1. It doesn't use github usernames, but uses email addresses (from the drafts).
2. It generates `./.github/CODEOWNERS` not `./CODEOWNERS`

Maybe give it a go some time: `make -f lib/setup.mk .github/CODEOWNERS`

**Comment by mnot** [comment]
I tried it once a while back, and it didn't work.

I tried again just now, and it seems to generate a file with no space between authors if there's more than one; e.g.,

~~~
# Automatically generated CODEOWNERS file.
draft-ietf-httpbis-bcp56bis.md mnot@mnot.net
draft-ietf-httpbis-cache-header.md mnot@mnot.net
draft-ietf-httpbis-client-cert-field.md bcampbell@pingidentity.commbishop@evequefou.be
draft-ietf-httpbis-digest-headers.md robipolli@gmail.comlucaspardue.24.7@gmail.com
draft-ietf-httpbis-expect-ct.md estark@google.com
draft-ietf-httpbis-h3-websockets.md rch@google.com
draft-ietf-httpbis-message-signatures.md richanna@amazon.comietf@justin.richer.orgmsporny@digitalbazaar.com
draft-ietf-httpbis-priority.md kazuhooku@gmail.comlucaspardue.24.7@gmail.com
draft-ietf-httpbis-proxy-status.md mnot@mnot.netpiotrsikora@google.com
draft-ietf-httpbis-rfc6265bis.md chlily@google.comsenglehardt@mozilla.commkwst@google.comwilander@apple.com
draft-ietf-httpbis-rfc7838bis.md mbishop@evequefou.bemt@lowentropy.net
draft-ietf-httpbis-safe-method-w-body.xml julian.reschke@greenbytes.demalhotrasahib@gmail.comjasnell@gmail.com
draft-ietf-httpbis-targeted-cache-control.md sludin@ludin.orgmnot@mnot.netme@yuchenwu.net
draft-ietf-httpbis-variants.md mnot@mnot.net
~~~

**Comment by martinthomson** [comment]
huh.  That's interesting.  I'll look into that.

**Comment by martinthomson** [comment]
So this works perfectly for me (both with and without xmllint installed, which is a source of some variance).  I'll bet that there is something weird about the mac bash or sed or something that is messing with this and making this not work for you.  I'm going to have to open my mac again (second time today, thanks to the big patches).

BTW, the build here takes forever, even with cached files, because we are referencing files on tools.ietf.org and those requests are timing out (at least for me).

**Comment by martinthomson** [comment]
OK, I hate the shell environment on macs.  xmllint there acts very strangely.  And it isn't the first time I've had issues like this.  Rather than deal with that, I've rewritten the tool in python.  It should be good to try again.

**Comment by mnot** [comment]
Thanks!
