### ISSUE TITLE
"Changes from RFC3230" appendix could be folded into the body

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1660]
Speaking to the current editors copy, appendix B just seems to contain things that should be in the main body of the text IMO. Section 1.3 seems like the most appropriate place for this. And we may chose to reinforce that parameters were removed in section 4.

**Comment by ioggstream** [comment]
I am open to suggestion from the wg.

**Comment by ioggstream** [comment]
closed via #1787
