### ISSUE TITLE
Digest qvalue length

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#1681]
In the Digest spec, a qvalue is defined to have 0-1 digits after the decimal, while http-core defines qvalues to have up to three digits after the decimal.  The decision to disallow `0.05` is absolutely sensible, but is it deliberate?

Is there a reason not to simply use the qvalue production from http-core by reference, rather than redefining it here? That section of Semantics is already being referenced.

**Comment by ioggstream** [comment]
Good catch, thanks! I'll add the qvalue rule from semantics and remove the abnf.

**Comment by LPardue** [comment]
yeah good spot, no need to redefine it here.
