### ISSUE TITLE
Hyphenation of digest-algorithm values

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#1682]
Absolutely banal and pedantic, I agree.  The section title, registry name, and basically all of the registrations do not hyphenate while (most) of the remaining text does.

I believe the unhyphenated form is correct, but I'm not totally certain and it's used widely enough that I don't want to include it in a "nits" PR without discussion.

**Comment by MikeBishop** [comment]
Ah, I think I see where this comes from.  RFC3230 uses `digest-algorithm` as a field in the ABNF; the hyphenated versions are references to the field, while the unhyphenated versions are references to the algorithms themselves.  So this may be correct.

Probably still worthwhile for the editors to review the instances of both to make sure they're used consistently, and perhaps to point out the distinction in the document.

**Comment by LPardue** [comment]
I removed `digest-algorithm` #1919 (except for the changelog, which doesn't count), so closing this issue as resolved.
