### ISSUE TITLE
Treat cookies that are set on http:// origins as ephemeral

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#170]
Note that the definition and scope of "ephemeral" is somewhat challenging given session restore capabilities.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1160368#c10

And http://mzl.la/1S62L0s

**Comment by mnot** [comment]
Martin, could you write up a *short* spec for this? I'm talking one-page I-D.

Ping @mikewest

**Comment by martinthomson** [comment]
I have put it on the list.  Only three new drafts on the list this time around (if I actually write them).

**Comment by mnot** [comment]
Closing, as we have a separate draft for this now.
