### ISSUE TITLE
CACHE_DIGEST: clients should seed hash and send seed

### ISSUE THREAD

**Issue by enygren** [httpwg/http-extensions#171]
To avoid hot-spots with collisions across many clients, it would be good for clients to use a random seed to seed their hashes and to send this along.

Considerations:
* This makes things somewhat more expensive for servers who have to recompute the hashes
* Care should be taken to make sure the seed isn't persisted in a scope that allows it to be used for tracking (or the seed should be small enough to make this less of an issue).

**Comment by martinthomson** [comment]
Why not derive the seed somehow?  Even a small amount of connection-bound entropy should suffice to split things up.  Worst case, use a TLS exporter, but folding in source ip and port might be enough to avoid problems.

**Comment by mnot** [comment]
This spec hasn't been adopted by the WG.
