### ISSUE TITLE
report-URI quoting

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1710]
[the spec](https://httpwg.org/http-extensions/draft-ietf-httpbis-expect-ct.html#name-the-report-uri-directive) doesn't make it very clear that report-URI should be quoted if it contains a comma.

It should always be quoted IMO, but that's just IMO...

**Comment by martinthomson** [comment]
Is this overtaken by https://w3c.github.io/reporting/#header ?

**Comment by reschke** [comment]
> Is this overtaken by https://w3c.github.io/reporting/#header ?

How so?

**Comment by reschke** [comment]
> [the spec](https://httpwg.org/http-extensions/draft-ietf-httpbis-expect-ct.html#name-the-report-uri-directive) doesn't make it very clear that report-URI should be quoted if it contains a comma.

If it contains any character not allowed in "token".

**Comment by estark37** [comment]
Is
```
report-uri-value = ("\"" absolute-URI "\"") / ("'" absolute-URI "'") / absolute-URI
```
(followed by text that "The report-uri-value MUST be quoted if it contains a comma") the right way to do this?

**Comment by mnot** [comment]
Single quoting isn't a convention in HTTP headers. Also, s/a comma/any character not allowed in token/ as per Julian above
