### ISSUE TITLE
CACHE_DIGEST: use a non-cryptographic hash

### ISSUE THREAD

**Issue by enygren** [httpwg/http-extensions#172]
Unless there are security problems with hash collisions, it would be better to use a non-cryptographic hash.  Not only is this much faster, but it removes a need to migrate when SHA256 becomes weak and needs to be retired.  If we stick with SHA256 due to security properties, a crypto hash negotiation scheme may be required in the frame.

**Comment by mnot** [comment]
This spec hasn't been adopted by the WG.
