### ISSUE TITLE
Live media prioritization

### ISSUE THREAD

**Issue by kixelated** [httpwg/http-extensions#1729]
I'm using WebTransport to deliver live media and it heavily depends on the server to prioritize streams in a particular manner. I would like the ability to use HTTP/3 for CDN support, and the current priorities draft is almost there, but it's not quite enough.

In my use-case, live media is broken into 2 second segments (ie. HLS or DASH). The current live segment is encoded and streamed to the player frame-by-frame. Audio and video are served as separate segments. The player maintains a buffer of anywhere from 1s to 10s, skipping over any media that does not arrive in time.

My goal is to prioritize delivering newer audio segments over older video segments. We would start with two requests:

```
GET video_segment_1, priority: "u=2,i"
GET audio_segment_1, priority: "u=6,i"
```

We issue two requests for the next segment when it becomes available:

```
GET video_segment_1, priority: "u=2,i"
GET audio_segment_1, priority: "u=6,i"
GET video_segment_2, priority: "u=3,i"
GET audio_segment_2, priority: "u=7,i"
```

Under normal network conditions, segment 1 will be fully delivered around the same time we issue the request for segment 2. However during congestion, we want `video_segment_1` to be starved in particular, spending any bandwidth on the other requests. `audio_segment_1` has been fully generated at this point so it will finish next.

```
GET video_segment_1, priority: "u=2,i"
GET video_segment_2, priority: "u=3,i"
GET audio_segment_2, priority: "u=7,i"
```

The congestion can continue while segment 3 is made available:

```
GET video_segment_1, priority: "u=2,i"
GET video_segment_2, priority: "u=3,i"
GET audio_segment_2, priority: "u=7,i"
GET video_segment_3, priority: "u=4,i"
GET audio_segment_3, priority: "u=8,i"
```

...and so on over the course of the live stream.

The main problem I see with the current priorities draft is that we run out of tarmac very quickly. When an application has strict ordering requirements:

1. We're limited to 8 concurrent requests, setting an upper bound on the size of the player buffer. Our segment size can go down to 1s but other protocols like LL-HLS use 200ms parts. In that case, we would be limited to 800ms of media inflight at once. The work-around would be to actively issue/cancel requests instead of relying on prioritization, which creates a ton of race conditions.

2. Because there's overlapping request, the urgency keeps increasing until we hit the max of 8. In theory we could use PRIORITY_UPDATE to constantly shuffle the priorities of our 8 requests around. For example, if we have two requests with priority 4 and 5 and want to change them to 1 and 2 to make space for the next requests. However, this opens up a few race conditions due to packet loss. 

PRIORITY_UPDATE frames are sent via a control stream so they will be ordered, but losing the packet containing the 2nd PRIORITY_UPDATE means we'll be using the wrong priority until the frame is retransmitted, in this example 4,2 or 1,5 instead of the intended 1,2. And if we simultaneously issue a new request with priority 3, the correct prioritization is contingent on the timely delivery of the control stream.

3. And probably the biggest issue: the urgency is really more of a hint and can't reliably influence delivery order. The server is free to prioritize responses however it sees fit.

**Comment by kixelated** [comment]
For my application, I've been assigning each QUIC stream a priority on creation and creating STREAM frames in descending priority order.

I would propose `order=int` for requests that depend on each other, with `urgency=0-8` remaining as a hint to handle ties. I definitely don't think there needs to be a full dependency tree like HTTP/2, but even just the ability to do simple ordering would do wonders. For example, two Javascript files may be `urgency=6` (more important than images) but with different orders if one depends on the other.

**Comment by kixelated** [comment]
Yeah, those are fair points, but I don't this this draft is actually _useful_ in it's current state.

As an developer, if I'm going to design my application to support prioritization, then I actually need CDNs and servers to behave in a somewhat specified manner. If request ordering is left up to server, then it's regularly going to be worse to make requests in parallel. HLS is a great example; it's a better user experience (less buffering) to download segments sequentially rather than in parallel, even though it means under-utilizing the network.

And yes, I can configure the server to do whatever prioritization scheme I want, but it defeats the purpose of this standard. My goal is to develop a CDN-agnostic video protocol and there just needs to be some uniformity to request segments in parallel.

**Comment by kixelated** [comment]
Also re-reading #1274 , @roger-on-github made some similar points. We just can't use an undefined prioritization scheme because it might actually produce worse results.

**Comment by kixelated** [comment]
To clarify, I'm absolutely NOT suggesting that servers MUST deliver responses in order, reintroducing head-of-line blocking. Like you mentioned this is neither feasible nor is a good idea.

I want some way of signaling to the server that it should allocate the connection's limited bandwidth to the highest priority stream/response first. This is only relevant when the server has data for multiple streams ready to send but the connection is congestion-limited. 

RFC 7540 puts it quite nicely:

```   
   The purpose of prioritization is to allow an endpoint to express how
   it would prefer its peer to allocate resources when managing
   concurrent streams.  Most importantly, priority can be used to select
   streams for transmitting frames when there is limited capacity for
   sending.

   Streams can be prioritized by marking them as dependent on the
   completion of other streams (Section 5.3.1).  Each dependency is
   assigned a relative weight, a number that is used to determine the
   relative proportion of available resources that are assigned to
   streams dependent on the same stream.

   Explicitly setting the priority for a stream is input to a
   prioritization process.  It does not guarantee any particular
   processing or transmission order for the stream relative to any other
   stream.  An endpoint cannot force a peer to process concurrent
   streams in a particular order using priority.  Expressing priority is
   therefore only a suggestion.
```

The thing missing from this new prioritization draft is the ability to specify dependencies. I completely agree that a full dependency graph is too complex, but I think a linear space will work for many situations (ex. `order=int`).

In my case, I'm dealing with large files and I want to ensure that bandwidth between two requests is allocated as close to 100-0 as possible (all bets are off when the path to origin is congested). `urgency` almost accomplishes this, but it's only a recommendation and the number space is too small.

**Comment by LPardue** [comment]
Thanks for the clarification Luke.

The avoidance of relationships between requests is a feature of this specification. Dependencies are a slippery slope in a stateless protocol. Changing that axioms we built on, I fear, that would require a complete analysis of the entire draft to avoid breaking things that have established consensus.

The signals in this document are not exclusive. A server can use many types of input to decide how to prioritize things. The extensibility of priority parameters would allow people to follow up with a new one that explores some ordering dependencies like you `order` proposal. 

Alternatively, we could find that server implementations do tend to serve requests in the order they are issued (oldest to newest). If you'd like (newest to oldest) for certain kinds of media a new spec could explain how a server can factor in the value of `content-type` into it's prioritization scheduling in order to optimize performance of a particular use case. 

Either way, I beleive this spec is open enough for continued innovation. Publishing the design we have provides a real benefit to implementations that need it, and reduces risk for implementations that have already deployed it widely and successfully.

**Comment by kixelated** [comment]
Alright, let me close this issue and focus on some of the more concrete items that I think are worth addressing.

**Comment by LPardue** [comment]
Happy to review an I-D for an `order` parameter though, let me know! No reason such a thing can't progress in parallel .
