### ISSUE TITLE
Interaction with caching

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1736]
Origin servers might select a response based upon the value of the `Client-Cert` request header. This might impact caches in these situations:

1. When an intermediary that's generating `Client-Cert` also has a cache
2. When an intermediary between the generator of `Client-Cert` and the origin has a cache (e.g., as part of a CDN hierarchy or a server-side reverse proxy) 
3. When the client on the other side of the TLS connection has a cache (e.g., the browser or other user agent) and the UA's use of client certs varies (e.g., different certs are used, or no cert is used)

Some guidance about this is probably necessary. In cases (1) and (2), it's just a matter of adding `Vary: Client-Cert` to all responses for an access-controlled resource. 

(3) is more subtle, because the browser/UA doesn't see the client cert in the request, since it's generated downstream. From its perspective, `Vary: Client-Cert` will always select a non-existent header field, and so it'll match whatever the certificate used actually is.

The most straightforward thing to do for (3) is to advise that an intermediary generating `Client-Cert` MUST/SHOULD transform `Vary: client-cert` on responses (when it occurs) to `Vary: *`. There need to be some detail work around how this should happen, to make sure that parsing corner cases are caught.

**Comment by bc-pi** [comment]
Thanks @mnot and apologies that I somehow missed seeing this issue when you initially submitted it. I think I can propose a bit of text with guidance along the lines of your suggestions. 

Is it okay or preferred to use `Vary: *` vs. `Cache-Control: no-store`?  [MDN says to use the latter](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary), which isn't a standard I know but it does show up near the top of search results. And on trying to educate myself more I found [the text in this section of RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-7.1.4 ) that says 'A proxy MUST NOT generate a Vary field with a "*" value.' I think RFC 7231 means proxy only in the forward proxy notion of proxy so it's okay for a reverse proxy / gateway. And draft-ietf-httpbis-semantics-19 has a more explicit definition of proxy as such. But it did give me pause.

**Comment by mnot** [comment]
Ignore MDN, it's often wrong (will file a PR there when I get a chance).

`Vary:*` is the most semantically correct, but making it uncacheable works too.

**Comment by b---c** [comment]
Thanks Mark. I took a pass at this with PR #1892
