### ISSUE TITLE
Priorities: too unreliable

### ISSUE THREAD

**Issue by kixelated** [httpwg/http-extensions#1739]
Summarizing some thoughts I left in other comments.

As an application developer, I can't reliably expect prioritization to work. If requests are not being adequately prioritized, then performing more requests in parallel could result in a worse user experience.

I don't know if the server supports prioritization, so I start my application in sequential mode. The presence of a `Priority` header in the first response indicates that at least one hop supports prioritization in some form, however it may not actually be the resource starved hops (ex. last mile). I'm also not sure what parameters are supported by the server without first trying them. Either way, I should issue more requests in parallel and blame any poor performance on server misconfiguration.

I choose an urgency priority for each request somewhere on the 1-8 scale. I don't actually know how the server will allocate bandwidth according to these priorities, it's only recommended that the server will even respect them, and the server is even allowed to override my decisions. My algorithm depends on important requests being delivered first, but it's undefined how or if that will happen.

All of these factors erode my trust in a generic server. I can realistically only prioritize requests when I've manually tested a particular configuration, or prioritization doesn't actually matter. It's not unreasonable to have an application that is tuned for a single CDN, but it does preclude using prioritization in any generic library or application (ex. browser).

**Comment by LPardue** [comment]
> My application uses QUIC for parallelism and server-side prioritization to avoid competition for bandwidth. In theory, HTTP/2 and RFC 7540 would work, but head-of-line blocking would not have a positive impact.

makes sense

> I think getting this draft out the door is important and we can add behavior that works for my application in the future. My only request is that some of the wording is a bit stronger, or better yet there's a quick blurb mentioning the potential impact when the server does not respect the provided priority parameters. It's a hint yes, but the client also has a reasonable expectation that it has impact.

I believe that [section 10](https://httpwg.org/http-extensions/draft-ietf-httpbis-priority.html#section-10) covers these considerations sufficiently. We could boost the visibility of these by referencing them in the intro or applicability sections (I can make a PR for that). If you have specific suggestions for the text in section 10, then please make a PR for review.

**Comment by LPardue** [comment]
https://github.com/httpwg/http-extensions/commit/a7cd8ee53105f0404adde475d357e1412687408f introduced a new paragraph to highlight that signals are hints - https://httpwg.org/http-extensions/draft-ietf-httpbis-priority.html#section-1-7
