### ISSUE TITLE
HTTP/2 PUSH cache mechanism?

### ISSUE THREAD

**Issue by bmeck** [httpwg/http-extensions#174]
Unsure if this is the right place to ask. Is there an existing effort to make a header for HTTP/2's PUSH promises able to sync dependency trees?

Consider:

```html
<!-- index.html -->
<script type="module" src="a"></script>
```

```js
// a
import "b";
```

```js
// b
import "c";
```

And so on...

Right now we can PUSH `a`, `b`, etc. when `index.html` is requested. However, when we receive an etag for `index.html` we are unsure what revision of dependencies are in the cache for `a`, `b`, etc.

I saw CACHE_DIGEST, but was wondering if there was an effort to make dependency tree caching available to reduce chatter for PUSH of large/deep resources as are common in JS applications.

**Comment by gaperik** [comment]
Do you mean making it available to the http layer in the UA or Web  app, e.g. SW JS, or both?

**Comment by bmeck** [comment]
I was talking about a header the server can send back w/ PUSH to declare the dependency tree version / digest. Then the client sends it back along w/ Etag when requesting anything with PUSH dependencies like `index.html` in this example.

**Comment by bmeck** [comment]
So, no JS API.

**Comment by gaperik** [comment]
...and sorry, yes, this is the place and time to discuss this i believe. Just to make thing clear for us pondering browser clients; there is one cache in the HTTP layer of the UA and one in the SW...

**Comment by bmeck** [comment]
We had a thought of [a solution using `Vary: Cookie`](https://docs.google.com/presentation/d/17JX15-Kq_5DGd7ALoa2qqdbEAGSnuF7dsg_7kBKHJKY/edit?usp=sharing) but that is not going to work w/ CDNs.

Our solution was less than optimal because cookies are applied once parsed and cannot be placed in the trailer to only be applied after a fully successful request (including PUSH promises). It did have some nice effects of doing delta based cache invalidation though.

**Comment by gaperik** [comment]
Ok, just saw your response; you are focusing on the http layer cache. 

yes, it's part of several discussions I would say. This was presented at Buenos Aires https://datatracker.ietf.org/doc/draft-kazuho-h2-cache-digest/. The use of Link header to inform a client about such stufff as an ODG has been mentioned. Expect it to be a piece of the puzzle here.
