### ISSUE TITLE
PRIORITY_UPDATE buffer limits need stronger advice

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1747]
Regarding the number of PRIORITY_UPDATE frames that a server should buffer, I think we need to state three things:
* Most recently-received PRIORITY_UPDATE frame for each request stream yet to be opened SHOULD be buffered.
* There should be enough slots in that buffer, so that prioritization information would not be lost when the client tries to fully utilize the concurrency.
* The number of slots MUST be bounded to avoid attacks.

I think that the first two points are already stated in Section 7. Regarding this paragraph, I think the problem with the text that we have is that it is discussing interoperability issues rather than security issues. This is Security Considerations section and what we need to state here is the attack and the mitigation (i.e. the third bullet point).

EDIT. Regarding what we do in h2o (our HTTP/3 stack), we [error-close the connection when receiving a PRIORITY_UPDATE frame carrying a Stream ID that it above the current limit](https://github.com/h2o/h2o/blob/6f6ecfc734dfaf30f3be9d62de81b7a327259ea9/lib/http3/server.c#L1441-L1443). But as you might have pointed out, QUIC stacks might not provide an API that allows HTTP/3 clients to prevent such PRIORITY_UPDATE frames from being sent.

_Originally posted by @kazuho in https://github.com/httpwg/http-extensions/pull/1740#discussion_r727746109_

**Comment by martinthomson** [comment]
I think that the rule for *sending* PRIORITY_UPDATE should be that you not send one prior to having *opened* the stream that you plan to use.  That ensures that you never violate stream limits.

The general requirements for the receiving side are fine.  It's OK (ish) if these signals are lost, so you are just balancing the desire to retain information against the need for endpoints to protect themselves.

Our implementation accepts the frame and does not allow it to be for a stream that exceeds the application MAX_STREAMS value, just like @kazuho.  Following the above advice is sufficient to avoid the stated problem.  Allowing for that rule to be enforced is fine; I would be opposed to *requiring* enforcement as it depends on an interface that doesn't exist in the QUIC spec.

**Comment by RyanTheOptimist** [comment]
> I don't think that endpoints should be free to send PRIORITY_UPDATE for arbitrary streams. It should be possible for applications to avoid sending the frame for streams that cannot exist yet.
> 
> (Right now, our implementation would generate a connection error if a peer did that, and I think that is entirely reasonable.)

Strong +1 to both of these points.
