### ISSUE TITLE
RFC6265bis: Minor improvements to the Max-Age attribute parsing algorithm

### ISSUE THREAD

**Issue by recvfrom** [httpwg/http-extensions#1757]
The current wording of the Max-Age attribute parsing algorithm could be improved so that `Max-Age=-` is handled better (right now, the instructions would lead to attempting to convert `-` to an integer).

Also, it might be worth mentioning that digits should be converted to an integer using base 10 (so it's clear that `Max-Age=0111` should be the same as `Max-Age=111` and not `Max-Age=73`).

I did some quick testing in recent versions of Chrome, Safari, and Firefox by setting cookies using `document.cookie` in the console, and these cases are all handled as expected.  Implementing the improvements above would be some nice dotting of i's and crossing of t's, though.

**Comment by miketaylr** [comment]
Assuming browsers behavior interoperably here, it would be nice to document that (and ensure we have WPTs).

(perhaps after https://github.com/httpwg/http-extensions/pull/1732 lands, so avoid any merge acrobatics)

**Comment by johannhof** [comment]
Testing on WebKit it seems like it differs from Firefox and Chrome:

Setting `a=b; max-age=11111; max-age;` (or `max-age=bla`) will result in WebKit ignoring the 2nd attribute and thus not setting a session cookie, but a cookie with expiry + 11111.

Looking at https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#section-5.4.2 the WebKit behavior actually seems much closer to spec and might be less confusing to web authors as well (invalid attributes get ignored, not turned into session somehow despite valid attributes being present).

I'd like to add tests for this but might need to add better infrastructure first for getting better information than cookie set/not set in WPT.

**Comment by sbingler** [comment]
The issue of what to do with an invalid attribute (ignore the attribute completely, ignore and use last valid, abort the cookie) has come up a few times now. It's probably worthwhile to come up with a story for how to handle this in general.
