### ISSUE TITLE
RFC6265bis: Handling a trailing dot in the domain attribute

### ISSUE THREAD

**Issue by recvfrom** [httpwg/http-extensions#1758]
@miketaylr I vaguely remember us having a discussion related to this from a few weeks ago, but I stumbled across it again today when reading the spec and figured I'd open an issue for it.

There are multiple places in the spec that say:

> Note that a leading %x2E ("."), if present, is ignored even though that character is not permitted, but a trailing %x2E ("."), if present, will cause the user agent to ignore the attribute.

I doesn't look like there's a step in the domain attribute parsing algorithm to actually ignore the attribute if a trailing dot is present, though.  My first thought was maybe this is implicitly handled by the domain-match algorithm.  It's unclear to me what the canonicalized version of `www.example.com.` would be, and whether that'd domain-match with `www.example.com`.  Assuming they don't domain-match, the algorithm states that the whole cookie should be ignored instead of just the attribute being ignored.  Assuming they do domain-match, then the attribute wasn't ignored.

Are we missing a step that would cause the attribute to be ignored in this case?

**Comment by annevk** [comment]
Almost universally throughout the web platform trailing-dot domains are treated as distinct from non-trailing-dot domains. If anything it seems to me that the note is wrong as the attribute should not be ignored if the user is actually visiting a trailing-dot domain, such as `example.com.`.

So I think we should update this to not state anything about trailing dots. (Domain matching should already do the right thing.)

**Comment by sbingler** [comment]
> Almost universally throughout the web platform trailing-dot domains are treated as distinct from non-trailing-dot domains

Thanks for the extra context Anne. That's good to know.

> So I think we should update this to not state anything about trailing dots.

To clarify, you're suggesting to remove 

> but a trailing %x2E ("."), if present, will cause the user agent to ignore the attribute.

within
```
 1.  Let the domain-attribute be the attribute-value of the last
        attribute in the cookie-attribute-list with both an
        attribute-name of "Domain" and an attribute-value whose
        length is no more than 1024 octets. (Note that a leading %x2E
        ("."), if present, is ignored even though that character is not
        permitted, but a trailing %x2E ("."), if present, will cause
        the user agent to ignore the attribute.)
```
rather than correct it?

**Comment by annevk** [comment]
I expect that removing it would be the correction as it is treated as significant by user agents. It's just that in most cases end users are not visiting trailing-dot domains so domain matching ends up failing. However, if the specified domain is `example.com.` and the end user is visiting `example.com.`, it'll work.
