### ISSUE TITLE
ORIGIN:  Support deltas

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#177]
During the discussion of the Secondary Certs work, Nick S. raised the point that it would be interesting to be able to inform the client about dependent domains which are also served by this server as the server returns content that references it.  In order to do this incrementally, an ORIGIN frame would need to be additive -- each successive frame augmenting the client's list of allowed domains.  However, we still need to support the original case, scoping it down.

I'd suggest changing the semantics to be additive and defining a flag whose presence/absence means that the existing list (initially inferred from the certificate) be discarded before processing this frame.

**Comment by martinthomson** [comment]
I think that there is value in having the initial set be empty.  It avoids inference issues, particularly with wildcard certificates.

**Comment by mnot** [comment]
In cache digests, we've just put in a `reset` flag (on the frame) with these semantics. Sound good?

**Comment by MikeBishop** [comment]
Works for me.
