### ISSUE TITLE
RFC6265bis: Consider minimum Max-Age/Expiration cookie attribute value/handling

### ISSUE THREAD

**Issue by arichiv** [httpwg/http-extensions#1774]
We came to an answer to the maximum (400 days) in #1732, but punted on defining a minimum (if any).

One suggestion with plurality support was: "SUOULD be 7 days or more"

**Comment by miketaylr** [comment]
I think this should be out of scope for the 6265bis work, and perhaps considered as an improvement to a future revision to the (new) cookies RFC, given multi-implementor support. 

Right now there's already [signal that we shouldn't pursue this](https://github.com/httpwg/http-extensions/pull/1775#pullrequestreview-792457090).
