### ISSUE TITLE
Message signatures: Pre-signed URLs

### ISSUE THREAD

**Issue by benkehoe** [httpwg/http-extensions#1778]
A useful feature of AWS's SigV4 implementation is to allow, at least for certain services, URLs to be created that include the signature as query parameters. This enables, notably, authorized Amazon S3 uploads and downloads scoped to a particular object as URLs that can be shared with another party. If I'm reading the current (-07) HTTP Message Signatures draft correctly, this sort of delegation would only work with message signatures if the client was able to receive a URL and the `Signature-Input` and `Signature` headers as separate values and construct the HTTP request accordingly. Is this correct, and if so, is there any potential for optionally allowing those two header values to be provided through query parameters instead?

**Comment by jricher** [comment]
This is correct - this draft is purposefully not intended to support URL signing like that, but instead to be completely HTTP-focused, taking advantage of all of the parts of HTTP. That's also why we didn't use the `Authorization` header like other signature methods have used.

While signed capability-style URLs have their uses, I believe those uses are distinct enough that support would warrant a different draft to define them. Such a draft could re-use the message normalization, base string generation, and even the header field format for the query parameter values. However, the application of all of that to a pure URL-based delivery context is substantially different from a full HTTP message, and so I don't think that feature belongs in the core draft.

**Comment by jricher** [comment]
Closing as there are no plans to add this capability within this specification.
