### ISSUE TITLE
Wildcard names

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#178]
If an origin has a wildcard certificate, the origin frame allows it to narrow scope.  But if we accept #177, then there is the potential for the origin to lose any claim to wildcards without enumerating the entire space (at high cost and with a privacy risk).  One way to avoid that would be to support the use of a wildcard.  The rules in RFC2818 are probably appropriate.

**Comment by mnot** [comment]
Thinking out loud, what about two new flags:

* `INHERIT` - if true, we assume that all origins implied by the presented cert are usable on this connection.
* `NOT` - if true, the origins in the frame are subtracted from the set of origins usable on this connection.

In conjunction, that would give more flexibility (and brevity) than wildcards, and be easier to process (is just strings). Would have to work out the interaction with the certs draft tho.

**Comment by martinthomson** [comment]
The implication being that if both were specified, you would be saying "what is in my cert, except these things".

If we do something like `NOT`, then the implication is that there is an existing understanding of the set of origins that are active.  That would need careful definition, and maybe a `RESET` flag so that you can incrementally modify the set in the common case, but set back to baseline as you see fit.

**Comment by mnot** [comment]
Yup, pretty much.

NOT also allows me to pare away origins in a long-lived connection (e.g., for load balancing).

**Comment by martinthomson** [comment]
Oh, that's devious, it's like alt-svc without the actual useful parts.

**Comment by equalsJeffH** [comment]
in terms of which spec to reference for wildcard-cert name matching, it ought to be RFC6125.

**Comment by mnot** [comment]
See recent changes; they define the origin(s) that the connection is authoritative for as the starting Origin Set -- including wildcard certs.

This doesn't allow a wildcard cert to be added; e.g., if Mike's certs draft eventually allows you to add a wildcard cert to the connection, you'd have to enumerate each origin covered by the wildcard to get them into the origin set. 

So, the remaining question is whether we want to allow wildcards into the origin syntax itself.

**Comment by mnot** [comment]
This seems to be overtaken by events; pleas comment if you disagree.
