### ISSUE TITLE
What does the PRIORITY_UPDATE frame override?

### ISSUE THREAD

**Issue by tfpauly** [httpwg/http-extensions#1780]
> Sending a
>    PRIORITY_UPDATE frame preserves the signal from the client, but
>    provides a signal that overrides for the next hop; see Section 14.

I have trouble parsing this sentence, specifically around "a signal that overrides for the next hop". Overrides _what_? Is a word missing here, or can we restructure the sentence to be clearer?

**Comment by LPardue** [comment]
Original context was a proposal from MT here https://github.com/httpwg/http-extensions/pull/1735#discussion_r725716608

So I think we are missing a _that_, e.g. `a signal that overrides that for the next hop`. I made #1781 to fix that that.
