### ISSUE TITLE
Unexpected Alt-Svc frames

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#18]
Section 4 requires PROTOCOL_ERROR on an ALTSVC frame. However, earlier we say that it's a non-critical extension, and can be ignored. Which is it?

Yes, we could make a distinction on "supporting the frame", but that doesn't seem to helpful.

Can we just drop the requirement and say it doesn't mean anything?

**Comment by mnot** [comment]
Discussed in HNL; can be editorial.

**Comment by mnot** [comment]
So, I think the plan is to a) talk about Alt-Svc as a hop-by-hop construct as Martin suggests, and b) drop the requirement to PROTOCOL_ERROR (but note that they'll just be ignored, and might cause the recipient to consider you to be hostile/broken, thus resulting in something similar).

**Comment by reschke** [comment]
a) the PROTOCOL_ERROR requirement is on the server; that still makes sense, no?

b) The spec already says: "The ALTSVC frame is processed hop-by-hop. An intermediary MUST NOT forward ALTSVC frames, though it can use the information contained in ALTSVC frames in forming new ALTSVC frames to send to its own clients." - so is there anything left to do?

**Comment by mnot** [comment]
It's nonsensical that an implementation that doesn't support ALTSVC can ignore it (and as a recipient, no server implements ALTSVC), only to require servers to PROTOCOL_ERROR when receiving it.

**Comment by MikeBishop** [comment]
Agreed -- requiring a PROTOCOL_ERROR if you understand something doesn't really make sense.  Just drop it.
