### ISSUE TITLE
Define fairness

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1819]
From the TSVART review, Bos says:

> §13. Fairness
> 
> T#13a) Please define fair. Seriously.
> 
> A prerequisite question is, "What parameters does a server scheduler
> manipulate?" The text implies the server can only control the order in which it
> starts a response to each request, and whether responses start while other
> responses are in progress or wait for their completion. If so, I'm not sure
> what fairness could mean.
> 
> Presumably a server can also determine the relative rate at which it sends
> different streams. And it could stall a stream to allow another absolute
> priority. In this context, fairness might mean instantaneously equal rates. But
> that's not fair if the objects are of different sizes.
> 
> So we genuinely do need to see a definition of what fairness means here.

We should address this.

**Comment by kazuho** [comment]
I think there's confusion here.

Section 13 discusses fairness of bandwidth allocated between end clients, not requests. I think clarifying this might help.
