### ISSUE TITLE
Why does the IETF have anything to say about scheduling across mutliple connections?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1820]
As part of the TSVART review, Boc said

>  T#13b) Why not make scheduling decisions across different clients?
> 
>    As a general guideline, a server SHOULD NOT use priority information
>    for making scheduling decisions across multiple connections, unless
>    it knows that those connections originate from the same client.
> 
> Why does the IETF have anything to say about this? It's surely an operator
> policy decision.

This seems like a fair point and we likely shouldn't say anything. We can remove this statement entirely but it is normative text so it'll be a change.

**Comment by kazuho** [comment]
I initially though the same, but now I have a counter-argument.

This section (Section 13. Fairness) discusses distributing bandwidth between multiple connections.

13.1 and 13.2 cover considerations when intermediaries coalesce requests originating from multiple connections onto a single backend connection, or split requests being received on one connection to multiple backend connections.

Section 13.3 distributing bandwidth between multiple connections that might share same path. 

I would argue that all of these belong to IETF, and that they should be covered in the document.

We can probably improve the explanation to avoid confusion.

**Comment by LPardue** [comment]
OK that works for me too, could you tackle that?

**Comment by kazuho** [comment]
:+1: Will do alongside #1819.
