### ISSUE TITLE
AD review of draft-ietf-httpbis-targeted-cache-control-02

### ISSUE THREAD

**Issue by fpalombini** [httpwg/http-extensions#1831]
Thank you for the work on this document.

I only have two minor comments, please address them at the same time as the Last Call comments.

Francesca

- [ ] 1. -----

FP: Probably just me missing this conversation, but I was surprised to see that section 2.4 explicitly calls for fields that needs to be registered to use this document as specification document. That surprises me, since for permanent registrations the registration procedure is specification required, and so a specification going into detail for that field should be provided. Maybe what this document meant to say was that draft-ietf-httpbis-targeted-cache-control should be *one of* the specifications for new registrations?

- [ ] 2. -----

FP: Section 3.1 Examples should have a sentence specifying what the target list for those examples is.

**Comment by mnot** [comment]
I think this was dealt with as part of IESG approval, I just forgot to close the issue.
