### ISSUE TITLE
Reduce cruft in the IANA algorith value descriptions

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1836]
From @jricher's WGLC review

> Some of the existing algorithm descriptions should be toned down. Specifically, CRC32c claiming "better hamming distance" and talking about its uses is completely out of place in this registry.

This seems like cruft. The important things for the table are clear pointers to the algorithm definition and the encoding of values created by the algorithm.

**Comment by ioggstream** [comment]
If it's not broken, don't fix it :P I think we spent too much time wrt old algorithms. I'm in favor of anyone that wants to provide a PR that has consensus.

**Comment by jricher** [comment]
It is broken -- let's fix it. :)
