### ISSUE TITLE
Discuss hash collisions in security considerations

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1837]
There's a few mentions of collisions peppered through the code. We should probably have a paragraph (at least) on the topic in the Security Considerations.

**Comment by ioggstream** [comment]
Ok, though this is mentioned in algorithm definitions (sha, md5).

**Comment by LPardue** [comment]
Since @jricher raised this issue, I'd like his opinion too. 

As Roberto says, we note the collision attacks in the algorithm definitions. What more would a specific section in the Security considerations have to say?

**Comment by jricher** [comment]
Choosing a secure algorithm is a security consideration, and they're only as secure as the underlying algorithm. It seems silly but it should be pointed out explicitly as a security consideration here that the digest is only as good as the algorithm used to create it. The registry is a great way to make that decision easier but the underlying consideration is that some digests are easier to force collisions -- for example, by adding semantically irrelevant padding to the content.

**Comment by ioggstream** [comment]
@jricher pls see/integrate the linked PR

**Comment by jricher** [comment]
@ioggstream I did, it doesn't go far enough. That's just a consideration for the registry, but like I said above it needs to be spelled out more as considerations for implementors, not just the experts running the registry.

**Comment by ioggstream** [comment]
@jricher do you suggest to add the following?

1- the digest is only as good as the algorithm used to create it.
2- some digests are easier to force collisions -- for example, by adding semantically irrelevant padding to the content.


1. while it's tautological, I'm ok with adding this
2. that some digests are easier to force collisions is implied by the fact of having insecured SHA-1 and MD5 
3. I'm ok wrt mentioning "adding semantically irrelevant padding to the content" together with the altering content using `content-enconding` in the "signature" section.

WDYT?

**Comment by jricher** [comment]
@ioggstream All of that would be good to add, but it needs to be in a security consideration paragraph about choosing algorithms, not in the instructions about registering algorithms. No implementor will read the IANA paragraphs that the PR currently targets.
