### ISSUE TITLE
Corruption might not be by accident

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1838]
From @jricher's WGLC review:

> §8.1: It's not just accidental corruption, but also malicious changes. The important part here is that it only protects the message body and not the rest.

Corruption could also be non-accidental. Let's remove the accidental qualifier or add words about explicit manipulation (for good or bad purposes).

**Comment by ioggstream** [comment]
Agree, but I think that accidental/bad implementation has to be mentioned.

**Comment by ioggstream** [comment]
@jricher @LPardue I'd close with no-action :)

**Comment by LPardue** [comment]
> @LPardue Removing "accidental" from the sentence in question would fix the issue.

I completely agree, I'll do that!
