### ISSUE TITLE
Explain the reasons why algorithm agility could be bad

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1841]
From @jricher's WGLC review:

> §8.6: This draft's algorithm agility effectively allows an attacker to choose and substitute the algorithm applied to the message, which could allow the attacker to choose a weaker algorithm and apply a collision hash to a request. Signing the digest headers, with things like message signatures, mitigates this by fixing the values in the digest header. Also, a recipient should have a limited set of algorithms that it should accept for a given application, and not just take whatever the message creator (or attacker) sends it.

**Comment by ioggstream** [comment]
@jricher is it ok to integrate the security consideration on signatures? Do you think we should describe stuff in other sections too?

**Comment by ioggstream** [comment]
re-reading, this is explained in "replacing rfc 3230". I'll add a link in the related sec-
