### ISSUE TITLE
Review use of checksum term

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1844]
From @jricher's WGLC review:

> Throughout document, "checksum" and "digest" are used interchangeably, is that intentional? It would probably be better to pick one, and I suggest "digest".

Personally, I think the use of both terms is ok. Mainly because digest is overloaded in the document. But it wouldn't hurt us to review the document for usages and perhaps add a note in notational conventions about the use of terms.

**Comment by ioggstream** [comment]
`checksum` is a generic checksum computation,
`digest` should be the actual digest algoritm computation. We need to clarify this and probably introduce new terminology.
