### ISSUE TITLE
Editorialize the IANA header registration

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1845]
Noted by Justin, it's a weird order and can be simplified to reduce repetition. Let's make the job easier for our friends in IANA.

**Comment by ioggstream** [comment]
@LPardue wdyt of the ratelimit layout? https://github.com/ietf-wg-httpapi/ratelimit-headers/blob/main/draft-ietf-httpapi-ratelimit-headers.md#iana-considerations

**Comment by LPardue** [comment]
I fixed the ordering in #1919. But that is subject to change as a result of #1933 and #1966. Let's make a table once we have the answer there.

**Comment by ioggstream** [comment]
#1983 fixes
