### ISSUE TITLE
Client hints: wording on Save-Data

### ISSUE THREAD

**Issue by vfaronov** [httpwg/http-extensions#186]
`draft-ietf-httpbis-client-hints.md`:

> The "Save-Data" request header field is a token that indicates

should be something like:

> The "Save-Data" request header field is one or more tokens that indicate

or maybe just:

> The "Save-Data" request header field indicates

**Comment by reschke** [comment]
Also: change "request header field" to "....field *value*".

**Comment by igrigorik** [comment]
@reschke all of the other definitions use "X request header field is a Y that...". If we change one we should change all the rest. Is this something we want or need to do?

**Comment by reschke** [comment]
You decide; maybe I am too pedantic...

**Comment by igrigorik** [comment]
Let's keep it as is for now. If this comes up again in other contexts, we can revisit.
