### ISSUE TITLE
Lifetime of Key headers

### ISSUE THREAD

**Issue by zwoop** [httpwg/http-extensions#187]
It could be better for some implementers if the lifetime of the Key headers is the same as the Cache-Control: from the response wherein the Key header was seen. The spec today says that the Key header used should be the last one seen, but this can cause some complex, and/or performance expensive issues for certain cache implementations.

Unless the intent here is that I can purge old variants from the cache, that are still fresh, by changing the Key header for subsequent variants?

**Comment by mnot** [comment]
That was the intent, yes.
