### ISSUE TITLE
Set-Cookie attribute name case sensitivity

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1881]
The grammar implies that set-cookie attribute names are case insensitive (because ABNF strings are), and the parsing algorithms say that they're case-insensitive, but I suspect many people may not realise this, because they're so often seen in CamelCase. 

Could we add a small statement to the Set-Cookie syntax section pointing this out?

**Comment by annevk** [comment]
It's also worth having a variety of styles in the examples to illustrate this.
