### ISSUE TITLE
No leading or trailing whitespace in field values

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1884]
The canonicalization rules for a field value lists [stripping leading and trailing whitespace](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-07.html#section-2.1-3.2) but field values [cannot start or end with whitespace](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.5.5.p.3). Therefore, this step is a no-op.

**Comment by jricher** [comment]
OK, thanks. Since we need to make sure that lazy header parsers don't much this up, we can move this into a note instead of an explicit step.

**Comment by jricher** [comment]
This has been changed in #1903: new text says to use the combined-value from SEMANTICS and provides the canonicalization algorithm as a different means to achieve this by hand. The string removal and obs-fold portions are called out specifically as ways of dealing with exceptions and bad HTTP implementations.
