### ISSUE TITLE
Signatures:  2.1.2. HTTP Field Examples broken

### ISSUE THREAD

**Issue by bblfish** [httpwg/http-extensions#1885]
The [canonicalised values example in 2.1.2 ](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-07.html#name-http-field-examples) seems to be broken in many ways.

```text
"cache-control": max-age=60, must-revalidate|
"date": Tue, 07 Jun 2014 20:51:35 GMT|
"host": www.example.com|
"x-empty-header":
"x-obs-fold-header": Obsolete line folding.
"x-ows-header":Leading and trailing whitespace.
"x-dictionary": a=1,    b=2;x=1;y=2,   c=(a   b   c)
"x-dictionary";sf: a=1, b=2;x=1;y=2, c=(a b c)
```

* The first three lines end in `|`.
* There is a missing space after `:` on the `"x-ows-header"` line
* the second to last line has more space than should be (I think) `"x-dictionary": a=1,    b=2;x=1;y=2,   c=(a   b   c)` 
* I am not sure what the `;sf` on the last line refers to.
* the date is wrong on the second line `"date": Tue, 07 Jun 2014 20:51:35 GMT` and in the HTTP example. The 07th was not a Tuesday but a Saturday, as shown by the screenshot below of my calendar.  Even though it is interesting to consider a mistaken date like this, I think it is highly likely to lead to signatures that don't work as many platforms will parse the http headers down to a unix time before passing it on to the the software that can use it.
<img width="751" alt="Screenshot 2022-01-10 at 20 33 52" src="https://user-images.githubusercontent.com/124506/148827649-7f569766-e009-4b15-8d93-ce21c1bb4af6.png">

**Comment by bblfish** [comment]
This is the signing string I get for the http request using my parser from version 04 of the spec

```
NOTE: '\' line wrapping per RFC 8792

"cache-control": max-age=60, must-revalidate
"date": Sat, 07 Jun 2014 20:51:35 GMT
"host": www.example.com
"x-empty-header": \

"x-obs-fold-header": Obsolete line folding.
"x-ows-header": Leading and trailing whitespace.
"x-dictionary": a=1, b=2;x=1;y=2, c=(a b c)
"@signature-params": ("cache-control" "date" "host" "x-empty-header" \
"x-obs-fold-header" "x-ows-header" "x-dictionary");keyid="some-key"
```

**Comment by jricher** [comment]
Yes, this is a typo from a last-minute reformatting of that section that was corrected in the editor's copy: 7d2529b3251ec3676cb7ff86abf78b719337a5d6

The "empty header" space still needs to be fixed as noted in #1876

**Comment by bblfish** [comment]
> `sf` should be `sv`

That does not help much :-) I can't find any definition of what `sv` means. Do you mean it should be `;key="sv"` or something like that? I can only find examples using `key="..."` such as this nice one

```
Signature-Input: sig1=("@method" "@path" "@authority" \
    "cache-control" "x-empty-header" "x-example")\
    ;created=1618884475;keyid="test-key-rsa-pss", \
  proxy_sig=("signature";key="sig1" "forwarded")\
    ;created=1618884480;keyid="test-key-rsa";alg="rsa-v1_5-sha256"
```

**Comment by jricher** [comment]
Oh wait, I was wrong -- `sf` is the right value after all. Anyway, it's defined in here:

https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-07.html#name-canonicalized-structured-ht

**Comment by bblfish** [comment]
Ah, yes. I see "sf parameter" now! 
Ok, I will try to implement that too :-)

**Comment by jricher** [comment]
Examples have been regenerated by #1903, please check for consistency. The x-empty-header has been removed from the signed examples and relegated to a field serialization example instead.
