### ISSUE TITLE
Client Hints: Accept-CH html meta http-equiv

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#189]
"Servers can advertise support for Client Hints using the Accept-CH header field or an equivalent HTML meta element with http-equiv attribute ([W3C.REC-html5-20141028])."

In which case it should be added to https://wiki.whatwg.org/wiki/PragmaExtensions  (like it or not).

"When a client receives Accept-CH, it SHOULD append the Client Hint header fields that match the advertised field-values. For example, based on Accept-CH example above, the client would append DPR, Width, Viewport-Width, and Downlink header fields to all subsequent requests."

Q: does the SHOULD also apply to the HTML http-equiv variant?

**Comment by igrigorik** [comment]
> Q: does the SHOULD also apply to the HTML http-equiv variant?

Yes. Is there a common term we can use here to refer to both the header field value and attribute value?

**Comment by reschke** [comment]
Well, that implies that every user agent SHOULD parse HTML and process <meta> elements. Is this a realistic requirement?

**Comment by igrigorik** [comment]
> The term "user agent" refers to any of the various client programs that initiate a request, including (but not limited to) browsers, spiders (web-based robots), command-line tools, custom applications, and mobile apps

Perhaps not. 

> When a client receives Accept-CH, or if it is capable of processing the HTML response and finds an equivalent HTML meta element, it SHOULD append the Client-Hint header fields that match the advertised field-values. For example, based on Accept-CH example above, the client would append DPR, Width, Viewport-Width, and Downlink header fields to all subsequent requests.

Warmer?

**Comment by igrigorik** [comment]
From: https://lists.w3.org/Archives/Public/ietf-http-wg/2016AprJun/0322.html

> This "all subsequent requests" is obviously intended to be qualified
> somehow. It's not "all requests to all servers ever", is it? Should it
> be "all subsequent requests to the same origin"? Should it be "all
> subsequent requests to this resource"?
>
> Likewise, the "SHOULD append" phrase is unclear: append to what exactly?

How about...

> When a client receives Accept-CH, or if it is capable of processing the HTML response and finds an equivalent HTML meta element, it SHOULD append the Client-Hint header fields that match the advertised field-values to the header list of all subsequent requests. For example, based on Accept-CH example above, a user agent could append DPR, Width, Viewport-Width, and Downlink header fields to all subresource requests initiated by the page constructed from the response. Alternatively, a client may remember the preference at origin level and advertise same header fields on all future requests initiated to and by the resources associated with that origin.

In other words, it's not the intent of this spec to spell out a specific behavior, we leave that to the client.

**Comment by reschke** [comment]
SGTM, where "may" ought to be "MAY" or "can".

**Comment by igrigorik** [comment]
Thanks, updated in https://github.com/httpwg/http-extensions/pull/190.
