### ISSUE TITLE
safe-method-w-body: ordering in Accept-Query

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#1896]
David Slik (https://lists.w3.org/Archives/Public/ietf-http-wg/2022JanMar/0081.html):

> The sentence "The order of types listed by the Accept-Query header field is insignificant." should be changed to "The order of types listed by the Accept-Query header field is not significant." Insignificant implies that there is a difference indicated by the order, but it can be disregarded, where not significant indicates that there is no difference indicated by the order, and it shall be disregarded.

**Comment by dslik** [comment]
Change looks good to me.

**Comment by reschke** [comment]
And thanks for the feedback!
