### ISSUE TITLE
Signature 07: Signing String date wrong in B.2.3 

### ISSUE THREAD

**Issue by bblfish** [httpwg/http-extensions#1901]
The Example from [Appendix B.2.3](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-07.html#appendix-B.2.3) uses the following request defined in  B.2

```scala
POST /foo?param=value&pet=dog HTTP/1.1
Host: example.com
Date: Tue, 20 Apr 2021 02:07:55 GMT
Content-Type: application/json
Digest: SHA-256=X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=
Content-Length: 18

{"hello": "world"}
```
The signing string is meant to be

```text
"date": Tue, 20 Apr 2021 02:07:56 GMT
"@method": POST
"@path": /foo
"@query": ?param=value&pet=dog
"@authority": example.com
"content-type": application/json
"digest": SHA-256=X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=
"content-length": 18
"@signature-params": ("date" "@method" "@path" "@query" \
  "@authority" "content-type" "digest" "content-length")\
  ;created=1618884475;keyid="test-key-rsa-pss"
```
But that does not work because in the request we have
```http
Date: Tue, 20 Apr 2021 02:07:55 GMT
```
and the date in the signing string is one minute later
```text
"date": Tue, 20 Apr 2021 02:07:56 GMT
```

**Comment by jricher** [comment]
Thanks, all the examples need to get re-generated and I'll work on that soon. The current generation script is at https://github.com/bspk/sig-example-scripts/blob/main/http_sig_examples.py ... it's very manual right now but I'm thinking of reworking it to do actual HTTP message parsing under the hood like we have at httpsig.org instead, so we don't end up with inconsistencies like this in the results.

**Comment by bblfish** [comment]
I am also developing a test suite for the examples in the spec, which is why I am reporting the bugs I find here :-) That can help you later verify that your new setup is correct. 

I just found a last error in the [Appendix B.3.](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-07.html#appendix-B.3)  Signing String. The Signing string given there is 

```
"@path": /foo
"@query": Param=value&pet=Dog
"@method": POST
"@authority": service.internal.example
"client-cert": :MIIBqDCCAU6gAwIBAgIBBzAKBggqhkjOPQQDAjA6MRswGQYDVQQ\
  KDBJMZXQncyBBdXRoZW50aWNhdGUxGzAZBgNVBAMMEkxBIEludGVybWVkaWF0ZSBD\
  QTAeFw0yMDAxMTQyMjU1MzNaFw0yMTAxMjMyMjU1MzNaMA0xCzAJBgNVBAMMAkJDM\
  FkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8YnXXfaUgmnMtOXU/IncWalRhebrXm\
  ckC8vdgJ1p5Be5F/3YC8OthxM4+k1M6aEAEFcGzkJiNy6J84y7uzo9M6NyMHAwCQY\
  DVR0TBAIwADAfBgNVHSMEGDAWgBRm3WjLa38lbEYCuiCPct0ZaSED2DAOBgNVHQ8B\
  Af8EBAMCBsAwEwYDVR0lBAwwCgYIKwYBBQUHAwIwHQYDVR0RAQH/BBMwEYEPYmRjQ\
  GV4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUCIBHda/r1vaL6G3VliL4/Di6YK0\
  Q6bMjeSkC3dFCOOB8TAiEAx/kHSB4urmiZ0NX5r5XarmPk0wmuydBVoU4hBVZ1yhk=:
"@signature-params": ("@path" "@query" "@method" "@authority" \
  "client-cert");created=1618884475;keyid="test-key-ecc-p256"
```

my test tells me that the diff should be:

```
=> Diff (- obtained, + expected)
   value = """"@path": /foo
-"@query": ?Param=value&pet=Dog
+"@query": Param=value&pet=Dog
 "@method": POST
```

**Comment by jricher** [comment]
Examples have been regenerated by #1903, please check the new example for consistency.

**Comment by jricher** [comment]
Just saw this other comment, yes it looks like there's a bug in the query value generator that drops the question mark! 🤦

**Comment by bblfish** [comment]
Btw. My EU project just ended, so I am looking for extension projects. But perhaps someone here knows companies that need me to work on the https://github.com/bblfish/httpSig implementation? (Ie,Java or JS or Scala)... I don't really know where one can ask this. A bit of a specialized thing :-)
