### ISSUE TITLE
Signatures: "Related response" feature

### ISSUE THREAD

**Issue by yaronf** [httpwg/http-extensions#1905]
I think the "related response" feature, as in:

>If used in a related-response, the `@path` identifier refers to the associated component value of the request that triggered the response message being signed.

is not a good idea, for two reasons:

* It only applies (and can only apply) to specialty/derived components, and cannot apply to normal headers and query params which people might also want to bind between requests and responses.
* It is subsumed by the `@request-response` feature, and request-response is simpler and more secure. You decide once which request fields need to be signed, and the response is then bound to the entire verified request.

So I would suggest to remove this feature, and allow `@path` and similar to only apply to requests.

**Comment by jricher** [comment]
It's not entirely subsumed by request-response, since this requires the client to sign the initial request, which the server has no control over. That said, it may be safer to have that restriction.

**Comment by yaronf** [comment]
On second thought, there may be cases when the client is unable to sign, because its public key is not trusted by the server. So the server is doing the signing for both of them. Strange.

This still doesn't address my first point. Specifically, if the whole semantics of the request is in the message body, there's no way for the server to bind the response to the Digest of the request.

**Comment by jricher** [comment]
You are correct, there's no way to bind a header from the request into the related-response method if you're doing it server-only. The editors discussed this and felt like it would be a very complicated path for people to get right, and it could lead to confusion and potential security issues. With the derived content, there's at least no ambiguity as to what the source of the data is -- if it's a request-only value and you're looking at a response, you know it came from the triggering request.

That said, this whole feature is more of a "nice to have" in my own book. I think it makes sense, but I'd like to hear more from implementors who would actually use this, or not. It's entirely possible that for real-life use cases the request-response derived content is sufficient for systems that would be able to make sense of such an advanced use case anyway.

**Comment by yaronf** [comment]
Just to throw it out there, I would have loved a more explicit construction. Such as:

* `@related/x-My-Header`
* `@related/@query`

I haven't checked if the `/` character is even allowed.

**Comment by jricher** [comment]
Thanks for that idea, it's something the editors considered. If we did that, the syntax would just use structured field parameters, like `"@related"; field="x-header"`. Things start to get really weird when you allow signing elements that have their own parameters, though. We started down that path to get the "request-response" functionality originally, since you could sign a "related" signature header, but we really didn't like the complexity that arose very quickly from that construct. The narrowly defined derived components were our way around that. I agree that they're still complicated and it's a reasonable question whether the functionality is worth it or not.

**Comment by mnot** [comment]
As discussed in the meeting today, in HTTP the corresponding request is necessary to fully understand and contextualise a response. while `@request-response` does that, as @jricher points out that doesn't work in the case when the client doesn't sign the request. 

My tentative suggestion would be to collapse `related-response` into `response` and distinguish request headers from response headers with prefix other than `@`.

**Comment by yaronf** [comment]
I like both the `;req` proposal as well as getting rid of the special-case `@request-response`.

**Comment by mnot** [comment]
WFM - not hung up on syntax.
