### ISSUE TITLE
Method rewriting and Redirects

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1916]
>  In some cases, the server may choose to respond indirectly to the QUERY request by returning a 3xx Redirection with a Location header field specifying an alternate Request URI from which the results can be retrieved using an HTTP GET request.

Some 3xx will rewrite the method, but others won't.

**Comment by reschke** [comment]
So this needs to be 303, right?

**Comment by mnot** [comment]
Yes. It might be worth mentioning that other redirects work too.

**Comment by reschke** [comment]
Which?

Yes, redirects work as expected, but if you want the subsequent request to be a GET, it needs to be 303, no?

**Comment by reschke** [comment]
This paragraph needs some rewriting, now that we have established what Location and Content-Location mean on a QUERY response.
