### ISSUE TITLE
Identifying QUERY results

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1918]
It might be good to explicitly point out that QUERY responses don't have a URL to identify them, as per [core](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#identifying.content).

**Comment by reschke** [comment]
...unless indicated by Content-Location, right?

**Comment by mnot** [comment]
Yes. Probably with something like:

> Note that a response to a QUERY request, is not identified by the target URI; see [ref to core].

**Comment by reschke** [comment]
I'm still confused why we would say that for QUERY, but not for PUT or POST... QUERY is not special with respect to this; GET is.

**Comment by mnot** [comment]
Because QUERY will be considered by many as a drop-in replacement for GET, and may not realise this implication.

**Comment by mnot** [comment]
See also #1745.

**Comment by reschke** [comment]
@mnot - given the resolution of #1745 - this can be closed, right?

**Comment by mnot** [comment]
Think so - need to review but if you think it's addressed go ahead and close.

**Comment by reschke** [comment]
We believe this has been taken care of with #1745.
