### ISSUE TITLE
Signatures: Host header

### ISSUE THREAD

**Issue by yaronf** [httpwg/http-extensions#1921]
There are quite a few occurrences of the `Host` header in the draft.

From an implementation point of view, Go "swallows" the `Host` header and it is not part of the standard Request structure. There's a good reason for the Go library to do it, and in fact the draft recommends to use @authority instead. Can we remove `Host` from examples, e.g. Sec. 2.1, so we don't train people to do the wrong thing?

**Comment by jricher** [comment]
There are only a couple instances of the "host" header in the current draft left, and one of them (section 2.1) is specifically about how to format headers. It could be removed from the other example signature input strings without affecting anything negatively. Same with the "date" header, which could be confused with the "created" parameter, see #1189
