### ISSUE TITLE
Consider an HTTP/2 example

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1924]
I appreciate this protocol encodes HTTP messages. But it mentions it's inspired by HTTP/2 and HTTP/3. Then it only gives examples using HTTP/1.1. 

I wonder if it would also be useful to include an example of how message carried over HTTP/2 can be converted into binary messages. If only to show that is is identical to the binary message content from a 1.1 request.

**Comment by martinthomson** [comment]
I'm not sure how much value it would provide a reader.  People who do HTTP in general understand it in terms of how it looks as HTTP/1.1, if only because that is the lowest common denominator.  Would you include the framing in the example?  Is there something in particular you think needs to be highlighted?

**Comment by LPardue** [comment]
Good questions. I think the piecethat confuses me is all the references to HTTP/2 in the document, particularly in S 3.4 and 3.5 where the term "corresponds" is used. 

At the top you say the format is informed by H2 and H3 but the body of the text seems to imply that there is a much tighter coupling to H2. And I'm getting more puzzled the deeper I read the document.

**Comment by LPardue** [comment]
I commented on the PR but want to bring it back to the issue before I digress too much.

S 3.4
> The control data for a request message includes four values that correspond to the values of the :method, :scheme, :authority, and :path pseudo-header fields described in HTTP/2 ([Section 8.3.1](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-http2bis-07#section-8.3.1) of [[H2](https://httpwg.org/http-extensions/draft-ietf-httpbis-binary-message.html#H2)]).

 These fields are encoded, each with a length prefix, in the order listed.The rules in [Section 8.3](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-http2bis-07#section-8.3) of [[H2](https://httpwg.org/http-extensions/draft-ietf-httpbis-binary-message.html#H2)] for constructing pseudo-header fields apply to the construction of these values. However, where the :authority pseudo-header field might be omitted in HTTP/2, a zero-length value is encoded instead.

One alternative way I would write this is to say something like

Request Control Data contains the method and target of a request message. That information is encoded as an orderd sequence of fields: Method, Scheme, Authority, Path. Each field is prefixed with a length. 

The values of these fields are extracted from an HTTP message by applying the rules in HTTP/2 (citation) that apply to the :method, :scheme, :authority, and :path pseudo-header fields. However, where the :authority pseudo-header field might be omitted in HTTP/2, a zero-length value is encoded instead.

**Comment by martinthomson** [comment]
That's a great help.  I'll steal that.  Thanks Lucas.

**Comment by LPardue** [comment]
The PR is helping. The last thing that sticks out to me is in https://httpwg.org/http-extensions/draft-ietf-httpbis-binary-message.html#section-3.6-8

> This format provides fixed locations for content that would be carried in HTTP/2 pseudo-fields. Therefore, there is no need to include field lines containing a name of :method, :scheme, :authority, :path, or :status. Fields that contain one of these names cause the message to be invalid; see Section 4. Pseudo-fields that are defined by protocol extensions MAY be included. Field lines containing pseudo-fields MUST precede other field lines; a message that contains a pseudo-field after any other field is invalid; see Section 4.

IIUC this draft is about HTTP encoding messages, and pseudo-headers are not part of those. So why are you saying anything about them? 

I think this paragraph is a good example of my confusion. It reads like an implementation is supposed to go HTTP message -> H2 HEADERS frame -> Binary HTTP Message. But based on our discussion here and the PR I think the transform is one step HTTP message -> Binary HTTP Message. If that's correct I suggest also rewording this paragraph and possibly removing the mention of pseudo-headers altogether

**Comment by martinthomson** [comment]
I'm going to say that we've resolved this with words rather than examples.  Re-open if you disagree or would like to see more.

**Comment by LPardue** [comment]
Yes thanks, an example would be weird now I understand what to goals and methods are.
