### ISSUE TITLE
Prohibited methods?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1925]
What does it mean for a client to send, for example, a CONNECT request in the binary message. Is that permitted or prohibited?

**Comment by martinthomson** [comment]
I don't think that it needs to be prohibited.  It's just not going to do anything that makes any sense.  Worth a note perhaps.

**Comment by LPardue** [comment]
I guess it could work if the thing you're delivering the binary message to actually actions the CONNECT, exchanging tunneled bytes would just look like content.

**Comment by martinthomson** [comment]
You would need somewhere for those bytes to go.  A valid CONNECT request doesn't include a body.  It's nonsensical basically.
