### ISSUE TITLE
ordering of concepts: checksum, integrity, digest, ... 

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1933]
Later you put content integrity first with representation integrity second.  Here, it's the other way around.  Maybe try to make that consistent.  (I'd prefer content-first ordering if it came down to a coin toss.)

_Originally posted by @martinthomson in https://github.com/httpwg/http-extensions/pull/1919#r799057884_

**Comment by ioggstream** [comment]
Addressed in #1919  with

> Hashing algorithm names respect the casing used in their definition document (e.g. SHA-1, CRC32c) whereas hashing algorithm keys are quoted (e.g. "sha", "crc32c").

>The term "checksum" describes the output of the application of an algorithm to a sequence of bytes, whereas digest is only used in relation to the value of the fields.

@martinthomson can this work? We probably need to proof-read the rest of the document though...

**Comment by martinthomson** [comment]
So you are using "integrity fields" to refer to the fields, "digest" to refer to the value that is output from a "hash algorithm", and just a few mentions of checksum.  I think that the "checksum" thing is still quite odd.  Why distinguish between the algorithm output and the value of the field?

**Comment by ioggstream** [comment]
I think the concepts around are the following:

1. the checksum of the data
2. the encoding of the above checksum, that should now be transparent since the encoding is now addressed by SF: I think that 1. and 2. can be  interchangeably be called "checksum"
3. what we once called "representation-data-digest" and that is now called "digest" eg.  `sha-256=:fafafafa=:` that is the serialization of the couple `(algorithm, checksum)`
4. the field value, *made of multiple "digest"s*, that I'd just call "field value" 

> Why distinguish between the algorithm output and the value of the field?

see 4. Does it make sense to you?

**Comment by LPardue** [comment]
Since the issue was opened, we made changes to text and ran the doc through WGLC. I'm going to close this as resolved. We can address additional feedback in LC if needs be.
