### ISSUE TITLE
Ambiguity about connection-specific fields

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1936]
> Field names and values MUST be constructed and validated according to
   the rules of Section 8.2.1 of [H2].  A recipient MUST treat a message
   that contains field values that would cause an HTTP/2 message to be
   malformed (Section 8.1.1 of [H2]) as invalid; see Section 4.

Those references are doing a lot of work -- but does it also include 8.2.2?  I.e., are `Transfer-Encoding` and friends allowed? It's ambiguous, because the text implies _all_ things that make it malformed, but only points to one source.

**Comment by martinthomson** [comment]
No point duplicating that work, but I agree that it might be unclear as stated.

Does this split make it clearer?

> A recipient MUST treat a message that contains field values that would cause an HTTP/2 message to be malformed according to {{Section 8.2.1 of H2}} as invalid; see {{invalid}}.
>
> Fields that relate to connections ({{Section 7.6.1 of HTTP}}) cannot be used to produce the effect on a connection in this context.  These fields SHOULD be removed when constructing a binary message.  However, they do not cause a message to be invalid ({{invalid}}); permitting these fields allows a binary message to capture the content of a messages that are exchanged in a protocol context.

I'll make a PR with those changes in context.

(I think that the latter is consistent with what you and @wtarreau are discussing on-list, though I need to spend a bit more time on understanding that.)

**Comment by wtarreau** [comment]
I think it does the job, indeed!
