### ISSUE TITLE
Applicability

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1937]
This document is going to be viewed by some as establishing the 'shape' of an HTTP message -- which is a good and perhaps necessary thing. 

However, some will be sad, because it doesn't suit some applications such as forensic preservation of messages, bot detection, debugging, faithful representation of HTTP/1, etc., due to transformations and loss of certain information (especially around headers).

So it'd be good to set expectations early on (perhaps in the Introduction).

**Comment by martinthomson** [comment]
Good point.  It's for semantics, not forensics and all that.
