### ISSUE TITLE
Binary messages: why is Known-Length Field length at least 2?

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#1944]
The draft currently shows:
```
Known-Length Field Section {
  Length (i) = 2..,
  Field Line (..) ...,
}
```

This Length field isn't well defined. Is it the length of the Known-Length Field Section in bytes or in lines? If in bytes, does it include or exclude the length of the Length field itself? Either way, I don't understand why Length is at least 2. Either it's possible for there to not be any field lines, in which case maybe it should be zero. And if there needs to be at least one field line, then (we should say so, and) the minimum number should be 3, because a field line is two lengths and at least one byte of field name.

**Comment by LPardue** [comment]
To pile on here, the spec also says in one place

> Both name and value are sequences of bytes that cannot be zero length

and in another 

> Each field line includes a name and a value. Both the name and value are length-prefixed sequences of bytes. The field name length is at least one byte.

So if the value also can't be zero-length, then the minimum should be 4?

**Comment by DavidSchinazi** [comment]
@LPardue see #1945

**Comment by LPardue** [comment]
Yeah saw that after hitting the button. Didn't intend to derail 😀
