### ISSUE TITLE
Binary message: are empty field values allowed?

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#1945]
The Known-Length Messages section states that `Both name and value are sequences of bytes that cannot be zero length.` whereas the Header and Trailer Field Lines section allows empty field values. Which is it?

**Comment by martinthomson** [comment]
Editorial error on my part.  Someone pointed out that fields can have empty values (yet another feature of the protocol that is weird and unnecessary).  I fixed it one place, but not the other.  Thanks for noticing.
