### ISSUE TITLE
Binary message: what is truncation?

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#1946]
The draft mentions that messages can be truncated in some places, but not in others. I think it would help to explain why one would want to truncated a message.

**Comment by martinthomson** [comment]
This is really just a neat way to avoid having to write out all of the pieces of a message.  So if you don't have trailers, it's OK not to say "I have 0 trailers".  The decoder is required to deal with it.

Before you say "that's hard", you don't need to change the parser to deal with truncation.  Adding three zero-valued bytes to the end of any message you receive does the job just fine.  If it isn't truncated, those will be treated as padding.
