### ISSUE TITLE
Binary messages: do known-length requests carry Known-Length Informational Response?

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#1947]
I suspect that requests do not carry the Known-Length Informational Response field (otherwise how do you know how many of them there are?) but that should be spelled out explicitly.

I'd suggest creating a different diagram for known-length request vs known-length responses to make this easier to reason about, and same for indeterminate length

**Comment by LPardue** [comment]
I think the optionality is supposed to be indicated by the three trailing dots `Known-Length Informational Response (..) ...,`. I admit to doing a double-take on this, similar to David's question. It's optional for a server, sure, but it's never optional for a request just wrong. I agree that separate diagrams would help, at the minor cost of some page space.
