### ISSUE TITLE
python code should use SF

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#1953]
## I expect

python code to use SF to ensure examples are ok

```
from http_sfv import Dictionary
from hashlib import sha512

content = b'{"hello": "world"}'
digest = sha512(content).digest()
str(Dictionary({"sha-256":  digest}))

# 'sha-256=:WZDPaVn/7XgHaAy8pmojAkGWoRx2UFChF41A2svX+TaPm+AbwAgBWnrIiYllu7BNNyealdVLvRwEmTHWXvJwew==:'
```

**Comment by mnot** [comment]
If you mark the examples with `http-message` and include your field names in `sf.json`, this should be automatic when you `make lint`.

**Comment by LPardue** [comment]
Working on this as part of #1919

**Comment by LPardue** [comment]
@ioggstream can we close or is there something more you wanted to do?

**Comment by ioggstream** [comment]
I wanted to show http_sfv in the examples

**Comment by ioggstream** [comment]
Since examples are not normative, I think we can close.
