### ISSUE TITLE
Merge section 2 and 6 so normative handling of representation digest is clearer

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#1967]
Section 2 defines the Representation-Digest field but doesn't really ever go as far as defining any MUST language requirements on how it is calculated. This is probably a hangover from RFC 3230, which also seemingly overlooked it.

But the important thing now is that Section 6 goes and states two requirements on Representations and state-changing requests. This seems like good stuff, but it's position in the draft is easily overlooked. So I suggest we merge these sections into one, then everything to do with representations is all together. That merge should consider if a more general MUST is needed on top of these special cases.

**Comment by ioggstream** [comment]
These can be subsection of 2. I think these should be linkable sections.
