### ISSUE TITLE
Check syntactic mismatches

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#1988]
For each field that's 'compatible', we need to ascertain whether _all_ registrable / usable values "fit" -- both by examining ABNF and common use. 

Where there are mismatches, we need to either drop the header, document the mismatch, or move it to a mapped field. Preference would be to document, so long as it doesn't affect real-world use.

**Comment by jricher** [comment]
My preference is also to document mismatches, with something in that documentation about how often one might see it in practice.

**Comment by mnot** [comment]
| Field Name                       | Structured Type | ABNF |
|----------------------------------|-----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------
| Accept                           | List            | `#( ( "*/*" / ( type "/" "*" ) / ( token "/" token ) ) parameters [ weight ] )` |
| Accept-Encoding                  | List            | `#( token / "identity" / "*" [ weight ] )` |
| Accept-Language                  | List            | `#( (1*8ALPHA *("-" 1*8alphanum)) / "*" [ weight ] )` |
| Accept-Patch                     | List            | `1#( token "/" token *( ";" parameter ) )` |
| Accept-Post                      | List            | `#( ( "*/*" / ( type "/" "*" ) / ( token "/" token ) ) parameters` |
| Accept-Ranges                    | List            | `1#token` |
| Access-Control-Allow-Credentials | Item            | `"true"` | 
| Access-Control-Allow-Headers     | List            | `#token` |
| Access-Control-Allow-Methods     | List            | `#token` |
| Access-Control-Allow-Origin      | Item            | `origin-or-null / "*"` |
| Access-Control-Expose-Headers    | List            | `#token` |
| Access-Control-Max-Age           | Item            | `1*DIGIT` |
| Access-Control-Request-Headers   | List            | `1#token` |
| Access-Control-Request-Method    | Item            | `token` |
| Age                              | Item            | `1*DIGIT` |
| Allow                            | List            | `#token` |
| ALPN                             | List            | `1#token` |
| Alt-Svc                          | Dictionary      | `%s"clear" / 1#( token "=" quoted-string *( OWS ";" OWS parameter ) )` |
| Alt-Used                         | Item            | `uri-host [ ":" port ]` |
| Cache-Control                    | Dictionary      | `#( token [ "=" ( token / quoted-string ) ] )` |
| CDN-Loop                         | List            | `#( ( ( uri-host [ ":" port ] ) / token) *( OWS ";" OWS parameter ) )` |
| Clear-Site-Data                  | List            | `1#( quoted-string )` |
| Connection                       | List            | `#token` |
| Content-Encoding                 | List            | `#token` |
| Content-Language                 | List            | `#( (1*8ALPHA *("-" 1*8alphanum)) / "*" )` |
| Content-Length                   | List            | `1*DIGIT` |
| Content-Type                     | Item            | `token "/" token parameters` |
| Cross-Origin-Resource-Policy     | Item            | `%s"same-origin" / %s"same-site" / %s"cross-origin" ; case-sensitive` |
| Expect                           | Item            | `#( token [ "=" ( token / quoted-string ) parameters ] )` |
| Expect-CT                        | Dictionary      | `1#( token "=" ( token / quoted-string) )` |
| Forwarded                        | Dictionary      | `1#( [ token "=" ( token / quoted-string ) ] *( ";" [ token "=" ( token / quoted-string ) ] ) )` |
| Host                             | Item            | `( "[" ( IPv6address / IPvFuture  ) "]" / dec-octet "." dec-octet "." dec-octet "." dec-octet / *( unreserved / pct-encoded / sub-delims ) ) [ ":" port ]` |
| Keep-Alive                       | Dictionary      | `0# (param-name "=" value)` |
| Max-Forwards                     | Item            | `1*DIGIT` |
| Origin                           | Item            | `"null" / ( scheme "://" host [ ":" port ] *( SP scheme "://" host [ ":" port ] ) )` |
| Pragma                           | Dictionary      | `1# (token [ "=" ( token / quoted-string ) ])` |
| Prefer                           | Dictionary      | `token [ BWS "=" BWS word ] *( OWS ";" [ OWS parameter ] )` |
| Preference-Applied               | Dictionary      | `1# (token [ BWS "=" BWS word ] )` |
| Retry-After                      | Item            | `HTTP-date / delay-seconds` |
| Sec-WebSocket-Extensions         | List            | `#(token *( ";" param ))` |
| Sec-WebSocket-Protocol           | List            | `1#token` |
| Sec-WebSocket-Version            | Item            | `DIGIT \ (NZDIGIT DIGIT) \ ("1" DIGIT DIGIT) \ ("2" DIGIT DIGIT)` |
| Server-Timing                    | List            | `#( token *( OWS ";" OWS token OWS "=" OWS ( token / quoted-string ) ) )` |
| Surrogate-Control                | Dictionary      | `#( token [ "=" ( token / quoted-string ) ] )` |
| TE                               | List            | `#( token *( OWS ";" OWS parameter ) )` |
| Timing-Allow-Origin              | List            | `1#( origin-or-null / "*" )` |
| Trailer                          | List            | `#token` |
| Transfer-Encoding                | List            | `#( token *( OWS ";" OWS transfer-parameter ) )` |
| Vary                             | List            | `#( "*" / token )` |
| X-Content-Type-Options           | Item            | `"nosniff"` |
| X-Frame-Options                  | Item            | `"DENY" / "SAMEORIGIN"` |
| X-XSS-Protection                 | List            | |

**Comment by mnot** [comment]
OK, I've been over the ABNF for the current headers and noted the issues I've found in caveats. I think this can be closed now.
