### ISSUE TITLE
Section 4.3.1

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2006]
[Section 4.3.1](https://www.rfc-editor.org/authors/rfc9218.html#section-4.3.1):  It appears that one or more words are missing from this entry.  If the suggested text is not correct, please clarify what "key" refers to.

Original:

     Name:  [a name for the Priority Parameter that matches key]

Suggested:

     Name:  [a name for the priority parameter that matches a key value]

**Comment by LPardue** [comment]
The intent here is that the "name" of a parameter matches it's "Structured Fields key". E.g. 'u' is the parameter name on on the wire the key is also 'u'. 

The suggested change to "matches a key value" seems like it could be confusing. Alternatively we could say "matches the key". @kazuho or anyone have other thoughts?
