### ISSUE TITLE
*AD Section 5

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2007]
*AD [Section 5](https://www.rfc-editor.org/authors/rfc9218.html#section-5): FYI, a normative reference to RFC 5234 has been added because this document contains ABNF. See the IESG statement on "Guidelines for the Use of Formal Languages in IETF Specifications" (https://ietf.org/blog/guidelines-use-formal-languages-ietf-specifications/) - specifically "The use of a language requires a reference to the specification for that language. This reference is normative, and needs to fulfil the usual requirements for normative references ([Section 7](https://www.rfc-editor.org/authors/rfc9218.html#section-7) of RFC 2026)." Please review where RFC 5234 is cited and let us know if you prefer otherwise.

Original:

       Priority is a Dictionary (Section 3.2 of [STRUCTURED-FIELDS]): 

   Priority = sf-dictionary

Current:
   Priority is a Dictionary (Section 3.2 of [STRUCTURED-FIELDS]).
   The following is its ABNF [RFC5234]:

   Priority = sf-dictionary

**Comment by LPardue** [comment]
I think we can just remove the ABNF entirely as part of https://github.com/httpwg/http-extensions/issues/1975, which would remove the need to ref rfc 5234

**Comment by LPardue** [comment]
Fixed now
