### ISSUE TITLE
SameSite: Clarify user-triggered navigation behavior.

### ISSUE THREAD

**Issue by mikewest** [httpwg/http-extensions#201]
If a user opens a new tab, and types in a URL, we ought to consider that same-site, as per step 1 of https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-2.1. That definition is pretty opaque, however; adding a note in to clarify would be helpful.

**Comment by martinthomson** [comment]
Not sure if this is needs to be a design issue. @mikewest, feel free to switch to editorial if you are sure that you won't change anything substantial.

**Comment by mikewest** [comment]
Will be addressed in the upcoming -02.
