### ISSUE TITLE
Section 16 IANA Considerations

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2017]
[Section 16](https://www.rfc-editor.org/authors/rfc9218.html#section-16) IANA Considerations: We've made the following updates to match the IANA registry information. Please review and let us know of any concerns.

  o We have reordered some of the information to match the column order of the IANA registries. 

  o We have changed "Specification" to "Reference" to match column labels of the IANA registries. 

  o Because the IANA registries now reference [HTTP/2], we have changed "established by [RFC7540]" to "defined in [HTTP/2]".

**Comment by LPardue** [comment]
These all look good to me.

**Comment by LPardue** [comment]
Applied elsewhere, so closing.
