### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2018]
Acknowledgements:  Would you like to rephrase this sentence so that you, as the authors of this document, are listed in general terms, rather than listing your names?

Original:

     In addition to the people above, this document owes a lot to the
     extensive discussion in the HTTP priority design team, consisting of
     Alan Frindell, Andrew Galloni, Craig Taylor, Ian Swett, Kazuho Oku,
     Lucas Pardue, Matthew Cox, Mike Bishop, Roberto Peon, Robin Marx, Roy
     Fielding.

Possibly:

     In addition to the people above, this document owes a lot to the
     extensive discussion in the HTTP priority design team, consisting of
     Alan Frindell, Andrew Galloni, Craig Taylor, Ian Swett, Matthew Cox,
     Mike Bishop, Roberto Peon, Robin Marx, Roy Fielding, and the authors
     of this document.

**Comment by LPardue** [comment]
Solid improvement.

**Comment by LPardue** [comment]
applied
