### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2020]
Terminology: 

a) The following terms were used inconsistently in this document.  We chose to use the latter forms.  Please let us know any objections.

 Priority Parameter (1 instance in text) /
   priority parameter (33 instances in text)

 push ID (1 instance in text) /
   Push ID (3 instances in text) (per the rest of this cluster of
     documents)

 stream ID (3 instances in text) / Stream ID (5 instances in text)
   (also per more common usage in the rest of this cluster of
   documents)

 the priority field value ([Section 6](https://www.rfc-editor.org/authors/rfc9218.html#section-6)) /
   the Priority Field Value ([Section 7](https://www.rfc-editor.org/authors/rfc9218.html#section-7)) 

 true (1 instance in text) /
   <tt>true</tt> (4 instances in text)

 false (2 instances) /
  <tt>false</tt> (0 instances, but updated to match <tt>true</tt>)

b) The following terms are used inconsistently. Please let us know how we may update these. We would prefer that the RFC number not be used as an adjective, but we can see how it is descriptive in this case. Perhaps we could define a shorter term to use throughout the document in [Section 2](https://www.rfc-editor.org/authors/rfc9218.html#section-2)?

    RFC 7540 stream priority (5 instances)
    RFC 7540 priorities (4 instances)
    RFC 7540 priority (1 instance)

**Comment by LPardue** [comment]
These were all good suggestions. For b) we went with RFC 7540 stream priorit{y|ies}. Changes rolled into the working auth48 branch. Closing this.
