### ISSUE TITLE
enhance title of RFC6265 to include "cookies" term

### ISSUE THREAD

**Issue by equalsJeffH** [httpwg/http-extensions#204]
a suggestion for 6265bis' title such that the term "cookies" is included...

```
Cookies: HTTP State Management Mechanism
```

**Comment by mnot** [comment]
Discussed in berlin: +1

**Comment by martinthomson** [comment]
HTTP State Management Mechanism: The Sequel

**Comment by mnot** [comment]
Marking this as editorial (much as we love a WG bike painting session).

**Comment by mikewest** [comment]
Will be fixed in the upcoming -02.
