### ISSUE TITLE
hop-by-hop / end-to-end -> hop by hop / end to end

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2045]
During AUTH48, the RFC editor suggested several places where the hyphenated term is replaced by the uhyphenated one. This is more grammatically correct but seems to grate with our traditional use of these terms in HTTP. 

We've been slowly moving away from those terms anyway but since the WG chose to ship this draft that uses them, I wondered if anyone had any strong opinions on the matter. diff here https://www.rfc-editor.org/authors/rfc9218-diff.html

* end to end: count 3
* hop by hop: count 1

**Comment by mnot** [comment]
We're using "hop-by-hop" in core. Perhaps we should add this to the style guide.

**Comment by LPardue** [comment]
So better to reject the change and instead propose we import that terms from [HTTP]?

**Comment by mnot** [comment]
Sure. Not sure what import means here...

**Comment by LPardue** [comment]
E.g. in notatioanal conventions saying something like

> The terms "hop-by-hop" and "end-to-end" are imported from [HTTP]

**Comment by mnot** [comment]
I don't think that's necessary, unless you also do it for terms like 'client', 'server', 'intermediary', 'message', etc.

**Comment by LPardue** [comment]
Fair point. In that case I'll just ask the RFC editor to unwind these specific changes.

**Comment by LPardue** [comment]
They are happy to stick with hyphens, closing this issue. Thanks for the input!
