### ISSUE TITLE
Fixing broken link on the wiki

### ISSUE THREAD

**Issue by nfrankel** [httpwg/http-extensions#2068]
Hello,

I've fixed a broken link on the [Wiki](https://github.com/httpwg/wiki/compare/main...nfrankel:master?expand=1)

Since GitHub's wiki doesn't allow for PR and I cannot open issues on the wiki, feel free to look at the proposal.

>Fix broken link
>  The new link points to the IETF Datatracker of the specification.
>  This way, the link will never break, whatever the version or the status change.

**Comment by mnot** [comment]
Done, thanks!
