### ISSUE TITLE
Warning from clear-for-DTD

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#208]
I get this warning.

```
Warning: at xsl:transform on line 42 column 2 of clean-for-DTD.xslt:
  Running an XSLT 1.0 stylesheet with an XSLT 2.0 processor
```

Do we really need to use saxon here, or is `xsltproc` enough now?

**Comment by reschke** [comment]
It's harmless. (Would be good if we could turn it off, though)

**Comment by reschke** [comment]
FWIW, xsltproc should work, but also Saxon apparently just got rid of the warning message.

**Comment by mnot** [comment]
OBE
