### ISSUE TITLE
Cookie value aliasing

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2082]
Should we recognise e.g., binary content in cookie values? If so, how?

**Comment by sbingler** [comment]
Do you mind expanding on what you mean?

**Comment by mnot** [comment]
This is for the retrofit spec's cookie mapping](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#name-cookies). Since many cookie's payloads are base64, it seems like it'd be beneficial to figure out a way to carry them as binary.

I've been meaning to start a discussion with the cookie authors about this section of the spec generally to a) make sure it's a good idea and b) it's correct / doesn't cause problems. PTAL if you have time.

**Comment by mnot** [comment]
Maybe the right thing to do here is to introduce a new parameter that indicates the type of the value.

**Comment by mnot** [comment]
... except parameters aren't available on Cookie; just Set-Cookie. hmm.

**Comment by mnot** [comment]
Perhaps the most we can do is to say that the SF-cookie headers can have a value in any type, but they get mapped to the string value in "normal" headers. That way you can automatically convert SF-cookie to cookie, but not the other way around.

The only alternative I see is to carry the type information in a separate header, which is not great.
