### ISSUE TITLE
Signing non-final response messages

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2086]
While looking at https://github.com/httpwg/http-extensions/pull/2085, I realized there's an implicit assumption of a 1:1 request:response relationship. That's not true at the semanic layer, https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.15.p.7 says 

> A single request can have multiple associated responses: zero or more interim (non-final) responses with status codes in the "informational" ([1xx](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#status.1xx)) range, followed by exactly one final response with a status code in one of the other ranges.

Those non-final response messages can take the form of 103 Early Hints, for example. Which would provide some header fields that might then later appear in the 200 OK carrying message.

I didn't think too hard about what specific problems there might be for signatures. But immediate thoughts are that it would be ok to sign non-final messages and maybe some considerations need to be called out. For example, is there any use case to chain the series of messages that might be produced, to detect if any message was dropped?

**Comment by jricher** [comment]
I don't see any problem with signing non-final responses. As long any given response has a single request associated with it, all of the rules added in #2085 hold fine.

**Comment by LPardue** [comment]
That seems fine. 

I can't think of any concrete use case where signing a chain of responses would be useful, so I'm happy to close this unless someone else can think of one.
