### ISSUE TITLE
Cookie tests should not be using the CookieStore API

### ISSUE THREAD

**Issue by mozfreddyb** [httpwg/http-extensions#2089]
Hi folks working on 6265bis, 

We've been ramping up various work on getting Firefox closer towards the latest 6265bis draft.
When reviewing the pull request https://github.com/httpwg/http-extensions/pull/1732, I noticed that the wpt tests developed alongside are using the CookieStore API that is only supported by Chromium browsers.

Considering previous and ongoing work to improve Cookie APIs in the test infra (https://github.com/web-platform-tests/rfcs/pull/74, https://github.com/web-platform-tests/rfcs/pull/108), may I suggest that we refrain from using the CookieStore API in for new changes and their tests?

**Comment by miketaylr** [comment]
heya @mozfreddyb - can you link to the tests in question? I agree we shouldn't use that API to test cookies, but it would be helpful if you can point to the tests (or file a bug on WPT or Chromium and tag me).

**Comment by mozfreddyb** [comment]
Scrolling down from the pull request #1732, you'll see a [commit to the CookieStore API tests](https://github.com/web-platform-tests/wpt/commit/54edb92b1da34b8db9d4363dba00a883d584012d).

I was under the  impression that those were meant to be the accompanying commits to wpt for that cookie spec change. Revisiting the commits, I now understand that this is not the case. That commit merely changes the default expiry behavior for the existing CookieStore API tests. In fact, there are no accompanying commits to wpt for #1732 at all. My apologies.

**Comment by miketaylr** [comment]
All good, seems like we can close here.
