### ISSUE TITLE
Expand on motivation for the encoding

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#213]
Explain why you probably shouldn't just use UTF-8.

**Comment by reschke** [comment]
...for new header fields?

**Comment by mnot** [comment]
Marking this as editorial, as I think it just means we need to point to 7230's restriction on header field values.

**Comment by reschke** [comment]
We already say:

"By default, header field values in HTTP messages ([RFC7230]) cannot directly carry characters outside the US-ASCII coded character set ([RFC0020])."

...which hints at the fact that RFC 7230 puts non-ASCII octets into the "obs-text" production. I'll try to expand a bit on this.

**Comment by reschke** [comment]
I believe this can be closed with the changes in https://github.com/httpwg/http-extensions/commit/5ec7eed4fa2c941a34e868117ef2fb634d8d506e
