### ISSUE TITLE
Formatting of italicized items in plain text version

### ISSUE THREAD

**Issue by yaronf** [httpwg/http-extensions#2135]
In sec. 2.2.9 there are some spurious underscores around component names.

cc: @jricher

**Comment by jricher** [comment]
I don't see any: https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-10.html#section-2.2.9

**Comment by yaronf** [comment]
“baz”, “qux” and “param” are italicized in the HTML version, and surrounded by “_” in the text version.

 

From: Justin Richer ***@***.***>
Reply-To: httpwg/http-extensions ***@***.***>
Date: Friday, May 27, 2022 at 16:30
To: httpwg/http-extensions ***@***.***>
Cc: Yaron Sheffer ***@***.***>, Author ***@***.***>
Subject: Re: [httpwg/http-extensions] Signatures: typos (Issue #2135)

 

I don't see any: https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-10.html#section-2.2.9

**Comment by jricher** [comment]
The underscores are what make it italicized in the HTML version, there must be a bug in the xml2rfc processing chain from markdown forward.

**Comment by martinthomson** [comment]
In [text](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-10.txt) (page 24):

```
   _baz:_ batman

   _qux:_ an empty string

   _param:_ value
```

**Comment by jricher** [comment]
The underscores are not in the source:

``` markdown
*baz:* `batman`

*qux:* an empty string

*param:* `value`
```

https://github.com/httpwg/http-extensions/blame/main/draft-ietf-httpbis-message-signatures.md#L755-L763

So I'm really not sure what we need to do to fix the text renderer, apart from just not using italics anymore.

**Comment by reschke** [comment]
...or alternatively, just ignore the plain text version. Changing the plain text rendering of xml2rfc at this point will be hard.

**Comment by martinthomson** [comment]
You might at least try "*baz*:" so that the decorations surround the name and not the colon.
