### ISSUE TITLE
message-signatures: broken deep links

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2137]
WARNING: apparently dangling reference to 5.7.2 of HTTP1
WARNING: apparently dangling reference to 5.7.1 of HTTP1
WARNING: apparently dangling reference to 5.7.1 of HTTP1
WARNING: apparently dangling reference to 5.7.1 of HTTP1
WARNING: apparently dangling reference to 5.5 of HTTP1
WARNING: apparently dangling reference to 5.5 of HTTP1
WARNING: apparently dangling reference to 5.5 of HTTP1
WARNING: apparently dangling reference to 5.5 of HTTP1

**Comment by jricher** [comment]
This was cruft from a previous document revision. These were all supposed to point to HTTP not HTTP1 anyway!
