### ISSUE TITLE
Signature algorithms that contain steps with multiple levels of bullets

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2141]
For example, https://httpwg.org/http-extensions/draft-ietf-httpbis-message-signatures.html#section-2.4 contains algorithms with several steps and substeps

```
1.
2.
  1.
  2.
  3.
  4.
  5.
3.
  1.
  2.
  3.
  4.
4.
```

If we were to try to refer to a specific step in the algorithm, is the intent that we could say `2.2` or `3.4`? If so, maybe the document could just explicityl list these steps e.g

```
1.
2.
  2.1
  2.2
...
```

**Comment by jricher** [comment]
The numbers are added automatically by the markdown conversion, I don't think it's possible to make markdown number those lists differently.

Additionally, I don't see there's a lot of utility to referring to sub-steps like that. Is there a particular one you're looking to reference elsewhere?

**Comment by LPardue** [comment]
Nothing in particular. And looking at structured fields, it does it similar to here, so let's just close this. Thanks!

https://datatracker.ietf.org/doc/html/rfc8941

**Comment by reschke** [comment]
FWIW, xml2rfc can do it, so only a minor tweak in kramdown might be needed.
