### ISSUE TITLE
If-Match and If-Range

### ISSUE THREAD

**Issue by gibson042** [httpwg/http-extensions#2149]
The [ETags section](https://www.ietf.org/archive/id/draft-ietf-httpbis-retrofit-04.html#name-etags) references a mapping for [If-None-Match](https://www.rfc-editor.org/rfc/rfc9110.html#name-if-none-match), but [If-Match](https://www.rfc-editor.org/rfc/rfc9110.html#name-if-match) is absent despite having the same `"*" / #entity-tag` value syntax.

**Comment by gibson042** [comment]
Also absent is [If-Range](https://www.rfc-editor.org/rfc/rfc9110.html#name-if-range) (`entity-tag / HTTP-date`).

**Comment by mnot** [comment]
If-Range would require a new mapped field, and it isn't commonly-used enough to merit defining one in _this_ document (see #1987 for the full list). Of course, a future effort could tackle it.
