### ISSUE TITLE
security considerations regarding tracking

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-extensions#215]
I think the security considerations in draft 01 are not adequate. Client hints are presumably sent on all requests, not just within contexts that currently allow execution of javascript via UA or site-specific policies. Hence, a site that does not allow javascript within certain frames (e.g., third party ads) will have no ability to similarly constrain the sending of client hints.

In short, the section should seriously discuss the privacy concerns rather than make a rather flippant comparison to existing problems with javascript fingerprinting. Assume, for example, that the user has already configured their browser to prevent fingerprinting via other means and teach what ought to be done for CH to do the same.

**Comment by igrigorik** [comment]
Good points on JS.. However, note that you can still obtain the same data (DPR, viewport width, ...) via CSS as well (e.g. combination of media queries that trigger different requests) and that cannot be disabled by any policy. As such, I think the current spec language is correct (and not meant to be flippant :)) but we should mention CSS in that first paragraph...

Does that sound reasonable?

**Comment by royfielding** [comment]
Sorry, I missed that response. A third-party inserting CSS media queries within an HTML page to fingerprint a specific user is a lot more difficult (and public) than simply recording the numbers received in an HTTP request header field. In any case, "no worse than other peoples' problems" is not something we put in HTTP specs, because these specs usually outlive other problems.

The section should say that sending the CH header field can increase the passive fingerprint of a browser request if the field values are not limited to values common across a range of users. For example, sending the exact viewport-width and downlink bandwidth can easily identify a specific user across multiple unrelated sites, whereas sending DPR is less likely to identify a specific user because such ratios tend to be common to many users. Restricting field values to an enumerated range, where the user agent picks an enumerated value that is close enough to its current state, might lessen the risk of fingerprinting. Likewise, a user agent might reduce such risk by only sending the field on same-site subrequests, in requests for which identifying information is already being sent in the form of authentication or persistent cookies, or in requests to sites that have been previously whitelisted.

I think that would be sufficient. We just need to explain the risk.

**Comment by mnot** [comment]
I tend to agree with Roy -- this is the difference between "active" and "passive" fingerprinting. See: https://w3c.github.io/fingerprinting-guidance/

**Comment by igrigorik** [comment]
@royfielding @mnot thanks, great feedback. Took a run at incorporating what you've outlined: https://github.com/httpwg/http-extensions/commit/2ba199856ae926284fe868de7c257009f01fe3b8 - how does that look?

**Comment by mnot** [comment]
LGTM, modulo that em dash :)

Let's publish a new draft and get wider review.

**Comment by igrigorik** [comment]
Landed https://github.com/httpwg/http-extensions/commit/bf9d6e7943991e45e792769b5e710aa475fb9632. 02 draft is live @ https://tools.ietf.org/html/draft-ietf-httpbis-client-hints-02
