### ISSUE TITLE
Updating/deleting a cookie with different SameSite value

### ISSUE THREAD

**Issue by kvibber** [httpwg/http-extensions#2152]
https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html

I've been reading over steps 17, 18 and 22 of the storage spec to try and figure out whether it actually says the SameSite value must be matched when setting a matching cookie. 

If I'm reading it correctly, it should be possible to update a cookie that has `SameSite=none;Secure` with a new cookie that has neither as long as the cookie came from a matching context.

But that doesn't seem to be the case: There are a lot of posts online about having to use the same attributes even when you delete a SameSite=none cookie. (Firefox seems to be merging the attributes as far as I can tell, taking SameSite=none from the previous cookie and applying the must-be-secure rule to the new one, but is currently just throwing a warning in the console log.)

If the intent is to require updates and deletions to match the attributes, I can't find it in the spec, and if the intent is to leave it up to the user-agent, I don't see that either.

**Comment by miketaylr** [comment]
> I just tried my example in Chrome 102 and it's working as I detailed. If you find a browser or situation that seems to be wrong I encourage you to file a bug.

It sounds like we can close here then. Thanks for filing an issue.
