### ISSUE TITLE
Module workers can be fetched across origins

### ISSUE THREAD

**Issue by annevk** [httpwg/http-extensions#220]
https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site needs to account for that somehow.

**Comment by annevk** [comment]
Note that we're reconsidering this in https://github.com/whatwg/html/issues/3109.

**Comment by mikewest** [comment]
Module workers can no longer be loaded cross-origin, as of https://github.com/whatwg/html/pull/3656/files.

According to https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-single-module-script, it looks like this is still the case, so we can safely close this out.
