### ISSUE TITLE
Add "ECDSA using curve P-384 DSS and SHA-384" algorithm 

### ISSUE THREAD

**Issue by richanna** [httpwg/http-extensions#2224]
Define a signature algorithm named `ecdsa-p384-sha384` that indicates the use of ECDSA using curve P-384 DSS and SHA-384. The algorithm description is probably just 3.3.4 with "256" replaced with "384", but should validate that assumption with actual crypto folks.

**Comment by jricher** [comment]
What's the push for this specific curve to be included here?

**Comment by richanna** [comment]
I agree with not defining every possible algorithm; however we should include those with known use cases, and AWS intends to use -384. Since the spec isn't finalized and the addition is trivial, it seems reasonable to add it here rather than punting it to an extension spec.
