### ISSUE TITLE
Date definition in retrofit

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#2225]
Is it better to have a separate document defining sf-date rather than have it hide in this one?

**Comment by reschke** [comment]
Absolutely, this should be separate.

(or just revise SF....)

**Comment by mnot** [comment]
There aren't currently any errrata on 8941, so I'd be inclined to do it as a separate doc, I think. Anyone else have an opinion?

**Comment by mnot** [comment]
(if we did replace 8941, the only thing that comes to mind is that we could remove the ABNF, since we've since decided it's distracting / problematic)

**Comment by reschke** [comment]
If we want all parsers to support this, we better should have all parts in a single place. (IMHO)

**Comment by mnot** [comment]
Discussed in interim meeting; sense of the room was to revise SF
