### ISSUE TITLE
httpbis-cookie-alone breaks backwards compat

### ISSUE THREAD

**Issue by dvdckl** [httpwg/http-extensions#223]
In [section 3](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-alone-00#section-3), after the line "Before step 11, execute the following step", the new step intentionally ignores the path.  A note says that "The intent is to allow the 'secure' flag to supercede the 'path' restrictions to protect sites against cookie fixing attacks."  However this change breaks backwards compatibility in the following common scenario:

1. https://example.com/login/ sets a Secure cookie named SESSIONID with the path /login/.
2. http://example.com/foo/ sets a non-secure cookie named SESSIONID with the path /foo/, which will be ignored.

This is the cause of https://bugs.chromium.org/p/chromium/issues/detail?id=580770.  If the draft is adopted as currently written, it will effectively force any website that hosts secure and insecure applications under the same host name to rename cookies in each application to avoid conflicts.  To date, using path provided sufficient scoping to avoid cross-application conflicts.

Even if the second cookie was allowed to be set in the scenario above, it would not have resulted in a fixation vulnerability because one path was not a path-match of the other.  It might be possible to fine-tune the algorithm to only block non-secure cookies if and only if a secure cookie already exists that is a [path-match](https://tools.ietf.org/html/rfc6265#section-5.1.4) of the insecure cookie.  However, that assumes that the cookie order algorithm in https://tools.ietf.org/html/rfc6265#section-5.4 is changed from SHOULD to MUST, and that servers only trust the first cookie.  It also wouldn't help improve backwards compatibility in this scenario:

1. https://example.com/ sets a Secure cookie named SESSIONID with the path /.
2. http://example.com/foo/ sets a non-secure cookie named SESSIONID with the path /foo/, which will be ignored.

Both the draft as written, and the path-match variant proposed above suffer from fixation attacks when an HTTP resource is visited first.  There are other ways that these types of attacks can be mitigated without breaking backwards compatibility, and cover more attack scenarios, at the expense of being opt-in by the server.  These might include the __Secure- prefix (assuming no one is using this in the wild), or introducing a new cookie header, like Cookie-Attributes, that servers could inspect to determine whether or not to trust a cookie.

**Comment by mikewest** [comment]
> However this change breaks backwards compatibility in the following common scenario

Thank you for spelling this out, it's helpful!

>  It might be possible to fine-tune the algorithm to only block non-secure cookies if and only if a secure cookie already exists that is a path-match of the insecure cookie.

This seems like a reasonable compromise. It would prevent a session fixation attack via a maliciously injected cookie on `us.battle.net` with a path of `/login/en/`, for instance, which seems like a valuable thing to maintain.

For clarity, I think we're talking about changing the text in [section 3](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-alone-00#section-3) to something like:

>    2.  Before step 11, execute the following step:
>
>       1.  If the newly created cookie's "secure-only-flag" is not set,
>           and the "scheme" component of the "request-uri" does not
>           denote a "secure" protocol, then abort these steps and ignore
>           the newly created cookie entirely if the cookie store
>           contains one or more cookies that meet all of the following
>           criteria:
>
>           1.  Their "name" matches the "name" of the newly created
>               cookie.
>           2.  Their "secure-only-flag" is set.
>           3.  Their "domain" domain-matches the "domain" of the newly
>               created cookie, or vice-versa.
>           4.  The "path" of the newly created cookie path-matches the "path"
>               of the existing cookie.

Changing 4 to include "or vice-versa" might also be reasonable; it would allow the initial example of two distinct cookies in two distinct root-level paths, but would disallow cookies with the same name but different `secure` settings inside a path (e.g. `/`, `/login/`, and `/login/en/`). That is, I think it is desirable to break backwards compatibility with the final example you provide.

> Both the draft as written, and the path-match variant proposed above suffer from fixation attacks when an HTTP resource is visited first.

Indeed. I think that's noted explicitly in [Section 4](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-alone-00#section-4), along with the prefix-based mitigation.

> introducing a new cookie header, like Cookie-Attributes, that servers could inspect to determine whether or not to trust a cookie.

Folks in the working group seemed generally opposed to adding new headers. This was explicit in the discussion of [Origin Cookies](https://tools.ietf.org/html/draft-west-origin-cookies-01), and implicit in the general tone of discussion around cookie changes in general. @mnot might have a different opinion as chair of the group, but my feeling is that anything more complicated that the current proposal is unlikely to garner much support.

**Comment by mnot** [comment]
I'd agree there seems to be a reluctance to make big changes like that, but we can always ask. 

Thinking out loud -- AIUI one of the objections was the bandwidth overhead; perhaps this could be reduced by doing something like:

    Cookie-A: s;h;;sh

where each member corresponds to a cookie in the lexical order of the `Cookie` header, and the letters are for `secure`, `httpOnly`, etc.

(Adding @mcmanus as co-chair for his thoughts)

**Comment by dvdckl** [comment]
@mnot yeah, the order matching was what I had in mind.  I have mixed feelings on abbreviation though.  Part of P3P's challenges were due to it being cryptic.  Other specs like CSP are not abbreviating too much.  But DNT/TSV are.  Would it be better to assume widespread HTTP/2 adoption and count on header compression?

**Comment by mnot** [comment]
The problem with relying upon header compression is that the dynamic table has a default of 4K, and it can quickly get filled with cookies, UAs, referers, etc. It's not a license to create big new headers.

**Comment by mcmanus** [comment]
I have heard some anecdotes about pressure on the 4K table - not a lot of data yet but I think people are more comfortable with less human readable syntaxes than in the past. Mark's arrangement seems sensible.. but by all means ask the list.

**Comment by mnot** [comment]
SGTM. Who's taking it to the list?

**Comment by dveditz** [comment]
I too, have concerns about the non-exact path matching and the asymmetry of the results depending on the order in which differing-path cookies are set.

A similar concern about symmetry: why should secure sites get a free pass to downgrade a secure cookie to insecure? That's not "leaving secure cookies alone". Such an attempt might actually just be a site bug.

**Comment by mikewest** [comment]
Hi! Sorry, I've been OOO for a little while. Starting at the bottom:

@dveditz 
> why should secure sites get a free pass to downgrade a secure cookie to insecure?

1.  Because they're delivered securely, so we ~know that the `Set-Cookie` header reflects the site's intent, and not the intent of a MitM.

2.  To prevent sites from downgrading `secure` cookies, we'd also have to prevent them from deleting `secure` cookies. That doesn't seem like something we should do, for the same reason that we wouldn't prevent a site from removing data from `localStorage`, et al.

> Such an attempt might actually just be a site bug.

I don't think site bugs are the threat we're concerned about. Sites certainly have bugs, but they can fix them. They can't fix the kinds of issues outlined in "Cookies Lack Integrity" and elsewhere. That's what I'm interested in addressing.

@mnot, @dvdckl 
> `Cookie-A: s;h;;sh`

Something like this syntax seems fine (though, does `s` map to `Secure` or `SameSite`? :) ).

I guess this kind of header seems reasonable to me. My concern is that it's (yet another) opt-in mechanism that developers need to know about in order to keep themselves safe (and, really, needs to be built into various frameworks to be useful at all). I think I'd be interested in exploring it in addition to the restrictions on `secure` proposed in the draft we're discussing. I don't think it's a suitable replacement.

> Who's taking it to the list?

Skimming the list, it doesn't look like anyone raised the notion in my absence. @dvdckl, would you be interested in sending a brief proposal for discussion, or shall I write something up?

**Comment by mikewest** [comment]
@dvdckl: The patch in https://github.com/httpwg/http-extensions/commit/3f58813b120dbedcf78d0df899b5a74e095fd068 aims to address the central objection you raised above. Are you happy with that change, or do you think it needs more work?

**Comment by dvdckl** [comment]
@mikewest the patch addresses most of my concern, but it's still going to cause problems on sites that have HTTP webapps on a path that's a descendant of an HTTPS webapp (I'm not aware of this case in our ecosystem, but I'm assuming that it exists in the wild).  Copying the second example in my first comment:

1. https://example.com/ sets a Secure cookie named SESSIONID with the path /.
2. http://example.com/foo/ sets a non-secure cookie named SESSIONID with the path /foo/, which will be ignored.

Yes the RFC would plug the cookie fixation hole quickly, but it effectively forces servers that write cookies to the current path to do one of two things: 1) never serve HTTP content on a path that is a descendant of an HTTPS resource, or 2) coordinate cookie naming conventions between potentially unrelated resources (and maybe unrelated development teams).  If I had to deal with that scenario, I'd probably just focus more on HSTS instead to avoid those cookie related headaches.

Mike, you [said yourself ](https://discourse.wicg.io/t/proposal-set-origin-wide-policies-via-a-manifest/1617/4) that you feel like path-level distinctions in cookies was a historical mistake, so wouldn't opt-in mechanisms (HSTS, Cookie-Attributes, [Suborigins](https://w3c.github.io/webappsec-suborigins/), etc) be better long-term than allowing the cookie path-match algorithm to further dictate how servers organize content?

I'll send the Cookie-Attribute header proposal to the mailing list (ietf-http-wg at w3.org, right?)

**Comment by mikewest** [comment]
> If I had to deal with that scenario, I'd probably just focus more on HSTS instead to avoid those cookie related headaches.

Doesn't that seem like a good outcome?

> Mike, you said yourself that you feel like path-level distinctions in cookies was a historical mistake,

The fact that I consider path-level distinctions for cookies to be a mistake (and I do) doesn't mean that I can pretend they don't exist. I'm doing my best to work within the constraints they create to incrementally raise the platform's baseline. *shrug*

> so wouldn't opt-in mechanisms (HSTS, Cookie-Attributes, Suborigins, etc) be better long-term than allowing the cookie path-match algorithm to further dictate how servers organize content?

Yes. When we can create opt-in mechanisms that allow sites to lock themselves down further than we can lock down the platform at large, we should.

However, relying strictly upon those mechanisms is unlikely to produce actual change in the ecosystem. For instance, despite fairly broad outreach and understanding, something like ~4% of the cookies Chrome users set in the last month have the `Secure` attribute. ~7% have `HttpOnly`. I think it's pretty clear that, in an ideal world, those numbers would be an order of magnitude higher.

It seems unlikely than an opt-in approach would buy us much in terms of protection, especially when the opt-in is fairly complicated, as `Cookie-Attributes` would be.

**Comment by mikewest** [comment]
Uploaded the updated document as https://tools.ietf.org/html/draft-ietf-httpbis-cookie-alone-01.

**Comment by dvdckl** [comment]
The data helps provide context, thanks.  Are stats like that and the results of Chrome experiments public somewhere?  Will stats be collected on how many cookies were blocked as a result of this draft RFC?

I'm biased by working in an environment where we're eager to opt in to new security mechanisms and have a strong aversion to breaking backwards compat.  But I understand that the number of sites that would have a backwards compat issue with the latest draft is probably low, and the pain experienced by a few devs is probably worth eliminating an attack vector that affects everyone that hasn't adopted HSTS yet.

Thanks for acknowledging all of my feedback.

**Comment by mikewest** [comment]
> The data helps provide context, thanks. Are stats like that and the results of Chrome experiments public somewhere?

Metrics we collect in Blink are publicized at https://www.chromestatus.com/metrics/feature/popularity. We unfortunately don't have a similar pipeline for metrics we collect from the network stack. I wish we did. :(

> Will stats be collected on how many cookies were blocked as a result of this draft RFC?

Yes. Currently, that's trending at ~0.05% of cookies over the last month, which is a lot of cookies. We're keeping an eye on it, and that's the main reason that the rollout has been so slow.

> I'm biased by working in an environment where we're eager to opt in to new security mechanisms and have a strong aversion to breaking backwards compat.

1. I love hearing that! I would like you to be my guinea pig for everything!
2. Most developers don't care until something happens that makes them wish they had cared. :(

> Thanks for acknowledging all of my feedback.

Thanks for feeding back!

**Comment by mikewest** [comment]
With the -01 draft published, and Chrome updated (in https://github.com/dstockwell/chromium/commit/2c857fb16cdef9783ba3caeb586b9a3648114b17), I think it's reasonable to close this out. We can continue the discussion of the other proposed paths forward (`Cookie-Attributes`, etc) on the list.

Thanks again for your feedback, @dvdckl!
