### ISSUE TITLE
Algorithms for retrofit compatibility fixes

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#2235]
We have the following text,

for [parameters and dictionary keys](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.2.1):

> compatibility can be improved by force-lowercasing them when parsing

for [parameter delimiters](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.4.1):

> Compatibility can be improved by allowing such whitespace when parsing

and for [strings](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.6.1):

> Compatibility can be improved by unescaping other characters before parsing

It would be very helpful if this could be expressed as an algorithm, or as modifications to the existing SF algorithms.  I say this because while you might be able to make the change for strings across an entire field value, I don't think that it is generally safe to downcase an entire field value and expect it to work.

That suggests targeted changes to the SF algorithms for compatibility with retrofit fields.  In that case, you probably don't want those compatibility changes affecting how native SF definitions are processed.  Being more precise about the processing rules here might head off problems of overly broad application.

**Comment by mnot** [comment]
If we reopen SF, should we integrate these into the algorithms -- possibly with a flag that indicates their use?

**Comment by reschke** [comment]
Absolutely.

The current text in retrofit encourages "fixes" without parsing, and we know what that leads to.

For these common cases, the options seem to

1. have a relaxed variant of the parsing algorithm, or
2. actually relax SF - for instance to allow whitespace in more places, or by making strings compatible with HTTP's quoted-string.

(I have a preference...)

**Comment by mnot** [comment]
Triaging the [current caveats](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-5):

> Parameter and Dictionary keys
> HTTP parameter names are case-insensitive (per [Section 5.6.6](https://rfc-editor.org/rfc/rfc9110#section-5.6.6) of [[HTTP](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#HTTP)]), but Structured Fields require them to be all-lowercase. Although the vast majority of parameters seen in typical traffic are all-lowercase, compatibility can be improved by force-lowercasing parameters when parsing. Likewise, many Dictionary-based fields (e.g., Cache-Control, Expect-CT, Pragma, Prefer, Preference-Applied, Surrogate-Control) have case-insensitive keys, and compatibility can be improved by force-lowercasing them when parsing.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.2.1)

Pretty straightforward to enable with a flag in SF.

>Parameter delimitation:
> The parameters rule in HTTP (see [Section 5.6.6](https://rfc-editor.org/rfc/rfc9110#section-5.6.6) of [[HTTP](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#HTTP)]) allows whitespace before the ";" delimiter, but Structured Fields does not. Compatibility can be improved by allowing such whitespace when parsing.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.4.1)

Likewise.

> String quoting:
> [Section 5.6.4](https://rfc-editor.org/rfc/rfc9110#section-5.6.4) of [[HTTP](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#HTTP)] allows backslash-escaping most characters in quoted strings, whereas Structured Field Strings only escape "\" and DQUOTE. Compatibility can be improved by unescaping other characters before parsing.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.6.1)

Yes, but this has the risk that if it's used on a field that is expecting "normal" SF, it'll munge the contents.

> Token limitations:
> In Structured Fields, tokens are required to begin with an alphabetic character or "*", whereas HTTP tokens allow a wider range of characters. This prevents use of mapped values that begin with one of these characters. For example, media types, field names, methods, range-units, character and transfer codings that begin with a number or special character other than "*" might be valid HTTP protocol elements, but will not be able to be represented as Structured Field Tokens.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.8.1)

Nothing can be done in SF about this; it's just a warning, really.

> Integer limitations:
> Structured Fields Integers can have at most 15 digits; larger values will not be able to be represented in them.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.10.1)

Likewise.

> IPv6 Literals:
> Fields whose values contain IPv6 literal addresses (such as CDN-Loop, Host, and Origin) are not able to be represented as Structured Fields Tokens, because the brackets used to delimit them are not allowed in Tokens.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.12.1)

Likewise.

> Empty Field Values:
> Empty and whitespace-only field values are considered errors in Structured Fields. For compatible fields, an empty field indicates that the field should be silently ignored.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.14.1)

Seems like this could be addressed a top-level parsing flag that says return null (or an empty structure) if this is the case.

> Alt-Svc:
> Some ALPN tokens (e.g., h3-Q43) do not conform to key's syntax, and therefore cannot be represented as a Token. Since the final version of HTTP/3 uses the h3 token, this shouldn't be a long-term issue, although future tokens may again violate this assumption.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.16.1)

Nothing we can do about this, unless we want to special-case a particular header field. 

> Content-Length:
> Note that Content-Length is defined as a List because it is not uncommon for implementations to mistakenly send multiple values. See [Section 8.6](https://rfc-editor.org/rfc/rfc9110#section-8.6) of [[HTTP](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#HTTP)] for handling requirements.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.18.1)

This is just advisory.

> Retry-After:
> Only the delta-seconds form of Retry-After can be represented; a Retry-After value containing a http-date will need to be converted into delta-seconds to be conveyed as a Structured Field Value.

Again, a single-field exception. The alternative is to turn Retry-After into a mapped field (using integer or date), but that seems like overkill IMO.

**Comment by reschke** [comment]
>> String quoting:
>>    [Section 5.6.4](https://rfc-editor.org/rfc/rfc9110#section-5.6.4) of [[HTTP](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#HTTP)] allows backslash-escaping most characters in quoted strings, whereas Structured Field Strings only escape "" and DQUOTE. Compatibility can be improved by unescaping other characters before parsing.[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#section-2-6.6.1)
>
> Yes, but this has the risk that if it's used on a field that is expecting "normal" SF, it'll munge the contents.

How so? In normal SF, quoting something that doesn't need quoting is a fatal error, no?

**Comment by mnot** [comment]
You're right, that shouldn't be an issue.

**Comment by mnot** [comment]
So, in summary, this involves:

- [ ] case normalising parameter and dictionary keys
- [ ] allowing whitespace before `;` in parameters
- [ ] unescape everything except `\` and `"` in strings
- [ ] returning null or an empty structure when the field is empty (WS only)

**Comment by mnot** [comment]
I'm somewhat unsure about the relative tradeoffs here:

1. Adding these to SF parsing of retrofit fields will _very_ slightly improve success rates (according to the numbers I've seen)
2. Adding them increases algorithm complexity (because a flag needs to be passed around) and
3. Adding them could be misused (e.g., by people who think compatible = better, without the context that they should only be used on retrofit fields).

(3) might be improved by _not_ calling it a compatibility flag (maybe just a `retrofit` flag?).

I do agree that putting them in sfbis is better than patching them from retrofit, but I wonder if we should consider another option -- dropping them altogether, since their benefit is so slight. After all, successful parsing of 'compatible' fields is not guaranteed, even when they are in place.

Thoughts?

**Comment by reschke** [comment]
- if we need to modify algorithms, we should do it where they are defined
- if we are scared about flags, we *might* consider making the "relaxed" mode the only mode - what would be the downside of that?

**Comment by mnot** [comment]
> we might consider making the "relaxed" mode the only mode - what would be the downside of that?

Variance in behaviour between implementations of the two specs -- we can't guarantee that all will upgrade at the same time, so a header that's valid by the later one would be invalid (unparseable) by the earlier. 

In theory as long as they serialise according to the algorithm that won't happen, but in practice it might. 

That's the downside. I don't think that completely precludes that path, but we should discuss the implications and make sure they're widely understood.

**Comment by mnot** [comment]
So it seems like we should:

1. Remove those caveats from Retrofit, since they're not going to end up there (if anywhere)
2. Transfer this issue to sf-bis to consider the impact of including them (either by default or behind a flag).

Even if the answer to (2) is that they don't get incorporated at all, that's OK.

**Comment by mnot** [comment]
Please review commit WRT retrofit; we'll continue discussign WRT sf-bis.

**Comment by mnot** [comment]
I'm still queasy about adding a flag to sf for this; it increases complexity and risks misuse. 

I'm also unsure about adding it as the default behaviour; it _seems_ like it wouldn't cause any real-world issues, especially this early in the lifetime of SF, but it's hard to predict.

So I'm leaning towards closing this with no action, other than the modification to retrofit that's already committed. Thoughts?

**Comment by reschke** [comment]
I don't see how not doing anything resolves the underlying issue. If retrofit needs relaxed parsing rules, we should sit down and figure out how to achieve that.

**Comment by mnot** [comment]
That's exactly the point, Julian -- it doesn't _need_ them.
