### ISSUE TITLE
HTTP Message Signatures - Consider renaming _context_ parameter

### ISSUE THREAD

**Issue by robelcik** [httpwg/http-extensions#2249]
Hello,

https://github.com/httpwg/http-extensions/pull/2222 introduced `context` parameter, "_to allow applications to signal specific usage between the signer and verifier_".

However, word _context_ is already used more than 40 times, mostly meaning the _context of HTTP message_. In my opinion, it adds ambiguity to the used vocabulary.

Please consider renaming the parameter, e.g. to _application_, _app_, _usage_, _use_, _purpose_.

Best regards,
Robert

**Comment by jricher** [comment]
Thanks, I noticed a similar term conflict when we added the functionality -- `context` was the proposed name from the folks that suggested the function so that's what we put in. I'm happy to have something else in there: I think `app` is a good suggestion.
