### ISSUE TITLE
JFV + ECMA-262

### ISSUE THREAD

**Issue by igrigorik** [httpwg/http-extensions#225]
Based on the various discussion at [IETF](https://github.com/httpwg/wg-materials/blob/gh-pages/ietf96/minutes.md#jfv), HTTP Workshop, and [mailing lists](https://www.ietf.org/mail-archive/web/httpbisa/current/msg26788.html), JFV may not be the right long-term "replacement" header encoding format. However, while [sketches are being pushed around](https://lists.w3.org/Archives/Public/ietf-http-wg/2016JulSep/thread.html#msg292), it's not clear if and when such a format will come either… In the meantime, I believe we can shape JFV (with minor modifications) into a format that is immediately useful and addresses many of the current pain points for **new** header fields. Specifically: 
- UA's want a reusable and tested parser. Today we end up hand-rolling parsers for most every field (due to ABNF quirks, past implementation mistakes, etc), which leads to interop problems, security issues, and so on. Also, this is not a Chrome specific problem, all major UA's have the same pain points, and we all need to do better.
- At the same time, all UA's have well-tested JSON parsers. Reusing existing code helps cut down on attack surface area, helps with interop, etc. As such, JFV format is a strong plus.
- JSON parsers are easy to come by on the server side and all the same benefits and motivation is just as applicable.

That said, as others have already pointed out, we do need additional restrictions on JFV beyond what is currently in the spec. Also, it just so happens that browsers already follow the [ECMA-262 spec](http://www.ecma-international.org/ecma-262/6.0/index.html), which addresses most of the  raised concerns:
- Specify how to deal with repeated fields:
  - [InternalizeJSONProperty(holder, 
    name)](http://www.ecma-international.org/ecma-262/6.0/#sec-internalizejsonproperty): 
    _"In the case where there are duplicate name Strings within an object, 
    lexically preceding values for the same key shall be overwritten."_ All 
    browsers already do this.
- Specify number encoding format
  - [4.3.20 Number 
    value](http://www.ecma-international.org/ecma-262/6.0/#sec-terms-and-definitions-number-value): 
    Number value is primitive value corresponding to a double-precision 64-bit 
    binary format IEEE 754-2008 value.
  - [11.8.3 Numeric 
    Literals](http://www.ecma-international.org/ecma-262/6.0/#sec-literals-numeric-literals)
- Specify date encoding format
  - [20.3.1.16 Date Time String 
    Format](http://www.ecma-international.org/ecma-262/6.0/#sec-date-time-string-format), 
    [Date.parse()](http://www.ecma-international.org/ecma-262/6.0/#sec-date.parse)
    - We can require ISO 8601 Extended format.
- Specify character encoding
  - UTF-8 [[RFC3629](https://tools.ietf.org/html/rfc3629)]

Are there other issues that were brought up that are not addressed above? 

My proposal is that we update JFV to spec above ECMA-262 restrictions and requirements. Doing so would enable UA's to adopt JFV with minimal work.

_p.s. in progress specs and browser features that plan on leveraging JFV: [Clear-Site-Data](https://www.w3.org/TR/clear-site-data/), [Feature Policy](http://wicg.github.io/feature-policy/), [Reporting](http://w3c.github.io/reporting/), [Network Error Logging](http://w3c.github.io/network-error-logging/), … and I'm sure we'll see more soon._

/cc @reschke @mnot @mcmanus

**Comment by mnot** [comment]
Hmm. The number issues are around parsing, not generation, AIUI. So, your solution is good for response headers, but not request headers -- because the browsers haven't *yet* taken over the server side implementations.

**Comment by clelland** [comment]
The pointer to 11.8.3 was intended to tackle parsing; 11.8.3.1 defines the parsing algorithm for numeric literals (precisely, down to potentially rounding in the 20th significant digit). The examples where actually significant digits get ignored would indicate a bug in parsing, according to the ES spec.

**Comment by mnot** [comment]
Right. The pushback against doing something like this that I've heard is that no matter what we say in the spec, people are going to just point the JSON parser they have at hand at the header field value, and trust what it gives them. 

As such, using JSON is a bit of an attractive nuisance.

It may be that we can specify a profile of JSON that is safe to use, **and** create a set of easy-to-use libraries and get them into the relevant server-side platforms, but that's a substantial amount of effort (any volunteers?), and the natural lag of many distros/platforms means that they might not be available for some time (leading people to use plain JSON parsers).

The most serious issue is undoubtedly the number format. Perhaps cautioning against minting headers that use non-integer numbers would be a workable stopgap (although the temptation might be quite strong in some use cases).

**Comment by igrigorik** [comment]
Well, the alternatives are: hand-rolled ABNF parsers with buggy substring matches (because that seems to be preferred "optimized" way of doing things); or completely new parses for each platform for some yet-to-be-defined format... *shrug*, pick your poison. 

UA's can enforce the JSON subset ("strict mode") we define here, which will nudge all the other parties in the right direction.

**Comment by mnot** [comment]
I do agree that not inventing something new is pretty attractive. How you feel about disallowing (or just strongly warning) against non-integer numbers in request headers?

**Comment by igrigorik** [comment]
Strongly warning seems reasonable. I'm not aware of any existing efforts that are planning to use non-integer values + JFV, but making that a requirement doesn't feel right either.

**Comment by rousskov** [comment]
A JSON profile, strict modes, wrapper API suggestions, and/or strong warnings simply document attack vectors without solving the underlying problem. If JSON is the answer, then it comes with a "fuzzy numbers" problem that does not have reliable solutions. You can sugar-coat it or hope that it will go away in 20 years, but you cannot solve it.

**Comment by kazuho** [comment]
@igrigorik @mnot 
If we are to going to use a modified variant of JSON, I strongly support disallowing non-integer numbers.

Using ECMA262's definition of number would not help us, neither in terms of the definition or the ease of implementation.

Regarding the definition, my understanding is that ECMA262 merely specifies how the numbers should look like as strings, but does _not_ specify _how_ the strings should be converted to IEEE754 numbers. Lack of a formal definition of such procedure is what leads us to disagreements between the implementation (that in turn becomes a cradle of vulnerabilities).

Regarding the ease of implementation, ECMA262 is a _superset_ of JSON in terms of how numbers can be represented (i.e. binary, octal and hexadecimal representations), which seems unnecessary complex to me.

@mnot 
> It may be that we can specify a profile of JSON that is safe to use, and create a set of easy-to-use libraries and get them into the relevant server-side platforms, but that's a substantial amount of effort (any volunteers?)

It _might_ be possible to filter out JSON containing floating point representations _before_ applying a JSON parser, and in that regard, using [json2.js](https://github.com/douglascrockford/JSON-js) (that uses `eval` to parse JSON after filtering out dangerous strings) as a basis might be worth considering. I anticipate that just modifying the number representation in [this regexp](https://github.com/douglascrockford/JSON-js/blob/master/json2.js#L163) would be sufficient for the matter.

**Comment by igrigorik** [comment]
Parallel thread: https://lists.w3.org/Archives/Public/ietf-http-wg/2016JulSep/thread.html#msg436

@rousskov I appreciate where you're coming from, but (personally, at least) I think that paints an overly black and white prognosis. I think we _could_ make reasonable progress here with a restricted set + browsers enforcement.

@kazuho @mnot I can't shake the feeling that restricting to integer values will come back to bite us, but if you think otherwise.. *shrug*, we can give it a shot.

**Comment by clelland** [comment]
Presumably, we'll also have to restrict the range of integers to `Number.MIN_SAFE_INTEGER <= n <= Number.MAX_SAFE_INTEGER`, to be sure that the value parsed is the same as the number presented in the JSON.

**Comment by rousskov** [comment]
@igrigorik I agree -- _reasonable progress_ is very possible, for some definition of reasonable, especially if your primary focus is "browsers". That reasonable progress will not solve the problem -- fuzzy JSON numbers will cause CVEs. If reasonable progress [with browsers] is good enough, and a few design-triggered CVEs are not important enough, then this JSON problem is not a big deal at all.

**Comment by reschke** [comment]
FWIW, another plausible thing to do would be to require conformance to the I-JSON profile (see https://tools.ietf.org/html/rfc7493).

@igrigorik -- is that something you would consider implementing (essentially adding a stricter mode to the existing JSON parser?)

**Comment by igrigorik** [comment]
> FWIW, another plausible thing to do would be to require conformance to the I-JSON profile (see https://tools.ietf.org/html/rfc7493).

@reschke that's effectively what we proposed above.. ECMA-262 and I-JSON dictate same rules for number encoding?

---

@clelland @esprehn fyi... phk put together a rough draft of his (alternative) proposal: 
- https://lists.w3.org/Archives/Public/ietf-http-wg/2016OctDec/0099.html
- https://datatracker.ietf.org/doc/draft-kamp-httpbis-structure/

**Comment by reschke** [comment]
@igrigorik it's different with respect to duplicate keys...

**Comment by igrigorik** [comment]
@reschke true, but what's the benefit of I-JSON over the existing ECMA-262 behavior in browsers?

**Comment by reschke** [comment]
easier to specify from an IETF spec :-).

At the end of the day, we'll forbid sending duplicate keys anyway, right? The difference is just how the recipient handles those (complain vs last wins)

**Comment by igrigorik** [comment]
> At the end of the day, we'll forbid sending duplicate keys anyway, right? The difference is just how the recipient handles those (complain vs last wins)

Right. I got internal pushback earlier on special-casing this in our JSON parser (to ignore+complain).. last-wins is simple and consistent with the rest of the (browser) platform.

**Comment by esprehn** [comment]
Yeah we don't want to have two versions of the JSON parser. So whatever this spec says should agree with 262.

**Comment by reschke** [comment]
@igrigorik - would something like https://github.com/httpwg/http-extensions/commit/9928ebd187ce272f21f999b26fe656a281defccb work for you?

**Comment by igrigorik** [comment]
@reschke yes, I think that looks reasonable. 

> Furthermore, ordering of object members is not significant and can not be relied upon.

Paging @clelland @esprehn for sanity check..

**Comment by mnot** [comment]
Closing, since the WG has abandoned JFV in favour of PHK's proposal.
