### ISSUE TITLE
All HTTP references are informative?

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#2266]
Currently, the references to HTTP semantics and to all HTTP versions are informative.  While there are only two references to RFC9110, I find myself skeptical that someone would be able to implement it without knowing HTTP.

We might consider making 9110 an normative reference, even if we think the individual pointers into it don't rise to that level.

**Comment by LPardue** [comment]
You could normatively depend on the intermediary definitions in https://www.rfc-editor.org/rfc/rfc9110.html#name-intermediaries

**Comment by b---c** [comment]
Agreed about making HTTP semantics a normative reference.

**Comment by b---c** [comment]
Using and alining with 9110's intermediary definitions is likely worthwhile too. However, that's a larger effort that should maybe be considered separately?

**Comment by LPardue** [comment]
I'm not too bothered about just changing labels between informative or normative. Thats easy to do and can be changed easily enough at later date.

I think this draft actually does a good job of talking about the specialist case of a TTRP and we should keep that without too much meddling.

 But if the prose would benefit from shaking out a stronger sense of if implementations have normative requirements, I thinkcthis is a good ticket to track that against.

**Comment by b---c** [comment]
Thanks for the thoughts, Lucas. I'm inclined to not do much meddling.
