### ISSUE TITLE
which document is it?

### ISSUE THREAD

**Issue by bblfish** [httpwg/http-extensions#2269]
I found this document 

  https://httpwg.org/http-extensions/draft-ietf-httpbis-message-signatures.html
published 10 Oct 2022 and expiring 13 April,
  and this one:
 https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures-13
published 26 Sept 2022 and Expiring March 2023

I think I saw a difference in the public key info published with the 13 April date having the name of the key.

**Comment by mnot** [comment]
The former is the editors draft; the latter is an Internet-Draft (analogous to a Working Draft in the W3C).

e-mail is best for this kind of question...

**Comment by bblfish** [comment]
ok, but which needs to be formally reviewed by the 25th of this month?
