### ISSUE TITLE
Accept-Signature: if it is a header, it must be stated explicitly

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#2277]
## Question

- if Accept-Signature to be a header (see "Processing Accept-Signature") it should be stated explicitly, or the processing section should replace "header" with "field" 

> The receiver of an Accept-Signature field fulfills that header as follows:
^^ replace header with field

- move normative parts  from Requesting signatures to the Accept-Signature Field

## Note

- it cannot be sent in a trailer section
- it must be header field
- it can be used in requests and responses

@jricher if it's ok, I'll PR on this

**Comment by reschke** [comment]
I don't see why it *can't* be in a trailer section. I wouldn't recommend to use that, but then what would be a technical reason to disallow it?

**Comment by ioggstream** [comment]
If it's ok in a trailer section, we should:

1. replace "header" with "field" in "Processing Accept-Signature";
2. explicit that it can be sent in a trailer section;
3. warn that when sending in a trailer section, intermediaries are allowed to strip it.

WDYT?
