### ISSUE TITLE
Introduction discussion on non-standard fields seems a bit long winded

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2281]
Intro para 3 has a chunk of text about fields not defined in this doc

> A common way this information is conveyed in practice today is by using non-standard fields to carry the certificate (in some encoding) or individual parts thereof in the HTTP request that is dispatched to the origin server. This solution works but interoperability between independently developed components can be cumbersome or even impossible depending on the implementation choices respectively made (like what field names are used or are configurable, which parts of the certificate are exposed, or how the certificate is encoded). A well-known predictable approach to this commonly occurring functionality could improve and simplify interoperability between independent implementations.

This could be condensed to say that the header fields in this document provide a standardized replacement for custom or proprietary fields that were known to be used prior to this document.

**Comment by bc-pi** [comment]
It is perhaps a bit long winded and admittedly not award winning literature. But I think it's useful context for the reader and prefer to keep it.

**Comment by LPardue** [comment]
Right but in 20 years if the RFC says "a common practice today is using non-standard fields" it could read odd. 

Its clearer if this spec focuses on what it provides  not what people came up with as custom solutions beforehand.
