### ISSUE TITLE
Signatures 13: Problem with test-key-rsa-pss in Browser JS

### ISSUE THREAD

**Issue by bblfish** [httpwg/http-extensions#2290]
I am having difficulty getting the [test-key-rsa-pss private key](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures-13#appendix-B.1.2) being accepted by the web browsers.

This is a bit of a weird problem that would benefit from help from some JS crypto experts. But it is not a new problem: we had a similar problem a year ago in draft 07, which was the last time I worked on an implementation of the spec. See https://github.com/httpwg/http-extensions/issues/1867 

I am developing a library called bobcats in Scala that compiles both to JS and to Java and runs the same tests.  I have been testing bobcats by developing tests take from the Message Signing spec.

Using the same data, the Java tests pass, but  the JS tests don't  when using the new keys placed  in [object `test-key-rsa-pss` extends TestKeyPair](https://github.com/bblfish/bobcats/blob/26e191d236b27ad6e21ea497238097aa8e947117/core/shared/src/test/scala/bobcats/HttpMessageSignaturesV13.scala#L175).  

When that code is commented out, and instead we use the  `test-key-rsa-pss` from draft 07, as shown in the code above,  then all the tests pass. 

So there is something in the given PEM keys that the JS Web Crypto APIs don't like. I am sure it would help implementations in JS browser land if it was not so difficult to get the PEM key working. There must be some explanation to what the problem is.

Browsers tested are Chrome and Firefox using Selenium. See for example [Chrome log](https://github.com/bblfish/bobcats/actions/runs/3397551264/jobs/5649813316#step:12:65) in PR https://github.com/bblfish/bobcats/pull/7

**Comment by bblfish** [comment]
I tried to just use the private pk8 key  from draft 07 with the new public key in commit https://github.com/bblfish/bobcats/commit/f5c5ef3db37ed42c1fc767e46dcac46cfadd814e but that failed the tests. Going back to fully using the private and public key from draft 07, with commit https://github.com/bblfish/bobcats/pull/7/commits/8f3e75ffee0adf2a7adf2074c9b5821750cb3e65 
and all the tests are passing again https://github.com/bblfish/bobcats/actions/runs/3399167351/jobs/5652745295

**Comment by bblfish** [comment]
In response to my question on the webcrypto repository @panva gave [some very valuable feedback](
https://github.com/w3c/webcrypto/issues/330#issuecomment-1304759709):

> The keys in appendix-B.1.1 are in PKCS1, which isn't accepted by webcrypto at all. Recommend using rsaEncryption OID PKCS8 and SPKI PEM or JWK if they ought to be imported as CryptoKey reliably.

> The private key in appendix-B.1.2 is 1.2.840.113549.1.1.10 (id-RSASSA-PSS). WebCryptoAPI implementations only generally accept 1.2.840.113549.1.1.1 (rsaEncryption) keys. Recommend using rsaEncryption OID PKCS8 PEM or JWK if they ought to be imported as CryptoKey reliably.

> The private key in appendix-B.1.3 is in SEC1 format, which isn't accepted by webcrypto at all. Recommend using id-ecPublicKey OID PKCS8 PEM or JWK if they ought to be imported as CryptoKey reliably.

> The keys in appendix-B.1.4 are fine but currently only Node.js and Deno runtimes implement Ed25519 as per [Secure Curves in the Web Cryptography API](https://wicg.github.io/webcrypto-secure-curves/).

> Hope this helps inform the WG. I would propose to keep the PEM keys as is and add their JWK representation.

**Comment by bblfish** [comment]
I updated the bobcats cryptography library for Scala and ScalaJS to verify 
1. that the keys load 
2. they can sign and verify the keys

[The PR](https://github.com/bblfish/bobcats/pull/7) has not passed all tests. 

But as explained by @panva in the message I quoted above that is not because the keys were in the right format. 
What happened is that I was able to get the keys to work correctly early this year somehow (I can't quite remember how) by converting keys and trying out various options, and publishing those that did work. 

The PEM files that work are listed in [HttpMessageSignaturesV07](https://github.com/bblfish/bobcats/blob/bbl/main/core/shared/src/test/scala/bobcats/HttpMessageSignaturesV07.scala#L200). The updated versions that are used by scalaJS are those named by the functions `privatePk8Key` and `publicPk8Key`. Where those are specified it is because the key in the spec 07 were not in the right format. 

As is visible from the [HttpMessageSignaturesV13.scala](https://github.com/bblfish/bobcats/blob/bbl/main/core/shared/src/test/scala/bobcats/HttpMessageSignaturesV13.scala#L237) all the keys just link to the ones from the 07 spec. 

So using those keys I think would cover all of Java and the WebCrypto API.

**Comment by jricher** [comment]
All the keys listed in the test vectors section are used by the test generation script at : https://github.com/bspk/sig-example-scripts/blob/main/http_sig_examples.py

The key formats in the draft are generated using openssl, as is mentioned at the head of the section. PEM formats like this seem to be not universally supported across different libraries, and even the underlying Python code that runs the examples does need to unwrap the PKCS8 values for some of these, but not others. Adding in the JWK equivalents of these keys is not a bad idea, per @panva 's suggestions.
