### ISSUE TITLE
Client-Cert extension to other certificate types?

### ISSUE THREAD

**Issue by bblfish** [httpwg/http-extensions#2300]
Would it be possible to have an extension mechanism to allow other Cerificate types?
I am aware of PGP certificates,  and [Verifiable Credentials](https://www.w3.org/TR/vc-data-model/), ... that could find this mechanism useful. 
I believe TLS also has an extension mechanism to use other types of certificates, and remember hearing of an RFC to allow PGP certs to be used.

**Comment by b---c** [comment]
That's well outside the scope of the draft, which is to document existing practice (MTLS with X509) while codifying some specific details (names & encodings) enough to facilitate improved and lower-touch interoperability.

**Comment by bblfish** [comment]
yes, that makes sense. 

But you could have it work as specified now by default, and then reserve an attribute `format` for
later usage... That attribute could be applied to the binary.

**Comment by LPardue** [comment]
Agree with Brian here, we should not extend the scope of this document. 

The fields are Structured Fields, they support parameters. If somebody would like to write and extension they can use a parameter to do that and proceed at their own pace.

**Comment by mnot** [comment]
I'm not a fan of this kind of generality -- it's just as easy to mint a new HTTP header for a new use case. 

Furthermore, I'm not at all confident that the semantics of another mechanism would be the same.

**Comment by bblfish** [comment]
> I'm not at all confident that the semantics of another mechanism would be the same.

That would be easy to resolve: Create a registry of formats (and other extensions) and only allow those to be added that have the right semantics.

**Comment by bblfish** [comment]
Ok, no problem. It's bound to happen, ... but I guess it will proceed at its pace.
