### ISSUE TITLE
New Digest IANA registry (AD review)

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#2302]
## From AD Review

> Section 5 and Section 7.2:

> * I encountered this section and followed the link to find that this section is talking about a registry that doesn't actually exist.  That this section is actually specifying a new registry was not clear until Section 7.2.  Can we clarify this somehow?  For that matter, why not merge this section down into what's in 7.2?

> * A "Specification Required" registry obligates the assignment of one or more Designated Experts.  Section 4.6 of RFC 8126 says the defining document should contain guidance to the DEs about what criteria are to be applied when doing reviews.  None seem to be present here.  Is there anything that needs to be said?

**Comment by LPardue** [comment]
Addressed by https://github.com/httpwg/http-extensions/pull/2448
