### ISSUE TITLE
Test Suite for Signature? Space to discuss corner cases?

### ISSUE THREAD

**Issue by bblfish** [httpwg/http-extensions#2316]
Hi, I was thinking that [Signing HTTP Messages](https://httpwg.org/http-extensions/draft-ietf-httpbis-message-signatures.html) could do with a an extensive test suite. The test suite in the doc is pretty good, but more may be better here...

Such a suite could consist of a set of data in some format each consisting of

* a (request response) pair, max one of them being optional
* a `Signature-Input` description
* the resulting signature base
* a signature, using one of the keys
* whether the signature is valid, and if not why not (eg,

Then one could have all kinds of corner cases such as HTTP requests with URLs such as `example.COM`, and cover many more problematic cases like dates where the signare and all are correct but the semantics are wrong (eg. date does not exist)... That would allow one to collect difficult cases. 

IT would also be good if there were a channel to discuss these cases, such as perhaps the IETF [Zulip Http Signature](https://zulip.ietf.org/#narrow/stream/225-httpbis/topic/Signing.20HTTP.20Messages) stream? If we can publicize it for implementors we may get some interesting feedback that way? 

Here is a little question I have for example. The spec says in §2.2.5 that for a request

```HTTP
CONNECT www.example.com:80 HTTP/1.1
Host: www.example.com
```

the  `@request-target` attribute should have as value the content of the string "www.example.com:80" . Is that specific
to `CONNECT`? What should the value be for?

```
GET http://example.com:80/hello HTTP/1.1
``` 
should it be "http://example.com:80/hello" or "http://example.com/hello" because the 80 is the default port for `http`.
If I am asking myself questions here, I guess many other implementors will too, and they may come to different conclusions.

It could also be useful to have a forum or DB where people can explain problems with intermediaries that comes with experience deploying this.

**Comment by mnot** [comment]
Henry, this repo is for issues against the spec itself. If you want to have a discussion like this, the best place is on the mailing list. Thanks!
