### ISSUE TITLE
message-signatures: requirement for field value concatenation

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2324]
https://www.ietf.org/id/draft-ietf-httpbis-message-signatures-15.html#section-2.1-3

> Unless overridden by additional parameters and rules, HTTP field values MUST be combined into a single value as defined in [Section 5.2](https://rfc-editor.org/rfc/rfc9110#section-5.2) of [[HTTP](https://www.ietf.org/id/draft-ietf-httpbis-message-signatures-15.html#HTTP)] to create the component value. Specifically, HTTP fields sent as multiple fields MUST be combined using a single comma (",") and a single space (" ") between each item.

I don't quite get the reasoning for the second "MUST". Why does it matter? What would break if the client uses a single comma, which is also allowed by HTTP?

IMHO the exact delimiter sequence here does not matter at all, as long as it is allowed per HTTP. Note that HTTP allows *combining* field values, it does not allow splitting them afterwards.

**Comment by jricher** [comment]
This isn't combination at the HTTP level by the client or intermediary, this is combination by either the signer or verifier when making the signature base. It's a MUST here because there needs to be only one way to do it at that step. If the lines are already combined then leave them combined.

**Comment by reschke** [comment]
Also...:

> Where that approach is not possible and multiple instances of a field need to be sent separately, it is RECOMMENDED that signers and verifiers process any list-based fields by parsing out individual field values and combining them based on the strict algorithm below, to counter possible intermediary behavior.

I think I misread that as a recommendation to parse individual field values into a list, before recombining everything. Maybe "parsing out individual field values" needs to be rephrased.

**Comment by jricher** [comment]
You would only parse out individual values if you:

1: Know the overall syntax/grammar of the field
2: Know that it's a list separated by commas
3: Can't send everything as a single field line
4: Know that an intermediary is going to mess with things sent as multiple lines in a way that you don't want

The recommendation is really only for that one corner case, not for every value.

**Comment by reschke** [comment]
I agree with that, but the spec really needs to be clearer here.
