### ISSUE TITLE
message-signatures: requirement to 'separate' values

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2326]
https://www.ietf.org/id/draft-ietf-httpbis-message-signatures-15.html#section-2.1-5

> 1. Create an ordered list of the field values of each instance of the field in the message, in the order that they occur (or will occur) in the message. If necessary, separate individual values found in a field instance.

This does not work. It's impossible to split multiple values (be it a list-based field or not) without knowledge of the field value's grammar.

For example, what is the canonicalized value for:

~~~
If-None-Match: W/"1,2", "3"
If-None-Match: "bar"
~~~

?

**Comment by jricher** [comment]
The value would be

```
"if-none-match": W/"1,2", "3", "bar"
```

Since it was sent as two instances, you combine the instances with a comma and space.

The language to split the field values was added late based on several conversations about list type fields and how they can be combined, but we can remove this. If someone needs additional armoring they can use the "sf" flag on a list formatted field.

**Comment by reschke** [comment]
Ok, but what the spec currently says would result in:

~~~
"if-none-match": W/"1, 2", "3", "bar"
~~~

...so that sentence really needs to go.

**Comment by jricher** [comment]
No, it would not result in that, because as you point out those are not separate field values that can be separated.

**Comment by reschke** [comment]
So what does:

> If necessary, separate individual values found in a field instance.

mean then? When is it "necessary"? How does the code know that for any given field name?

**Comment by bblfish** [comment]
I think what is meant is what that you take a list of the values of a given field (one member of the list for each header line) and then concatenate them by seperating them with ", ". 

In scala this is 
```scala
headerValuesList.mkString(", ")
```

or just to make it explicit
```scala
 scala -cli
bad option '-cli' was ignored
Welcome to Scala 3.2.1 (17.0.4.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> val headerVal1 = """W/"1,2", "3""""
val headerVal1: String = W/"1,2", "3"

scala> val headerVal2 = """"bar""""
val headerVal2: String = "bar"

scala> val values = List(headerVal1, headerVal2)
val values: List[String] = List(W/"1,2", "3", "bar")

scala> values.size
val res0: Int = 2

scala> values.mkString(", ")
val res1: String = W/"1,2", "3", "bar"
```

**Comment by reschke** [comment]
Thanks @bblfish - I get that, but that doesn't address the question I asked...

**Comment by bblfish** [comment]
Ok, I see the problem is:
> If necessary, separate individual values found in a field instance.

I would not know how to do that, whereas I do know how to seperate the fields in the list.

**Comment by reschke** [comment]
We need to be very clear with the terminology. What do you mean by "seperate the fields in the list"? Do you have an example?

**Comment by bblfish** [comment]
If you are talking to me, I meant what the code above showed: the list is the list of header values (for a given header name). And I meant seperating the values of that list. 

I don't know how to write that up well in the spec though...

**Comment by reschke** [comment]
Ok, AFAIU: just drop "If necessary, separate individual values found in a field instance." from the spec.
