### ISSUE TITLE
message-signatures: method casing

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2329]
https://www.ietf.org/id/draft-ietf-httpbis-message-signatures-15.html#section-2.2.1

> Note that the method name is case-sensitive as per [[HTTP](https://www.ietf.org/id/draft-ietf-httpbis-message-signatures-15.html#HTTP)], [Section 9.1](https://rfc-editor.org/rfc/rfc9110#section-9.1), and conventionally standardized method names are uppercase US-ASCII.

I would drop the "and conventionally standardized method names are uppercase US-ASCII". Method names are case-sensitive, that's what is relevant. The second part somewhat weakens that statement.

**Comment by jricher** [comment]
This is a note to implementors and doesn't change the normative requirements or behaviors -- I think we should leave it in. Note that the text in question appears in section 9.1 as referenced:

> By convention, standardized methods are defined in all-uppercase US-ASCII letters.

**Comment by reschke** [comment]
Good catch, and I should have objected to that.

Anyway; I don't think it makes sense to note it here. It doesn't help at all - the method name is what appears in the request message. The note doesn't add anything useful, but might cause confusion. Take this ticket as proof.

**Comment by jricher** [comment]
Having seen people try to normalize things by lowercasing because "it made sense", I disagree that the note doesn't add anything useful. I'd like to leave it in.

**Comment by reschke** [comment]
Just to clarify: my concern is that implementers will take that as a suggestion to *upper*case.
