### ISSUE TITLE
message-signatures: IANA reg name lengths

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2335]
> The name MUST be an ASCII string that conforms to the key ABNF rule defined in [Section 3.1.2](https://www.rfc-editor.org/rfc/rfc8941.html#section-3.1.2) of [[STRUCTURED-FIELDS]](https://greenbytes.de/tech/webdav/draft-ietf-httpbis-message-signatures-15.html#STRUCTURED-FIELDS) and SHOULD NOT exceed 20 characters in length

(in several places)

Who is going to enforce that, and under which circumstances are longer names ok?

**Comment by jricher** [comment]
The expert reviewers both enforce and make decisions on exceptions for all of these, as is common practice.

**Comment by reschke** [comment]
Yes. Maybe. But a "SHOULD" without any explanation is really problematic.

**Comment by jricher** [comment]
This is covered by updated guidance to the DE in #2366
