### ISSUE TITLE
message-signatures: status code when sig in request is invalid

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2336]
This is not necessarily a spec issue, but I thought it should be recorded and maybe discussed here.

Is there a recommendation how a server should respond when a request is signed but the signature is invalid. It's likely a 400, unless we want to define a more specific code? Maybe a pointer to the HTTP problem format would be useful?

**Comment by bblfish** [comment]
Good question. If one was using signatures for authentication would 401 be correct? 
Clearly an additional error message would be useful.

**Comment by ioggstream** [comment]
I agree it depends on signature, but a bit of confrontation is beneficial.

WDYT about:

-  400 in a generic case (malformed signature)
-  401/403 if signature is used for authnz

This is the case of Content-Encoding and Content-Type. Eg.

```
Content-Encoding !=  null 
*-Digest ∈ Signature-Input
Content-Encoding ∉ Signature-Input
```

**Comment by reschke** [comment]
Almost: https://www.ietf.org/archive/id/draft-ietf-httpapi-rfc7807bis-04.html

**Comment by tyler-ham** [comment]
I like the approach in PR #2392 to make a suggestion on the error codes and leave it up to the application to determine what makes sense in its context.
