### ISSUE TITLE
ABNF

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2338]
As discussed during adoption, we want to reconsider our use of ABNF in this specification.

Uncontroversial was removing the recommendation to define new fields using ABNF; that can be easily accommodated and I'll do that in a commit to `main` shortly.

More discussion is needed about completely removing ABNF from the definitions of the types, and other potential changes to the use of ABNF.

**Comment by reschke** [comment]
I completely disagree.

FWIW, I have implemented structured fields based on the given algorithms (and it passes all tests from the non-official test suite): https://github.com/reschke/structured-fields

So this is implementor (not just spec reader) feedback: the ABNF is extremely useful (for those who speak ABNF) to quickly see what the syntax of a construct in the syntax is. Reading prose or algorithms expressed in prose doesn't work as well.

I'll also note that removing the ABNF was *removed* from the scope of this work; compare https://lists.w3.org/Archives/Public/ietf-http-wg/2022OctDec/0013.html with https://lists.w3.org/Archives/Public/ietf-http-wg/2022OctDec/0051.html (which only says: "Add clarifications to the use of ABNF in the document (for example, emphasize that they are not normative), subject to WG discussion").

I'm fine with clarifications - and that's exactly what the call for adoption mentions.

**Comment by tfpauly** [comment]
What about keeping the ABNF, but moving all of the ABNF definitions to an appendix all in one place, and mark the whole thing as non-normative? That seems like it would retain the value for implementors who are fluent in ABNF while not adding extra bulk or confusion to the main document.

**Comment by mnot** [comment]
That's a compromise, yes. I'd prefer to remove them but that might mitigate the risks.

**Comment by reschke** [comment]
> What about keeping the ABNF, but moving all of the ABNF definitions to an appendix all in one place, and mark the whole thing as non-normative? That seems like it would retain the value for implementors who are fluent in ABNF while not adding extra bulk or confusion to the main document.

The spec already says that the ABNF is not normative (in that if there's a conflict, the prose algorithm wins).

WRT moving to an appendix - that could be done, but it de-values the ABNF and I still do not see a good reason for that. It would be really helpful to have an example where readers of the original spec got confused by the presence of the ABNF.

**Comment by LPardue** [comment]
As an anecdote, I've seen people that want to implement SF pick up the spec, more or less skip sections 1 and 2 and going to section where the types are defined. They see the ABNF and start building up a mental model of what things to do (governed by if they are a producer or consumer) and might not be aware that section 4 is where they should be investing their efforts. That risks an incorrect model or annoying the reader.

Moving the ABNF later in the document (such as the appendix), and more actvely promoting the relevant serilizing/parsing sections as each type is introduced might do better to promote the intention that the document had.

**Comment by reschke** [comment]
I hear you.

But then, it is impossible to optimize specs for people who are not reading the important parts.

**Comment by LPardue** [comment]
So why does the ABNF deserve to be in section 3? Section 3 is about the abstract types but then we immediately jump to a concrete on-wire protocol expression. That seems odd, especially if we're considering other representations of SF types like binary structured fields.

**Comment by tfpauly** [comment]
@reschke I'm not hearing a ton of other opinions for keeping the ABNF where it is. While I get that removing it entirely would be a problem, I don't see how having a dedicated section for the ABNF mappings hurts the implementers that want to reference that. Could you live with the ABNF being in its own section/appendix as a compromise between the positions here?

**Comment by reschke** [comment]
I've been in the rough before...

No matter what we do, we have to double-check the prose for potential inconsistencies with the ABNF, as mentioned in another ticket.

**Comment by mnot** [comment]
@tfpauly are we OK to merge?
