### ISSUE TITLE
sfbis: ensure prose introductions are in sync with ABNF and parsing algorithms

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2341]
Example:

> [3.1.](https://greenbytes.de/tech/webdav/draft-ietf-httpbis-sfbis-latest.html#rfc.section.3.1) [Lists](https://greenbytes.de/tech/webdav/draft-ietf-httpbis-sfbis-latest.html#list)
>
> Lists are arrays of zero or more members, each of which can be an Item ([Section 3.3](https://greenbytes.de/tech/webdav/draft-ietf-httpbis-sfbis-latest.html#item)) or an Inner List ([Section 3.1.1](https://greenbytes.de/tech/webdav/draft-ietf-httpbis-sfbis-latest.html#inner-list)), both of which can be Parameterized ([Section 3.1.2](https://greenbytes.de/tech/webdav/draft-ietf-httpbis-sfbis-latest.html#param)).
>
> The ABNF for Lists in HTTP fields is:
>
> sf-list       = list-member *( OWS "," OWS list-member )
> list-member   = sf-item / inner-list
>
> Each member is separated by a comma and optional whitespace. (...)

The last sentence is in conflict with both the ABNF and the parsing algorithm - it needs to say "Each member is separated by _optional whitespace,_ a comma and optional whitespace"

(there may be more cases like this)

**Comment by mnot** [comment]
Strongly disagree. The prose is not in conflict (it doesn't say anything about ordering or cardinality). 

Right now the prose is clearly an overview and not specific. If we add that level of precision to the prose, it will lead to ambiguities that will cause issues.

**Comment by reschke** [comment]
Wait - I think this is clearly a bug.

If you have prose describing what a datastructure is, *either* just describe the structure, or include the syntax. If you include the syntax, it needs to reflect reality.

This is not editorial - reopening.

**Comment by mnot** [comment]
In the original drafting, we qualified these statements with "in the textual representation..." or similar.

I think the options are:

a. Reintroduce that framing, to make it clear we're not talking about the abstract data model, just one expression of it
b. Remove anything about the serialisation-specific syntax and just stick to the abstract data model.

Thoughts?

**Comment by reschke** [comment]
The first option sounds good to me.

We may also have to say somewhere that right now, there's just that one representation, but that this might change in the future.

**Comment by mnot** [comment]
Waiting for #2338...

**Comment by mnot** [comment]
[62a67d0](https://github.com/httpwg/http-extensions/commit/62a67d0a4471e322f1b552bb980d2e540c9504c1) attempted to do that. 

We might also do one or both of:

1. Introducing subsections in each of the abstract data model to separate those summaries of the textual form from the abstract model
2. Add more summaries of the textual forms (but the ones that are missing are pretty obvious)

On balance, I think neither of these is necessary, and they'd add noise to the document without corresponding value. 

Opinions?

**Comment by mnot** [comment]
Closing, but please give more feedback if necessary.
