### ISSUE TITLE
Client-Cert HTTP Header: guidance for layered usage

### ISSUE THREAD

**Issue by enygren** [httpwg/http-extensions#2346]
A common usage pattern is likely to be:

1) Client authenticates to a CDN which validates the client cert and passes along this information in a header
2) CDN authenticates to an origin TLS-terminating load balancer or ingress gateway which passes along this information in a header to the app server

In this case, the app server probably cares about (1) but may also need to validate (2) as well.  Or alternatively, only pass along (1) when (2) is validated.

Trying to add semantics here into the headers seems like way more complexity than we want to take on,
so allowing the use of alternate pre-arranged header names may make sense.

Taking an approach from RFC 9213 (Targeted HTTP Cache Control) might be an option, such as having
a short section that describes this scenario and says  "implementations MAY prefix with an identifier 
by prior arrangement".

**Comment by bc-pi** [comment]
**I somehow missed this - apologies for coming to it months later...**

With the goal of keeping it simple and reflecting current practice, such layered cases are out of scope of this document. There's text in the last paragraph of the intro that attempts to capture that https://www.ietf.org/archive/id/draft-ietf-httpbis-client-cert-field-04.html#section-1-4 FWIW 

Nothing in the document would prohibit using alternate prearranged header names in such a situation. But If you'd like to propose or PR some non-normative text for an appendix that describes the scenario with general guidance (the alternate header(s) would be used for (2)), that seems like it'd be okay/appropriate for the doc.

**Comment by b---c** [comment]
Draft is in the RFC Editor queue https://datatracker.ietf.org/doc/draft-ietf-httpbis-client-cert-field/ so past the window for changes.
