### ISSUE TITLE
"tus"

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#2349]
The title of the resumable uploads draft starts with "tus", which is a little weird as the inclusion is entirely unexplained.

If the intent is to acknowledge something, might I suggest the Acknowledg[e]ments section.

**Comment by LPardue** [comment]
Agreed. I think this helped during the "pitch period" as a differentiator for this proposal vs others. However, now its an adopted document the lone use of the term is odd. I'll prepare a PR that gives a nod back to the tus v1 spec that inspired this.

**Comment by mnot** [comment]
+1

**Comment by Acconut** [comment]
I opened a PR for this: https://github.com/httpwg/http-extensions/pull/2407

@LPardue Let me know if you had something different in mind.
