### ISSUE TITLE
require .well-known/http-opportunistic

### ISSUE THREAD

**Issue by mcmanus** [httpwg/http-extensions#235]
2] /.well-known/http-opportunistic should always be required. The current doc is actually a little fuzzy on this, I think by accident. It refers to this as an "additional mechanism" in addition to authentication. But .wk does not really play the same role - it allows the server to opt-in to being an alternate for specific origins on specific ports. So if we're going to use it - we should always use it. (This has no bearing on https:// alt-svc, this is just about http:// as that is all this doc governs).

[There is further discussion of this on list]

**Comment by martinthomson** [comment]
@mcmanus let me know if this isn't clear in the latest version.  I think that we're OK.

**Comment by mcmanus** [comment]
lgtm; thanks
