### ISSUE TITLE
Return `type` for Integer/Decimal parsing

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#2354]
[Parsing an Integer or Decimal](https://www.ietf.org/archive/id/draft-ietf-httpbis-sfbis-01.html#section-4.2.4) doesn't return `type`.  Without that, the number itself isn't necessarily enough to determine what the type is (necessary for parsing Date).

**Comment by reschke** [comment]
So what we need to prevent here is that:

~~~
@0.0
~~~

parses as date.

**Comment by mnot** [comment]
I don't think this is necessary; the result of Parsing a... already has a type, and that's already checked in Date parsing.

Nevertheless, see PR...

**Comment by mnot** [comment]
The PR isn't correct; it fails to account for the different return signature everywhere it's called.

Fixing that is much more invasive, so I'm going to push back on this more strongly; it isn't necessary. What _Parsing an Integer or Decimal_ returns **is** typed; it's either an integer or a decimal. This can be seen in other places as well -- e.g., in Serializing a Bare Item ("If input_item is an Integer, return...").

No change is necessary here.

**Comment by mnot** [comment]
@martinthomson @reschke can I close this with no action, or should we take it to the list, or...?

**Comment by martinthomson** [comment]
So your assertion is that a value inherently carries a type?  That's not obvious to me.

**Comment by mnot** [comment]
Yes. [Section 3](https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#name-structured-data-types) defines those types; the serialisation algorithms take them as parameters, and the parsing algorithms return them. That's reflected in the introduction text for each individual algorithm.
