### ISSUE TITLE
draft-ietf-httpbis-alias-proxy-status: Refer to AI_CANONNAME

### ISSUE THREAD

**Issue by bemasc** [httpwg/http-extensions#2358]
I think the alias draft should probably have a (non-normative) reference to [getaddrinfo's AI_CANONNAME functionality](https://pubs.opengroup.org/onlinepubs/9699919799/functions/freeaddrinfo.html), in particular noting that:

* `next-hop-aliases` can be populated from the output of `getaddrinfo`.
* `next-hop-aliases` can be used to emulate or substitute for `getaddrinfo`.

**Comment by edmondsfastly** [comment]
I think the `AI_CANONNAME` flag to `getaddrinfo` only gives you the "canonical name" which is the final CNAME target at the end of the CNAME chain. If you want the full set of interior names across a chain of multiple CNAME records I don't believe you can retrieve that with `getaddrinfo`.

**Comment by tfpauly** [comment]
Yeah, I'm hesitant to add references to system APIs like `getaddrinfo`, and particularly for the reason given above. @bemasc what do you think?

**Comment by bemasc** [comment]
I think AI_CANONNAME is important historical context here.  You can't
understand where the draft is coming from without it.  I also think that
this extension will often be implemented by wrapping getaddrinfo, and some
guidance about whether that is compliant would be appropriate.

I think Robert's comment raises a good example of why this is not trivial,
and hence is worth mentioning.

**Comment by tfpauly** [comment]
I'm not sure `AI_CANONNAME` is really required to understand the context of the draft. We don't use it at all on iOS/macOS implementations for current CNAME cloaking detection.

I do see that it may be good to warn that it is not sufficient to just wrap up `AI_CANONNAME`.
