### ISSUE TITLE
Accept clarification question

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2365]
_Comment by @fpalombini_

[Section 5.1](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-15.html#section-5.1): >algorithm or key identifier. These parameters MUST NOT include parameters that the signer is expected to generate, such as the created parameter.

Why should it not? Couldn't the verifier include these empty parameters to indicate that the signer is expected to generate and send them?

**Comment by jricher** [comment]
That's a good point -- that functionality had not been requested but I don't see why it couldn't work that way. I'll propose some text to handle that case.
