### ISSUE TITLE
Reference to HTMLURL

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2370]
_Comment by @fpalombini_

Thanks to Tommy for detailed shepherd write up, that tells me you have discussed this already. Seems obvious that the HTMLURL reference needs to be normative, so we might need to reference a snapshot of this instead.

See the following text in the IESG statement: https://www.ietf.org/about/groups/iesg/statements/normative-informative-references/

> Note 4: Normative references in RFCs cannot be to "work in progress" documents such as Internet Drafts. Drafts with such references will not be published as RFCs until the references are also published.

I'd like to get this fixed before starting the Last Call.

**Comment by jricher** [comment]
A permanent anchor has been requested of the WHATWG: https://github.com/whatwg/url/issues/740

**Comment by jricher** [comment]
This has been implemented by the WHATWG in https://github.com/whatwg/url/pull/741 , so we just need to move our references to use the new permanent anchors.

**Comment by jricher** [comment]
@reschke while true, as the target document is a "living standard" there is no way to guarantee a specific version. Nor is that reason to believe that the document is "unstable" in the way an I-D is. At the very least, implementors will be able to find the information they need at the referenced anchors.

**Comment by reschke** [comment]
Yes, I agree with that. I just wanted to mention that this might not address the *AD* feedback.
