### ISSUE TITLE
6.5 Usage with Encryption - it isn’t clear what layer of encryption is assumed (representation, content)

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2384]
James Manger wrote:

> In “6.5 Usage with Encryption” it isn’t clear what layer of encryption is assumed (representation, content). I guess it is assuming a Content-Encoding that encrypts, such as “Content-Encoding: aes128gcm” from RFC 8188. And the security consideration is pointing out that if the encryption is performed multiple times to respond to multiple HTTP requests then the ciphertext (& hence Content-Digest & Repr-Digest) is likely to change each time, as each encryption (of the same plaintext) is likely to use a different nonce and/or key.
> 
>  This issue could occur without encryption. For instance, compression algorithms often have different “levels” (eg 1=fast, 9=best). So the representation could change if the level changed between requests. Maybe that will be rare enough to ignore?
> 
> I thought “6.5 Usage with Encryption” might be warning against including a digest of the plaintext if encryption was applied as, say, a transfer-encoding (not sure if there are encrypting transfer-encodings). That would be insecure.

**Comment by LPardue** [comment]
yeah I think  RFC 8188 was the target of the section here. @ioggstream can you recall? What can we add to make this section a bit more clear?

**Comment by ioggstream** [comment]
That's correct. And the suggestion wrt different compression levels is correct to! This is worth mentioning and maybe highlight that it applies to a specific kind of content codings.
