### ISSUE TITLE
No examples of encoding output any of the 6 "insecure" algorithms

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2385]
From James Manger:

> There are no examples of any of the 6 “insecure” algorithms that are still listed in the table. This is particularly important as checksums were conveyed in decimal and hex in Digest, but will now be base64-encoded in Content-Digest & Repr-Digest. Do you base64-encode the decimal digits from, say, cksum; or base64-encode the 32-bits (most significant byte first?) they represent?

**Comment by LPardue** [comment]
Yeah I think this identifies some ambiguities. But addressing those with examples alone doesn't seem right. If people to run a hash algorithm and calculate an output, but disagree on the presentation format of that output *before* it is converted into a Byte Sequence, then that seems like a potential interop problem.

**Comment by LPardue** [comment]
I think the simplest thing to do here is to state clearly that the value sent on the wire is the base-64 encoding of the actual bytes produced by an algorithm (and pick MSB or LSB).

**Comment by LPardue** [comment]
Another option here is to add some test vectors to the document. That way we could be exhaustive for all algorithms that populate the IANA table, without having to generate lots of examples.

**Comment by c799878** [comment]
The examples for unixsum and unixcksum are incorrect. They have been calculated over the input plus a newline, ie over 19 bytes instead of 18.

WRONG
unixsum -   :jIw=:
unixcksum - :rF3+Zw==:

RIGHT
unixsum -   :GQU=:
unixcksum - :7zsHAA==:

**Comment by LPardue** [comment]
Thanks!

**Comment by reschke** [comment]
> The examples for unixsum and unixcksum are incorrect. They have been calculated over the input plus a newline, ie over 19 bytes instead of 18.

:eyes:
