### ISSUE TITLE
Base-64 encoding bodies is unfortunate

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2387]
From James Manger

> Base64-encoding non-printable bodies so they can be included in the document is unfortunate. Particularly as there are lots of “real” base64 values (ie all the …-Digest values). Perhaps hex would have been better to display bodies.
>
> If sticking with base64 to display bodies, the “Range: bytes=1-7/18” examples would be better as “Range: bytes=3-10/18”. That way you can visually recognize that the range (“AItWyFwC/6s=”) is a subset of the original (“H4sIAItWyFwC/6tW…”).

**Comment by LPardue** [comment]
In appendix A, we do use hex-encoding for representing gzipped binary.

In appendix B, i seems that there are some brotli-encoded objects we represent as bas64. I'm going to say that we just accidentally missed these and that we can also just show some hex. 

Since you did the gzip hex, could you pick this up @ioggstream?

**Comment by ioggstream** [comment]
To me it's ok to switch to hex. I'll check the content of other I-D to be consistent.

**Comment by c799878** [comment]
Ugh. Repeating "0x" for every byte with no spacing is unreadable.
0x8B0x080x800x7B0x220x680x650x6C0x6C0x6F\
0x220x3A0x200x220x770x6F0x720x6C0x640x22\
0x7D0x03

Spaced hex pairs would be better. You don't need the `\` RFC 8792 line wrapping as these aren't the real lines anyway.
8B 08 80 7B 22 68 65 6C 6C 6F
22 3A 20 22 77 6F 72 6C 64 22
7D 03

**Comment by LPardue** [comment]
The existing hex encoding examples used the 0x style, so yhis PR was consistent. I can make a followup PR with your suggestion

**Comment by LPardue** [comment]
see https://github.com/httpwg/http-extensions/pull/2449
