### ISSUE TITLE
Can 2 algorithms have the same preference?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2389]
From James Manger:

> Can 2 algorithms have the same preference? For example:
Want-Repr-Digest: sha-512=5, sha-256=5, unixsum=0

**Comment by LPardue** [comment]
Good question. Syntactically, Structured Fields allows dictionary members to have the same value. We say the value conveys an ascending, relative, weighted preference. So members with the same value are relatively the same.

The intention here is to emulate RFC 3230's `q` parameter, based on HTTP "Quality Values" aka `qvalue`, https://www.rfc-editor.org/rfc/rfc9110.html#name-quality-values. We just apply a much smaller range. Partly because we never got much feedback on whether RFC 3230'sWant-Digest or its `q` parameter was used in the wild. Partly because the thing is just a hint and the server can do what it wants anyway. 

AFAICT, RFC 9110 says nothing about how to treat quality values that use the same number. Maybe @mnot @royfielding or @reschke have an opinion on the matter. 

Since RFC9110 is quiet on the matter of same qvalue number, I'm inclined to stay quiet here.

**Comment by reschke** [comment]
Right, same value is same value (there are fields that range "simpler" values better (Accept?) - but that doesn't seem to apply here).

**Comment by ioggstream** [comment]
+1 on quiet

**Comment by LPardue** [comment]
Based on this discussion, closing with no action
