### ISSUE TITLE
sf: (potentially) clarify strict error handling

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2399]
https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#section-2

> When parsing fails, the entire field is ignored (see [Section 4.2](https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#text-parse)); in most situations, violating field-specific constraints should have the same effect. Thus, if a header is defined as an Item and required to be an Integer, but a String is received, the field will by default be ignored. If the field requires different error handling, this should be explicitly specified.

It appears that some read the last sentence:

> If the field requires different error handling, this should be explicitly specified.

as saying that the generic draconian handling of parsing errors can be relaxed.

**Comment by mnot** [comment]
It's saying that a generic parser will fail, but the field-specific handling of that failure might do somthing else, including try to parse the field using an alternative method. SF cannot constrain what a field does with the output of parsing.

**Comment by reschke** [comment]
That sounds like "we require draconian error handling, but if there's an error, you are free to do something else".

Of course we can't force anybody not to do that, but we should be clear that this is not what the spec says.
