### ISSUE TITLE
Hashes of uploaded files

### ISSUE THREAD

**Issue by Acconut** [httpwg/http-extensions#2408]
At IETF 115, Hans-Jörg Happel mentioned the idea of an extension to add checksum mechanism to resumable uploads.

One option is that the server calculates a checksum of completed uploads and provides it to the client, which can compare this checksum with an expected value. If the values do not match, the client can error out or retry the upload.

Another option is that the client tells the server the expected checksum in the beginning, and the server verifies the checksum once the upload is complete.

**Comment by LPardue** [comment]
[HTTP digests](https://httpwg.org/http-extensions/draft-ietf-httpbis-digest-headers.html)  can probably deal with both of these options. I would be resistant to implementing something new just for resumable uploads.

The question for me is how much, if at all, resumable uploads should discuss this kind of scenario. Maybe just mentioning the possibility of HTTP digeat, or maybe some examples if the sequence if messages is non-obvious. But we should try to keep text lean IMO.

**Comment by Acconut** [comment]
HTTP digests seems to fit very well here. There is also some discussion in https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0067.html around this topic. 

> Maybe just mentioning the possibility of HTTP digeat, or maybe some examples if the sequence if messages is non-obvious. But we should try to keep text lean IMO.

I agree. Such a mention and a few examples should be sufficient.
