### ISSUE TITLE
message-signatures: addition of leading or trailing whitespace to a field value

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2410]
1.3:

> As mentioned earlier, HTTP explicitly permits and in some cases requires implementations to transform messages in a variety of ways. Implementations are required to tolerate many of these transformations. What follows is a non-normative and non-exhaustive list of transformations that could occur under HTTP, provided as context:
> ...
>  -  Addition or removal of leading or trailing whitespace to a field value.

This is misleading. No HTTP permits *addition* of leading/trailing whitespace. Leading/trailing whitespace in field values by definition is invalid.

**Comment by mnot** [comment]
While technically true, many (including implementers) won't understand the nuance Here. Given the impact, it's better to be over-inclusive, I think.

**Comment by martinthomson** [comment]
If invalid changes are included, then it might be best to either say that some of these changes might be invalid or point specifically to those that are.

**Comment by reschke** [comment]
Yes, my proposal would be to split the list into two; the second just listing the transformatios that might happen in reality despite bing forbidden.

**Comment by jricher** [comment]
@reschke I agree that we need to prepare developers for the messy reality of HTTP in addition to what's strictly allowed. What else would appear in this second list?

**Comment by reschke** [comment]
The only other thing that I can see right now is addition of obs-fold.

**Comment by jricher** [comment]
@reschke Re-serialization of a field value by an intermediary would likely break things in an expected way. It was my impression that this was not allowed by intermediaries in general. A structured field does help this, and the `sf` flag protects against that kind of transformation, as mentioned in the section.

**Comment by reschke** [comment]
I don't think we have a rule anywhere that would keep an intermediary from parsing and re-serializing fields.

And even if that was the case, the same would be true for the original point (addition of leading/trailing WS), so I'm trying to understand where we draw the line.
