### ISSUE TITLE
empty next-hop-aliases?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2420]
Since next-hop-aliases is a String parameter, the syntax allows an empty string `""`. In cases where there is no chain, is it advisable to send the empty string to indicate this, rather than omitting the parameter? If so, it might help to add a sentence somewhere that highlights this usage type.

**Comment by tfpauly** [comment]
That's a good question! I don't think there needs to be a normative requirement here, but I think it's reasonable to have `""` signify that there were no aliases.
