### ISSUE TITLE
Per-authenticator context labels

### ISSUE THREAD

**Issue by chris-wood** [httpwg/http-extensions#2429]
I would recommend making the TLS exporter labels specific to the type of algorithm in use. For example, rather than use "EXPORTER-HTTP-Unprompted-Authentication-Signature" for signature-based authenticators, I might use "EXPORTER-HTTP-Unprompted-Authentication-Signature-Ed25519" for authenticators using Ed25519.

**Comment by martinthomson** [comment]
Any case that involves intermediaries forwarding tokens will necessarily involve some amount of trust in the intermediary.  The intermediary can provide the exporter output when it forwards the token, which would allow the signature to be verified, but the recipient is going to have to trust that this isn't copied from some other request.

I definitely think that the context string is the right place to include origin, key identifier, algorithm choice, and maybe even some context from the request (URL).  That latter depends on how heavily people intend to lean on the intermediation case.

**Comment by DavidSchinazi** [comment]
Discussed at IETF 116, sense of the room appeared to be that adding the key identifier and algorithm to the context made sense. We can skip URL and instead add realm, see #2428

**Comment by DavidSchinazi** [comment]
OK wrote up #2572 to address this
