### ISSUE TITLE
List nesting

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#243]
From Kari on-list:

5.1.3.  Domain Matching
https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-00#section-5.1.3

There is some nested lists lost.

|   o  The domain string and the string are identical.  (Note that both
|      the domain string and the string will have been canonicalized to
|      lower case at this point.)
|   o  All of the following conditions hold:
|   o  The domain string is a suffix of the string.
|   o  The last character of the string that is not included in the
|      domain string is a %x2E (".") character.
|   o  The string is a host name (i.e., not an IP address

These should be on nested list, I think:

|   o  The domain string is a suffix of the string.
|   o  The last character of the string that is not included in the
|      domain string is a %x2E (".") character.
|   o  The string is a host name (i.e., not an IP address

RFC 6265 was

5.1.3.  Domain Matching
https://tools.ietf.org/html/rfc6265#section-5.1.3

|   o  The domain string and the string are identical.  (Note that both
|      the domain string and the string will have been canonicalized to
|      lower case at this point.)
|
|   o  All of the following conditions hold:
|
|      *  The domain string is a suffix of the string.
|
|      *  The last character of the string that is not included in the
|         domain string is a %x2E (".") character.
|
|      *  The string is a host name (i.e., not an IP address).

**Comment by mikewest** [comment]
Thanks! This will be taken care of in a -01 (but I'll wait to publish that, as I assume we'll find more of these porting mistakes over the next week or so).
