### ISSUE TITLE
Signature optional

### ISSUE THREAD

**Issue by chris-wood** [httpwg/http-extensions#2430]
Is there a reason why the signature parameter in the header field is listed as optional? That seems fairly essential for this thing to work.

**Comment by martinthomson** [comment]
Presumably the signature algorithm is determined by the key that is used, which is either implicit (`u=` is optional too) or indirectly identified via `u=`.

**Comment by DavidSchinazi** [comment]
That's correct. We can add some editorial text to make this clearer

**Comment by chris-wood** [comment]
I think making it optional probably requires some analysis to ensure it's safe. This feels like a sharp edge. I would recommend making it mandatory for now and then possibly let it be optional if we have evidence it's safe.

**Comment by DavidSchinazi** [comment]
@chris-wood I think you're misunderstanding the draft. `s` is OPTIONAL in general because it's only used by `Signature` but not by `Hash`. `Signature` requires `s`. Can you re-read to double-check this and see if you still have concerns?

**Comment by chris-wood** [comment]
That matches my understanding. My point is that if the algorithm actually requires a signature to be provided, then I think it MUST be included, not left up for interpretation by the receiver. Specifically, if authenticating with a digital signature and not a MAC, then I'm suggesting this parameter to be mandatory. I understand that it's not needed by the other variants.

**Comment by DavidSchinazi** [comment]
@chris-wood that's what the draft already says:
> The "Signature" HTTP Authentication Scheme uses asymmetric cryptography. User agents possess a user ID and a public/private key pair, and origin servers maintain a mapping of authorized user IDs to their associated public keys. When using this scheme, the "u", "p", and "s" parameters are REQUIRED.

**Comment by chris-wood** [comment]
Great! In that case, we can close this.
