### ISSUE TITLE
New header field vs existing Authorization header

### ISSUE THREAD

**Issue by chris-wood** [httpwg/http-extensions#2432]
Is there a technical reason why the `WWW-Authenticate` header was not chosen for this draft? That can be sent without a corresponding challenge (in an unprompted way), as we note in the [HTTP authentication scheme for Privacy Pass](https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-auth-scheme.html). It seems like that would work in this context, too.

**Comment by tfpauly** [comment]
Is this rather about using the Authorization header?

**Comment by chris-wood** [comment]
🤦 Yep!

**Comment by DavidSchinazi** [comment]
@chris-wood can you elaborate on "as we note in the [HTTP authentication scheme for Privacy Pass](https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-auth-scheme.html)"? I skimmed through that draft and it seems to clearly require a TokenChallenge before sending a Token.

**Comment by chris-wood** [comment]
I thought we had text that described it, but I can't find it. In any case, I think one can send the Authorization header unsolicited, so I think this draft ought to do that instead of rolling a new auth header.

**Comment by DavidSchinazi** [comment]
Fair enough, let's discuss this at 116.

**Comment by bemasc** [comment]
FWIW, I agree that unprompted "Authorization" is permissible in this context, but I think "Unprompted-Authorization" could be useful for clarity when reading logs, etc.

**Comment by DavidSchinazi** [comment]
Discussed at IETF 116, sense of the room appeared to be that switching to Authorization made sense.

**Comment by DavidSchinazi** [comment]
OK wrote up #2571 to address this
