### ISSUE TITLE
Comments on the updated draft

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [httpwg/http-extensions#2434]
Thank you for the draft updates, @DavidSchinazi.  Here's a shot at a "validating scenario" for HTTP Unprompted Auth:

We seek to emulate the phenomenon of the "speakeasy" in Prohibition America, with a bit more rigor to support higher levels of usage.  

Imagine a back alley deep in a maze of warehouse buildings in 1920s Chicago USA.  A person stands in front of door beneath a dimly lit bulb. Another person arrives and says "Is this the club where they serve free beer?".  The person answers "I don't know what you mean" and the man leaves. Another person arrives later and, without being asked, nods their head to the side and says "Whiskey Tango Foxtrot".  The person is let in the door.  A third person, arriving much later, emulates the second person but is told "I don't know what you mean".  

The second person in this scenario knows the speakeasy's location, knows the code and knows to provide it without being asked.   Everyone else fails to gain access and learns no information about the failure.  As a secondary measure, anyone who re-uses a previously-used code similarly fails to gain access and learns no information about the failure.  This secondary measure assures the code itself can not be shared along with the location. 

In an HTTP use case, certain resources provided by an origin require a mechanism for differentiating valid users from invalid ones. Validity is determined by perhaps account settings, expressed preferences or fees. These resources are valuable and, if the origin was known, it could be flooded with invalid requests, rendering the resources unusable by all.  Therefore the resource location is provided only to known valid users.  However, to prevent unwanted sharing of the location with invalid users, a mechanism is necessary to allow valid users to gain entry in a manner that does not indicate (a) the resource's location has been found or (b) that a special authentication is required.  The mechanism proposed by HTTP Unprompted Authentication supports this scenario by (a) using per-connection private data combined with pre-agreed or pre-generated authentication tokens and (b) generic failure codes.

**Comment by DavidSchinazi** [comment]
@m4mb01t4l14n0 ping?

**Comment by m4mb01t4l14n0** [comment]
@DavidSchinazi re the authentication type string - I am happy to drop discussion of this topic completely.

**Comment by DavidSchinazi** [comment]
Thanks. I think we can close this and use
* #2427 to discuss use-cases
* #2428 and #2429 to discuss what goes into the TLS exporter context/label
