### ISSUE TITLE
feedback from IETF115

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [httpwg/http-extensions#2435]
Following IETF115 presentation: Some very good questions - "comparisons to available techniques" - teased out just by naming the draft differently? (this could have all come out at IETF114 maybe)

Need to have answers for the difference between this approach and (a) token-binding (is this only TLS 1.3?), (b) exported authenticators.

Issue raised (paraphrased): why is this useful if you already have lots of information about the user provisioned out-of-band?

**Comment by DavidSchinazi** [comment]
Closing as this is covered by individual issues #2427 and #2432
