### ISSUE TITLE
Discuss security properties of keys

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#2438]
From @nharper on the [list](https://lists.w3.org/Archives/Public/ietf-http-wg/2022OctDec/0028.html):

> The draft is very light on details about where the user's key (private or symmetric) comes from. I assume that key generation/distribution/registration/etc is out of scope for this draft, but the draft should address the security properties expected of said key, e.g. can a key be used for Unprompted Authentication and another use?

**Comment by jhoyla** [comment]
The conservative thing to do here would be to insist that the key be unique to the protocol. 
We have domain separation in our outputs, so we don't need to worry about unprompted auth messages being used in cross-protocol attacks, but a different protocol (that doesn't use context strings) could possibly be induced to generate unprompted auth messages. We also need to worry about key compromise.

Imagine a protocol that leaks the private / secret key, that shares a key with unprompted auth. This doesn't even need to be a bug, it could be a commit-before-reveal style protocol. (Obviously that's a pathological example, but it shows we can't assume composability with all protocols) 

If we want to do a formal analysis (which I do) I think we need to be conservative here.

**Comment by DavidSchinazi** [comment]
SGTM
