### ISSUE TITLE
Signature hash algorithm is ambiguous

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#2440]
From Ilari Liusvaara on the [list](https://lists.w3.org/Archives/Public/ietf-http-wg/2022OctDec/0027.html):

> There is no requirement to include hash algorithm in signatures. There are TLS signature algorithms that mean totally different things depending on hash function, and more of those could appear in the future. E.g, signatures 7 and 8 already have double meaning (EdDSA [hash 8] and some Chinese stuff [hash 7]).

From @nharper on the [list](https://lists.w3.org/Archives/Public/ietf-http-wg/2022OctDec/0028.html):

> I agree with Ilari - do not use the TLS SignatureAlgorithm and HashAlgorithm registries that were orphaned by RFC 8447. For (asymmetric) signatures, you could use the 16-bit TLS SignatureScheme registry (https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-signaturescheme).

**Comment by jhoyla** [comment]
@DavidSchinazi Doesn't it define the algorithm `EdDSA` and then define the subkey types `Ed25519` and `Ed448` in [RFC 8037](https://www.rfc-editor.org/rfc/rfc8037.html#section-3.1)?

**Comment by DavidSchinazi** [comment]
@jhoyla that could be made to work though it's quite clunky since it requires a separate string parameter for "alg". Overall I think the [TLS SignatureScheme registry](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-signaturescheme) is a much better fit for signatures here. We already tightly integrate with TLS but not JWA. All that said, the closest option for hashes is the [TLS HashAlgorithms registry](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-18) and that's been orphaned by RFC 8447.

At this point I guess we should bite the bullet and define a new registry. Perhaps we include as current values:
* hmac-sha256
* hmac-sha384
* hmac-sha512
* signature-rsa_pkcs1_sha256
* signature-rsa_pkcs1_sha384
* signature-rsa_pkcs1_sha512
* signature-ecdsa_secp256r1_sha256
* signature-ecdsa_secp384r1_sha384
* signature-ecdsa_secp521r1_sha512
* signature-rsa_pss_rsae_sha256
* signature-rsa_pss_rsae_sha384
* signature-rsa_pss_rsae_sha512
* signature-rsa_pss_pss_sha256
* signature-rsa_pss_pss_sha384
* signature-rsa_pss_pss_sha512
* signature-ed25519
* signature-ed448

Of course this requires to paint the bikeshed one of two colors:
1. HMAC and Signatures in the same registry, using a single new auth scheme
2. Separate registries, using separate auth schemes

Thoughts? At this point I suspect this issue will need WG discussion at IETF 116.

**Comment by jhoyla** [comment]
I had to implement rsa_pss_pss_shaX algorithms to produce test vectors for DCs, and unless there's a really compelling reason to include them, I'd really rather not. They're just such a pain to use, and the support for them is very poor (thus me needing to implement them).

**Comment by DavidSchinazi** [comment]
FWIW, adding an entry in the registry doesn't mean it'll be mandatory to implement so there's not much of a cost. But I don't feel strongly about this one so I'm happy to not include it if it's the WG's preference.

**Comment by seanturner** [comment]
Just saying here's a registry that you might could co-opt:

https://datatracker.ietf.org/doc/rfc8122/

**Comment by jricher** [comment]
This is an existing registry of hash algorithms with string identifiers: https://www.iana.org/assignments/named-information/named-information.xhtml#hash-alg

**Comment by DavidSchinazi** [comment]
Discussed at IETF 116, sense of the room appeared to be that removing the HMAC feature entirely and switching to the TLS SignatureScheme registry for signatures was the simplest solution here.

**Comment by DavidSchinazi** [comment]
OK wrote up #2571 to address this
