### ISSUE TITLE
Unprompted Auth: Freshness & Signature Binding

### ISSUE THREAD

**Issue by dennisjackson** [httpwg/http-extensions#2490]
In the current draft, the header is composed as: 
```
{key_id}, {sig_alg}, {hash_alg}, {signature_over_nonce}
```
The server computes the nonce from the TLS key material exporter and verifies the signature. 

This doesn't actually guarantee freshness, because its possible for parties to construct signatures which are valid for any message/nonce. This means that a party which does not have access to the TLS Export material can still inject a valid Auth header. I don't think that's a major problem, but it is a bit unintuitive and its hard to predict how drafts like this will eventually get deployed. 

A simple fix would be in to add an additional parameter, say `v` which is `hash(seperator || nonce)` or similar and have servers check its been correctly computed. This ensures that only parties that can access TLS key material can inject valid headers. 

Behind the scenes, this attack / fix works because hash functions have to be collision resistant for all inputs, whereas signatures don't have to satisfy **any** properties if the associated public key was generated maliciously. [Seems Legit](https://dennis-jackson.uk/assets/pdfs/signatures.pdf) has a longer discussion.

**Comment by DavidSchinazi** [comment]
Thanks! This sounds like an easy fix. Instead of a hash, we could also generate more bytes from the key exporter and use some for the nonce and some for the `v` parameter

**Comment by DavidSchinazi** [comment]
Wrote up #2573 to fix this
