### ISSUE TITLE
Overwriting references (client-cert)

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#2495]
This is not good:

```
*** overwriting RFC9113
*** overwriting RFC9112
*** overwriting RFC9114
*** overwriting I-D.ietf-httpbis-message-signatures
```

**Comment by b---c** [comment]
Sorry, somehow didn't see this. There are reasons but they are unimportant.  

It's not good. But not so bad either. Regardless, PR #2579 should cleanup the messages.

**Comment by bc-pi** [comment]
ping

**Comment by b---c** [comment]
ping

**Comment by b---c** [comment]
Also FWIW this draft went into the RFC Editor's queue round about the time this issue was created  https://datatracker.ietf.org/doc/draft-ietf-httpbis-client-cert-field/history/
