### ISSUE TITLE
Mapped fields break pre-existing HTTP field blocklists and pass-through rules

### ISSUE THREAD

**Issue by davidben** [httpwg/http-extensions#2499]
Sorry for noticing this so late. I don't think the security considerations of [mapped fields](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#name-mapped-fields) in retrofit work out. (Also CC @mikewest who is much better at web security than me.)

If we introduce two ways to spell some field, we need to worry about whether this can allow various issues when sender and receiver don't agree on what's going on. The draft mostly leaves this to the future, but it does include some [text](https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#name-security-considerations) about this:

> Section 3 defines alternative representations of existing fields. Because downstream consumers might interpret the message differently based upon whether they recognise the alternative representation, implementations are prohibited from generating such fields unless they have negotiated support for them with their peer. This specification does not define such a mechanism, but any such definition needs to consider the implications of doing so carefully.

This seems to put the onus on the sender, not the receiver. If you don't know the receiver accepts the alternate representation, you can't send it. It includes no corresponding receiver obligation, I guess on the assumption that if you see SF-Cookie, you can assume the sender meant it?

I don't think that works. In a browser, the sender is a combination of browser logic (which has the final say) and JS (with a complex trust relationship). The browser logic specifies some [forbidden headers](https://fetch.spec.whatwg.org/#forbidden-request-header) which JS cannot set. Other HTTP systems have similar splits: an HTTP serving frontend may get fields from a CGI script or act as an intermediary, but it cannot allow the downstream code to specify fields like `Content-Length`. These rules typically look like a blocklist with the default behavior to pass fields through.

All this is to say, browsers won't let JS set the `Cookie` field directly, but setting `SF-Cookie` is perfectly fine, up to CORS rules. A receiver may see that text and incorrectly assume that processing `SF-Cookie` is fine, breaking some cookie invariants. Or `Referer` vs `SF-Referer`, which will break some sites' CSRF processing.

Beyond just blocklists, a retrofit-unaware HTTP cache that processes caching fields but passes through other fields will likely make a mess of the mapped caching fields.

#### Prefix with `Sec-`

If we prefixed the names with `Sec-`, that would at least meet the browsers' rules, though I worry it'll still break other intermediaries. It's also a little unsatisfying of a fix.

#### Require explicit negotiation on the receiver

We could say that a receiver cannot process these either unless it's received some explicit negotiation that the sender knows about this. That's vague and unspecified, but probably would work, depending on what the intent is here.

#### Don't introduce new field names

This is a bit handwaivy because I'm not sure what the use cases are here. But if we require explicit sender _and_ receiver negotiation, it's unclear what we're getting out the parallel field names in the first place. It seems to me that's where all this risk comes from. Giving alternate names interferes with pass-through logic across the pipeline.

Maybe we can get a more robust story, inspired a bit by [draft-nottingham-binary-structured-headers](https://www.ietf.org/archive/id/draft-nottingham-binary-structured-headers-03.html) (I'm just assuming this is one of the main use cases here) is to say:

- The text representation of `Cookie` is what it is. If this part of the system uses the text form, use the existing syntax
- The structured field representation of `Cookie` is this mapped thing. If this part of the system uses structured fields, use that syntax
- At boundaries where forms change, convert. We need to be a bit careful about fallibility here, but perhaps: Conversion from text to other forms is allowed to fail, since you can just fallback to the text form. Conversion from other forms to text probably needs to be stricter?
- The difference between mapped and normal fields is the structured field and text representations don't directly align, so they need to be treated a bit special

Like I said, this is handwaivy and definitely incomplete. But it feels to me like something in this might be more sound. It makes it more obvious we have to be sure what representation we're using at each layer and there's no risk of one side thinking something is a generic header and another thinking it's an alternative representation of a special header.

**Comment by davidben** [comment]
Main nuisance with `SF-` prefix is that, on the receiver side, you don't know a priori if the client is an updated browser, which knows about the `SF-` prefix, or a preexisting browser which does not. I suppose you could do UA sniffing, but let's not design a system that requires UA sniffing to work if we can help it! :-)

**Comment by mikewest** [comment]
That's fair. `Sec-SF-` would be safe without a change to Fetch. Still, given my expectations about the current deployment of mapped fields, I think we could reasonably get ahead of them in the browser world. Not at all sure about the rest of the ecosystem... 🤷

**Comment by MikeBishop** [comment]
I like the direction that if you've already negotiated support, you could just replace the legacy headers with their spiffy (SFfy?) new equivalents using the same names, and if you haven't negotiated support then you have no business sending these variants and expecting them to work. Of course, that means this draft probably can't get away with "We don't define a way to negotiate this, but you [OUGHT TO](https://www.rfc-editor.org/rfc/rfc6919#section-4) do that."

**Comment by davidben** [comment]
I think we'd avoid needing "OUGHT TO" in that model. That model is more explicit that these are two incompatible representations of these fields. The negotiation requirements become more straightforward, I think:

> Section 3 defines alternative representations of existing fields. These representations are incompatible with existing syntax and MUST NOT be used unless negotiated between sender and receiver. This documentation does not define such a negotiation mechanism, but any such definition MUST ensure which representation is in use at any time is unambiguous.

E.g. draft-nottingham-binary-structured-headers meets this requirement because you set a `BINARY_STRUCTURED` flag on the message, and gates usage on a setting. A hypothetical SF-based HTTP API would also meet this requirement because it's unambiguous that `SetHeader(name string, value StructuredField)` takes some in-memory structured field representation.

**Comment by mnot** [comment]
Hey David,

Yes, I've been somewhat concerned about the potential issues in this area for a while. Minting new field names for the alternative forms was the initial approach, but I was half expecting someone to raise this issue :)

One thing:

> I guess on the assumption that if you see SF-Cookie, you can assume the sender meant it?

No; the assumption is that a recipient sees SF-Cookie, they'll ignore it unless they've positively opted into it meaning something. Perhaps, as you point out, that should be more explicit -- e.g., say that these fields MUST NOT be processed unless the sender does [magic]. Making sure that evidence of [magic] is propagated properly may be tricky, though.

I could also see removing the new field names. That should work for many contexts, although I suspect it might make handling the new forms difficult in some.

Prefixing with `Sec-` doesn't seem very attractive to me.

**Comment by davidben** [comment]
> No; the assumption is that a recipient sees SF-Cookie, they'll ignore it unless they've positively opted into it meaning something. Perhaps, as you point out, that should be more explicit -- e.g., say that these fields MUST NOT be processed unless the sender does [magic]. Making sure that evidence of [magic] is propagated properly may be tricky, though.

Ah interesting. So I guess the middle option, "require explicit negotiation on the receiver" was actually the intended interpretation. That's not how I read the draft. It says "implementations are prohibited from generating such fields unless they have negotiated support for them with their peer" without saying anything about the recipient's responsibilities. So it sounds like, at minimum, we should update the draft.

Getting that right in the presence of a chain of intermediaries is quite subtle however. Suppose we go A -> B -> C and both B and C support mapped fields, but A does not. B must be careful not to forward along a mapped field from A. E.g. it might decline to advertise mapped field support to C because A doesn't support it. Or it might reject all mapped field names from A, on grounds that A cannot know what to do with it.

Moreover, "intermedaries" has to be intepreted very loosely. _Every_ processing step in the entire HTTP pipeline needs to carefully manage these alternate names. This seems a disaster waiting to happen.

> I could also see removing the new field names. That should work for many contexts, although I suspect it might make handling the new forms difficult in some.

I think I'm now convinced this is the only plausible option.

Regarding "many contexts" and "some", do you have use cases in mind here? I saw draft-nottingham-binary-structured-headers, but I gather there are others?

Something to keep in mind is that this draft intentionally punts figuring out the negotiation design to the future anyway. That means this is also the more flexible. If we define `SF-Cookie`, etc., now, we have permanently committed ourselves to this security problem. If we decline to define `SF-Cookie` now, we can still choose. We can always define the parallel field names later, should something that needs them come up. (Of course, I'd raise the security problem again, but it'll be easier to reason about with a concrete use case! 😄)

**Comment by davidben** [comment]
I guess this raises another question: how do we handle mapped field values that cannot be represented in the underlying text representation?

Given how many intermediaries and intermediary-like constructs are involved in HTTP process, and given how every HTTP API today uses the current syntax, I suspect mapped values that cannot be represented in the original syntax have to be treated as an error. Which means I think we need to go through the exercise of writing SF-to-text converters for each mapped field and then narrowing the allowed inputs until that converter is infallible.

**Comment by mnot** [comment]
It sounds like removing the field names is the best path forward. 

> I guess this raises another question: how do we handle mapped field values that cannot be represented in the underlying text representation?

Yes, for those, the application using retrofit needs a fallback, just as it does for compatible fields. If that isn't obvious from the document, it should be clarified -- perhaps in a new 'Using Retrofit Fields' section.

**Comment by kazuho** [comment]
I could very well be incorrect, but it sounds we want to have alternatives per each hop. Does that mean that these mappings would be best represented by ther per-hop pseudo headers that we have in H2 and H3?

Not that I feel that doing so would be the best option, though.

**Comment by davidben** [comment]
Ooh yeah, per-hop is a good way to think about this!

For pseudoheader vs. something else, I suspect it'll depend on use? draft-nottingham-binary-structured-headers already has a `BINARY_STRUCTURED` flag, so it probably could just use the original names, though pseudoheader names would work too I suppose. The existing names has the minor benefit of being able to reuse the existing HPACK static table.

Some sort of SF-based HTTP API like `func (f Fields) SetStructuredField(name string, value StructuredField)` probably (?) doesn't want pseudoheaders in the API and can just use the original names. But I haven't put much thought into that.

If one wanted to send them in their textual form in existing `HEADERS` frames, we probably need pseudoheaders. Though I don't know if we really get much value out of defining that, over just using the existing syntax. *shrug*

**Comment by martinthomson** [comment]
If you want to use an invalid field name, there are a lot more options than putting a ":" in the first byte.  You need to negotiate that usage, but then you can do anything at all, including using that to signal lots of stuff.  (If you want to avoid the extra byte, you can pack data into the high bit of each byte...)

**Comment by mnot** [comment]
I feel like punting is the right solution, unless we can come up with a convention that addresses the identified issues in all cases.

**Comment by martinthomson** [comment]
Not acting is a decision of a sort.  But I'm not sure what that would concretely mean for retrofit?  No `SF-` prefix?  Or just that we shouldn't worry yet about the effect this has on smuggling through WAFs and whatnot?

**Comment by mnot** [comment]
I think it means:

* No new header names; applications that use mapped fields need to define their own way to distinguish them
* A new section about these considerations
