### ISSUE TITLE
JSON mapping

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2504]
SF's data structures are somewhat weird, because of how HTTP fields work. It might be useful to suggest (not mandate) a mapping to JSON data structures, e.g., in an appendix.

We talked about what the right mapping should be in the 2022 HTTP Workshop, and this was what we ended up with on the whiteboard:

~~~
{
  "@type": "string",
  "@val": "foo",
  "a": 1,
  "b": 2
}
~~~

Note that `@type` could default to `string`.

**Comment by martinthomson** [comment]
Is this an appendix or a separate document?

**Comment by mnot** [comment]
I was thinking appendix.

**Comment by mnot** [comment]
After watching discussion go by on list, let's punt to a separate doc.
