### ISSUE TITLE
Digest compression example inflates payload

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2506]
@reschke reported on the list 

> draft-ietf-httpbis-digest-headers-11, "Appendix A. Resource Representation and Representation Data"

> Compression is an efficient way to reduce the content length.
> 
> But then, the example payload is indeed longer as in the previous example.
> 
> Maybe it would be good to use the same JSON payload in both examples, in
> order to avoid potential confusion? (Also, adding Content-Length might
> clarify things).

The way the test plays out is confusing and distracting. We don't really care whether the representation is smaller or not. The example should be succinct for understanding, changing the "plaintext" to something that compresses well is not going to improve comprehension IMO. 

I'll prepare an editorial PR to make this read better without changing the section significantly.

**Comment by ioggstream** [comment]
The point here is just to show how content-coding modifies the representation.
