### ISSUE TITLE
message-signatures: repetition in referencing HTMLURL

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2516]
""application/x-www-form-urlencoded" section of [[HTMLURL]](file:///C:/projects/xml2rfc/draft-ietf-httpbis-message-signatures-latest.html#HTMLURL)"

appears 4 times in a single section. Maybe name it once, and then just reuse that name.

**Comment by jricher** [comment]
Those are not all the same anchor/section, they should each stay to be more specific.
