### ISSUE TITLE
Digest: Section 6.4: Usage in Trailer Fields

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2526]
On the list, Rob Sayre asked:

> I'm a little confused by the last paragraph of Section 6.4: Usage in Trailer Fields.
> 
> > Not every hashing algorithm is suitable for use in the trailer section, some may
> > require to preprocess the whole content before sending a message (e.g., see [I-D.thomson-http-mice]).
> 
> Firstly, there's a small grammar problem with "require to...". But that's not my main concern.
> 
> Isn't the point of using a trailer to work around those algorithms that require processing all of the content?
> 
> For example, the code samples for Python's "hashlib" show SHA-256:
> https://docs.python.org/3/library/hashlib.html
> 
> Presumably, you'd call the update() method as you put bits on the wire, and then put the result of digest() in the trailer.
> 
> draft-thomson-http-mice-02 would seem to address issues with "eager processing" that the document covered in the previous paragraph.
> 
> Anyway, I think there's something to fix here, even if I am confused about the technical issue.

I agree it seems we can improve the text here a little.

Maybe @ioggstream or @martinthomson can elaborate as to why a digest trailer is not suitable in this case?

**Comment by martinthomson** [comment]
The reason is that in order to produce a MICE hash, you need to process the content in *reverse* order.  Therefore, there is no reason not to put the hash in the header.  The advantage you get in return is that you can process the response in natural order.

**Comment by LPardue** [comment]
Thanks martin. We should just say it that way, because it is clearer to the reader. I'll follow up with a PR.
