### ISSUE TITLE
Signatures: Wrong URI query normalization?

### ISSUE THREAD

**Issue by rogerk-unifysquare** [httpwg/http-extensions#2532]
The current draft (17) specifies in section 2.2.7 (Query) that the component value for the `@query` derived component
> is the entire normalized query string defined by [[URI](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-17.html#URI)], including the leading ? character".

[RFC 3986 in section 6.2.2.2 (Percent-Encoding Normalization)](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.2.2) specifies that (emphasis added)
> URIs should be normalized by _decoding any percent-encoded octet that corresponds to an unreserved character_, as described in [Section 2.3](https://www.rfc-editor.org/rfc/rfc3986#section-2.3).

And according to [that section 2.3](https://www.rfc-editor.org/rfc/rfc3986#section-2.3), the hyphen `-` is an _unreserved character_, which should therefore be decoded during normalization, right?

Yet, the first example in 2.2.7 does not appear to have that normalization applied to the value produced for `@query` for the signature base line, which is produced as
```
"@query": ?param=value&foo=bar&baz=bat%2Dman
```

instead of
```
"@query": ?param=value&foo=bar&baz=bat-man
```

Is this a bug?

(Note: I have not looked for other instances of this in the spec yet, but can report them as I find them on this issue's thread if desired)

**Comment by jricher** [comment]
There are different levels of normalization in the URI spec - the intent for the `@query` derived component is not to do the percent-encoding normalization. Section 2.2.7 already calls this out:

> The value is read using the simple string comparison rules in [Section 6.2.1](https://rfc-editor.org/rfc/rfc3986#section-6.2.1) of [[URI](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-17.html#URI)]. Namely, percent-encoded octets are not decoded.

**Comment by rogerk-unifysquare** [comment]
Thanks Justin. I got that, but section 6.2.1 of the URI RFC is talking about string _comparison_, which is not the use case here. The goal here is to produce a (reproducible) signature input, which should be _normalized_ like other components, such as `@authority`, `@scheme`, `@path`, or structured field values. In fact the second sentence of [2.2.7](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-17.html#section-2.2.7) is:

> The component value is the entire normalized query string defined by [[URI](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-17.html#URI)], including the leading ? character.

 Or in the words of the 4th paragraph of section [6.2.1 of URI](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.1) itself (**_emphasis_** added):

> False negatives are caused by the production and use of URI aliases. Unnecessary aliases can be reduced, regardless of the comparison method, by consistently providing URI references in an **_already-normalized_** form (i.e., a form identical to what would be produced after normalization is applied, as described below).

Then, the sections "below" (6.2.2 - 6.2.2.2) explicitly call out normalizations that should be applied. In particular section [6.2.2.2](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.2.2) calls for _decoding any percent-encoded octet that corresponds to an unreserved character_, of which the hyphen `-` is one.

That gets us back to the example from [2.2.7](https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-17.html#section-2.2.7), where the query of the request (in raw form) is `?param=value&foo=bar&baz=bat%2Dman`, but would need to be normalized to `?param=value&foo=bar&baz=bat-man`. Without the normalization, the `@query` produced would always be at the mercy of the HTTP stack that's used: some may pass the original URL, and some may apply normalization rules, making it impossible to reproduce correct signature input in every case. Thus, shouldn't the code producing or verifying signatures remove that variance?

**Comment by reschke** [comment]
That indeed seems to be a problem. Either we could document it (query can be fragile, but I guess the same is true for path), or we'd need to specify normalisation.

That said: some APIs provide access to the raw components (for instance, Java servlet).
