### ISSUE TITLE
sfbis: [STD63] reference

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2536]
STD63 (as opposed to RFC3629) does not have a DOI; it IMHO should be removed. (Apparently this was done in AUTH48 for 8941).

**Comment by mnot** [comment]
? I still see a STD63 ref at https://www.rfc-editor.org/rfc/rfc8941.html#section-7.2

**Comment by reschke** [comment]
The *DOI* should be removed; sorry for not being clear.
