### ISSUE TITLE
sfbis: is draft-ietf-httpbis-sfbis-02 up to date ?

### ISSUE THREAD

**Issue by Jxck** [httpwg/http-extensions#2539]
on sfbis-02

<img width="395" alt="image" src="https://github.com/httpwg/http-extensions/assets/322289/f9c7f440-c933-431b-8b97-85edd4f23cf2">

newly added line says "serialise" but on lates markdown says "serialize"

https://github.com/httpwg/http-extensions/blob/main/draft-ietf-httpbis-sfbis.md#serializing-a-date-ser-date

Is https://www.ietf.org/archive/id/draft-ietf-httpbis-sfbis-02.html really up-to-date ?

**Comment by LPardue** [comment]
You're comparing the live editor copy, which updates on every commit, to an IETF draft that is a snapshot back in time. The IETF draft is likely always trailing the editors copy.

**Comment by Jxck** [comment]
Ah I reviewed WGLC announced version but it's already updated after that as editor copy.
I'll waite for draft-03, thanks.
