### ISSUE TITLE
ABNF for sf-date

### ISSUE THREAD

**Issue by Jxck** [httpwg/http-extensions#2540]
according to "Parsing a Date"

https://github.com/httpwg/http-extensions/blob/main/draft-ietf-httpbis-sfbis.md#parsing-a-date-parse-date

> Let output_date be the result of running Parsing an Integer or Decimal ({{parse-number}}) with input_string.

align ABNF to this line, I think sf-date should be like below

```diff
- sf-date = "@" ["-"] 1*15DIGIT
+ sf-date = "@" sf-integer
```

**Comment by reschke** [comment]
Not convinced. It adds a level of indirection; that is, it makes the ABNF less readable.

**Comment by martinthomson** [comment]
Indirection means DRY, which edges out that sort of readability for me.

**Comment by LPardue** [comment]
I find the ANF confusing anyway. The prose says parse it as Integer or Decimal, then `If output_date is a Decimal, fail parsing. For a library that cares to differentiate between a parse failure due to bad characters vs bad types, then the ABNF would imply that you're not allowed to parse the Decimal type correctly?

**Comment by Jxck** [comment]
@LPardue IIUC, that's why this draft made ABNF as Appendix.
That caused since Algorithm has "Parse Number" returns Integer | Decimal, but not in ABNF.
What should be intends is just allow sf-integer, and in serialization point of view, it works fine.

**Comment by mnot** [comment]
I don't have particularly strong feelings about this; does anyone else?

**Comment by LPardue** [comment]
The ABNF already has layers upon layers of indirection. I think trying to avoid it for this field is inconsistent. So I'm sort of with MT that DRY wins out.
