### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#255]
We need to evaluate and possibly pare down / adjust the flags in the frame, based upon real-world use cases.

See Kazuho's evaluation:
  https://github.com/HTTPWorkshop/workshop2016/blob/master/talks/cache-digests.pdf

**Comment by kazuho** [comment]
I agree the need for evaluation. OTOH, I do not think we should pare down / adjust flags, since real-world use cases could change as time evolves.

The way it is defined now represents the cache state as-is and I believe that it would be most resilient in the long term.

**Comment by mnot** [comment]
OK.
