### ISSUE TITLE
Advice for ServiceWorker implementation

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#256]
Perhaps we should add an appendix to help people do this?

**Comment by cbas** [comment]
FYI/FWIW I've just implemented this spec via a service worker.

- NPM: https://www.npmjs.com/package/cache-digest-immutable
- Code: https://gitlab.com/sebdeckers/cache-digest-immutable

It would be nice if the spec clarified and defined the following. (I deduced it from @kazuho 's server and serviceworker implementations.)

- HTTP header is called `cache-digest`. This is a very handy alternative to the HTTP2 frame which service workers can't access currently.
- Base64 encoding must not be padded with `=` trailing.
- String equivalent of the `COMPLETE` (0x2) flag for the HTTP header is `complete` and appended as `... base64 ...; complete` (note the semicolon and white space)

Additionally more examples would be welcome, to aid implementors in validating their support. In particular the etags concatenation is unclear to me from the referenced spec.
