### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2567]
In 'Encoding special characters', you use a comma as an example of a character that needs to be encoded. 

However, because you specify it as an SF String, that's not the case -- commas are perfectly safe there.

Similarly, I'm a bit confused by "It is also possible for a DNS name to include a period character (".") within a label,
instead of as a label separator."

This escaping mechanism makes sense if you want to encode non-ASCII characters in the String; otherwise, what's the use case?

**Comment by bemasc** [comment]
A CNAME target can be any domain name.  A domain name is a sequence of labels, each of which is an arbitrary byte sequence.  You can think of the escaping section as an encoding scheme for `byte[][]` in ASCII.  In this spec, "." and "," are both used as separators (between labels within a name, and between names in a list), so we need a way to distinguish their use inside a label from their use as separators.

For example, the domain name consisting of the labels "ab.cd", "example" is valid and distinct from the domain name consisting of the labels "ab", "cd", "example".  The latter is conventionally rendered "ab.cd.example".  The most common convention to represent the former is backslash-escaping as described in this draft, resulting in "ab\\.cd.example".

**Comment by tfpauly** [comment]
Right, we have these cases because (a) a comma is used to separate out the domains in this list within the string and (b) there's a nasty edge case with labels that contain dots themselves.

@mnot see https://github.com/httpwg/http-extensions/issues/2486

Do you have anything you think needs to concretely change?

**Comment by mnot** [comment]
Are you trying to accommodate URI schemes that doesn't use the DNS for registered names?

**Comment by tfpauly** [comment]
No, the URIs should only be DNS. But CNAMES/aliases don’t conform to the same rules are dns names that can be put into URIs as hostnames. They’re more loose (unfortunately).

**Comment by mnot** [comment]
Odd, but ok.
