### ISSUE TITLE
DisplayString pick-your-own-escaping is an invitation for smuggling attacks

### ISSUE THREAD

**Issue by bsdphk** [httpwg/http-extensions#2575]
As currently defined, the two serialized DisplayStrings

    %"foo\"bla%22bar"

and

    %"foo%22bla\"bar"

are semantically identical.

We should either use %-escapes or \\-escapes, mixing them this way is asking for smuggling-attacks.

**Comment by mnot** [comment]
I think probably `%`-escapes; will work up a PR.

**Comment by reschke** [comment]
Sounds good to me.
