### ISSUE TITLE
Decide whether to keep structured fields or not

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2581]
> These parameters use structured fields in their definition, even though the Authorization field itself does not use structured fields.

This nags at me a bit. I think you want to be crystal clear are what parts of Stuctured Fields you are and what you aren't. 

As far as I see, you want to use the `bare-item` aspect in order to reuse the serialization/deserialization, legal characters, legal range, etc., for the auth parameter values. But you don't need the `Item` aspect, which would allow you to parameterise the parameters. Does that sound accurate?

**Comment by DavidSchinazi** [comment]
We added this sentence based on a https://github.com/httpwg/http-extensions/pull/2571#discussion_r1242981431 from @martinthomson. Martin, do you have thoughts here? I think the intent was just to point out that we're in the new structured fields world even though Authorization hasn't been retrofitted yet

**Comment by DavidSchinazi** [comment]
In #2580, @LPardue pointed out that we can't simply use byte sequences from structured fields because authentication parameter values need to be `( token / quoted-string )` which doesn't allow non-quoted colons. So I switched to double-quotes in dcc520544cf98cf634c9ca0a24119256fd18d58e, but that makes the usage of structured fields somewhat messy. Thoughts?

**Comment by LPardue** [comment]
Copying my comment from the change

> I know this is merged but I was thinking if you want these to be SF bytestrings on the wire, you keep the colons as well e.g. ":dmVyaWZpY2F0aW9uXzE2Qg==:". That way, a parser can remove the Authorization encapsulation (dequote) and then feed the bytes into an SF parser directly

**Comment by DavidSchinazi** [comment]
Good call. I now added both colons and double-quotes via 690ee072bb450ab631db5b32a23b457cec9bb6be

**Comment by LPardue** [comment]
I could live without structured fields here, presumably there are servers that already have to handle Authorization fields using the more-traditional encodings

**Comment by DavidSchinazi** [comment]
I'll note however that if we go with `base64url` we'll need to either double-quote it or explicitly ban padding, because `=` is not allowed as part of `token`

**Comment by martinthomson** [comment]
While base64 proper is often padded, it is more common for base64url to be unpadded (indeed, I think that the string "base64url" specifically refers to the unpadded version if you follow it to its origin, which I think is https://datatracker.ietf.org/doc/html/rfc7515#section-2).

**Comment by DavidSchinazi** [comment]
`base64url` dates back at least as far as [RFC4648 s5](https://datatracker.ietf.org/doc/html/rfc4648#section-5) and that spec explicitly [states](https://datatracker.ietf.org/doc/html/rfc4648#section-3.2):
> Implementations MUST include appropriate pad characters at the end of encoded data unless the specification referring to this document explicitly states otherwise.

None of which is a problem, we just need to be explicit. We know how to do that.

**Comment by martinthomson** [comment]
Right, the 7515 thing was what we ended up using in another context, where padding was explicitly not included.  Clearly, we shouldn't use it here either[^1].

[^1]: I hold the view that it shouldn't be used in any situation, because if knowing the length is important, you would have a length prefix or delimiter, rendering padding pointless for anything other than protection against traffic analysis.  And you can't arbitrarily pad with base64 padding, so that's no good.

**Comment by tfpauly** [comment]
I'd ideally want to align with draft-ietf-privacypass-auth-scheme. We reviewed this a lot with @reschke and went back and forth and ended up with:

> When used for client authorization, the "PrivateToken" authentication scheme defines one parameter, "token", which contains the base64url-encoded Token struct. Since the length of the Token struct is not fixed, the base64url value MUST include padding. As an Authentication Parameter (auth-param from [[RFC9110](https://www.ietf.org/archive/id/draft-ietf-privacypass-auth-scheme-11.html#RFC9110)], [Section 11.2](https://rfc-editor.org/rfc/rfc9110#section-11.2)), the value can be either a token or a quoted-string, and might be required to be a quoted-string if the base64url string includes "=" characters. All unknown or unsupported parameters to "PrivateToken" authentication credentials MUST be ignored.

So from a syntax standpoint, this is "base64url and you don't need quotes, but do include quotes if you have padding". If you define that you don't use padding, then you don't need quotes.

So I think things can be consistent here.

**Comment by DavidSchinazi** [comment]
Based on the conversation in the room at IETF 117, I'm inclined to make these no longer structured headers, and to use base64url without padding, without quotes, and without colons.
