### ISSUE TITLE
Editorial: summarize how the auth scheme interacts and uses parameters earlier on

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2582]
Section 2 gives an overview of the Signature Authentication scheme but doesn't really speak about how the information is exchanged over the wire. Instead Section 3 leaps to crypto stuff and then Section 4 just states there are parameters, leaving some interpretation of the exchange to rely on the example in Section 5. It would be nice to add a little exposition about how the pieces tie together earlier on.

**Comment by DavidSchinazi** [comment]
Agreed, will do!
