### ISSUE TITLE
Multi-version support for Upload-Draft-Interop-Version

### ISSUE THREAD

**Issue by jrflat** [httpwg/http-extensions#2597]
Currently, the client advertises which version it supports (e.g. `Upload-Draft-Interop-Version: 3`), and the server advertises resumable uploads if it supports that version.

As the draft evolves and introduces new values for the interop header field, clients that update to the new version lose resumable upload capabilities with a server that hasn't updated. Maybe we could define a way to advertise multiple versions to make this transition smoother.

One idea is the client could provide a list of versions it supports (e.g. `Upload-Draft-Interop-Version: 3,4`), and the server could choose one of these versions to advertise in the `104` response. However, this might not work if there's a breaking change in the discovery mechanism. For instance, if version 3 uses `Upload-Incomplete` and version 4 uses `Upload-Complete`, there's a discrepancy (we could send both?).

Regardless, would we be interested in solving this multi-version issue? Does anyone have insight or experience with draft versioning like this? Thanks!

**Comment by LPardue** [comment]
It's a good question. I think the outcome will depend how how closely the implementers are working together and how responsive they can be to change.

There's a temptation to make a complex solution for something that is not intended to be shipped in the RFC. We should try to keep things simple if we can.

**Comment by Acconut** [comment]
During IETF 117, we concluded that this is probably not necessary since it will only be valid while this is a draft and would make implementation not complex. I don't think we need/want this right now. Do you agree, @jrflat? If so, we could close this.

**Comment by jrflat** [comment]
@Acconut Yeah I think we can close this and re-evaluate in the future if we need to.
