### ISSUE TITLE
QUERY Method Status

### ISSUE THREAD

**Issue by Frizlab** [httpwg/http-extensions#2611]
I’m considering using QUERY in my API; is there a chance it becomes a standard at some point in the future or should I go with something else?
I haven’t seen much development regarding this method in some time now.

**Comment by mnot** [comment]
We believe work will start on it again soon; see our most recent meeting minutes. 

Please dont' ask questions in issues; the best place for that is in the mailing list.

**Comment by Frizlab** [comment]
Thanks for answering; will do if I have other questions.
