### ISSUE TITLE
Specification style - procedures vs artefacts

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2616]
Currently, the resumable specification is defined in terms of four 'procedures'. That's a bit unusual for HTTP specifications; usually we talk about artefacts (on-the-wire or more ephemeral, like resources). That allows for unintended reuse, and also tends to be more robust when the specification needs to evolve.

For example, the spec could introduce something like an 'upload management resource', and then define how to interact with them.

I hesitate to raise this, because it might require non-trivial editorial changes (but not any signficant technical changes). However, I think it might lead to a better spec.

Is there interest in this? If so, I'm willing to do a PR to illustrate what it might look like.

**Comment by Acconut** [comment]
Thanks for bringing this up. It would be great if you could make a PR with the first steps.

**Comment by mnot** [comment]
I'll try to get something into a PR soon.

**Comment by LPardue** [comment]
Closed since we merged #2617
