### ISSUE TITLE
Require Display Strings % encoding to be serialised in lowercase

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2618]
It's annoying to test for otherwise. Still allow both cases in parse.

**Comment by duerst** [comment]
Postel's law ("Be liberal in what you accept, and conservative in what you send.") isn't as popular these days as it once was. Not sure we need to accept upper case % anymore.

**Comment by martinthomson** [comment]
I am sure that we don’t.

(Though I have thoughts on the use of the Robustness Principle to guide this sort of decision. Generally, it is better to look at what the case needs. Here, the values are created by code, so permissiveness is not a valuable feature.)

**Comment by mnot** [comment]
Fine. See https://github.com/httpwg/http-extensions/pull/2619
