### ISSUE TITLE
ABNF issues

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#2620]
In the current ABNF, Display Strings are built upon:

~~~ abnf
uchr             = chr / uescaped
~~~

However, `chr` is:

~~~ abnf
chr       = unescaped / escaped
~~~

I think it would be better to remove the `chr` and `uchr` abstractions and just put the alternations directly in `sf-string` and `sf-displaystring`. 

It'd probably also be good to change `escaped` to `backslash-escaped` and `uescaped` (which is super confusing) to `percent-escaped`.

Also, `\` (`%x5C`) _is_ allowed in display strings.

And HEXDIG is not case sensitive.

Yes, I've been using a fuzzer.

**Comment by mnot** [comment]
Also, this looks wrong:

~~~ abnf
dict-member   = member-key ( parameters / ( "=" member-value ))
~~~

but it's actually correct; there are either bare parameters (because the value defaults to true, but still can carry paramters), or the member-value can carry its own parameters.

Can we do anything to clarify this in the abnf?

**Comment by reschke** [comment]
FWFW, why does sf-dictionary require at least one dict-member, but the prose says it's "zero or more"?

**Comment by mnot** [comment]
I think you mean

~~~ abnf
sf-dictionary  = [ dict-member ] *( OWS "," OWS dict-member )
~~~

... but that won't work, as it would allow a field value starting with `OWS ","`.

IIRC we specified it this way due to the limits of ABNF (per above) and because the first step of the serialisation algorithm is

> If the structure is a Dictionary or List and its value is empty (i.e., it has no members), do not serialize the field at all (i.e., omit both the field-name and field-value).[¶](https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#section-4.1-2.1).

**Comment by reschke** [comment]
a) Right.

b) That is true, but it's still jarring that the ABNF requires a member whereas the prose says something else. The parsing algorithm IMHO accepts an empty string and will produce an empty dictionary.

**Comment by reschke** [comment]
So if we wanted the ABNF to reflect that, we could write:

~~~ abnf
dict-member   = [ member-key ( parameters / ( "=" member-value )) ]
~~~

**Comment by reschke** [comment]
> Also, this looks wrong:
> 
> ```abnf
> dict-member   = member-key ( parameters / ( "=" member-value ))
> ```
> 
> but it's actually correct; there are either bare parameters (because the value defaults to true, but still can carry paramters), or the member-value can carry its own parameters.
> 
> Can we do anything to clarify this in the abnf?

That's still open, no?
