### ISSUE TITLE
ABNF sf-dictionary and sf-list do not allow empty lists

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2623]
...which are disallowed in serialization (as fields), but allowed in prose and in parsing.

**Comment by reschke** [comment]
Proposal:

~~~ abnf
sf-dictionary  = [ dict-member *( OWS "," OWS dict-member ) ]
~~~

**Comment by martinthomson** [comment]
Does this apply to `sf-list` as well?

**Comment by reschke** [comment]
Yes, it does.

**Comment by mnot** [comment]
As discussed elsewhere (somewhere; maybe last time around?), the ABNF is used to

> illustrate expected syntax of Structured Fields

Given that the first step of [Serializing Structured Fields](https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#name-serializing-structured-fiel) is:

> 1. If the structure is a Dictionary or List and its value is empty (i.e., it has no members), do not serialize the field at all (i.e., omit both the field-name and field-value).

This _is_ the "expected syntax."

**Comment by martinthomson** [comment]
That's a pretty fine distinction to draw, but I think that this is mostly OK in that case.

These look problematic in that case:  "[No structured data has been found; return members (which is empty).](https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#section-4.2.1-2.3.1)" and "[No structured data has been found; return dictionary (which is empty).](https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#section-4.2.2-2.3.1)"

My view is that this is an error condition instead.  I don't recall a decision to be tolerant of this particular deviation from the serialization process.

**Comment by mnot** [comment]
I don't see that as an error condition at all -- an empty structure is valid, but the correct way to serialise that in HTTP/1.1 is to omit the field.

**Comment by martinthomson** [comment]
Are you saying that because the current definition does allow for variant serializations in some cases, this is just another case where the serialization is stricter than the parsing?

Maybe that ship has sailed already, but I can't see any good thing to come from empty fields.

**Comment by mnot** [comment]
I'm confused by your statement, that's not where I was going. However, I agree regarding _no good from empty fields_ -- which is why the ABNF shouldn't include them.

**Comment by martinthomson** [comment]
Oh, I moved on, sorry.  I'm talking about the parsing being lenient about empty fields (for list and dictionary).  It doesn't need to be.  In which case the ABNF question resolves itself cleanly.

**Comment by mnot** [comment]
Ah, I see. Yes, I suspect the ship has sailed.

**Comment by mnot** [comment]
I think we can close this issue - any more discussion?
