### ISSUE TITLE
# Document title, URLs, estimated publication date

### ISSUE THREAD

**Issue by bandrqaid654** [httpwg/http-extensions#2627]
# Document title, URLs, estimated publication date

* Generic Sensor API - https://xfq.github.io/testing/generic-sensor-CR/Overview.html
* Accelerometer - https://xfq.github.io/testing/accelerometer-CR/Overview.html
* Gyroscope - https://xfq.github.io/testing/gyroscope-CR/Overview.html
* Orientation Sensor - https://xfq.github.io/testing/orientation-sensor-CR/Overview.html

# Abstract

* Generic Sensor API: https://xfq.github.io/testing/generic-sensor-CR/Overview.html#abstract
* Accelerometer: https://xfq.github.io/testing/accelerometer-CR/Overview.html#abstract
* Gyroscope: https://xfq.github.io/testing/gyroscope-CR/Overview.html#abstract
* Orientation Sensor: https://xfq.github.io/testing/orientation-sensor-CR/Overview.html#abstract

# Status

* Generic Sensor API - https://xfq.github.io/testing/generic-sensor-CR/Overview.html#sotd
* Accelerometer - https://xfq.github.io/testing/accelerometer-CR/Overview.html#sotd
* Gyroscope - https://xfq.github.io/testing/gyroscope-CR/Overview.html#sotd
* Orientation Sensor - https://xfq.github.io/testing/orientation-sensor-CR/Overview.html#sotd

The CR exit criterion is two interoperable deployed implementations of each feature.

# Link to group's decision to request transition

https://www.w3.org/2019/09/19-dap-minutes.html#x06

# Changes

The only substantial change since the last CR is the the addition of WebDriver extensions:

* Generic Sensor API: https://xfq.github.io/testing/generic-sensor-CR/Overview.html#automation
* Accelerometer: https://xfq.github.io/testing/accelerometer-CR/Overview.html#automation
* Gyroscope: https://xfq.github.io/testing/gyroscope-CR/Overview.html#automation
* Orientation Sensor: https://xfq.github.io/testing/orientation-sensor-CR/Overview.html#automation

# Requirements satisfied

The specifications meet the requirements set forth in the DAS WG Charter and satisfy [Sensor Use Cases](https://w3c.github.io/sensors/usecases) as demonstrated in [Motion Sensors Explainer](https://w3c.github.io/motion-sensors/).

# Dependencies met (or not)

New normative references since the last CR:

* Generic Sensor API: `[ACCELEROMETER]` `[AMBIENT-LIGHT]` `[GEOLOCATION-SENSOR]` `[GYROSCOPE]` `[MAGNETOMETER]` `[MAGNETOMETER]` `[WebDriver]`
* Accelerometer: none
* Gyroscope: none
* Orientation Sensor: none

# Wide Review

The specifications have received wide review: https://github.com/w3c/sensors/issues/299

# Issues addressed

No open issue for this version ("Level 1").

# Formal Objections

None.

# Implementation

Preliminary implementation reports:

* Generic Sensor API: n/a (an abstract base class)
* Accelerometer: https://wpt.fyi/accelerometer
* Gyroscope: https://wpt.fyi/gyroscope
* Orientation Sensor: https://wpt.fyi/orientation-sensor

# Patent disclosures

https://www.w3.org/2004/01/pp-impl/43696/status

None.

-----

/cc @anssiko @reillyeon

_Originally posted by @xfq in https://github.com/w3c/transitions/issues/189_

**Comment by tfpauly** [comment]
Was this added to this repo by accident @bandrqaid654 ? This is the repository for IETF documents in the HTTPBIS working group.
