### ISSUE TITLE
Client hints: add support for hinting Display Gamut / Color Profile

### ISSUE THREAD

**Issue by gunta** [httpwg/http-extensions#263]
Add Client hints support for the following:

`Viewport-Color-Gamut`
https://drafts.csswg.org/mediaqueries-4/#color-gamut

`Viewport-Color-Profile`
https://www.w3.org/TR/css-color-4/#at-ruledef-profile

**Comment by reschke** [comment]
The spec is past WGLC, so adding new hints right now might be bad timing.

**Comment by igrigorik** [comment]
@gunta can you elaborate on the use cases and motivation for sending this data as a request header?

**Comment by gunta** [comment]
@igrigorik Yes, definitely.

The reason for this request is that recently, there has been a huge market increase in Displays that are non-sRGB (In particular DCI-P3 and AdobeRGB displays).

As an example: iPhone 7, Galaxy S7, MacBook Pro, Surface Studio, all of them support DCI-P3 wide color.

However since the **color-gamut** it’s a display thing the only way to detect for `wide-color` support from server side would be `Client Hints` since its not even possible with `UA-sniffing`.

The motivation behind is, we are building an image optimisation service for Automating Resource Selection, based on DPR, supported file format, and display wide color support, among other variables.

For example, [Apple is recommending now](http://devstreaming.apple.com/videos/wwdc/2016/712ugi7vg8jznn3pc3u/712/712_working_with_wide_color.pdf) to create 2 separate assets for Normal and Wide Color images, as in Retina vs. Non-Retina images.

> The best solution is to serve a wide-gamut image when the user is on a wide-gamut display, and an `sRGB` image when the user is not on a `wide-gamut` display. This is just another case of responsive images, and is exactly what the element and media queries were designed to handle.

This is also why [Safari has added `color-gamut` media query](https://webkit.org/blog/6682/improving-color-on-the-web/) to `CSS Color Level 4`.


So the reason of making this as a `Request Header` is exactly the same logic to `DPR`: 
We should send this info between Browser and Server, so the developer doesn't have to do it by hand, solving the problem more elegantly.


### Current Problem
```html
<picture>
  <source media="(color-gamut: p3)" srcset="photo-wide.jpg">
  <img src="photo-srgb.jpg">
</picture>
```

### Proposed Solution
```html
<picture>
  <img src="photo.jpg">
</picture>
```

**Browser Request Header**
```yml
Color-Gamut: p3
```
**Server response**
```yml
HTTP/1.1 200 OK
Content-Color-Gamut: p3
```

**Result: Server returns a `8 bit sRGB` or `16 bit Display wide-color` image in a responsive way**

The core use case behind `Color-Gamut` hint is to enable automatic resource selection for image assets based on display type. This will enable delivery of optimal image variant without any changes in markup.

**Comment by igrigorik** [comment]
@gunta thanks, this is really helpful. Also, take this with a grain of salt, but some [polling numbers](https://twitter.com/igrigorik/status/799304405396824064)...

![image](https://cloud.githubusercontent.com/assets/10652/20449131/63713528-ad9c-11e6-9851-5e4d395a24fc.png)

To be honest, the number of deployed+roadmap responses is much higher than I would have guessed! Stepping back, I think this does make sense to provide in CH; it's consistent with other image specific variables that affect which response should be served, and automation is definitely warranted here.

- `Color-Gamut` + `Content-Color-Gamut`: I think this makes sense.
- `@color-profile`.. I'm still trying to grok. From what I can tell right now, it accepts a URL to a profile, plus a rendering intent. Do we have some concrete examples of how we expect developers to use this?

> The spec is past WGLC, so adding new hints right now might be bad timing.

Does this prevent us from publishing a new "replacement" draft? How do we advance these things forward?

**Comment by reschke** [comment]
> Does this prevent us from publishing a new "replacement" draft? How do we advance these things forward? 

The draft was supposed to go to IETF LC next. If you want to put in new stuff, you can do that (after negotiating with the WG), but then it'll require a new Working Group Last Call.

**Comment by gunta** [comment]
@igrigorik Exactly. 
Still the poll numbers are not high but we can expect them to go wild next year since most manufactured displays are now wide-color. We can expect something alike to the Retina/Non-Retina race revolution. 

> Color-Gamut + Content-Color-Gamut: I think this makes sense.

Yes, this would cover 95% of use cases, and spec-wise it should be simple enough. 

So, even for simple cases, this CH spec addition is close to a `MUST` for responsive color optimisation. Why? Because `wide-gamut` is one of things those things that cannot even be guessed by *User Agent*: there is no info about the display on the string. So this spec is gonna be the only way to advertise to the server in an automated way.

> @color-profile.. I'm still trying to grok. From what I can tell right now, it accepts a URL to a profile, plus a rendering intent. Do we have some concrete examples of how we expect developers to use this?
Yes, I agree the use cases for `color-profile` are few, thus I don't see this one as `MUST`, however a `nice to have` one.

The use cases I see for this are minor but:
1) To override a photo ICC profile (ie. it was wrong in the first place)
2) To specify a ICC profile for a photo that had ICC stripped - or didn't had one in the first place (ie. it was removed by some "optimisation" tool like [jpegoptim](http://www.kokkonen.net/tjko/src/man/jpegoptim.txt) or [ImageOptim](https://imageoptim.com/color-profiles.html))

So yeah I can guess mostly photographer / design websites would make use of this one.
Note that, at least [CSS Level 4](https://www.w3.org/TR/css-color-4/#at-ruledef-profile), doesn't need to include the URL for the profile since its predefined in two cases: `DCI-P3` and `Rec.2020`.

> Does this prevent us from publishing a new "replacement" draft? How do we advance these things forward?

I don't know about this *WG particular timing interests*,
however having `Color-Gamut + Content-Color-Gamut` in the spec as soon as possible would give Browser vendors enough time and pave the way to implement it smoothly. 
Be either an addition to CH or a different spec. For **consistency** it makes sense to be a part of the CH spec though, just like `DPR`.

I can understand well why some don't see the *urge for it*: 
you need to have a `wide-color` hardware first to *see* the need, 
but we can be sure that almost **any smartphone or computer display that you get in 2017 is gonna be a `wide-color` one**.

**Comment by igrigorik** [comment]
@gunta thanks for the context, once again. I agree that these are high value targets worth pursuing.. 

Based on discussion on http-wg, it sounds like a separate draft is the best way forward. Would you be up for driving that work? I can assist if/where needed.

**Comment by mnot** [comment]
Just to be clear -- there's no guarantee that the WG will adopt such a document; it depends on getting consensus to adopt, which in turn often depends on implementer interest. That's not to dissuade you from writing a document; however, the next logical step would be to engage with implementers (probably, Chrome) to see if they want to support it, not to create a standard in hopes of getting it implemented.

**Comment by grorg** [comment]
I have no opinion on the client hint proposal, but I'll comment on the poll.

I expect commerce sites to be the first to care about accurate color. They'll want to make sure they show you a picture of the bright red shoes that matches what will turn up on the doorstep. Then I predict art/photography etc content. And before long, so many people will have extended displays that designers will just want their content to look more awesome.

Also, it's not the kind of thing you care about until you see the improvement in person. It would be interesting to see the poll result in 12-24 months.

(Note that while Apple has done the work to support extended colors in WebKit, we're still missing pieces. Implementing it within other browsers might take more effort. Last time I checked they didn't even color match to sRGB.)

**Comment by njdoyle** [comment]
I'm a little fuzzy on some of the implications of `Content-Color-Gamut`. While I definitely see the savings that can be had by being able to specify a pre-understood named colour profile (or some reusable cached ICC profile) instead of embedding the profile in its entirety in each image, I feel a little uncomfortable about the separation of the image asset from instructions that are absolutely necessary for rendering it.

What this means is that information that is necessary for rendering the image will be in HTTP headers instead of the image content itself. If you save that image, it will essentially be incomplete (unless the browser rewrites the data or something).

In a perfect world, I would have common colour profiles be available in some shorthand in the image file itself. Basically just like the sRGB chunk in PNG just generalized for other common colour profiles. I feel that HTTP headers aren't the right place to solve this problem.

**Comment by njdoyle** [comment]
Just to clarify, because there may have been some confusion:

Of the two headers, I am okay with `Color-Gamut` (when the client sends the server the gamut of the client's display). My previous comment is referring to `Content-Color-Gamut` where the server sends the gamut of an image to the client as an HTTP header. I feel like this information is necessary to rendering an image and should be included in image data and not as an HTTP header. Rendering the image without this information is impossible to do correctly.

**Comment by colinbendell** [comment]
This is probably implicit in the discussion, but for posterity I want to enumerate the decision matrix that `Color-Gamut` would help address:
* Maximize the experience: A server has 10bit/channel images and client can display wide gamut (aka serve P3 to P3)
    * If client supports jp2/jpegxr then use; 
    * If bandwidth permits, use png. 
    * Otherwise reduce color space to 8bit/channel and add p3 icc and serve webp/jpg.
* Preserve the experience: A server has 10bit/channel images but client is only sRGB. Sending P3 to sRGB has poor effects and will result in banding and clamping therefore we want to reduce to 8bit/channel, color correcting to sRGB.
* Balance experience and performance: A server wants to reduce bytes by stripping icc metadata. BUT doing this today has inconsistent experiences with different browsers. Notably, browsers that incorrectly assume the attached display is also sRGB and don't color correct (Chrome/FF). The very presence of this CH is a legacy v. modern color-correcting indicator. (this is assuming that [667431](https://bugs.chromium.org/p/chromium/issues/detail?id=667431) ships ahead of CH)

**Comment by igrigorik** [comment]
@colinbendell @njdoyle thanks a lot for the great feedback.

To echo @mnot's suggestion: 
 - formalize above use cases and rough proposal via an ~explainer doc
 - publish explainer on WICG, engage vendors in discussion
 - ... 
 - write down spec once we have implementation's underway

@gunta @colinbendell @njdoyle perhaps something you could drive/own together?

**Comment by mnot** [comment]
I'm going to close this, as we're going to ship CH without this hint, but please do continue to discuss (here if necessary to coordinate).

**Comment by gunta** [comment]
@igrigorik I'll try to formalize the use cases I have at the current project I'm working in which is a Responsive Images as Service.
