### ISSUE TITLE
Should not use Content-encoding - Raised by Roy T. Fielding

### ISSUE THREAD

**Issue by pmeenan** [httpwg/http-extensions#2635]
I think implementation of such through content-codings is fundamentally misguided because it changes the resource itself and impacts all caching along the chain of requests in ways that are non-recoverable. That is due to the lost metadata and variance on whatever request field is used to indicate that some downstream client can grok some possible dictionary.

In short, it looks like an easy solution for a browser, but will wreak havoc with the larger architecture of the Web.

The right way to do this is to implement it as a transfer encoding that can be decoded without loss or confusion with the unencoded resource, which would require extending h2 and h3 to support that feature of HTTP/1.1.

[Original listserv response](https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0130.html)
cc @royfielding 

Moved from private ID [issue #6](https://github.com/pmeenan/i-d-compression-dictionary/issues/6)

**Comment by pmeenan** [comment]
The decoded version of the resource is unchanged. It's not fundamentally different than brotli which happens to include a default dictionary and the caching is guaranteed to be maintained in a consistent way as long as "Vary" works on "Accept-Encoding" as well as whatever header negotiates the dictionary.

Even without the dictionary, if something in the middle doesn't know how to process one of the content-encodings (and needs to be able to access the content) then the accept-encoding should be modified to only include encodings that it knows how to work with.

This isn't really notably different than "br" or "zstd".

Moving the compression down into the transport layer is what we tried before but failed to navigate the browser security issues because the transport layer doesn't have the context of which responses need to be opaque, which responses are partitioned across document or frame boundaries, etc and that the dictionary compression could be used to perform oracle attacks across those boundaries.

[listserv response](https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0131.html)

**Comment by pmeenan** [comment]
@royfielding if the response includes the hash of the dictionary that was used for the compression so that the response is self-contained and independent of the request, would that address your concerns?

That is being discussed in #2636 and would allow for other ways of negotiating dictionaries (but would require a new header to identify the used dictionary).

**Comment by pmeenan** [comment]
For the scale of improvement (for the resources impacted), we see results that are 60-90% smaller than brotli which is orders of magnitude bigger than we get from deflate -> brotli (for example). A few bytes added to headers or elsewhere aren't going to make a difference and, honestly, if it does then those resources are probably not appropriate for dictionary compression in the first place.

## Variants
As far as the variants, we added the `ttl` param to minimize the number of different dictionaries that will be in the wild at a time and recommend that it be adjusted based on release cadance of the dictionaries but it currently defaults to 1 year. We could go the other way and default to a short ttl (say, 7 days) and require origins to be explicit if they want longer-lived dictionaries.

The variants introduced by the encodings themselves should only be present when a matching dictionary is provided (e.g. `br-d` would not be advertised unless there is also an `Available-Dictionary`). The main cause of variants that they would introduce would be from clients supporting a different set of encodings or ordering them differently (as they do today).

We could improve that situation by requiring that the encodings be in alphabetical order when dictionaries are being used which would help get cross-client consistency in the accept-encoding header. It would still vary by the encodings supported by the clients but the new dictionary encodings wouldn't add any permutations. We could also require that the base encoding be present if the dictionary variant is present (`br-d` requires that `br` also be supported).

## Encoding
The encoding itself has a few different deployment models that also favor using Content-Encoding over Transfer-Encoding.  In the dynamic compression case where the edge is doing the compression, it doesn't make much difference between the two from a complexity or performance perspective (though there are HTTP/2 and HTTP/3 complexities around transfer-encoding).

The more interesting case for the Content-Encoding side is when the compression is done at build/publish time. The static artifacts (css, js, wasm) can be compressed using previous releases as dictionaries and stored on-disk as dictionary-compressed artifacts with the hash as part of the file name. At serving time, it can be a quick lookup at the origin to see if the asset is available with the `Available-Dictionary` hash as part of the file name and fall-back to the full file if it isn't. This eliminates the compression from the serving flow and largely just requires cache support (as long as the boxes along the path aren't trying to inspect the contents).

**Comment by royfielding** [comment]
> We could improve that situation by requiring that the encodings be in alphabetical order when dictionaries are being used which would help get cross-client consistency in the accept-encoding header. It would still vary by the encodings supported by the clients but the new dictionary encodings wouldn't add any permutations. We could also require that the base encoding be present if the dictionary variant is present (`br-d` requires that `br` also be supported).
> ##

What about leaving the Accept-Encoding as the base encoding and defining Available-Dictionary as implying br-d if br is present for A-E? A response that used br-d would Vary on A-E and Available-Dictionary, whereas a response that used the standard dictionary would only need to Vary on A-E.

**Comment by royfielding** [comment]
I should add many of the worrisome questions don't matter for content > 10MB (or so) because they would be evicted too fast, so a custom dictionary is going to be a huge benefit for those resources, regardless of variance.

**Comment by pmeenan** [comment]
> What about leaving the Accept-Encoding as the base encoding and defining Available-Dictionary as implying br-d if br is present for A-E? A response that used br-d would Vary on A-E and Available-Dictionary, whereas a response that used the standard dictionary would only need to Vary on A-E.

If A-E only had the base encodings then an Available-Dictionary request would match a cached standard dictionary response that had only varied on A-E.  By having the dictionary-specific encodings on A-E then it will require the dictionary compression be taken into account.

If there's no dictionary-compressed version of the asset then it will end up generating a duplicate cache entry (on middle boxes) but I think we'd be better off if we could focus on minimizing those cases by specifying match pattern capabilities and defaults that encourage dictionaries to only match the requests that are very likely to be dictionary-compressed.

**Comment by royfielding** [comment]
> If A-E only had the base encodings then an Available-Dictionary request would match a cached standard dictionary response that had only varied on A-E. By having the dictionary-specific encodings on A-E then it will require the dictionary compression be taken into account.

If both are available, the match would go to the smaller encoded variant. If only the standard compression is available, a cache would be able to deliver the one it has, whereas the origin server can choose whether to use the standard dictionary or the available dictionary as it sees fit. I don't see any downsides.

**Comment by royfielding** [comment]
Well, the downside would be that the sender of Available-Dictionary would have to accept both standard and custom dictionaries in response, for any of the standard dictionary encodings (with -d alternatives) that it sends in A-E.

**Comment by pmeenan** [comment]
Assuming we're talking about a cache in front of whatever generates the responses, if a dictionary-compressed response was not generated before a standard-dictionary response got cached then the dictionary-compressed response would never enter the cache since the standard-dictionary response would always match.

**Comment by pmeenan** [comment]
> Well, the downside would be that the sender of Available-Dictionary would have to accept both standard and custom dictionaries in response, for any of the standard dictionary encodings (with -d alternatives) that it sends in A-E.

That's likely to be the case all of the time anyway for when the server can't generate a dictionary-compressed response. I guess it could fall back to gzip or a different encoding but the same client code that decompresses the dictionary schemes can also decode the non-dictionary schemes.

**Comment by royfielding** [comment]
No, an origin server (including CDN) can do whatever it wants in terms of selecting a representation. This would only make a difference for shared caches for which there was no specific origin config, and in those cases the origin can choose to add Available-Dictionary to Vary on a standard dictionary response if they want the request to be passed through.

**Comment by pmeenan** [comment]
> No, an origin server (including CDN) can do whatever it wants in terms of selecting a representation. This would only make a difference for shared caches for which there was no specific origin config, and in those cases the origin can choose to add Available-Dictionary to Vary on a standard dictionary response if they want the request to be passed through.

Ah, yes, sorry.  Then the only concern would be assuming `zstd-d` support could be inferred by `gzip, br, zstd` and `Available-Dictionary`.  It's likely to be the case but, for example, Chrome 117 supports zstd but only dictionaries on brotli (118 added zstd-d).

Other than the added bytes on the request, there shouldn't be any difference on the variants by including `zstd-d` and `br-d` on the requests, particularly if we require the standard version be supported when the dictionary versions are and that the ordering be deterministic.

**Comment by pmeenan** [comment]
Working through the edge cases here, the PR above has some tweaks to reduce the default variations (lowerd default dictionary expiration to 7 days and require clients to normalize the accept-encoding header so they are more likely to be consistent across clients).

For range requests I'm thinking it makes the most sense to just not allow range requests to be make using dictionary compression. Browsers already don't allow anything except for identity for range requests so it would just be making it explicit for all clients.

For etags, there's not a technical issue since the HTTP RFC requires the etags represent each encoding separately but I can see where that would be difficult in a revalidation case to keep track of the different etags and know if they represent the same resource or not (when applying compression somewhere other than the origin). It's not really different that the case of gzip but it does add more variations and the variations may be opaque. 

Would it be useful to not allow `Content-encoding:` of a dictionary encoding type to also carry `Etag:` and if they are both provided to ignore the etag on the client, not use it as a validator and not request dictionary encoding when revalidation a previous resource that was delivered with an etag? It doesn't feel like either of those would be too restrictive for apps and it would avoid propogating more confusion around the interaction between etags, caches and content-encoding.

**Comment by pmeenan** [comment]
We talked about parts of this at IETF 118 today and the decision was made to not add any encoding normalization and that caches should be normalizing the `Accept-Encoding` and managing their caches.

As far as the original topic about `Content-Encoding` (CE) vs `Transfer-Encoding` (TE), I think we've addressed why CE is appropriate since origins will be pre-compressing resources with dictionaries and storing the variants which is appropriate for CE and not TE.

If there are specific concerns that still remain around etags or otherwise making it easier for caches to work well, please open up separate issues and we can work though those in isolation.

**Comment by royfielding** [comment]
Already closed, but I wanted to note that I looked through this again for draft 04 and I don't have any more concerns after the proposed change in #2787. The use of CE is justified by the use cases and excessive cache variance will be avoided by only sending the dictionary-aware content-codings when the client has a matching dictionary and wants it to be applied.
