### ISSUE TITLE
Wildcard matching - Raised by Martin Thomson and Roy Fielding

### ISSUE THREAD

**Issue by pmeenan** [httpwg/http-extensions#2639]
From @martinthomson:

For what it's worth, I like Roy's idea of prefix+suffix matching in place of arbitrary wildcards. Pattern matching is more expensive than simple prefix/suffix matches.

Also, "*" is a valid path character in HTTP. Maybe that was unwise, but that's what RFC 3986 says. Probably not a big deal (you can avoid using it if you plan to use this feature), but still.

Moved from private ID [issue #1](https://github.com/pmeenan/i-d-compression-dictionary/issues/1)

**Comment by pmeenan** [comment]
[Original listserv response](https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0130.html) from @royfielding:

Using * as a wildcard in arbitrary URL references is a foot gun. It would make more sense to have two attributes, prefix and suffix, and have them only match within the URL path (i.e., exclude the origin and query portions, preventing matches on full URIs or user-supplied query parameters). That is far more likely to get right than allowing things like "//example.com/////****"

**Comment by pmeenan** [comment]
The origin is already excluded from being configurable. There is some discussion about only supporting relative paths but allowing for full URLs just made it easier to reference the existing URL RFC without having to re-define just the parts we need to support.

Query params can't necessarily be excluded and some sites are going to want to allow for either fixed query param matching or wildcard (and maybe for both the static and dynamic use case). Allowing for * allows for some flexibility in site URL structure while still keeping the matching relatively simple and without the complexity of [URLPattern](https://github.com/WICG/urlpattern/blob/main/mdn-drafts/QUICK-REFERENCE.md)

[listserv response](https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0131.html)

**Comment by pmeenan** [comment]
From @royfielding:

I get really nervous when I see shell syntax mixed with URI syntax as a form of pattern matching. We usually don't do that on servers. Regular expression syntax is an even bigger foot gun, but we already have that implemented. Alternatively, the URI Template syntax is a form of pattern matching that is more specific than a wildcard.

If prefix/suffix is insufficient, then maybe "contains" could be there as well, though I'd seriously question why a site would want this much flexibility.

**Comment by pmeenan** [comment]
@royfielding Not sure that it helps any, but the server wouldn't be doing any path matching. It just provides the path string as a hint to the client for where the dictionary would be usable (doesn't need to be validated on the server side at request time - no harm if a resource outside of the path is compressed).

I'll do some browsing over the next week or so and build up a library of URL patterns for static resources and "similar" HTML pages and see what things look like in the wild.

**Comment by pmeenan** [comment]
Sorry, took me a bit to get back to the pattern matching search.

For HTML content things are kind of difficult if you also want the root page on your origin compressed. If we allow for matching on the `destination` (#2625) then it could do something like `use-as-dictionary: match: "/*", match-dest: "document"`. Otherwise, if you want a separate dictionary for product listing pages vs search pages, Amazon (for example) has a `/dp/` in the path but it's not always at the beginning.

I looked at a really quick sampling of subresource URLs in the HTTP Archive and didn't take long to find lots of cases that have more complicated patterns with versions and hashes on either side of parts of the URL.

```
https://www.nadri4u.com/shopimages/ss2565/template/work/3162/common.css?r=1523930855
```

would probably need something like `../*/common.css*`. This case if we allowed separating out the path and search string we could treat as a suffix but there are lots of other cases where it isn't as simple.

```
https://api.manufaktura.cz/api/tenantboot/2_XBBZ/app~80a78feb.css
```

Would need something like `/api/tenantboot/*/app~*.css` or `../*/app~*.css`

**Comment by royfielding** [comment]
The server config is where the hint would be coming from, which is why I am concerned from a origin server standpoint, but I should just get used to people using the * as a wildcard. We do use it, but frequently fail to define exactly what it includes (or excludes), and almost always end up having to provide full regex eventually.

However, wildcard * seems to be more common these days in CDN/AWS configs.

I think if the document is clear that it applies to the path and optional query component only, then we transmit fewer characters and limit possible abuse. Specifically, that would be the [origin-form of RFC9112](url)
```
  origin-form    = absolute-path [ "?" query ]
```
as would appear in HTTP/1.x origin requests after being extracted from the target URI.

**Comment by pmeenan** [comment]
Closing this as we have moved to use URLPattern as discussed at IETF 118.  Feel free to open a new issue if there are concerns specific to how URLPattern is being used.
