### ISSUE TITLE
Allow 200 status code for offset retrieval

### ISSUE THREAD

**Issue by Acconut** [httpwg/http-extensions#2662]
The current draft requires the server to respond with a 204 No Content status code for HEAD requests:

> If an upload is interrupted, the client MAY attempt to fetch the offset of the incomplete upload by sending a HEAD request to the upload resource.
[...]
If the server considers the upload resource to be active, it MUST respond with a 204 (No Content) status code.

This restriction is too strict and does not allow the server to respond with a 200 OK. Since the HEAD requests for resumable uploads do not include any specific additional header field, the server cannot tell apart whether a HEAD request is used for resumable uploads or used for starting a download, for example.

For example, a server might allow to download the uploaded file through a GET request to the upload URL. HEAD requests to this URL should then return the same status code (e.g. 200) and header fields as the GET request would do. But the draft requires a server to always respond with 204, leading to a conflict.

Can we also allow 200 for HEAD responses?

**Comment by smatsson** [comment]
I think this would be a good change to the spec. Maybe use similar language as with PATCH, where we allow the entire 2xx range but have a recommended status code? I don't think this would be an issue for any client.

> If the request completes successfully and the entire upload is complete, the server MUST acknowledge it by responding with a successful status code between 200 and 299 (inclusive). Servers are RECOMMENDED to use 201 (Created) unless otherwise specified.

Is this a typo? Should be "... 200 for HEAD..."? 
>Can we also allow 204 for HEAD responses?

**Comment by Acconut** [comment]
> Is this a typo? Should be "... 200 for HEAD..."?

That's correct. Thank you for pointing out
