### ISSUE TITLE
Give us something to hang onto

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#267]
In working on RFC5988bis, I'm referring to this spec, and finding it's difficult to talk about the concepts, because so much has been pared back.

In particular:

* [ ] There isn't any prose reference to the "*" form of the attribute name; it only occurs in examples. One would assume that this is the normative way to invoke this encoding, but it isn't specified.
* [ ] A distinct name for the encoding would help; right now, the best I can do is "the encoding specified in RFC5987bis".
* [ ] The examples of how to use this in header specifications needs to be deeper.

**Comment by reschke** [comment]
Any name suggestions?

**Comment by mnot** [comment]
Hmm. "i18nPE" (Internationalisation Parameter Encoding)?

**Comment by reschke** [comment]
"nape"? (non-ASCII P. E.)

**Comment by mnot** [comment]
Nape is an English word, a bit odd to use as a name. IPE?

**Comment by reschke** [comment]
sgtm

I  should use that everywhere then, including the title, right?

**Comment by mnot** [comment]
Think so.

**Comment by reschke** [comment]
On the other hand, given the fact that just a few weeks ago you wanted to deprecate the encoding, you are now asking for a way to make it *easier* to reference? Maybe "the encoding defined in RFC xxxx" or "RFC xxxx encoding" really is good enough.

**Comment by reschke** [comment]
>  There isn't any prose reference to the "*" form of the attribute name; it only occurs in examples. One would assume that this is the normative way to invoke this encoding, but it isn't specified.

Actually, this spec can't (or doesn't want to) make a normative requirement for this. The syntax of the parameter names is supposed to be under the control of the specification using them.

That said, I can try to make this clearer in the prose.

**Comment by mnot** [comment]
Transitional Retrograde Internationalised Parameter Encoding?

**Comment by mnot** [comment]
Re OTOH -- you convinced me very effectively.

**Comment by reschke** [comment]
> The examples of how to use this in header specifications needs to be deeper.

The whole of Section 4 is about that. What exactly are you missing?
