### ISSUE TITLE
sfbis: clarify what display strings can contain

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#2672]
[4.1.11. ](https://www.ietf.org/archive/id/draft-ietf-httpbis-sfbis-03.html#section-4.1.11)[Serializing a Display String](https://www.ietf.org/archive/id/draft-ietf-httpbis-sfbis-03.html#name-serializing-a-display-strin) currently does not consider what happens when UTF8 serialization fails, although this could happen with surrogate points. I believe it should explicitly say that.

Alternatively, the introduction of display strings could say that only unicode scalars (https://www.ietf.org/archive/id/draft-bray-unichars-07.html#unicode-scalars) are allowed (but even then I'd add the extra precaution in the serializer).

Finally, we may want to add an example because all of this is far from obvious.

**Comment by jyasskin** [comment]
@domenic pointed out that https://www.rfc-editor.org/rfc/rfc3629.html doesn't define the ["applying UTF-8 encoding [UTF8] to input_sequence."](https://www.ietf.org/archive/id/draft-ietf-httpbis-sfbis-03.html#name-serializing-a-display-strin) and ["decoding byte_array as a UTF-8 string"](https://www.ietf.org/archive/id/draft-ietf-httpbis-sfbis-03.html#name-parsing-a-display-string) operations that this draft uses. RFC 3629 only defines a character at a time.

RFC 3629 also doesn't say to fail encoding or decoding in any particular situations. It says "The definition of UTF-8 prohibits encoding character numbers between U+D800 and U+DFFF", but its definition of encoding doesn't actually prohibit those characters. It also says "MUST protect against decoding invalid sequences", but the definition of decoding doesn't fail in that case.

https://encoding.spec.whatwg.org/#utf-8 is more explicit on these questions and might therefore be a better reference.

**Comment by domenic** [comment]
Note that the recommended entry points for other specs are https://encoding.spec.whatwg.org/#specification-hooks which are clear about how to handle BOMs as well.

**Comment by mnot** [comment]
Seems reasonable - will try to work up a PR. I'm likely to keep the general reference to 3629 for UTF-8, and use encoding for the specifics.

**Comment by reschke** [comment]
I would very very very much prefer not to have a normative reference on a "living" document here. Let's just add the missing needed on top of RFC 3629 to this spec.

**Comment by reschke** [comment]
> Note that the recommended entry points for other specs are https://encoding.spec.whatwg.org/#specification-hooks which are clear about how to handle BOMs as well.

We were clear how to handle BOMs, but what you suggest is a change on top of that.

**Comment by mnot** [comment]
See minimal PR.

**Comment by clelland** [comment]
(Posted on the PR by accident:)

Is it worth dealing with the fact that 3629 doesn't actually define how to encode a sequence of characters, but we're calling it with one? We'd need to add something to 4.1.11, like "for each character (or code point?) in input_sequence, append the result of applying UTF-8 encoding to character to byte_array".
