### ISSUE TITLE
Resumable uploads and security inspection

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#2681]
Some security measures that involve looking at incoming HTTP requests might be circumvented by resumable uploads. For example, a filter which looks for certain HTTP headers and corresponding text in the request payload might not be triggered when the header occurs in one request and the matching body fragment in a subsequent request.

I don't believe there's anything we need to change about the protocol here, but it's probably mentioning this in Security Considerations. Perhaps guidance would be to ensure any security measures are either resumable-upload-aware or are explicitly called to inspect the final request between receipt of the last chunk and execution of the original request.

**Comment by Acconut** [comment]
Thank you, that is a good point. I have opened #2686 to add a paragraph in this regard. Please let me know if that expresses the problem correctly.
