### ISSUE TITLE
rfc6265bis-draft13 lacks section 7.2 in HTML

### ISSUE THREAD

**Issue by bagder** [httpwg/http-extensions#2683]
Section 7.2 is being referenced to in five places in the [html version of the draft](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-13), but surprisingly there *is* no section 7.2 in the document. The links all go to `#cookie-policy`, but there is no such anchor.

Section 7.2 cookie policy is mentioned in the table of contents.

The section does however exist in [the TXT version](https://www.ietf.org/archive/id/draft-ietf-httpbis-rfc6265bis-13.txt) of the document.

**Comment by reschke** [comment]
I see https://www.ietf.org/archive/id/draft-ietf-httpbis-rfc6265bis-13.html#name-cookie-policy - and that is https://www.ietf.org/archive/id/draft-ietf-httpbis-rfc6265bis-13.html#section-7.2

**Comment by bagder** [comment]
I see no section 7.2 on those URLs...!

**Comment by reschke** [comment]
![grafik](https://github.com/httpwg/http-extensions/assets/332994/5965863d-52f8-4f8c-a038-9e4b02268088)

**Comment by reschke** [comment]
Very weird.

**Comment by reschke** [comment]
Very interesting. Seems it doesn't like cookies.
