### ISSUE TITLE
Cannot use mailing list, neither receiving nor sending

### ISSUE THREAD

**Issue by falsandtru** [httpwg/http-extensions#2691]
I first tried to send #2690 to the mailing list but despite completing all the formalities I can't even get an email from the mailing list. I have contacted the contact person in this case but have not received a reply. There is no other place I can access it other than here. Please make the mailing list accessible and available.

**Comment by mnot** [comment]
You must be subscribed to the list to send e-mail to it; per
 https://lists.w3.org/Archives/Public/ietf-http-wg/
you need to send an e-mail to `ietf-http-wg-request@w3.org` with a subject of `subscribe`.

Again, this issues list is not appropriate for administrative problems; please contact the chairs via e-mail or use httpwg/admin. Please do not open any other issues on this repo that are not related to a currently adopted draft.

**Comment by falsandtru** [comment]
My mailing list subscription application has been in the following status since about Nov 25th. Approved but can neither receive nor send.

ID already processed

Error: The message with id: xxx has already been processed (approved).

**Comment by falsandtru** [comment]
OK, I contact that address. I hope to get a reply from that address. I did not receive a reply from the address given on the web page.
