### ISSUE TITLE
Require that upload offset does not decrease over time

### ISSUE THREAD

**Issue by Acconut** [httpwg/http-extensions#2695]
https://github.com/httpwg/http-extensions/pull/2664 added the requirement that the offset reported in 104 informational responses must not decrease over time. For example, it is not allowed that one 104 response includes `Upload-Offset: 100` and the next includes `Upload-Offset: 50`.

For now, this requirement is not mentioned for responses to offset retrieval responses. As @guoye-zhang mentioned in https://github.com/httpwg/http-extensions/pull/2664#issuecomment-1828633857, we should add this rule there as well.

Maybe it also makes sense to move this into a more central section of the document, so that we don't have to repeat this rule trice (upload creation, upload appending, and offset retrieval).

**Comment by guoye-zhang** [comment]
Thinking about this a bit more, progress reporting and offset retrieving are different enough that adding this requirement to offset retrieving might not actually make sense. In a single append, it's impossible for progress to go back and it's fine to be extremely strict. However, offset retrieving can happen much later. A server could have already forgotten about the previous uploaded body, but still want the upload restarted from 0. In the case that the client cannot supply the bytes, it can always decide to not resume, or perform an explicit cancel.
