### ISSUE TITLE
Timezone Offset Client Hint (Sec-CH-Timezone-Offset)

### ISSUE THREAD

**Issue by vrubleg** [httpwg/http-extensions#2707]
It would be nice to add `Sec-CH-Timezone-Offset` Client Hint. The time zone offset is already available from JavaScript as `(new Date()).getTimezoneOffset()`, but in some cases it would be much more convenient to have it available as a Client Hint HTTP header, so server side could adjust all times on a page without a requirement to execute some client side JavaScript.

The value of the Client Hint could be equal to the result of the `(new Date()).getTimezoneOffset()` call.

**Comment by mnot** [comment]
This repo is only for drafts that the Working Group has adopted. If you want to make a proposal, the best thing to do is to send an e-mail to the mailing list - see [CONTRIBUTING.md](https://httpwg.org/CONTRIBUTING.html#proposing-new-work).
