### ISSUE TITLE
5987bis writeup

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#271]
A few things I noticed / need to ask:

* Is the Abstract still suitable? I note it doesn't mention 5987.

* Is the intended status really Internet Standard? Given that 2026 requires "a high degree of technical maturity and by a generally held belief that the specified protocol or service provides significant benefit to the Internet community" and in light of the doubt around the use of this format, it seems like Proposed Standard might be more appropriate. Also, we'd need to document the implementations.

* @reschke - If you have direct, personal knowledge of any IPR related to this document, has it already been disclosed?

**Comment by reschke** [comment]
- I think advice from the IESG varies about whether the abstract should include this. Maybe ask our AD before proceeding.

- It is definitively mature, and we currently do not have an alternative. That said, where does the implementation documentation requirement come from? FWIW, there's Appendix B.

- I'm not aware of any IPR related to my profiling of RFC 2231.

**Comment by reschke** [comment]
After checking a few recent RFCs, I see that obsoletions are indeed usually mentioned in the abstract. Added that.

**Comment by mcmanus** [comment]
based on https://lists.w3.org/Archives/Public/ietf-http-wg/2017JanMar/0025.html the consensus is to proceed with this on a proposed standard basis.
