### ISSUE TITLE
connect-tcp: target_host is under-defined

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#2714]
The target_host variable is only described vaguely. It should be defined more rigorously. For example, it doesn't specify whether IPv6 scope IDs are allowed or not. I'd recommend reusing the text from RFC 9298.

**Comment by bemasc** [comment]
OK, I've opened #2719 to make the definition more rigorous.

**Comment by bemasc** [comment]
Fixed by #2736
