### ISSUE TITLE
connect-tcp: target_host list feature seems broken

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#2715]
connect-tcp makes the target_host variable a list, which is a feature that connect-udp didn't have. I'm not an expert of URI templates, but this doesn't seem correct. The feature definition links to [composite values from RFC 6570](https://www.rfc-editor.org/rfc/rfc6570#section-2.4.2), but those require a `*` in the template - which is something that the document does not use in its examples nor the default template. Additionally, an example in connect-tcp uses `:path = /proxy?target_host=192.0.2.1,2001:db8::1&tcp_port=443` whereas the notation from RFC 6570 would be `:path = /proxy?target_host=192.0.2.1&target_host=2001:db8::1&tcp_port=443`

**Comment by bemasc** [comment]
No, the `*` is optional.  Section 3.2.1 [says](https://www.rfc-editor.org/rfc/rfc6570#section-3.2.1:~:text=For%20a%20variable%20that%20is%20a%20list%20of%20values%2C%20expansion%20depends%20on%20both%0A%20%20%20the%20expression%20type%20and%20the%20presence%20of%20an%20explode%20modifier.%20%20If%0A%20%20%20there%20is%20no%20explode%20modifier%2C%20the%20expansion%20consists%20of%20a%20comma%2D%0A%20%20%20separated%20concatenation%20of%20the%20defined%20member%20string%20values.):
>  If there is no explode modifier, the expansion consists of a comma-separated concatenation of the defined member string values.

This is what is shown in the example.

I've adjusted the reference (https://github.com/httpwg/http-extensions/commit/6923144327ef12fe1eefe88c2a132a538a0eff16) to point to a different section of RFC 6570.

**Comment by DavidSchinazi** [comment]
Thanks for clarifying
