### ISSUE TITLE
Prohibit an empty string Dictionary-ID

### ISSUE THREAD

**Issue by horo-t** [httpwg/http-extensions#2721]
Dictionary-ID was introduced to the Compression Dictionary Transport specification by #2687.

However, it is unclear whether empty string dictionary IDs are allowed.
I don't think there is any use case for an empty string dictionary ID.
So how about explicitly disallowing empty string dictionary IDs in the spec?
@pmeenan

**Comment by pmeenan** [comment]
I'll make a zero-length string the default and have that mean "no ID".  The dictionary ID will only be sent if it has a length > 0.
