### ISSUE TITLE
Support a list of match-dest

### ISSUE THREAD

**Issue by horo-t** [httpwg/http-extensions#2722]
`match-dest` option was introduced in the Compression Dictionary Transport spec by #2646.
But if my understanding is correct, currently it is not allowed to setting multiple types of destinations.
So if I want to use a dictionary for HTML files including top frame, `<frame>` and `<iframe>`, I need to download the dictionary three times.

@pmeenan 
How about allowing setting multiple types of destinations?
Example:
```
Use-As-Dictionary: match="/", match-dest=("document" "frame" "iframe")
```

**Comment by pmeenan** [comment]
Sounds good (though document/frame is probably the only practical use case). I'll switch it to an inner-list of tokens.
