### ISSUE TITLE
Handling empty destination

### ISSUE THREAD

**Issue by horo-t** [httpwg/http-extensions#2723]
The spec of compression dictionary transport says:
```
The "match-dest" value of the Use-As-Dictionary header is a sf-string value that provides a request destination (https://fetch.spec.whatwg.org/#concept-request-destination).

An empty string for "match-dest" MUST match all destinations.
``` 

But an empty [request destination](https://fetch.spec.whatwg.org/#concept-request-destination) "" is used for some features such as `navigator.sendBeacon()`, `EventSource`,  `fetch()`, `XMLHTTPRequest`, `WebSocket`, Cache API, Download, prefetch and prerender. (See this [table](https://fetch.spec.whatwg.org/#destination-table)).

So currently there is no way to set up a dictionary for such destinations.
For example, I want to use a dictionary for fetch() API, but I don't want to use the dictionary for HTML documents.

@pmeenan 
How about using a string "empty" for such empty destination?
We are already using "empty" for `Sec-Fetch-Dest` header of empty destination request.
https://w3c.github.io/webappsec-fetch-metadata/#abstract-opdef-set-dest

Also if we don't need to use an empty string "" for `match-dest`, I think `match-dest` should be a [sf-token](https://datatracker.ietf.org/doc/html/rfc8941#section-3.3.4) instead of a [sf-string](https://datatracker.ietf.org/doc/html/rfc8941#section-3.3.3). We don't need to use double quotes.

**Comment by pmeenan** [comment]
Having special values feels a bit strange, particularly since it's only defined in the internal processing part of the w3c spec.

If we use a list of strings we can use `""` for an explicit empty destination and use an empty list `()` for matching everything (and as the default).  Does that seem reasonable?

**Comment by horo-t** [comment]
OK, sounds reasonable. Thanks.
