### ISSUE TITLE
Resumable examples in section 4 run into each other

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#2725]
I think there's two different creation examples being shown in https://httpwg.org/http-extensions/draft-ietf-httpbis-resumable-upload.html#section-4 but the presentation of them isn't great and could be a source of confusion. If so, lets break them apart by having a short sentence before each example expliaining it.

**Comment by Acconut** [comment]
Yes, these are two separate examples, which are confusing. Most of the example are in need of a proper description. I can open a PR to address this. Thank you!
