### ISSUE TITLE
Record size (rs) should be of ciphertext, not padded-plaintext

### ISSUE THREAD

**Issue by manger** [httpwg/http-extensions#274]
It would be better to define the 'rs' (record size) parameter as the size of each ciphertext record (including the 16 byte tag for AEAD_AES_128_GCM).

That way a receiver can split the body into records without needing to add the algorithm-specific tag length. Then pass the bytes to a crypto library that does know details such as the tag length for a given alg.

This spec doesn't absolutely need alg agility as other algs would define their own content-encoding label. But it would be cleaner (& safer) if future algs could follow exactly the same pattern and same body format by simply defining a new content-encoding label. The format is very close, with the need to add 16 to 'rs' being the only wart.

**Comment by martinthomson** [comment]
Yes, I will define it this way.  Forgot to tag this correctly, so I missed it.

**Comment by martinthomson** [comment]
Addressed in latest version.

**Comment by manger** [comment]
Looks good. Couple of typos.
* "content of rs octets minus padding less padding (2-65537) and tag (16)" -- drop "minus padding"
* "a record that contains contains only padding" -- drop 1 "contains"

**Comment by martinthomson** [comment]
Thanks.

**Comment by manger** [comment]
1 more typo:

- "cannot increase the record size beyond 65537 octets" -- should be "65553" now that rs includes the tag
