### ISSUE TITLE
Citation format

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#2757]
For example: 

> provides the URLPattern to use for request matching (https://urlpattern.spec.whatwg.org/).

Usually, we add something like URLPattern to the references, then `[CITE]` that.

**Comment by pmeenan** [comment]
Sorry, didn't mean to close the issue. Feel free to close this out if the current language looks OK (also happy to update it if it needs some more tweaking).

**Comment by pmeenan** [comment]
Going to close this out now. Thanks for taking the time on this.
