### ISSUE TITLE
Consider changing `match` to a list of patterns

### ISSUE THREAD

**Issue by pmeenan** [httpwg/http-extensions#2771]
The `match` key for the `Use-As-Dictionary` response header is currently a single URLPattern string, allowing each dictionary to match a single wildcard path.  It would allow for more flexibility with minimal added complexity if it was a list of pattern strings instead of a single pattern.

e.g.

```Use-As-Dictionary: match="/product/*"```

would become:

```Use-As-Dictionary: match=("/product/*")```

and allow for something like:

```Use-As-Dictionary: match=("/product/*", "/search/*", "/dictionary.dat")```

In this case, allowing the dictionary to be used as a dictionary for dictionary updates as well as a few different product paths.

This adds 2 bytes to every response (unless we can allow for it to be either a string or list and parse accordingly).

The existing specificity rules should continue to work, with the longest matching pattern taking precedence.

The main downside is that it makes it easy to increase the number of match operations that the client needs to do on every outbound request since the client needs to compare every request to every match pattern. If we do allow for it, we should consider having a limit on the number of list entries.

**Comment by pmeenan** [comment]
@mnot Quick SF question... Is it possible to have a field be `either an Inner List or a String` and detect at parse time or does it always need to be a list? Not a big deal but could save 2 bytes for the cases where it is just a single item.

@horo_t does this add more complexity to the implementation that I might not be aware of?

@yoavweiss FYI since I think we chatted about this a bit.

I don't want to add things just for theoretical benefit and we haven't had a user that has needed this yet so maybe it isn't really needed but I'd hate to ship and then need it.

**Comment by reschke** [comment]
>  Is it possible to have a field be either an Inner List or a String and detect at parse time

Yes. The parser won't care. It's up to the application to handle this.

**Comment by pmeenan** [comment]
Going to close this out. None of the feedback from the Chrome trials have expressed concern with a single match pattern. If, for some reason, it does become a critical issue, a new field can be created that has a list of additional match patterns.
