### ISSUE TITLE
Add link relation to trigger compression dictionary fetches

### ISSUE THREAD

**Issue by pmeenan** [httpwg/http-extensions#2772]
The explainer calls for a link relation of `dictionary` to let clients know of stand-alone dictionaries that should be fetched for future use. The ID should include the link relation definition and registration.

`dictionary` is too generic for this use case to use so we will have to come up with alternatives. `compression-dictionary` and `comp-dict` have been floated. Multiple references to the same dictionary will likely be compressed away after the first one by HPACK/QPACK so the length may not be a significant issue (if it is, `cdict` might be worth considering).

Some other things to include:

There needs to be some language about the risk of abuse as a tracking vector. Practically, this means it should be treated the same as `preload` and, for browsers, be limited to the main document resource.

The response needs to be CORS-readable. The explainer also calls for it being fetched with credentials omitted to discourage private information from being included in the dictionary contents but that's more to prevent a footgun since the resources are CORS-readable anyway. Forcing a new connection for the cases where it will commonly be used (documents, scripts, etc) for what will likely be a single request on the separate connection might be more cost than the footgun-prevention justifies.

**Comment by yoavweiss** [comment]
That seems like something we'd want to define as part of HTML, and then the header variant would just fall off of that.

**Comment by pmeenan** [comment]
There are non-web use cases where HTTP could benefit from referencing a dictionary. [RFC 8288](https://datatracker.ietf.org/doc/html/rfc8288) covers link relations with an IANA-managed [registry of link relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml).

There's some discussion of it in the [HTML spec issue](https://github.com/whatwg/html/issues/10162) for the link relation as well but the HTML-specific parts aren't particularly involved and defining it as part of HTTP for non-HTML cases seems appropriate (as long as we come up with a name that everyone is OK with).

On the naming side, HTTP-level concerns are probably more restrictive than HTML as well since it's in headers outside of the normal compression and only benefitting from HPACK/QPACK (for exact duplicates).
