### ISSUE TITLE
Add motivation to draft-ietf-httpbis-compression-dictionary

### ISSUE THREAD

**Issue by hoehrmann** [httpwg/http-extensions#2786]
I had a look at draft-ietf-httpbis-compression-dictionary-04.txt and it seems the draft does not explain the motivation for this work. I think it should explain who would be interested in using this, under which circumstances, what the benefits are, what kind of data would benefit from the proposed mechanism in particular, stuff like that.

--- 

Over the weekend I made a toy script that uses large language models to autonomously review Internet-Drafts (https://github.com/hoehrmann/IETF-CERT/) and I used draft-ietf-httpbis-compression-dictionary-00.txt as sample input and then wondered why the language model insists on repeating the same comment again and again on each page, and then had a look at the latest version, and the model seems right here:

> Comment: The abstract is clear about the purpose of the proposal, but it would be helpful to have a more detailed overview of the problem space addressed by this draft. What specific issues does this proposal aim to solve? Are there other approaches or proposals that address similar issues?

> Comment: The Use-As-Directory header seems to be a key part of the proposal, but it would be helpful to have more detail about how it will be used. What are the specific use cases for this header? Are there other approaches or proposals that address similar issues?

> Comment: While the draft provides some examples for the "hashes" value, it would be helpful to have more specific use cases or examples of how this value is used. Are there particular hash algorithms that are more suitable for specific types of data?

> Comment: While the draft provides some useful examples, it would be helpful to have more specific use cases or examples of how this proposal would be used. Are there particular types of data that would be well-suited for this type of directory-based approach? How does this proposal address issues with cache validity?

> Comment: While the draft provides some useful details about how the Available-Directory request header works, it would be helpful to have more specific use cases or examples of how this proposal would be used. Are there particular types of data that would be well-suited for this type of directory-based approach? How does this proposal address issues with cache validity?

> Comment: While the draft provides some useful details about how the algorithm for compressive directory- based approach works, it would be helpful to have more specific use cases or examples of how this proposal would be used. Are there particular types of data that would be well-suited for this type of directory-based approach? How does this proposal address issues with cache validity?

> Comment: While the draft provides some useful details about how to use the proposed directory-based approach for compressive, it would be helpful to have more specific use cases or examples of how this proposal would be used. Are there particular types of data that would be well-suited for this type of directory-based approach? How does this proposal address issues with cache validity?

**Comment by hoehrmann** [comment]
@mnot You are attacking a straw man. There is an issue description, a "cut below this line" marker, and a backstory.

**Comment by LPardue** [comment]
HTTP compression is commonly used. This spec can't add much to the topic in terms of motivation. Any engineer dealing with compression will understand that content-aware dictionaries are an optimization.

Less is often more. I don't think IETF specifications are the correct place to speculate about the performance outcomes of the protocol extension. That's better suited to supporting documents or implementer testing.
Nor is a specification a good place to capture surveys of other extensions.

**Comment by hoehrmann** [comment]
@LPardue Have a look at sections 2.2 through 2.4 of BCP 22. Including sufficient context is literally and formally considered the best current practise here.

**Comment by LPardue** [comment]
>  The author should consider what level of descriptive detail best conveys the protocol's intent.  Concise text has several advantages. It makes the document easier to read.  Such text reduces the chance for conflict between different portions of the specification.  The  reader can readily identify the required protocol mechanisms in the standard.  In addition, it makes it easier to identify the requirements for protocol implementation.  A disadvantage of concise descriptions is that a reader may not fully comprehend the reasoning behind the protocol, and thus make assumptions that will lead to implementation errors.

> Longer descriptions may be necessary to explain purpose, background, rationale, implementation experience, or to provide tutorial information.  This helps the reader understand the protocol.  Yet, several dangers exist with lengthy text.  Finding the protocol requirements in the text is difficult or confusing.  The same mechanism may have multiple descriptions, which leads to misinterpretation or conflict.  Finally, it is more difficult to comprehend, a consideration as English is not the native language of the many worldwide readers of IETF standards.

Seems to support my opinion. The document in question is an extension to HTTP, it doesn't need to explain why conpression is useful. 

I'm finding it hard to believe anyone will struggle to understand the underlying concepts related to compression, or to understand why optimizations are a motivation. 

If you have concrete suggestions to make, I'm sure the authors would appreciate proposed text in the form of a PR.
