### ISSUE TITLE
Inconsistent offsetting of parameter names

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#2801]
The five authentication parameters are offset in various ways throughout the document. Examples:

- using the `p` Parameter (Section 3.3)
- using the v Parameter (Section 3.2)
- The REQUIRED "p" (proof) parameter (Section 4.3)

Additionally, the word "directive" is used instead of parameter in Section 4.4.  It might be advisable to align the document on always using one of these, with a possible difference where the parameter is being defined.

**Comment by DavidSchinazi** [comment]
Agreed. I'll write a PR that standardizes on
* parameter and not directive
* "p" when defining a new parameter
* `p` when referencing the parameter
