### ISSUE TITLE
Clarify public key vs. structure

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#2802]
In 4.2, the `a` parameter is "a byte sequence that **contains** the public key", and the encoding of the public key is taken from Section 3.1. When reading this, I was initially unclear whether `a` was only the key or the entire structure defined in Section 3.1 or another structure, particularly given the use of the word "contains."

I might clarify that the `a` parameter *is* the public key, and perhaps point from both 3.1 and 4.2 to the same place for how to get the bytes which are being base64url-encoded here.  (Make a 3.1.1?)

(Marking editorial, as I don't think I'm asking for a technical change here, just clarification of how this already works.)

**Comment by DavidSchinazi** [comment]
What you're describing is indeed what we intended. I'm write up an editorial PR to clarify this.
