### ISSUE TITLE
Reference in IANA registries

### ISSUE THREAD

**Issue by nidhijaju** [httpwg/http-extensions#2838]
_Comment by @fpalombini_

I see that this document updates the IANA “HTTP Content Coding Registry” registration to reference this doc instead of 8878. I think it should actually reference both.

Additionally, has the wg considered updating the media type registration made in https://www.rfc-editor.org/rfc/rfc8878#name-the-application-zstd-media- for consistency? I am ok with not updating it, as the link is also done via the document, but just checking for consistency.

**Comment by nidhijaju** [comment]
> I see that this document updates the IANA “HTTP Content Coding Registry” registration to reference this doc instead of 8878. I think it should actually reference both.

Although I'm open to adding a reference to RFC 8878 as well, I'm just wondering if referencing both docs would confuse people since we want to make sure that they see the size restriction before using the token.

> Additionally, has the wg considered updating the media type registration made in https://www.rfc-editor.org/rfc/rfc8878#name-the-application-zstd-media- for consistency? I am ok with not updating it, as the link is also done via the document, but just checking for consistency.

This doc is specifically for HTTP Content Encoding use cases so IIUC we don't really want to restrict the media type itself. Applications are free to transfer zstd archives that used any window size around as files, but we just don't want to require HTTP clients/servers to (de)compress with window sizes above 8 MB.

**Comment by fpalombini** [comment]
As mentioned in the mailing list:

Re adding the reference to RFC 8878 as well in the IANA registry, I still think it should be done: the Zstandard protocol mentioned in the description of the IANA registration is still only defined in 8878 (I would have another opinion if this document replaced 8878, but that’s not the case here).
 
Ok for the media type, sounds fine as is.

**Comment by nidhijaju** [comment]
> Re adding the reference to RFC 8878 as well in the IANA registry, I still think it should be done: the Zstandard protocol mentioned in the description of the IANA registration is still only defined in 8878 (I would have another opinion if this document replaced 8878, but that’s not the case here).

Got it, sounds good! Just landed a PR for this.
