### ISSUE TITLE
connect-tcp: require capsules

### ISSUE THREAD

**Issue by DavidSchinazi** [httpwg/http-extensions#2855]
As of draft-ietf-httpbis-connect-tcp-05, connect-tcp now optionally supports the capsule protocol. However, this optionality adds non-trivial complexity to implementations. As currently written, if a client wishes to use capsules, the server can reject the use of capsules, and now the client needs to cache that this server doesn't support them. However it's undefined for how long the client should cache this information, and within what scope. We could potentially figure out recommendations for all these questions, but fundamentally it might be best to instead make capsules mandatory for connect-tcp, like they are for connect-udp and connect-ip. That would simplify implementations and improve consistency.

**Comment by tfpauly** [comment]
Individually, I think it would be interesting to try out this direction — probably based on implementation experience for how easy it is to add.

On one hand, this makes connect-tcp less of a trivial drop-in. On the other, it opens up more possible use cases.

**Comment by bemasc** [comment]
I heard a good deal of support for this direction in the HTTPBIS meeting.
