### ISSUE TITLE
The inverse of immutable

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#288]
Chrome currently implements the semantics of `immutable` using a browser heuristic rather than an explicit signal from the server.

if we define a complimentary CC extension with the inverse semantics of `immutable` -- i.e., roughly, "always refresh this when the user hits reload" -- it would allow Chrome to continue using a heuristic, but override it with an explicit signal from the server when the server cares about it.

If we do that, I think the CC extension name should be short (e.g., one or two characters).

**Comment by mcmanus** [comment]
I can imagine such an extension, but its not this one and this one isn't incompatible with adding such a thing in a separate draft. immutable is based on running code and I'm not comfortable expanding that scope here.

**Comment by mnot** [comment]
Makes sense. If anyone needs this, we can revisit.
