### ISSUE TITLE
immutable definition

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#289]
The definition of `immutable`s semantics are a bit weird:

> When present in an HTTP response, the `immutable` Cache-Control extension indicates that the origin server MUST NOT update the representation of that resource during the freshness lifetime of the response.

I think it should be defined in terms of client operation, rather than server operation. E.g.,

> When present in an HTTP response, the `immutable` Cache-Control extension indicates that clients SHOULD NOT issue a conditional request during the response's freshness lifetime (e.g., upon a "reload"), unless explicitly overridden by the user (e.g., a "force reload").

**Comment by mcmanus** [comment]
https://github.com/httpwg/http-extensions/commit/dd7a9513d21b5e4c8a4571c909828bf002afaabe
