### ISSUE TITLE
Feedback on QUERY in HN thread

### ISSUE THREAD

**Issue by nicowilliams** [httpwg/http-extensions#2895]
See https://news.ycombinator.com/item?id=41552804

**Comment by MikeBishop** [comment]
Thank you for the pointer. Is there something specific here you think we should track that you haven't captured in your other issues?

**Comment by nicowilliams** [comment]
I haven't read all of that thread.  Now that you've seen that thread I'll close this issue, and you can either re-open it or open new issues as you see fit.
