### ISSUE TITLE
QUERY: What to say about CORS?

### ISSUE THREAD

**Issue by nicowilliams** [httpwg/http-extensions#2898]
A safe method with a request body should probably have the same CORS handling as `GET`, I think.

**Comment by MikeBishop** [comment]
CORS is not a feature of HTTP itself; it's something defined at the browser level on top of HTTP.

**Comment by reschke** [comment]
That's an interesting question, but I'm not sure that touching CORS is going to work. But certainly we can make the Fetch authors think about it.

**Comment by nicowilliams** [comment]
The Security Considerations section certainly could say something to the effect that because `QUERY` is a safe and idempotent method, something like: "we expect that CORS should evolve to treat `QUERY` in a substantially similar way as `GET`".

HTML too will need extensions to support the use of `QUERY` from HTML.  My guess is that JavaScript will probably get support for `QUERY` before HTML.  Cross-origin `QUERY` requests ought to work as well as cross-origin `GET`s.

**Comment by nicowilliams** [comment]
Text about this can say something like: "We expect that an upcoming update to CORS will handle `QUERY` similar to `GET`, however, we cannot update CORS.  Implementors should watch for updates to CORS."

**Comment by reschke** [comment]
we could but it's rather pointless and likely wouldn't get past last call.Am 18.09.2024 12:23 schrieb Nico Williams ***@***.***>:
Text about this can say something like: "We expect that an upcoming update to CORS will handle QUERY similar to GET, however, we cannot update CORS.  Implementors should watch for updates to CORS."

**Comment by nicowilliams** [comment]
I don't see why non-normative language would be removed at WGLC or IETF LC, but you could always merely note that currently CORS cannot and does not say anything about `QUERY`.

**Comment by reschke** [comment]
Why would Javascript need extensions for QUERY?

**Comment by reschke** [comment]
See https://github.com/whatwg/fetch/issues/1774
