### ISSUE TITLE
About Intermediaries

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#290]
> An immutable response has the same semantic meaning for proxy clients as it does for User-Agent based clients and they therefore MAY also presume a conditional revalidation for a response marked immutable would return 304. A proxy client who uses immutable to anticipate a 304 response may choose whether to reply with a 304 or 200 to its requesting client.

Parse error :) What are you trying to do?

**Comment by mcmanus** [comment]
https://github.com/httpwg/http-extensions/commit/fdc18b2ae5fee1e2a2540ca8d71ba0ed2553104b
