### ISSUE TITLE
QUERY: Difference between `Location:` and `Content-Location:`?

### ISSUE THREAD

**Issue by nicowilliams** [httpwg/http-extensions#2900]
In the [I-D section 4.2 example](https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-05.html#section-4.2) we see:

```
HTTP/1.1 200 OK
Content-Type: text/csv
Content-Location: /contacts/responses/42
Location: /contacts/queries/17

...
```

Questions:

 - why should the `Location:` header be present in a `2xx` response?
 - why should the `Content-Location` differ from the `Location` in this example?
   Surely a `GET` of either should produce the same response, no?  I would think so.

IMO `Location:` SHOULD be present in all responses unless the server does not want the query cached, and `Content-Location:`, if it is present, SHOULD be the same as `Location:`.

Question: shouldn't the server use `201` for direct responses when it "creates" a URI for the query??  I would think so (though the issue that might then arise is: is `QUERY` truly safe? but I think it the answer to that would be "yes").

IMO `200` should be for direct responses w/o a `Location:`, and `201` should be for direct responses with a `Location:`.

**Comment by nicowilliams** [comment]
One possibility for why `Location:` and `Content-Location:` should be different is that one can be for "this query" and the other for "this particular response to executing that query".  However, it's not likely that the server will be able to re-compute a particular response to a long-ago execution of a particular query, and if that is desired then perhaps the ability to create a persistent response should be a separate operation.

**Comment by MikeBishop** [comment]
These are questions that we tried to address in [Section 2](https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-05.html#section-2); if they're not clear there, we can try to make them more pointed.

**Why does a 200 have a Location?**

The semantics of Location are defined with respect to the method and the status code. Nothing says that a Location header can't have defined semantics for a 200. Section 2 describes the semantics in this case.

**What's the difference between Location and Content-Location?** 

> A successful response to a QUERY request can include a Content-Location header field ([...]) containing an identifier for a resource corresponding to the results of the operation. This represents a claim from the server that a client can send a GET request for the indicated URI to retrieve the results of the query operation just performed. The indicated resource might be temporary.

>
> A server MAY create or locate a resource that identifies the query operation for future use. If the server does so, the URI of the resource can be included in the Location header field of the response ([...]).

That is, Content-Location (if present) will return the result of the query from the time it was executed, while Location indicates where the same query can be re-performed against up-to-date data. So no, they will essentially never be the same resource if both are present.

The apt example from another issue was that Content-Location might point to weather records of a particular date and time, while Location would point to the current weather for the same location. As you say, it's not going to be the case that both (or either!) exists for every server and every request, but the mechanisms exist to convey them if they do.

**How is this "safe"?**

> QUERY requests are both safe and idempotent **with regards to the resource identified by the request URI**. That is, QUERY requests do not alter the state of the targeted resource. However, while processing a QUERY request, a server can be expected to allocate computing and memory resources or even create additional HTTP resources through which the response can be retrieved.

**Shouldn't it be a 201?**

The server might reasonably send a 201 if it created a new resource to track the query. Or, for frequent queries, one might already have existed and it's merely supplying a pointer. But ultimately, the client doesn't care. The client isn't requesting the creation of such a resource; these are merely affordances for the server to reference them if they exist / it creates them.

**Comment by nicowilliams** [comment]
Thanks.  I should have read section 2 more carefully.  I note the lack of normative language regarding this ("can" instead of "MAY").
