### ISSUE TITLE
Real-time web.

### ISSUE THREAD

**Issue by boludoz** [httpwg/http-extensions#2925]
I think it is necessary to implement native techniques that do not depend on JS (like Socket.IO) to update websites in real time. It is necessary to rethink http.

**Comment by boludoz** [comment]
Adding new methods of real-time communication and streaming would help to optimize performance, facilitate programming and reduce the carbon footprint.

**Comment by mnot** [comment]
This repository is only for discussing drafts that the HTTP Working Group has adopted.

**Comment by boludoz** [comment]
Maybe websockets and webtransport will be enough
