### ISSUE TITLE
Issues from old repo

### ISSUE THREAD

**Issue by estark37** [httpwg/http-extensions#294]
I want to address these issues that were filed in the old repo https://github.com/bifurcation/expect-ct/:

- [x] https://github.com/bifurcation/expect-ct/issues/18
- [x] https://github.com/bifurcation/expect-ct/issues/16
- [x] https://github.com/bifurcation/expect-ct/issues/7
- [x] https://github.com/bifurcation/expect-ct/issues/6
- [x] https://github.com/bifurcation/expect-ct/issues/4

**Comment by estark37** [comment]
Oops, sorry, it looks like I wasn't supposed to close this on my own because of the design label, is that right @mnot?

I think https://github.com/bifurcation/expect-ct/issues/18 was the only design issue on this list. I ended up only making fairly superficial changes, with my reasoning described in https://github.com/bifurcation/expect-ct/issues/18#issuecomment-303517543

**Comment by mnot** [comment]
That's OK, we can reopen it if someone complains.
