### ISSUE TITLE
Resumable Upload: Mention cookies?

### ISSUE THREAD

**Issue by Acconut** [httpwg/http-extensions#2950]
A server could set cookies when an upload is started via a POST request or when an upload is resumed via a HEAD request. These cookies might be used to authenticate subsequent PATCH requests. Of course, this is optional and a client could also choose to ignore the cookies altogether. Should we mention this possibility explicitly in the resumable upload draft or is it not necessary since RFC 9110 and RFC 6265 cover this already?

**Comment by smatsson** [comment]
My two cents: Does this spec handle cookies differently than the other RFCs? If yes we should add it. If no we leave it out.

**Comment by guoye-zhang** [comment]
I don't think it's necessary to mention cookies. Nearly all http based protocols interact with cookies directly or indirectly, and it's fairly clear how cookies should work here.

**Comment by Acconut** [comment]
Thanks for your input. In that case, we should not add additional text for cookies.
