### ISSUE TITLE
RFC6265bis: Set-Cookie grammar can be simplified

### ISSUE THREAD

**Issue by sbingler** [httpwg/http-extensions#2969]
```
    set-cookie        = set-cookie-string
    set-cookie-string = BWS cookie-pair *( BWS ";" OWS cookie-av )
```

could be

```
    set-cookie-string = BWS cookie-pair *( BWS ";" OWS cookie-av )
```

Credit to Mark Thomas for bringing this to my attention

**Comment by roryhewitt** [comment]
I forget the syntax used in other RFC's, but couldn't/shouldn't this alternately be:
```
    set-cookie        = "Set-Cookie:" set-cookie-string
    set-cookie-string = BWS cookie-pair *( BWS ";" OWS cookie-av )
```
IOW, the `set-cookie` includes the definition of the header name itself?

**Comment by markt-asf** [comment]
@roryhewitt  The removal of the header name was deliberate. See #1302.

@sbingler A similar change is possible for the Cookie grammar:
```
cookie        = cookie-string
cookie-string = cookie-pair *( ";" SP cookie-pair )
```
could simplified to
```
cookie-string = cookie-pair *( ";" SP cookie-pair )
```

**Comment by martinthomson** [comment]
Are you sure this is right?

With the existing code, the name of the field is implicitly the name of the starting rule for the content of the field.

So isn't this:

```abnf
cookie = cookie-pair *( ";" SP cookie-pair )
```

**Comment by markt-asf** [comment]
@martinthomson Ah. That wasn't clear to me. I just spotted what seemed to be some unnecessary definitions. Is that implicit rule documented anywhere? I don't recall reading it but there are plenty of docs I haven't read in full so I may well have missed it.

On that basis the other proposed change would be:
```
cookie        =  cookie-pair *( ";" SP cookie-pair )
```

**Comment by sbingler** [comment]
After looking at the text more closely I think `set-cookie-string` and `cookie-string` provide value outside their immediate grammars.

Both are used throughout the text as references to the grammar and the concept of the string itself. Removing them would hurt readability imo and so I've decided to keep them. But thank you for the suggestion nonetheless.

**Comment by markt-asf** [comment]
Fair enough. Once Martin explained the implicit mapping from the name of the first rule to the name of the field I was beginning to think the same.
