### ISSUE TITLE
Typo in SameSite cookie algorithm (?)

### ISSUE THREAD

**Issue by estark37** [httpwg/http-extensions#302]
Step 5 of Section 2.1.1 of https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00#section-2.1.1 says `return "top-site"`, but "top-site" isn't defined anywhere. I think it's supposed to be the registerable domain of "top-origin"?

cc @scotthelme

**Comment by mikewest** [comment]
Thanks! Will be fixed in the -02 draft of RFC6265 I'm about to upload.
