### ISSUE TITLE
CH editorial

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#308]
Taking a run through the spec before we sent it upstairs, a few suggestions --

* In the abstract, `s/clients/user agents/g` (proxies aren't going to generate them, and shouldn't try)
* Introduction - you might get complaints about the "UA" abbreviation; spell out as `User-Agent`?
* Section 2 - "Each one conveys a list of client preferences" -- are they all list-based?
* 2.2 - "Servers respond with an optimized response based on one or more received hints from the client." -- awkward; suggest: "When presented with a request that contains one or more client hint headers, servers can optimise the response based upon the information in them."
* 2.2 - "used hint" --> "hint used"
* 2.2 - "emit" --> "generate"  (has meaning in HTTP)
* 2.2 "confirm the property of the response, such that the client can adjust its processing" --> "convey related values to aid client processing"
* Sections 3-7: These feel like they should all be in their own subsection. Also, would you consider changing "client hint" in each title to "header field"? That will emphasise that they're just regular headers, not some new class of thing (I continue to be concerned that people think these are magical because they are called Client Hints).
* Section 7: "New token and extension token values can only be defined by revisions of this specification" --> "New token and extension token values can be defined by updates to this specification."  (IETF-specific wording)
* Section 9: "Client Hints defined in this specification do not expose new information about the user’s environment beyond what is already available to, and can be communicated by, the application at runtime via JavaScript and CSS." --> "The request header fields defined in this specification expose information that is already available to Web applications in the browser runtime itself (e.g., using JavaScript and CSS)."
* Section 9: "However, implementors should consider the privacy implications of various methods to enable delivery of Client Hints - see “Sending Client Hints” section." --> "However, servers that gather this information through such mechanisms are typically observable (e.g., you can see that they're using JavaScript to gather it), whereas servers' use of the header fields introduced by this specification is not observable. Section 2.1 discusses potential mitigations." 
* Section 9: "might reduce such fingerprinting risks" --> "can help mitigate the risk of such fingerprinting."
* Section 9: "The implementers can..." --> "Implementers ought to..."
* Section 9: "...advertised: require..." --> "...advertised. For example, they could require..."

**Comment by mnot** [comment]
ping @igrigorik

**Comment by igrigorik** [comment]
Thanks for the thorough review Mark!

> In the abstract, s/clients/user agents/g (proxies aren't going to generate them, and shouldn't try)

I'm building an iOS/Android app and want to use CH.. "user agent" doesn't seem to fit? I'd prefer to keep it inclusive.

> Introduction - you might get complaints about the "UA" abbreviation; spell out as User-Agent?

We do define it at the start: "User-Agent (UA; Section 5.5.3 of {{RFC7231}})"

--

Opened PR to address the rest: https://github.com/httpwg/http-extensions/pull/309

**Comment by mnot** [comment]
"client" and "user agent" are defined terms in HTTP; client covers *anything* that sends a request, including proxies, whereas user agent is only the originator of requests -- regardless of whether it's a Web browser or app.

(this is not the WHATWG :)

I saw that you defined the abbreviation, but I suspect the RFC editor is going to change it; all other HTTP RFCs use the phrase "user agent." Besides which, "User-Agent" is the name of the header field, further confusing things.
