### ISSUE TITLE
Expect-CT report-uri should be quoted

### ISSUE THREAD

**Issue by estark37** [httpwg/http-extensions#312]
The report-uri syntax in Section 2.1.1 should quote the `absolute-URI`. This would most closely match HPKP, for which the report-uri syntax is not specified but all given examples are quoted. (https://tools.ietf.org/html/rfc7469#section-2.1.5)

**Comment by reschke** [comment]
Actually, it should be silent on this.

Any parameter should take *either* token *or* quoted-string, without exception.

If the type of the parameter always requires to use quoted-string, that's fine and is something the sender needs to be aware of. That said, it should not be enforced in the grammar.

**Comment by estark37** [comment]
On second thought. I'm going to WontFix this. I don't think there's any reason that the report-uri has to be quoted, and since the syntax already differs somewhat from HPKP, I don't think we need to match the examples in the HPKP spec that closely.
