### ISSUE TITLE
Expect-CT uses cookie syntax

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#316]
Roy noted that the header syntax is copied from Cookies, which is an abomination.

We have the header-structure draft, which this could follow. Many of the other recent header fields that use comma-separated lists with semi-colon-separated parameter maps could serve as an example.

**Comment by reschke** [comment]
Does it? I don't think so:

> Expect-CT-Directives = directive *( OWS ";" OWS directive )
> directive            = directive-name [ "=" directive-value ]
> directive-name       = token
> directive-value      = token / quoted-string

**Comment by martinthomson** [comment]
What is the definition for `Expect-CT` itself?  Because you are right, this looks fine.

**Comment by reschke** [comment]
This seems to be the ABNF for the field value (good), but the prose could be a bit more clear about that.

**Comment by martinthomson** [comment]
We can close this (invalid) and I will open a smaller issue about the definition of `Expect-CT` itself.  That can be just editorial.

**Comment by royfielding** [comment]
No, it is supposed to be a list.  It is defined as a semicolon-separated list.  That's the cookie syntax.

It should be

```
   Expect-CT       = #directive
   directive       = directive-name [ "=" directive-value ]
   directive-name  = token
   directive-value = token / quoted-string
```

**Comment by reschke** [comment]
:-) just because it doesn't use list syntax doesn't make it like cookies. For instance, that would make Content-Type "cookie-like" as well.

That said: yes, this might be a candidate for list syntax.

**Comment by martinthomson** [comment]
I agree that the current text is incredibly opaque.  I think that #318 is OK to replace this.
