### ISSUE TITLE
Potential security issues with ORIGIN frame

### ISSUE THREAD

**Issue by wolfbeast** [httpwg/http-extensions#339]
When investigating http extensions, I came across the `ORIGIN` frame draft here.

Although I think the goals set out for it are good, there are some inherent issues with adding this extension:
- Service exposure on servers: the `ORIGIN` frame will potentially expose previously unknown services on the same host (e.g. administration interfaces on different ports) that should not be advertised.
- Shared-host exposure: the frame will (by design) expose other domains/hosts served by the same server. For shared hosts, this can cause severe privacy issues by exposing which other domains/hosts are served by the same server.
- Origin IP exposure: unless explicitly filtered out, any reverse-proxied connection can expose the origin server's IP to a connecting client, due to the previous point's type of exposure. 
e.g. `example.com` is proxied, `example2.com` is not proxied. Connecting to `example.com` connects to the proxy, exposes `example2.com` also being hosted in the `ORIGIN` frame. Looking up `example2.com` in DNS then exposes the origin IP of `example.com`.

**Comment by enygren** [comment]
Since the ORIGIN frame can only be used for hosts covered by the TLS certificate, how does this make 1 and 3 worse?  All of these can already be seen in the certificate (at least until certificate pushing is defined).  For the second point, that may be worth calling out in Security Considerations that giving ORIGINs for specific names which are covered by a broader wildcard certificate may expose information about the server to the client (albeit intentionally on the server's behalf).

**Comment by wolfbeast** [comment]
The first is an issue because it exposes port numbers. Stuff you can otherwise only garner from port scanning (which any IDS will easily catch and halt)
The other points are worse because it provides direct confirmation that the hosts covered are _actively_ running on the same machine. That is crucial information and lead to discovery of information a server operator may not want exposed. Certificates often cover more hosts than are running on servers, but the origin frame will actually confirm which hosts are running on which servers; and as said, can indirectly lead to origin IP discovery (making the server more effectively targetable for DoS attacks, bypassing a CDN, for example)

**Comment by martinthomson** [comment]
I don't get this.  Why would a server advertise something that it doesn't want to advertise?  This is entirely voluntary for servers.

**Comment by wolfbeast** [comment]
Let me ask you this then: does it offer granular control over exactly which hosts are being advertised in this frame on a multi-homed server with a broadly-covering certificate?

**Comment by mcmanus** [comment]
yes - the point of the origin extension is fine grained control of which
origins you wish to advertise on a per connection basis.

**Comment by wolfbeast** [comment]
Well, considering the following in the document:

> senders are encouraged to include as many origins as practical within a single ORIGIN frame

One would assume that server implementations would use a default set of all active hosts served by the server that are part of the TLS certificate. So as it stands, this fine-grained control will likely not be security-aware unless a server implementation does not make this assumption and requires administrators to specifically indicate which hosts to advertise. The document focuses mainly on client implementations and should be extended to address these concerns for the server side.

Don't get me wrong, there's nothing _inherently_ wrong with the spec, but as the issue title said, there are certainly _potential_ security issues with this extension, depending on how it is implemented and to what level configuration is possible. That should be given some more attention.

**Comment by mcmanus** [comment]
On Fri, Apr 28, 2017 at 9:09 AM, Moonchild <notifications@github.com> wrote:

> senders are encouraged to include as many origins as practical within a
> single ORIGIN frame



ah - that language can be tweaked. It is meant to say "dear servers: you
are encouraged to use as few frames as possible to send your origin set"
(as opposed to one origin per frame).

it isn't meant to influence which origins you decide to advertise.

overall though I think you're right that its worth a sentence in the
security considerations to just say pay attention to what you advertise.
