### ISSUE TITLE
Viewport Height

### ISSUE THREAD

**Issue by JamiesonRoberts** [httpwg/http-extensions#342]
With the slow but continual adoption of CSS grid's and allowing of 2 dimensional layouts, as well as the push to eliminate render blocking CSS for initial views, it would be incredibly useful to be able to capture both the width and height of the requesting viewport to handle server side inclusion of the specific styles needed for the initial view. This allows developers to not have to tightly align their markup creation with the style creation and maintain the separation of concerns.

**Comment by mnot** [comment]
It's probably best to bring this up the mailing list.
