### ISSUE TITLE
text about why RFC 3490 is cited is missing

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#343]
See the annotation in https://greenbytes.de/tech/webdav/rfc6265.html#RFC3490

**Comment by reschke** [comment]
Opened https://github.com/cabo/kramdown-rfc2629/issues/42

**Comment by mikewest** [comment]
Will be addressed in the -02 I'll be uploading shortly, thanks to your patch in https://github.com/httpwg/http-extensions/commit/d5f7cb8c000f7a5c6d3545827883efe1a90eac99.
