### ISSUE TITLE
ORIGIN and Server Push

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#355]
#349 made me realise that, from the server's perspective, they don't have hard information about whether the client supports ORIGIN at the time they send the ORIGIN frame. 

While they might gather this based upon the requests that the client subsequently sends, this isn't information you'd want to rely upon.

This is especially relevant to Server Push. Right now, ORIGIN is defined to affect what the client is able to push, but (as above), the server doesn't have a firm idea about the origins that are actually valid to use on the connection at any given time. 

A number of potential solutions:

1. The server just speculatively pushes and figures it out based upon the responses (i.e. no change)
2. We create an explicit signal from the client to the server (e.g., "I will process ORIGIN", probably a SETTING, or "I have processed ORIGIN", probably a frame)
3. ORIGIN doesn't constrain Server Push

Note that 1 is not optimal (wasted bytes), and 3 might collide badly with future uses of ORIGIN.

**Comment by icing** [comment]
_what the_ server _is able to push_, you mean?

Hmm, I would expect a server that sends out ORIGIN to have a positive idea what it is willing to serve on the connection. If it has no clear idea, it should probably refrain from ORIGIN?

If I understood correctly, the question boils down to: "Can the server, having send out ORIGIN, still PUSH resources from domains that are not in ORIGIN?"

And my answer would be no. I would like to use ORIGIN to hint to the client that on any other domain, it can expect a 421 as answer. The reason for that lies in separate TLS options for hosts that share a certificate. If those differ, the server should not server _or push_ resources from the other domain. It could require a client cert, or only stronger ciphers.

**Comment by mnot** [comment]
@icing - the server doesn't know whether the client implements ORIGIN. It may have different PUSH strategies based upon ORIGIN support.

**Comment by mnot** [comment]
(It may be a corner case now, but if we open up the origin set a la CERTIFICATE, we'll hit this. That might be an argument for approach 1 - i.e., "we'll deal with it then.").

**Comment by icing** [comment]
It could, yes. But is that sane? Can ORIGIN require that the server answers requests outside of those domain the same way, no matter if the client understands it or not?

**Comment by mcmanus** [comment]
even in the absence of ORIGIN, the server does not know the client's effective origin set unless it is completely ignoring 7540 coalescing.. as mike bishop says we don't standardize pki decisions. istm its just a particular instance of a general push problem.

**Comment by kazuho** [comment]
@mnot 
> (It may be a corner case now, but if we open up the origin set a la CERTIFICATE, we'll hit this. That might be an argument for approach 1 - i.e., "we'll deal with it then.").

My +1 goes to this.

When servers start sending secondary certificates to expand the authority (than that allowed by the names stored in the certificate sent during the TLS handshake), we would inevitably requiring the client to send a signal indicating if it accepted the certificate, which can be used as a signal.

Until then, I think that there is no need for an indication.

In fact, I think that it might be a good idea to clarify that the ORIGIN frame only changes what a _client_ is expected to request, and that it does not change what a server is allowed to push.

**Comment by mcmanus** [comment]
in the end, there are always going to be two different evaluations of the can-i-push rule and its going to be done on a per origin basis - once on the server and once on the client. This is just a generalization of the existing situation (and yet another example of the complexity of push). That's true of 7540 coalescing (e.g. client has a key pin rule that prohibits the coalescing the server doesn't know about), origin, and certificate.

I really think the RST_STREAM mechanism is sufficient - perhaps with a new error code made available for it.

This is an argument for 1.

**Comment by mnot** [comment]
Sounds like there's agreement on #1; closing with no action.
