### ISSUE TITLE
Form-encode Expect-CT report bodies?

### ISSUE THREAD

**Issue by estark37** [httpwg/http-extensions#356]
Background for this issue is in https://github.com/bifurcation/expect-ct/issues/18, where it is argued that Expect-CT reports should have a special Content-Type, like Content Security Policy reports, but it is also argued that they should be sent with CORS preflights when Expect-CT is implemented by a web browser, since they are not a whitelisted safe request.

Unfortunately, implementing preflights for Expect-CT reports probably can't be done in Chrome in any reasonable amount of time, and would probably be difficult for other implementors as well. Expect-CT is checked at connection setup time, completely divorced from any context from which we can construct an `Origin` header.

Therefore I think we need to resort to using `application/x-www-form-urlencoded` for reports, if we want Expect-CT to be reasonably implementable in a web browser without violating the SOP.

@scotthelme @mikewest @eranmes

**Comment by estark37** [comment]
@sleevi do you think this is the right way forward given the time pressures on Expect-CT?

**Comment by sleevi** [comment]
@estark37 It's above my paygrade. I'm not sure these requests should abide by CORS, especially if we think of "Expect-CT" as part of an input to the PKI validation blackbox, but if it helps adoption, then such is the life of standards and compromises.

**Comment by reschke** [comment]
Use an HTTP method other than POST?

**Comment by estark37** [comment]
@reschke that doesn't resolve the issue; preflight requests are required as long as there is a non-whitelisted `Content-Type` header of application/json.

**Comment by reschke** [comment]
That would be a bug in CORS. No preflight is needed if the HTTP method by definition can not ve generated by an HTML form.

**Comment by estark37** [comment]
That's not a bug in CORS, it's exactly the point of CORS -- to prevent requests that cannot be generated by legacy web content (for example, via an `img` tag or an HTML form submission) unless the server opts in.

**Comment by reschke** [comment]
Yes.

But form content and links can only generate GET, HEAD and POST requests.

I was suggesting to use a different method than these.

**Comment by estark37** [comment]
But CORS also disallows non-GET/HEAD/POST methods without a preflight, and that's not a bug; it's because servers might rely on web content not being able to generate those methods and would be vulnerable if web content could send such requests.

**Comment by reschke** [comment]
Yes, indeed. I was temporarily confused.

**Comment by estark37** [comment]
After further discussion on the list (https://lists.w3.org/Archives/Public/ietf-http-wg//2017AprJun/0168.html), I suppose we should leave things as they are: leave it up to the UA to decide if and how to send preflights, with the report-collection server advised to expect preflights from some clients ("The UA MAY perform other operations as part of sending the HTTP POST request, for example sending a CORS preflight as part of [FETCH]").

While it isn't feasible to implement true preflights in a network stack like Chrome's, we could feasibly implement null-origin preflights for Expect-CT reports.

**Comment by estark37** [comment]
Moving discussion over to Fetch (https://github.com/whatwg/fetch/issues/567), will circle back here if it turns out there's something we should do in Expect-CT specifically. cc @martinthomson

**Comment by martinthomson** [comment]
@estark37, I don't want to create a false impression that there is no issue remaining.  Is your intent to track the issue we discussed in some other way?

As we discussed, I think that the requesting origin for the request is the origin of the response that contained the Expect-CT header field.

**Comment by estark37** [comment]
@martinthomson I thought your suggestion was to discuss with Fetch how to handle these requests?

I'm fine with using the Expect-CT origin as the Origin for the preflight, but I'm still not sure that the Expect-CT spec is the right place to say that, as it doesn't make sense for non-browser clients. (I think it belongs better in Fetch.)

**Comment by martinthomson** [comment]
OK, that sounds good.  My suggestion is to keep this open until we have greater clarity about how this is captured, even if that means closing this with no action because Fetch is covering it.

**Comment by estark37** [comment]
This is covered as an exception in Fetch now: https://fetch.spec.whatwg.org/#cors-protocol-exceptions
