### ISSUE TITLE
Julian's CH feedback

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#359]
http://www.w3.org/mid/624e3e87-43bc-0dc2-d38c-2d69cbb9e93b@gmx.de

Most of this is editorial, so you can dispose of it as you see fit (although some of it is likely to come back up in IETF LC if not addressed. The exceptions are **bold**; I think we need to give some sort of response to those.

* [x] Througout: avoid lowercase BCP14 keywords (may->can, should->ought to, ...), or actually invoke the new boilerplate defined in draft-leiba-rfc2119-update.
* [x] s/headers/header fields/
* [x] **It's not optimal to mention a draft that for now is work in progress so close to a "MUST", even with "optionally" sprinkled in. My recommendation continues to move all material that refers to the Key header field to an appendix.**
* [x] s/defines/defines the/
* [x] We should define "origin" somewhere (and also explain "subresource").
* [x] Througout: uppercase "header field" in section titles.
* [x] Isn't that evident because sending the hints is purely OPTIONAL anyway?
* [x] **Why aren't we using HTTP list syntax here? Also, what does it mean when the field appears more than once?**
* [x] I would rename this to "CSSVAL" (or something like that) for readability.
* [x] I would rename this to "HTML5" (or something like that) for readability. 
* [x] I would rename this to "KEY" (or something like that) for readability. 
* [x] Finally: no Acknowledgements?

**Comment by igrigorik** [comment]
> I would rename this to "CSSVAL" (or something like that) for readability.
>  I would rename this to "HTML5" (or something like that) for readability.
>  I would rename this to "KEY" (or something like that) for readability.

I'm inclined to keep them as is. The CSS spec is CSS2, not CSS values specific, and other names are auto generated -- don't think it's worth overwriting.

>> If the desired resource width is not known at the time of the request
>> or the resource does not have a display width, the Width header field
>> can be omitted. ...
>
> Isn't that evident because sending the hints is purely OPTIONAL anyway?

Yes, you could make that case, but it's there to highlight a non-obvious implementation edge case that most will not consider until much later in implementation.. I think it's worth keeping as is.

>> Save-Data = sd-token *( OWS ";" OWS [sd-token] )
>>      sd-token = token
>
> Why aren't we using HTTP list syntax here? Also, what does it mean when 
> the field appears more than once?

This is a repeat of discussion in https://lists.w3.org/Archives/Public/ietf-http-wg/2016OctDec/0688.html + https://lists.w3.org/Archives/Public/ietf-http-wg/2016OctDec/0678.html. I've added a callout for repeat fields.

---

Opened https://github.com/httpwg/http-extensions/pull/361. I believe it should address all of the above -- ptal.

**Comment by reschke** [comment]
> I'm inclined to keep them as is. The CSS spec is CSS2, not CSS values specific, and other names are auto generated -- don't think it's worth overwriting.

I think it's worthwhile to override names when those are clearly ugly because they're auto-generated (for instance, because they include a date that the reader will not care about at all).

**Comment by igrigorik** [comment]
Resolved via https://github.com/httpwg/http-extensions/pull/361.
