### ISSUE TITLE
Header relationships, cardinality

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#360]
From thread at <http://www.w3.org/mid/20170419164106.EFBCF24249@welho-filter4.welho.com>:

> Is it assumed that "Accept-CH" is given in http-equiv attribute, but "Accept-CH-Lifetime" on http response ?

Yes. 

> Or is that needed so that "Accept-CH" can be given on several times?

No, that's implicit in its definition as a comma separated list of values. Correct me if I'm wrong, but my understanding is that default semantics allow multiple headers with same field-name, as long as the field-value is defined as a comma separated list.. Meaning, there can be multiple Accept-CH header fields and they can be combined into a single list.
 
> What happens if there is several "Accept-CH-Lifetime" on response?

For Accept-CH-Lifetime, I guess we just need to specify which one wins, correct? Any defaults I can point to or reuse? Last one wins?

**Comment by igrigorik** [comment]
I believe https://github.com/httpwg/http-extensions/pull/361 should address this, ptal.

**Comment by igrigorik** [comment]
Resolved via https://github.com/httpwg/http-extensions/pull/361.
