### ISSUE TITLE
No multiple headers with the same name

### ISSUE THREAD

**Issue by vasilakisfil** [httpwg/http-extensions#365]
I just noticed that you have 2 `Link` headers in the same response. According to 7230:

>  A sender MUST NOT generate multiple header fields with the same field
>   name in a message unless either the entire field value for that
>  header field is defined as a comma-separated list [i.e., #(values)]
>   or the header field is a well-known exception (as noted below).

**Comment by vasilakisfil** [comment]
This is for Early Hints draft, not sure how I can put labels.

**Comment by mnot** [comment]
Yes, but `Link` is defined by RFC5988 as:

```
  Link           = "Link" ":" #link-value
```

i.e., it uses the comma-separated list syntax.

**Comment by vasilakisfil** [comment]
right.
