### ISSUE TITLE
Accept-CH-Lifetime privacy concerns

### ISSUE THREAD

**Issue by arturjanc** [httpwg/http-extensions#372]
Based on https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/QHI3sio6--Q/v_zWX1O6AAAJ I have a couple of questions about the impact of `Accept-CH-Lifetime` as currently defined in https://tools.ietf.org/html/draft-ietf-httpbis-client-hints-04#section-2.2.2

The main risk, touched upon in the [Security Considerations](https://tools.ietf.org/html/draft-ietf-httpbis-client-hints-04#section-5) section, is the fact that providers of cross-origin subresources (e.g. images) loaded from pages with `Accept-CH` headers will start receiving fingerprinting-prone information about the configuration of a connecting client. Note that it will expose more information than what was available to these parties in the past because subresources such as images cannot use client-side logic to access information sent in Client Hints. A related issue is that based on the sets of headers sent in such subresource requests, the subresource owner might be able to identify the referring site even if it sets a Referrer Policy to prevent disclosing its URL or origin. For example, requests from a large site which sets `Referrer-Policy: no-referrer; Accept-CH: DPR` will be distinguishable from requests from sites with `Accept-CH: DPR, Viewport-Width` and from those without client hints. Depending on the chosen set of hints this can in practice uniquely identify the origin visited by the user.

The introduction of `Accept-CH-Lifetime` will extend this problem to all resources on a given origin -- if one page sets the header, then subresource requests from all pages in that origin will start carrying hint information. This can be undesirable for the user because it can disclose information about the visited origin and broadcasts fingerprintable information to all parties from which the given origin loads subresources.

It seems like this should be mitigated, possibly by one of the following:
- (Preferably) Not broadcasting client hints on cross-origin subresource loads.
- Obeying Referrer Policy and omitting hints if the referring page attempts to restrict data which is sent in the `Referer` header. Similarly, hints should probably also be stripped on HTTPS -> HTTP transitions.

**Comment by tarunban** [comment]
> The introduction of Accept-CH-Lifetime will extend this problem to all resources on a given origin -- if one page sets the header, then subresource requests from all pages in that origin will start carrying hint information. 

IIUC, this is not correct. If the origin includes `Accept-CH-Lifetime` header, then the user agent is expected to send the client hints for requests to only that origin.

> Similarly, hints should probably also be stripped on HTTPS -> HTTP transitions.

The Chromium implementation (currently underway) processes `Accept-CH-Lifetime` header from only HTTPS origins. So, the client hints sent because the user agent received `Accept-CH-Lifetime` in the past would be sent to only HTTPS origins. Quoting the spec:

> Implementers ought to provide mechanisms and policies to control how
   and when such hints are advertised. 

cc'ing @igrigorik to comment on if any spec changes are needed here to make this more explicit.

**Comment by igrigorik** [comment]
@arturjanc thanks for the great feedback. Let me try to unpack...

Prior to introduction of `Accept-CH-Lifetime` (ACL) — which is very recent — there was no mechanism in place for an origin to persist a preference for hints across independent requests. As a result, navigation requests did not get any hints and only subrequests of the "opted-in document" were eligible. The extra complication here is that the initial set of core use cases (image optimization) frequently relies on use of CDN's and third-party services+origins, which means that prior to ACL there was no way for those origins to enable CH hints, since page origin != resource origin. As a result, the decision was to extend Accept-CH opt-in to all resources fetched by the page.

Now that we have ACL, it may be possible to revisit this setup. In particular, if we scope ACL to per-origin, then both the page origin and resource origin can advertise support separately and these preferences will be persisted across requests. In fact, I suspect that this is what will happen anyway, because for cases like image serving CDNs will advertise support for hints on their own origins, such that any site relying on their service can benefit by default.

@yoavweiss wdyt?

---

> What about HTTPS pages which have HTTP subresources? The behavior I currently see for Accept-CH is that the HTTP subresource requests have client hints (but no Referer);
> ...
> Obeying Referrer Policy and omitting hints if the referring page attempts to restrict data which is sent in the Referer header. Similarly, hints should probably also be stripped on HTTPS -> HTTP transitions.

I think this would naturally fall out of the origin-scoped model? As in, if opt-in is scoped to HTTPS then we wouldn't send hints to HTTP, unless the HTTP origin also explicitly opted-in. 

Re, Referer:  "I have third party resources on my site, which may have hints enabled, and I want to strip those alongside referrers", is that the use case? If so, that seems legitimate, but using Referer does feel a little action-at-a-distance to me. As in, I wouldn't expect Referrer to control hints? That said, I don't have a better suggestion either. @mikewest wdyt?

> A related issue is that based on the sets of headers sent in such subresource requests, the subresource owner might be able to identify the referring site even if it sets a Referrer Policy to prevent disclosing its URL or origin. For example, requests from a large site which sets Referrer-Policy: no-referrer; Accept-CH: DPR will be distinguishable from requests from sites with Accept-CH: DPR, Viewport-Width and from those without client hints. Depending on the chosen set of hints this can in practice uniquely identify the origin visited by the user.

Good points, we should flag this in the privacy & security section.

**Comment by arturjanc** [comment]
> Now that we have ACL, it may be possible to revisit this setup. In particular, if we scope ACL to per-origin, then both the page origin and resource origin can advertise support separately and these preferences will be persisted across requests.

This seems like a better model than the status quo because it limits the sending of hints to origins which opt into receiving them. However, it still has the issue of revealing new information to providers of third-party subresources which they can't obtain now. This seems fine to do with opt-in from the first party (which can already get the Viewport-Width, etc via client-side scripts and then provide it to the CDN in the URL), but seems less great if the CDN can decide to always get hints in all requests, because of the passive fingerprinting potential.

What do you think of double-keying the hints on both the first- and third-party? That is, if you set `Accept-CH(-Lifetime)`:
- Requests for same-origin subresources will carry client hints (up until the max-age if you specify the lifetime).
- Requests for non-same-origin subresources will not carry client hints if the other origin doesn't set `Accept-CH-Lifetime`.
- If you load third-party resources from an origin which sets `Accept-CH-Lifetime`, requests from your origin to the third party will carry client hints.
- Requests from other origins (which don't set `Accept-CH`) to the third party will not carry hints.

I realize this reduces the "on by default" benefit you mentioned, but it seems like a relatively simple opt-in for the first party (which is already a necessary condition in `Accept-CH`) and it mitigates the risk of enabling passive tracking of users based on client hints, which I assume will evolve to expose more interesting data. As you mentioned above, this would also make the Referrer discussion moot (and I agree that controlling client hints via Referrer Policy seems awkward).

**Comment by igrigorik** [comment]
Would double-keying have material effect on this though? Yes, implementing it this way reduces passive fingerprinting, but only for the very first visit. Nothing prevents every 3P origin from advertising a blanket opt-in policy (in fact, I expect that's exactly how image CDN's will implement it), which will result in same exposure for any repeat visit. Also, as a side effect, double-keying would expose first vs repeat visit bit?

I'm not ruling it out, but it's not clear to me that it would be a big win in this context?

**Comment by igrigorik** [comment]
@arturjanc started a branch @ https://github.com/httpwg/http-extensions/pull/373 - ptal.

**Comment by arturjanc** [comment]
Re: double-keying, the point is that if you're visiting a first party _without_ Accept-CH then the browser wouldn't send client hints to a CDN even if it sets ACL. Essentially, if you have a first party which wants to use client hints they can opt into them and then their non-same-origin subresources can gets hints if their providers also set ACL (which is fine because the first party could manually pass the hints in the URLs anyway). This prevents CDNs and other origins from which subresources are loaded from getting hints during the user's visit to non-cooperating sites, but should still offer the benefits you're looking for in cases where both parties opt in.

I commented on https://github.com/httpwg/http-extensions/pull/373 -- it looks good to me in general, modulo the broader double-keying issue (which I believe is important).

**Comment by igrigorik** [comment]
Artur: makes sense, thanks. 

@yoavweiss @tarunban curious to hear your thoughts on double-keying. Any implementation gotchas here that we should think through?

**Comment by tarunban** [comment]
No implementation gotchas wrt double-keying.

**Comment by yoavweiss** [comment]
Apologies for the late reply (was exploring the Canadian wilderness...)

I don't see a particular problem with double keying but I also don't to see the privacy advantages of it. As @igrigorik said earlier, all third parties will add an automatic ACHL and will get the hints as soon as the main document opts-in, meaning the situation will not be different from today.

I think the concerns that @arturjanc raises are real and ACHL will expose new information regarding origins that are not capable of running scripts in the context of the page, new info regarding viewport, DPR and network conditions that they don't currently have. 

Maybe we need `Accept-CH-Lifetime` to be able to define a list of hosts that will get subresource hints? I vaguely remember us discussing a proposal in that spirit in the past, but failing to find references to such a discussion.

**Comment by mnot** [comment]
*not chair hat*

Could we please stop calling this use case "CDN"? Most CDNs take all traffic for an origin, not just images, etc. (that's very 1999). It's true that some sites direct images.* to a CDN (for example), but that's not great practice.

We should really be talking about this as 3rd party content -- e.g., widgets and ads. Given the history there, it's entirely reasonable to be concerned about increasing fingerprinting exposure.

Requiring the origin to opt-in to any 3rd party CHs is an improvement, but not a huge one; it'll just give an incentive to 3rd parties to instruct the origin to set whatever policy we require.

I think that at a minimum, we should warn (Security Considerations) specifically about the new vector for 3rd party content fingerprinting here, and allow implementations to decide whether they send it to 3rd parties (at all, or when they're in private browsing mode, or...).

I'd like to also see at least consideration of making this 1st party only. Given that the use case for CH is mostly to allow intermediaries to do content optimisation -- and remembering that origins already have other techniques available to them -- I'm wondering if allowing third party origins to do intermediary-imposed optimisations is worth the potential privacy tradeoff here. After all, widgets and ads are usually served by `script` tags, so there's an opportunity for script running and URL rewriting by them before the requests are made.

**Comment by mnot** [comment]
Hey Yoav. Absolutely, but the Web security model doesn't have any concept of CDN; images.* is a third-party host as far as same-origin is concerned.

**Comment by yoavweiss** [comment]
> Absolutely, but the Web security model doesn't have any concept of CDN; images.* is a third-party host as far as same-origin is concerned.

Indeed. All I'm saying is that exposing CH to such "first party owned third parties" is a legitimate and very common use-case. I'd prefer we'd find ways to address that use-case (with appropriate means to maintain user-privacy), rather than block it.

**Comment by michael-oneill** [comment]
I agree. If subresources can use CH then it is bound to be misused. The trend is to further restrict access to third-party cookies e.g. Safari’s ITB, so there will be more incentive to find other ways to track. CH headers allow that to be done much more efficiently as there is no need for an extra roundtrip.

**Comment by igrigorik** [comment]
Thanks everyone for the feedback. 

Nomenclature discussions on "CDN" vs.  "widget" vs "3P" aside, I agree with Yoav that subresource optimization is a _critical_ use case for CH and not something we can omit. It may be the case that some particular hints make sense to be scoped to first-party only, but that's a discussion we should have in the context of individual hints; as a general mechanism, CH must support delivery of hints to all origins, possibly with knobs for 1P origin to control which 3P origins are allowed to receive hints. 

**Current proposal for `Accept-CH-Lifetime` is to allow hint preferences to be registered by any origin.** The limitation, as pointed out in discussion above, is that it doesn't provide any distinction between 1P or 3P opt-in. To that end, we discussed a few options:

1. We can add double-keying to scope 3P registrations to within 1P origin — i.e. 3P registration on foo.com does not propagate to same 3P origin on bar.com.
1. We can further restrict 3P ability to register for hints by requiring that 1P opts in for receiving CH hints — i.e. what @arturjanc proposed above.

FWIW, I think (1) is the right behavior, from a user perspective. However, what it doesn't address is the 1P -> 3P delegation case where 1P origin may want to control if (and which) 3P is allowed to request CH. @arturjanc's proposal (b) is an attempt at this, but a fairly blunt one: 3P is allowed to receive hints if 1P opt's in, but this is a blanket policy for all 3P origins and it similarly doesn't provide any fine grained control for which hints are allowed to be requested. If we all agree that the "1P -> 3P hint delegation" use case is an important one, I think we need to explore mechanisms beyond (b). 

To that end, squinting at this space, I see close parallels to Feature Policy: we have features (hints) that we want to selectively enable/disable, and we may want to scope them to a list of origins — e.g. enable them for "self" / 1P only, selectively enable them for some set of origins, or disable them outright. And so, here's my crazy proposal of the day: 

1. ACL registrations should be double keyed -- see (1).
1. Control over which hints are enabled, plus delegation, should (?) be addressed via Feature Policy. 

```
Feature-Policy: {
   "ch-dpr": ["self"],  // DPR hint is 1P only
   "ch-ex1": ["self", "foo.com", "bar.com"],  // ex1 hint is 1P + select 3P
   "ch-ex2": [] // ex2 hint is disabled for everyone
} 
```

The other benefit here is that this opens a well-defined way to think about a "default FP policy" for each hint. For example, some hints may be restricted by the UA to be 1P only, other may be on-by-default for everyone (e.g. save-data), and others may be off by default.

WDYT? Crazy talk? :)

/cc @clelland @rbyers

**Comment by clelland** [comment]
It's not the craziest thing I've read today :)

It's a bit mind-stretching to think of these as features, but it definitely is a kind of power or trust that is being delegated to other origins by the embedding page, so it's not *too far* from the goals of feature policy.

One question I would bring up would be regarding the inheritance of ACL in deeply-nested frame trees -- Feature Policy's model is that once disabled in an frame, a feature can never be reenabled by any subcontent; I wouldn't want to break that invariant without a real compelling case.

With the FP model, if `a.com` embeds `b.com`, and does not grant it the ability to receive hints, then it is not possible for `b.com` to embed a fourth-party, `c.com`, and have hints sent to *that* domain instead. That sounds like desirable behavior to me, but I don't think it's been brought up on this thread yet.

**Comment by igrigorik** [comment]
I think FP's current inheritance behavior makes perfect sense in this context as well. If I disable use of a particular hint on my site, I expect this policy to propagate to all nested frames.

**Comment by tarunban** [comment]
> If we all agree that the "1P -> 3P hint delegation" use case is an important one

Naive question: IIUC, any information that can be obtained by an origin via client hints can also be obtained by that origin using a combination of Javascript and cookies. Is it currently possible for 1P origins to control Javascript/cookies behavior of 3P origins?

**Comment by tarunban** [comment]
At a high level, I am not sure why the client hints permission for foo.com is not the same as (permission for foo.com to run Javascript AND permission for foo.com to store cookies)?

**Comment by igrigorik** [comment]
@tarunban the key difference here is passive content (e.g. images, audio, video, etc): today such resources/origins cannot obtain data that we expose with CH, unless there is active content executing in top level page and scheduling their fetches. I think it's reasonable for origins to have control over whether such passive content providers should be able to request data exposed by CH.

**Comment by mnot** [comment]
Really interesting, Ilya. It *is* a big change :)

On the face of it, it seems workable. Feature Policy doesn't have a concept similar to `Accept-CH-Lifetime`; would that move into FP, or remain CH-specific?

I'm not crazy about the verbosity of `Feature-Policy`, nor the (relative) complexity. Also a bit concerned about making such a prominent part of CH an external dependency -- especially since FP is effectively browser-specific, whereas I suspect at least some people want CH to be applicable to other HTTP clients.

Still digesting...

**Comment by yoavweiss** [comment]
Interesting indeed!
a few thoughts:
* FP's inheritance model makes some sense, but *is* more restrictive than info that iframes currently have (as iframes are *not* passive content). Would've been great if we could limit exposure of privacy sensitive info to 3rd party passive content while enabling it for active content (by allowing new contexts to override). One use case I can think of is an ad iframe that wants to do the right thing in terms of DPR/viewport based image compression will now require all embedding sites to opt-in, which most won't.
* This will obsolete `Accept-CH` entirely, correct?

**Comment by yoavweiss** [comment]
Not essential to the proposal's semantics, but seems like FP is [moving away](https://groups.google.com/a/chromium.org/d/msg/blink-dev/uKO1CwiY3ts/2pSbOUb3CQAJ) from JSON towards a CSP-like structure.

**Comment by reschke** [comment]
Interesting. I'm pretty sure that the newly proposed syntax has several flaws.  See my comment over there.

**Comment by yoavweiss** [comment]
@reschke Could you add a link to your comments? I'm failing to find them...

**Comment by reschke** [comment]
https://github.com/WICG/feature-policy/issues/78#issuecomment-326544934

**Comment by igrigorik** [comment]
@mnot @yoav I'm _not_ suggesting we rebase the entire opt-in mechanism against FP — it's also not sufficient on its own because, as you pointed out, it's missing ACHL semantics amongst other things. Rather, I'm suggesting that we should separate these concerns: 

- Accept-CH + Accept-CH-Lifetime define a mechanism for origins to advertise their hint and hint lifetime preferences for subsequent visits; these two primitives are used to negotiate what hints will be made available to the origin.
- With above in place, delegation is — I claim — a separate and complex enough problem that deserves its own treatment. As it happens, that's what FP is solving, and we should leverage that. 
  - We _can_ still make a default double-keyed recommendation for 3P opt-in.
  - We _can_ define default hint policies in terms of FP primitives.

Yes, we are coupling two mechanisms here, but delegation is not an easy problem and I'd much rather we reuse mechanisms than try to blaze yet another trail here. Also, it's true that FP is designed with browser in mind, but there is no reason why it can't or shouldn't work with other types of clients.

**Comment by igrigorik** [comment]
Updated https://github.com/httpwg/http-extensions/pull/373 with outstanding feedback — ptal. 

As a quick recap, with #373 we have:
 - Accept-CH and Accept-CH-Lifetime are the mechanisms to advertise support and lifetime prefs.
  - Both are scoped to secure transports.
  - Preference is bound to the origin / double-keyed.

Current update does _not_ address delegation. As proposed above, I'm suggesting we solve that part of the problem via Feature Policy. If that sounds reasonable, I can add some language in #373 to outline how/where this should be defined.

WDYT?

**Comment by igrigorik** [comment]
@arturjanc @mnot @yoavweiss friendly bump.. :bowtie:

**Comment by tarunban** [comment]
Is this fixed?

**Comment by mnot** [comment]
I think it'd be good to see #373 in situ; from what I see in the patch, I think it's strictly better. No guarantees that there aren't other issues, or that this isn't completely covered, but personally I think it's better.

**Comment by igrigorik** [comment]
I've landed #373. As a tl;dr on substantive changes: 
- Accept-{CH,CH-Lifetime} opt-in is scoped to secure transports
- Opt-in preference is bound to opt-in origin

In effect, this update makes Client Hints HTTPS-only and opt-in preference is double keyed against opt-in origin. We've also updated [security considerations section](http://httpwg.org/http-extensions/client-hints.html#security-considerations) to reflect these updates.

---

The one remaining thread raised in this issue is around "hint delegation": if origin A is loading a subresource from origin B, can A control if B is allowed to opt-in to receive hints? As it stands today, the answer is "yes", and CH does not define a mechanism to control this.

I do think this is a valid use case, but I don't think we should be solving it within CH directly. Rather, we should be reusing client specific infrastructure to address this.. e.g. in a context of a browser that's [Feature Policy](https://wicg.github.io/feature-policy/), which provides a mechanism to selective enable/disable features and defines relevant delegation mechanisms — e.g. policy based, frame-level control, cascading logic, etc.

So, my proposal here is:
 - @arturjanc I believe we addressed your original concerns via #373. 
    - We can resolve this thread
    - Publish new 05 draft with updates in #373
 - Pursue delegation discussions in context of Feature Policy.

@arturjanc @mnot does that sound reasonable?

**Comment by arturjanc** [comment]
Thanks, Ilya! I re-read the spec with your changes and I also think it's a significant improvement, particularly when it comes to binding subresource hints to the opt-in origin, hindering cross-origin linking between 1p sites which don't use `Accept-CH`.

My main outstanding worry is indeed the "hint delegation" issue you mentioned above: specifically, the fact that opting an origin into receiving hints still results in sending hints on subresources by default if the 3p also opts in, potentially giving it information about the referring page that it wouldn't currently receive. Similarly, such 3p origins hosting subresources used by an `Accept-CH`-enabled origin would start getting hints which disclose a few bits of information about the user and could be used for opportunistic linking across 1p visits to different `Accept-CH`-enabled origins.

I like the idea of using Feature Policy to control this, but it's doubtful that developers would understand the privacy benefit of restricting subresource hints via FP, which means they wouldn't take action to prevent them from being sent. What do you think about flipping this around and only sending hints on 3p subresource requests if the origin is explicitly whitelisted via Feature Policy? This would be a direct signal from the developer that they want to trust the third-party, and might be more in line with the interests of both the first-party and the user.

**Comment by yoavweiss** [comment]
> What do you think about flipping this around and only sending hints on 3p subresource requests if the origin is explicitly whitelisted via Feature Policy? This would be a direct signal from the developer that they want to trust the third-party, and might be more in line with the interests of both the first-party and the user.

I'd be supportive of restricting third party access by default and providing a Feature Policy explicit opt-in to specific third-party domains that the origin trusts.

**Comment by tarunban** [comment]
How important it is to expose client hints to third party domains? It seems that even now (without Accept-CH header) first party can provide client hints to the third party domains as URL parameters. In that case, I wonder if it is worth the effort to tie Accept-CH for third-party with Feature Policy, or we should just: (i) Restrict Accept-CH to only first part domains; and, (ii) Let first party use URL parameters to pass on the client hints to third parties.

The goal of Accept-CH was to provide client hints to the first parties in the very first HTTP request itself. Restricting third party access by default does not affect that goal, so I am in support of it.

**Comment by igrigorik** [comment]
> How important it is to expose client hints to third party domains? It seems that even now (without Accept-CH header) first party can provide client hints to the third party domains as URL parameters. In that case, I wonder if it is worth the effort to tie Accept-CH for third-party with Feature Policy, or we should just: (i) Restrict Accept-CH to only first part domains; and, (ii) Let first party use URL parameters to pass on the client hints to third parties.

That's precisely the problem we're trying to solve, you shouldn't have to jump through these hoops as it doesn't play well with caching, and doesn't work for dynamic preferences (e.g. save-data, memory, etc) where the URLs would have to be dynamically generated for each request and enumerate all the hints. This _is_ what some sites already do today, but it's gnarly and complicated solution that doesn't play well with edge delivery / hinders automation of this space.

> My main outstanding worry is indeed the "hint delegation" issue you mentioned above: specifically, the fact that opting an origin into receiving hints still results in sending hints on subresources by default if the 3p also opts in, potentially giving it information about the referring page that it wouldn't currently receive. Similarly, such 3p origins hosting subresources used by an Accept-CH-enabled origin would start getting hints which disclose a few bits of information about the user and could be used for opportunistic linking across 1p visits to different Accept-CH-enabled origins.

Can you elaborate on a particular use case or example that you're worried about here? I hear your concern, but I'm not convinced that the real risk is any more significant than what is already exposed by most sites to 3P's through active content (or CSS even). 

> What do you think about flipping this around and only sending hints on 3p subresource requests if the origin is explicitly whitelisted via Feature Policy? 

On a tactical (spec language) level, FP is a UA-specific concept and I don't think we can couple it here with CH; FP does not apply to non-UA clients. On the other hand, a UA may choose to define a "default off" FP policy for CH for 3P origins and that's totally fine: that's an implementation decision of the UA, and different UAs may even chose different policies for different hints, instead of applying a blanket policy for all CH hints - e.g. Chrome communicates Save-Data hint to all origins today if data saver feature is enabled.

As such, I think we can add some language in CH to explain and allow for above implementation options, but I don't think we can dictate a default FP policy in this spec. 

Spec language bits aside, and with respect to UA implementation: I think we should have a more detailed conversation, on a hint-by-hint basis, to determine default on/off policies, and I'd suggest that we move that discussion to FP forum. 

Does that sound reasonable to you guys?

**Comment by arturjanc** [comment]
> Can you elaborate on a particular use case or example that you're worried about here? I hear your concern, but I'm not convinced that the real risk is any more significant than what is already exposed by most sites to 3P's through active content (or CSS even).

I'd set aside the case of fully active content and focus on 3p resources that do not allow the hosting party to get information that would be exposed in hints (i.e. loading content such as images, fonts, audio/video, or even JS/CSS pinned to a specific version via Subresource Integrity). If a website loads such resources -- which is very common -- and it enables hints, *and* the 3p separately also enables hints, it has two consequences:

- The user will start sending hint information to the third party, which may allow the 3p to correlate requests from that user across different 1p sites which use hints, even if third-party cookies are disabled. The hints will also be sent automatically, rather than require active probing, which will result in potentially fingerprintable information being sent out to third parties which either couldn't obtain it, or which likely wouldn't resort to actively detecting it and sending it out.
- The user will start sending hint information which might tell the 3p which website/page the user is on, even if the website uses Referrer Policy to remove the Referer header (e.g. in the case where the 3p knows their resource is being loaded by 10 other sites, and only 1 of them enables the set of hints they see in the request).

This behavior is arguably worse privacy-wise than the status quo for users of sites which enable hints. I like being able to control 3p hints via FP, but developers won't understand why they might want to do it (partly because the third-parties they load data from might not enable hints until later, so the developer would not see them in 3p requests while testing on their sites).

FWIW I do think this is strictly better than the original proposal, so "3p hints should be off by default unless enabled by Feature Policy" is not a hill I'd want to die on. Solving this with safe defaults at the FP level sounds okay; I'm a little wary about relying on a completely independent mechanism to enforce good privacy properties of client hints, but it's probably workable -- we'd just need to have the FP-focused discussion about this.

**Comment by igrigorik** [comment]
@arturjanc thanks, I think we're converging on a good solution here.

a) Opened a feature request against FP: https://github.com/WICG/feature-policy/issues/129
b) Assuming we all agree on the above, I'd propose the following update in CH...

```diff
diff --git a/draft-ietf-httpbis-client-hints.md b/draft-ietf-httpbis-client-hints.md
index 91ebc81..4455ff0 100644
--- a/draft-ietf-httpbis-client-hints.md
+++ b/draft-ietf-httpbis-client-hints.md
@@ -100,7 +100,7 @@ A Client Hint request header field is a HTTP header field that is used by HTTP c

 ## Sending Client Hints

-Clients control which Client Hints are sent in requests, based on their default settings, user configuration and/or preferences. The client and server can use an opt-in mechanism outlined below to negotiate which fields should be sent to allow for efficient content adaption.
+Clients control which Client Hints are sent in requests, based on their default settings, user configuration, and server preferences. The client and server can use an opt-in mechanism outlined below to negotiate which fields should be sent to allow for efficient content adaption, and optinally use additional mechanisms to negotiate delegation policies that control access of third parties to same fields.

 Implementers should be aware of the passive fingerprinting and network information disclosure implications when implementing support for Client Hints, and follow the considerations outlined in "Security Considerations" section of this document.

@@ -263,6 +263,7 @@ Transmitted Client Hints header fields SHOULD NOT provide new information that i

 Implementers ought to consider both user and server controlled mechanisms and policies to control which Client Hints header fields are advertised:

+  - Implementers SHOULD restrict delivery of some or all Client Hints header fields to the opt-in origin only, unless the opt-in origin has explicitly delegated permission to another origin to request Client Hints header fields.
   - Implementers MAY provide user choice mechanisms so that users may balance privacy concerns with bandwidth limitations. However, implementers should also be aware that explaining the privacy implications of passive fingerprinting or network information disclosure to users may be challenging.
   - Implementations specific to certain use cases or threat models MAY avoid transmitting some or all of Client Hints header fields. For example, avoid transmission of header fields that can carry higher risks of linkability.
```

To recap, this would leave us with:
- CH is HTTPS only
- Delivery of hints is bound to origin and requires explicit origin opt-in
- FP controls 3P delegation for UAs, with custom default policies for each hint:
  - By default most hints are scoped with FP policy of `self`, which means that 1P has to explicitly allow 3P's to request access to the hint. 
  - One exception today is Save-Data, which we believe (and as currently implemented in Chrome) should have a default FP policy of `*`.

Does that land us in a good place to resolve this thread? :-)

**Comment by yoavweiss** [comment]
LGTM2! :)

**Comment by igrigorik** [comment]
Excellent, looks like we've landed in a good place! I've updated the CH spec and resolving this issue. Let's continue the FP discussion in WICG/feature-policy#129. 

Thanks all for your patience and help here!

**Comment by npdoty** [comment]
I'm confused by this text, given my understanding of the resolution of this issue:
>    Implementers SHOULD restrict delivery of some or all Client Hints
      header fields to the opt-in origin only, unless the opt-in origin
      has explicitly delegated permission to another origin to request
      Client Hints header fields.

Why SHOULD and not MUST? Why the qualification of "some or all"? If explicit delegation of permission is required (through feature policy or some other means), shouldn't we just say so? Also, would it help to cite Feature Policy explicitly?

**Comment by igrigorik** [comment]
I don't think we can or should assume that the only "client" for CH is a browser. I may be building a (native) app that's not subject to this and hence SHOULD. Does that sound reasonable?

**Comment by npdoty** [comment]
I'm not sure I understand. In your non-browser app example, will the opt-in origin not delegate permission to another origin but the app will choose to send Client Hints to that other origin anyway? Is there a reason that behavior needs to be considered conformant? Or just that delegated permission will be communicated in a different way than Feature Policy for non-browser clients?

Re-reading this thread, it seems like maybe "some or all" is here because `Save-Data` is considered a special case where first-party opt-in won't be required. That seems like something that could be explicitly stated, rather than needing to dig through issue threads to discover.

**Comment by npdoty** [comment]
Gotcha. So it sounds like there is agreement that non-browser clients should restrict delivery unless there is explicitly delegated permission, and just that in the non-Web case that permission might be delegated through means other than Feature Policy, e.g. internal policy implemented through server/client code.

Can we remove "some or all" or explicitly note the hints that aren't restricted to particular origins? Do we want this to be SHOULD even if it applies to all kinds of servers/clients?

**Comment by igrigorik** [comment]
> Can we remove "some or all" or explicitly note the hints that aren't restricted to particular origins? 

As outlined in https://github.com/WICG/feature-policy/issues/129, in some cases the default "delegation policy" can be "*" — i.e. deliver to all. Concrete example today is Save-Data, where Chrome decided to deliver this hint on all requests when Data Saver feature is enabled. As such, I think we need to keep the "some or all".

> Do we want this to be SHOULD even if it applies to all kinds of servers/clients?

"MUST ... some or all" doesn't seem right? In fact, I'm wondering if I ought to convert all the capital terms in that sections to non-normative.

**Comment by mnot** [comment]
Generally, 2119 requirements in Security Considerations are a bit weird / frowned upon. Requirements are to improve interop; general advice to specifications and implementations aren't what they're for. 

Also, the W3C TAG has expressed some sadness about these requirements. So personally I think that turning this text into prose is appropriate, FWIW.

**Comment by thiemonagel** [comment]
Now that Save-Data has been dropped from the spec, would it make sense to revisit the "some or all" language?

**Comment by thiemonagel** [comment]
> CH is HTTPS only

The way I read the spec, secure transport is only required for CH opt-in, but CH could be delegated to non-secure origins via Feature Policy. Do you agree with that reading of the spec? Is it intentional to allow CH for (some) non-secure connections? -- That would provide passive network attackers with additional information to track users which I don't think is good.

**Comment by igrigorik** [comment]
@thiemonagel Save-Data is alive and well, we just moved its definition to [NetInfo API](https://wicg.github.io/netinfo/#save-data-request-header-field). 

Re, opt-in: you cannot opt-in an non-secure origin. The opt-in only extends to the origin for which it was advertised, and CH is now scoped to only support opt-in on secure origins.

**Comment by thiemonagel** [comment]
> Save-Data is alive and well, we just moved its definition to NetInfo API.

Thanks! Where can the complete list of client hints be found? Would it make sense to insert a reference?

> The opt-in only extends to the origin for which it was advertised, and CH is now scoped to only support opt-in on secure origins.

Thanks! I missed that for 3rd parties both delegation and opt-in are required. (Would it make sense to spell out explicitly that secure transport is a prerequisite, e.g. in 2.1. or in 5.?)

**Comment by igrigorik** [comment]
> Where can the complete list of client hints be found?

@dret assuming upstream specs provide the IANA registrations with a CH note, is there a page where we could see all the CH hints in one place? 

@thiemonagel in the meantime, at least for Chrome: https://client-hints-demo.appspot.com/

> Would it make sense to spell out explicitly that secure transport is a prerequisite, e.g. in 2.1. or in 5.?

We already do in:
- https://httpwg.org/http-extensions/client-hints.html#rfc.section.2.2.1
- https://httpwg.org/http-extensions/client-hints.html#rfc.section.2.2.2

**Comment by dret** [comment]
> @dret <https://github.com/dret> assuming upstream specs provide the IANA 
> registrations with a CH note, is there a page where we could see all the 
> CH hints in one place?

yes, but only if the spec creates a registry of the hints and 
requires/recommends hints to be registered.

i may understand the spec wrong, but currently there is no clear 
definition of which header fields can be used in Accept-CH, right? if 
that's true, then almost be definition *all* registered header fields 
can be CH hints, right?

for this to be different, a registry might be the way to go.

**Comment by mnot** [comment]
I don't understand the value a registry would provide here.

The primary reason for registries -- avoiding collisions -- is already served by the HTTP header registry. 

Is there any technical use case for being able to recognise that a particular header is a client hint without actually implementing it?

**Comment by dret** [comment]
On Oct 1, 2018, at 08:46, Mark Nottingham <notifications@github.com> wrote:
> I don't understand the value a registry would provide here.
> 
the question was how to have a place where to look up possible client hints. a registry would be one way of achieving that, right?
> Is there any technical use case for being able to recognise that a particular header is a client hint without actually implementing it?
> 

that i don't know. i just wanted to point out one possibility how to provide a list of possible client hints.

**Comment by thiemonagel** [comment]
Say I'm a web developer and I'd like to know which values I can set for Accept-CH. Shouldn't the spec answer that question, if only by referring to some other doc?

**Comment by mnot** [comment]
Client Hints is a framework describing a pattern of use for other headers. It's not developer documentation, as such; I think we'd expect that need to be filled elsewhere (e.g., books, blog entries, etc.).
