### ISSUE TITLE
Early Hints and Caching Intermediaries

### ISSUE THREAD

**Issue by filex** [httpwg/http-extensions#374]
The proposal for the _103 Early Hints_ response contains a few examples referencing (probably caching) intermediaries. For example, to trigger a h2 server-push when an origin sends a 103 carrying `Link` headers. However, there is no explicit definition on what a cache or proxy server may or may not do with 103 responses.

By definition, the informational response cannot have any own meta data:

_"A client MUST NOT interpret the 103 (Early Hints) response header fields as if they applied to the informational response itself"._

Obviously, 103 is not among the status codes cacheable by default defined in [RFC7231 6.1](https://tools.ietf.org/html/rfc7231#section-6.1). Furthermore the response cannot contain an entity body and it must be considered an intermediate response as the final response is still to come. I assume all that forbids storing the 103 in a cache.

Considering the objective to speed up Web site delivery, I would like to discuss the idea of adding a mechanism that would allow an intermediary cache to store data from the 103 response.

In a CDN-like setup an edge-server first receives an HTTP request and forwards it to the origin. Let's say the final answer took a long time, was private and could not be stored in the cache. However, a 103 intermediate response was received in the mean time and forwarded to the client. For subsequent requests to the same URL (according to the cache key calculation…) the edge cache could send the _cached_ 103 downstream to the client while the original request is sent upstream to the origin _at the same time_. I think this could be a very effective way to use waiting time.

A similar situation was proposed at the end of section 2, where an _"intermediary generates a 103 (Early Hints) response based on the header fields of a stale-cached response"_. However, this can only apply to cacheable content. But HTML documents are most often private.

To avoid "guessing" in intermediaries, we could define a special Cache Control header field accompanying the 103 status, such as `Early-Hint-Control`. An origin could then define a 103 to be cacheable in a proxy server or cache. For subsequent requests the stored 103 could be sent downstream regardless of whether the final response is public or private.

The header field could follow the `Cache-Control` semantics. The `public` and `max-age=N` directives seem appropriate. A proxy server would have to store the Early Hint information apart from regular responses (e.g. 200) to not confuse it with a final response. When the field `Early-Hint-Control: public` is not present, the 103 response should not be stored.

**Comment by mcmanus** [comment]
The early hints document has completed both WG and IETF last call so it should not be re-opened for new features.

It sounds like you're suggesting new work - and httpbis is open to taking on new work. You should suggest that, even better with a draft, on the mailing list.

Thanks.

**Comment by mnot** [comment]
Also, this is a general problem with the HTTP caching model, not specific to 103. See:
httpwg/http11bis#29
