### ISSUE TITLE
wglc cache digest editorial feedback reschke

### ISSUE THREAD

**Issue by mcmanus** [httpwg/http-extensions#382]
https://lists.w3.org/Archives/Public/ietf-http-wg/2017JulSep/0263.html

Some editorial feedback:

1) ABNF list rule reference has wrong section 
(https://github.com/httpwg/http-extensions/pull/376)

2) Throughout s/header/header field/

3) 
<https://www.greenbytes.de/tech/webdav/draft-ietf-httpbis-cache-digest-02.html#rfc.section.5.p.4>:

"TODO: discuss how effective the suggested mitigations actually would be."

4) Please avoid lowercase BCP 14 keywords such as "may", or invoke 
<https://tools.ietf.org/html/rfc8174>

Best regards, Julian

**Comment by reschke** [comment]
Left to do:



    Throughout s/header/header field/

https://www.greenbytes.de/tech/webdav/draft-ietf-httpbis-cache-digest-02.html#rfc.section.5.p.4:

"TODO: discuss how effective the suggested mitigations actually would be."

    Please avoid lowercase BCP 14 keywords such as "may", or invoke
    https://tools.ietf.org/html/rfc8174

**Comment by mnot** [comment]
Closing, as we're no longer working on cache digests.
