### ISSUE TITLE
HTML references

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#383]
The spec currently references both HTML-the-living-spec (with potentially incorrect author information), and HTML 4.01. Only the latter is actually used.

**Comment by mnot** [comment]
It's not that cut-and-dried.

**Comment by mnot** [comment]
Emily - there are a few things going on here:

1. If you want to keep the WHATWG HTML reference, you need to actually use it.
2. The WHATWG has moved away from listing document authors, so you'll need to reflect that.
3. How to reference HTML is a thorny issue. I personally think the right thing to do is reference both the WHATWG and W3C specifications; YMMV. 
4. Referencing "living documents" may cause some issues/discussion in IETF evaluation. However, we're going to need to figure out how to do that, as we're starting to have more dependencies on WHATWG documents, so don't take that as discouragement from referencing them.

**Comment by reschke** [comment]
FWIW, I don't think this is going to work, because references appear in a "MUST NOT" statement, but are listed as informative.
