### ISSUE TITLE
How does the CSP syntax fit into the header structure?

### ISSUE THREAD

**Issue by jyasskin** [httpwg/http-extensions#388]
https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-01?#appendix-A surveys the 723* RFCs but not, for example, https://www.w3.org/TR/CSP2/#content-security-policy-header-field. You probably should include that example of structured data in your analysis.

https://github.com/WICG/feature-policy/issues/78 proposes to extend the CSP format into a new non-CSP header. Should they be considering draft-ietf-httpbis-header-structure?

**Comment by mnot** [comment]
Overcome by events.
