### ISSUE TITLE
SameSite Cookie Attribute - Is attribute-value required?

### ISSUE THREAD

**Issue by ericlaw1979** [httpwg/http-extensions#389]
https://bugs.chromium.org/p/chromium/issues/detail?id=635882

Section 3.1 of the spec states that "SameSite" alone (without an attribute value) is a valid token: https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00#section-3.1

Section 4.1 https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00#section-4.1 states 

   1.  If "cookie-av"'s "attribute-value" is not a case-insensitive
       match for "Strict" or "Lax", ignore the "cookie-av".

**Comment by ericlaw1979** [comment]
Ah.  https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00 draft is outdated vs. https://github.com/httpwg/http-extensions/edit/master/draft-ietf-httpbis-cookie-same-site.md. The latter no longer allows a bare "SameSite" token, and it calls for the cookie to be dropped in the event that the samesite-value isn't either "strict" or "lax".

However, I think this text isn't quite right:

  If `cookie-av`'s `attribute-value` is not a case-insensitive match for
    "Strict" or "Lax", ignore the `cookie-av`.

The `cookie-av` in this case is 'SameSite=whatever' and we want to ignore the whole cookie, not just the invalid attribute?

**Comment by fmarier** [comment]
#574 is my proposal to fix this.

We ran into this issue in the Firefox implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=1430803
