### ISSUE TITLE
table of contents is "#rfc..toc"

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#394]
Note the two periods in the identifier.  It's screwing up the styling.  @reschke, this appears to be a product of your XSLT.  Can you see if this is a problem specific to this repo, or a more general one?

**Comment by reschke** [comment]
Actually caused by @mnot 's bootstrap modifications out of sync with the base XSLT.

**Comment by martinthomson** [comment]
Ahh, we can assign this to @mnot then.

**Comment by reschke** [comment]
We could, but I already fixed the issue in https://github.com/httpwg/http-extensions/commit/e93b105d34f5a8418edcfe32193508e21ef7d83b

**Comment by mnot** [comment]
Thanks! PR for upstream?
