### ISSUE TITLE
Post-review notes, typos, editorial stuff only

### ISSUE THREAD

**Issue by wtarreau** [httpwg/http-extensions#401]
This is what I found during a quiet throrough review : 

- paragraph 4: s/The client the retries the request/The client then retries the request  (s/the/then)

Well, nothing else, the doc looks very exhaustive on all possible situations, all the interrogations that stemmed in my mind during the reading were answered a few lines later.

**Comment by martinthomson** [comment]
Glad to hear it Willy :)
