### ISSUE TITLE
Support includeSubdomains in Expect-CT

### ISSUE THREAD

**Issue by devd** [httpwg/http-extensions#420]
It would provide immense security value and ease of deployment.

Cookies are sent across all sub domains; so if example.com has auth cookies, a malicious actor can compromise a CA and create a "$random.example.com" cert and serve it to get a user's cookies. Since example.com never knew about nor had ever served $random.example.com, the UA won't enforce CT requirement on this domain. This would mean a cert that's not on a CT log would work fine to get the user's cookies.

**Comment by martinthomson** [comment]
Prompted by @estark37's feedback on this, we discussed this in person during IETF 101.  The minutes don't capture this, but no one objected to the outcome that was proposed, except that @mnot hasn't uploaded his slides to httpwg/wg-materials, so I can't remember exactly what that was.

**Comment by mnot** [comment]
Her summary:

> No major changes to the Expect-CT draft in a while -- only some minor tweaks to reporting (https://github.com/httpwg/http-extensions/issues/416, https://github.com/httpwg/http-extensions/issues/417). The open design issue is whether the header should have includeSubdomains support (https://github.com/httpwg/http-extensions/issues/420). I am not inclined to add this at the moment unless another implementer comes along and wants it. We are unlikely to implement it in Chrome because it's a moderately complex implementation and the marginal value is somewhat small considering that the full CT enforcement date is coming up so soon (April).

**Comment by estark37** [comment]
Closing per https://github.com/httpwg/http-extensions/issues/420#issuecomment-379127529
