### ISSUE TITLE
Editor draft links are broken (404)

### ISSUE THREAD

**Issue by igrigorik** [httpwg/http-extensions#449]
On https://github.com/httpwg/http-extensions, pointers to editor drafts all return 404s:

- http://httpwg.org/http-extensions/rand-access-live.html
- http://httpwg.org/http-extensions/client-hints.html
- http://httpwg.org/http-extensions/key.html
- ...

Did something change / break recently?

**Comment by mnot** [comment]
Yes, see #448 *ahem* 

/cc @MikeBishop @martinthomson
