### ISSUE TITLE
Reuse of Exported Authenticator Context fields

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#468]
The Request-ID and Cert-ID fields are currently matched with the Exported Authenticator context value.  These values are subject to certain randomness requirements:

> The certificate_request_context MUST be unique within the scope of this connection (thus preventing replay of authenticators). The certificate_request_context SHOULD be chosen to be unpredictable to the peer (e.g., by randomly generating it) in order to prevent an attacker who has temporary access to the peer's private key from pre-computing valid authenticators.

In the current draft, Cert-ID and Request-ID are sender-local and required to be unique over the lifetime of a connection, but there's no randomizing/unpredictability requirement.  The simplest way to be unique is to be a counter, which is highly predictable.  To what extent do we need this property and how should we best accomplish it?  (Or do we just declare that it should be unpredictable and leave the issue to implementations?)

**Comment by grittygrease** [comment]
I'm fine with just declaring that it should be unpredictable.

**Comment by MikeBishop** [comment]
This seems to be OBE.  The certificate_request_context in the current draft (stated in #481) is `the two-octet Request-ID as well as at least 96 bits of additional entropy.`  This seems sufficiently unpredictable, and the Request-ID is required to be unique, so even if it's a counter the combination should be both unique and unpredictable.

Cert-ID doesn't appear to be passed to the Exported Authenticator API at all, so that's a moot point.

@grittygrease, @martinthomson, please re-open if you think there's more required to meet these requirements.
