### ISSUE TITLE
h2 net::ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by 1265578519** [httpwg/http-extensions#470]
![qq 20180113044248](https://user-images.githubusercontent.com/6442439/34895015-b5d4bd1c-f81e-11e7-8d41-2fc739d1023a.png)
![3](https://user-images.githubusercontent.com/6442439/34895016-b6084402-f81e-11e7-82c7-3c8f45c53cfb.png)
![4](https://user-images.githubusercontent.com/6442439/34895017-b637afc6-f81e-11e7-9e4a-100fe9110427.jpg)

![qq 20180113044248](https://user-images.githubusercontent.com/6442439/34895011-b1dead08-f81e-11e7-8d87-9ddeea427f03.png)

**Comment by 1265578519** [comment]
互联网上非常多的http2.0启用后出现net::ERR_SPDY_PROTOCOL_ERROR，但是都没有解决方法

**Comment by mnot** [comment]
This repository is for the specification, not implementation bugs.
