### ISSUE TITLE
CONNECT: consider using ALPN registry for the :protocol values.

### ISSUE THREAD

**Issue by PiotrSikora** [httpwg/http-extensions#471]
Please consider using the [ALPN protocol IDs registry] instead of the [HTTP Upgrade token registry] for the `:protocol` values in HTTP/2 extended CONNECT method, since it's more appropriate for the use case.

The only downside is that there is no `"websocket"` ALPN value, but that could be easily added.

Also, we should add `"bytes"` / `"bytestream"` to the registry, for the purpose of proxying arbitrary TCP connections over HTTP/2.

[ALPN protocol IDs registry]: https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids
[HTTP Upgrade token registry]: https://www.iana.org/assignments/http-upgrade-tokens/http-upgrade-tokens.xhtml

cc @mcmanus

**Comment by wtarreau** [comment]
IMHO this would not be logical. CONNECT and Upgrade are really similar in that they are used to transport something over HTTP, and that something may very well be a TLS stream which itself contains its own ALPN.

Anyway this should be discussed on the mailing list, not via issues here.

**Comment by mcmanus** [comment]
discussed in london/101 and decided to not make a change

**Comment by PiotrSikora** [comment]
Sounds good, thanks for bringing this up to the forum!

**Comment by PiotrSikora** [comment]
Though, reading [IETF101 meeting notes](https://github.com/httpwg/wg-materials/blob/gh-pages/ietf101/minutes.md#bootstrapping-websockets) (sorry for missing it!), it seems that discussion was around using ALPN for negotiating WebSocket-over-HTTP/2 and not about `:protocol` values.

**Comment by MikeBishop** [comment]
@PiotrSikora, those are the same topic.  The `:protocol` extension to CONNECT was defined for the primary purpose of using WebSockets over an HTTP/2 stream; it just happens to be a general-purpose mechanism we can use for other things too.  And I think the Upgrade registry, being an existing registry which contains protocols that HTTP can upgrade to is probably the right choice when defining a new sort of upgrade within HTTP.

However, if we were redefining the Upgrade registry now, I'd argue for using the ALPN registry for both of these.  Fundamentally, they are both registries of tokens which identify an application-layer protocol which can run over a bytestream.  (Or collection of bytestreams, when used with QUIC.)  The only real restriction is that Upgrade requires that the protocol be able to answer the original HTTP request in the new protocol, which means there has to be a defined mapping between HTTP requests and whatever the new protocol is.

The currently-registered values are disjoint, but I wonder if perhaps HTTPter should consider merging the two registries?
