### ISSUE TITLE
0-length binary content?

### ISSUE THREAD

**Issue by jyasskin** [httpwg/http-extensions#474]
https://tools.ietf.org/html/draft-yasskin-http-origin-signed-responses-02#section-3.8.3 would like to allow clients to pass a 0-length binary string (as a prefix that matches anything), but https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-02#section-4.5 requires at least 1 base64 character. Does it make sense to allow 0-length content?

(If not, you should at least start with 2 characters, since 1 character isn't valid base64 since it doesn't specify a whole octet.)

**Comment by mnot** [comment]
Fixed in 9b495e31.
