### ISSUE TITLE
Number algorithm

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#475]
doesn't enforce syntactic limits.

**Comment by phluid61** [comment]
Could be related to #479 (the higher-order issue being that algorithms and ABNF aren't exactly 1:1), in which case it's probably part of #477.

**Comment by mnot** [comment]
I just meant that what's there is only a sketch :)

**Comment by phluid61** [comment]
Just call me the problem dwarf.  (I dig too deep.)

Integer is a weird one, though.  The ABNF limits input to 19 characters (plus hyphen), the prose restricts output values, and the algorithm glosses the actual transformation of characters to value.  So the authoritative specification is all over the place.

Do you have to choose which part is more authoritativer (#477) before you can work out how to flesh out the sketch?

**Comment by bsdphk** [comment]
Both integer and float ABNF allows leading zeros.  Do we want that ?

**Comment by mnot** [comment]
Probably not.

**Comment by mnot** [comment]
@bsdphk said: "Does step 3 & 4 need to say something explicit about failing if they get "22-22-22-22" as input ?"

**Comment by mnot** [comment]
WRT leading zeros -- I suspect they'll be allowed in almost all environments, so disallowing them invites differences in implementation. Is there a good reason for disallowing them, given we have overall length limits?

**Comment by mnot** [comment]
@phluid61 #477 is closed, so please take a crack if you'd like.
