### ISSUE TITLE
Dictionary parsing - trailing comma

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#479]
The dict parsing algorithm currently allows a trailing comma (and OWS). 

Is the comma intentional?

**Comment by phluid61** [comment]
The ABNF doesn't allow it.

**Comment by phluid61** [comment]
Could just change "2. While input_string is not empty:" to "2. In a loop:"

I think that also makes steps 3 and 4 unreachable.

**Comment by mnot** [comment]
My plan was to add a step at the bottom of the loop "if input_string is empty, fail parsing."

Question is whether we want to be tolerant of trailing commas. Based upon the approach we seem to be taking elsewhere, I think we probably don't want to be. That means that this would fail:

> FooHeader: bar,baz,

... and this would as well:

> FooHeader: bar, baz
> FooHeader:

I think I'm comfortable with that.

**Comment by phluid61** [comment]
+1

**Comment by phluid61** [comment]
(The ticket talks about dictionaries, but you're talking about lists. The same rule/fix should apply to both.)
