### ISSUE TITLE
Include pictures for all frames

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#484]
The pictures are great anchors for finding frames.  Omitting them makes it harder to read the document.

**Comment by MikeBishop** [comment]
I was following the convention that frames with a single field don't get a picture.  However, I see that QUIC is now only omitting for frames that don't have a payload at all, or are exact duplicates of a different frame.  Perhaps HTTP/QUIC should do likewise.

**Comment by martinthomson** [comment]
Right, and I started doing that because it's easier to scan the document to find what you need when you have nice pictures breaking things up.
