### ISSUE TITLE
Add Request-ID to CERTIFICATE

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#486]
I think that it would be better to explicitly reference CERTIFICATE_REQUEST in the cases where a CERTIFICATE is generated directly in response to one.  Using the "get context" API from exported authenticators is ugly.

This is more important now that exported authenticators folds the request into the response.

We probably want to use a flag for whether this is spontaneous so that we can avoid reserving a Request-ID for spontaneous CERTIFICATE messages.

**Comment by MikeBishop** [comment]
I'm a little dubious about this.  Having the same value transported in two different fields and then checking that they're equal seems potentially more error-prone than just transporting it in one place, even if that one place is by calling into a library to interpret for you.

**Comment by MikeBishop** [comment]
For posterity, discussion in Montreal:  Nice not to have to dig out the Request-ID.  However, if you duplicate it, then you have to compare and check that they're equal, so you're still calling into TLS.  There is an existing duplication in the CERTIFICATE_REQUEST, where the Request-ID is carried outside the EA.
