### ISSUE TITLE
Auth-Info purpose consistency

### ISSUE THREAD

**Issue by hruellan** [httpwg/http-extensions#49]
I think the purpose of the headers should be made more consistent across the document.
In the Introduction, they are used to "*return additional information during or after authentication*", while in 3, the Authentication-Info header is used to "*communicate additional information regarding the successful authentication*".

DIGEST use it in an optional manner, to convey additional information after a successful authentication.
Scram is using it in a mandatory manner, to finalize the authentication, by conveying information for authenticating the server.

I think that Authentication-Info should be used by the server once the client is authenticated (i.e. the status code is not 401), to either convey additional information or finalize the authentication. 

Proposal in #47.

**Comment by reschke** [comment]
This change was applied in https://github.com/httpwg/http-extensions/commit/849702e4f7f6476b09a8e7777941dac21a848e00
