### ISSUE TITLE
Protocols based upon HTTP and IANA registries

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#492]
Michael Sweet pointed out IPP, which uses HTTP POST and status codes (very basically) to get its job done, and it doesn't register anything new.

When this is the case, it doesn't seem harmful to say that they can use HTTP registries. What's harmful is when a non-HTTP protocol puts something into HTTP's registries, creating confusing about what can be used where.

Is it sensible to drop the aspect of "using HTTP" that is:

> The message formats described in {{RFC7230}} and/or {{RFC7540}} are used in conjunction with the IANA registries defined for HTTP.

... and add a requirement that protocols that are based upon HTTP MUST not register anything in HTTP's registries, but instead define their own registries if they want to add new protocol artefacts?

**Comment by MikeBishop** [comment]
It's a fine line; I'd go one step further.  It's okay if they use the entries *unchanged*.  They MUST NOT register anything new, and they MUST NOT modify the semantics of existing entries.
