### ISSUE TITLE
binary content, non-paddability

### ISSUE THREAD

**Issue by bsdphk** [httpwg/http-extensions#495]
I'm not sure I understand the ban on '=' in binary content, how can that confuse dictionaries, when the binary content doesn't end until the final '*' ?

**Comment by mnot** [comment]
It's from when there wasn't a final delimiter. I think you're right; we should accept  `=`. I *think* we should also accept without.

**Comment by bsdphk** [comment]
I think we should just rely on whatever the B64 rfc says, without inventing anything new.  (Postel Was Wrong and all that.)

**Comment by bsdphk** [comment]
WFM
