### ISSUE TITLE
Issues with server detection of attacks

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#522]
ORIGIN removed the need for DNS lookups for servers, and IP connectivity.  Servers can look for bad DNS records or BGP hijacking to detect attacks without ORIGIN, but now those techniques don't work.  In particular, key compromise is a concern; misissuance is perhaps less of a concern.

Secondary certificates makes the entire situation worse.

In particular, it means that you can get a standalone certificate for the victim.  Previously, with coalescing, you would need to have a certificate that has both your own origin and the victim's origin, so that would be visible in a CT log.

Subcerts can help with this (they have much shorter lifetimes).

**Comment by martinthomson** [comment]
From Kyle N: We could annotate the certificate to enable opt-in.

**Comment by MikeBishop** [comment]
I assume annotation would just be an OID on the certificate?  It makes me a little sad to say that all current certificates are invalid for this purpose, but there's definitely value in limiting the scope of a key compromise.

**Comment by martinthomson** [comment]
Yeah.  The standard approach is to include a critical extension and reject attempts to use an EE cert that doesn't include the extension.  We would probably only levy that requirement on servers though.
