### ISSUE TITLE
If you have multiple connections

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#523]
What do you do?  What certificates apply to these?  Are the connections independent.

What if these are resumptions?  What from the previous connection do you use in that context?

**Comment by MikeBishop** [comment]
Draft currently says:

> As a result, clients MUST NOT assume that because one origin was previously colocated with another, those origins will be reachable via the same endpoints in the future. Clients MUST NOT consider previous secondary certificates to be validated after TLS session resumption. However, clients MAY proactively query for previously-presented secondary certificates.

While that was originally talking about future session resumption, I think it's equally applicable to parallel connections.  The only certificate that applies to a connection when it begins is the one proven in TLS.  Anything else has to be bound to that specific connection.  You can remember interesting things you want to send a request for, but you can't assume.

**Comment by martinthomson** [comment]
Ahh yes, that seems totally adequate (I was just trying to capture concerns that I heard during the meeting).  Closing.
