### ISSUE TITLE
netinfo still mentioned in client-hints

### ISSUE THREAD

**Issue by npdoty** [httpwg/http-extensions#524]
It looks like the network information hints (Downlink) were removed, but there are still a couple references to network information, particularly in security considerations discussion, since there were security/privacy issues related to exposing network information through this. Should we just remove those references to network information?

(`Save-Data` is potentially network-related, but I'm less concerned about that as a network information property that users might not realize is being disclosed.)

**Comment by igrigorik** [comment]
Yep, that makes sense! Assigning to myself.
