### ISSUE TITLE
structured-headers: Has JSON been considered?

### ISSUE THREAD

**Issue by evert** [httpwg/http-extensions#538]
This is a question I got after publishing a first stab at [an implementation](http://github.com/evert/structured-header/). Was JSON considered as an alternative for this?

At least some reasons why I can think of why it wouldn't be good are:

* It doesn't encode binary data
* It's not as aesthetically pleasing, especially considering how HTTP headers generally 'look'.

However, parsers are everywhere and JSON has some properties that structured-headers doesn't have, such as deeper nesting, encoding `null` and it also solves #534

**Comment by mnot** [comment]
Yes - there's a long history behind that, and we originally had a JSON-based approach.

Besides the reason you mention, there was a lot of discomfort around the imprecision of numbers in JSON, and also about enabling arbitrary nesting of data structures.

**Comment by evert** [comment]
Thanks for the feedback. I'm gonna try to dig into the discussions
