### ISSUE TITLE
Adopt Structured Headers

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#570]

**Comment by mnot** [comment]
* `Variants` looks like a parameterised list
* `Variant-Key` is currently a list of strings, but if #548 is adopted, its syntax will need to be changed, as it doesn't fit into parameterised list particularly well (although I guess it could).

**Comment by mnot** [comment]
Currently waiting on resolution of #721.

**Comment by ioggstream** [comment]
@mnot #721 is closed now. Any hints?
