### ISSUE TITLE
Number of alternate services used

### ISSUE THREAD

**Issue by hruellan** [httpwg/http-extensions#58]
At the end of section 3, the paragraph:

> The value(s) advertised by Alt-Svc can be used by clients to open a new connection to one or more alternative services immediately, or simultaneously with subsequent requests on the same connection.

says that several alternative services can be used simultaneously by a client. 

However, section 2.4 Using Alternative Services, recommend choosing one alternative service and using only one alternative service (except during the transition time).

I think we should align the two by rephrasing the sentence in 3.

**Comment by mnot** [comment]
I tend to agree. Marking this as design, just to confirm with the WG that this is the intent. Please ping the list.

**Comment by reschke** [comment]
Done in https://lists.w3.org/Archives/Public/ietf-http-wg/2015AprJun/0331.html

**Comment by mnot** [comment]
No objection on list.
