### ISSUE TITLE
Minimum version

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#587]
Should applications using HTTP be allowed to specify a minimum version? If so, what are the criteria / limits?

**Comment by mcmanus** [comment]
The DoH WG answered this by saying "no" - applications are supposed to be defined at the semantic layer. (although I would quibble and say 56bis and the word 'allow' don't go too well together - its advice).

Most of the discussion centered around how it is impossible to really leverage the ecosystem and actually know what versions are available. (mitm, load balancers, browser portabiity, etc..) so this would be very fragile.

This conclusion was reached for DoH even though there was agreement  DoH really requires multiplexing to work well. DoH did end up documenting this relationship and SHOULDing h2, but not requiring it.

**Comment by mnot** [comment]
@mcmanus how does that look?

**Comment by reschke** [comment]
Do we actually still have a concept of "maximum"? What would be the relation between HTTP/QUIC vs HTTP/2?

**Comment by mcmanus** [comment]
sgtm
