### ISSUE TITLE
network quality related client hints

### ISSUE THREAD

**Issue by tarunban** [httpwg/http-extensions#588]
We should update spec to include 3 network quality related client hints:
"rtt", "downlink", "ect".

The values of the client hints matches the value provided by the JavaScript API (navigator.connection.rtt, navigator.connection.downlink, navigator.connection.effectiveType respectively):
https://wicg.github.io/netinfo/

**Comment by tarunban** [comment]
cc @igrigorik

**Comment by igrigorik** [comment]
These headers will be defined in NetInfo, same as `Save-Data`. PR: https://github.com/WICG/netinfo/pull/69. Let's continue discussion there.
