### ISSUE TITLE
shout out to cert checking

### ISSUE THREAD

**Issue by mcmanus** [httpwg/http-extensions#612]
> Certificates - Applications using HTTP MUST specify that TLS certificates are to be checked according to [RFC2818] when HTTPS is used.

why is this more special than any of the other 2818 rules (it is a MUST there I believe)? This doesn't seem to square with the optional theme of cookies and redirects.

cool btw that https is RECCOMMENDED

**Comment by mnot** [comment]
Not sure I understand; the intent is to require clients to check certificates; is there a more clear way to say that?

**Comment by mcmanus** [comment]
sorry that wasn't very clear.

The section was on stuff that normally isn't mandatory (like chasing redirects) - I was having trouble seeing how certificate checking fit in there. Its a mandatory part of https so it might not even rate mention - is there confusion on it?

**Comment by mcmanus** [comment]
I just reread 2818 - and I think want to retract the issue now.. the 2818 language is restricted to validating server identity afaict.
