### ISSUE TITLE
Client authentication with certificates

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#615]
This isn't mentioned in the client authentication section.  It's a practice that is used quite often, so it should be mentioned.  That naturally means addressing some of the (many) shortcomings though.

**Comment by martinthomson** [comment]
In passing would suffice.  As in, "With HTTPS, clients might also be authenticated using certificates."  If you want to avoid the compendium problem, avoid getting into the shortcomings.

**Comment by MikeBishop** [comment]
Probably want a reference to TLS in there for further reading.
