### ISSUE TITLE
Proxy and .pac interaction

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#62]
Ryan asks what you should pass to proxy.pac when you know about a potential alt-svc.

I suggested that you use the original request origin and only use alternatives if the proxy.pac doesn't provide a proxy address.  That is proxy.pac overrides alternative services.

**Comment by mnot** [comment]
Yeah. Alt-Sv is for finding an origin, not for finding a proxy -- a proxy might use it, though.

This *should* all be clear based upon reading of RFC7230, but if not we could add a sentence or two to clarify.

**Comment by reschke** [comment]
Is there something we need to do here?

**Comment by RolandZink** [comment]
Maybe we need to specify an alternative to pac files or define how to 
get a proxy for http over TLS in pac.

Regards,
Roland

**Comment by mnot** [comment]
For *this* spec, I think we could just add a sentence to the effect that 'clients configured to use a proxy SHOULD NOT use alternative services."

**Comment by mnot** [comment]
Add: "A client configured to use a proxy for a given request SHOULD NOT send it to an alternative service, but instead use that proxy."

**Comment by mnot** [comment]
Modification: "A client configured to use a proxy for a given request SHOULD NOT directly connect to an alternative service for it, but instead route it through that proxy."

**Comment by reschke** [comment]
(seems the discussion on the mailing list hasn't come to a conclusion)

**Comment by mnot** [comment]
It did regarding this issue, I think; the remaining discussion is a tangent.
