### ISSUE TITLE
Header fields that are valid SH, but invalid according to the definition of that field

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#623]
If a header field is valid according to SH, but invalid according to some additional constraints that are included in the definition of the specific header field, what happens?

* it needs to be dropped because malformed header fields are dropped according to SH

* the definition of the specific header field needs to define what happens in this case

**Comment by mnot** [comment]
Current text:

> However, header field authors are encouraged to clearly state additional constraints upon the syntax, as well as the consequences when those constraints are violated. When Structured Headers parsing fails, the header is discarded (see {{text}}); in most situations, header-specific constraints should do likewise.

Is that sufficient?

**Comment by martinthomson** [comment]
Yes.
