### ISSUE TITLE
secondary-certs: misleading citation

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#632]
<https://tools.ietf.org/html/draft-ietf-httpbis-http2-secondary-certs-01#section-1>:

~~~
   HTTP clients need to know that the content they receive on a
   connection comes from the origin that they intended to retrieve in
   from.  The traditional form of server authentication in HTTP has been
   in the form of a single X.509 certificate provided during the TLS
   RFC5246 [I-D.ietf-tls-tls13] handshake.
~~~

This makes it  look as if RFC5246 *is* [I-D.ietf-tls-tls13].

**Comment by MikeBishop** [comment]
True; I think this was originally intended to cite both, but the first one stopped being special at some point, if it ever was.  Once TLS 1.3 hits RFC, we may want to trim some of the RFC 5246 references unless we're specifically talking about the older version, too.
