### ISSUE TITLE
Mark httpbis-cookie-same-site as superseded if possible

### ISSUE THREAD

**Issue by annevk** [httpwg/http-extensions#641]
It took me quite long to find httpbis-rfc6265bis.

**Comment by mnot** [comment]
Done.

**Comment by annevk** [comment]
Cool, I guess it'll take some time to propagate before https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site is updated?

**Comment by mnot** [comment]
Yes.

**Comment by MikeBishop** [comment]
You can see it in the [datatracker](https://datatracker.ietf.org/doc/draft-ietf-httpbis-cookie-same-site/).
