### ISSUE TITLE
Handling Non-ASCII Content

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#662]
From [Kari](https://www.w3.org/mid/20180702190902.6769054978@welho-filter1.welho.com):

But parsing algorith seems missing text:

	If non-ASCII characters seen, fail parsing.

All algrithm have text

	"Given an ASCII string input_string"

so they do not apply situation when there is non-ASCII characters.

So there seems to missing top level algorithm, which is

   Given an string input_string, return parsed context.

   1. Check input_string character values.

      1. If all characters are on range %x00-%x7f,
         let output be the result of 
         Parsing HTTP/1 Header Fields into Structured Headers
         (Section 4.2)

      2. Otherwise, fail parsing.

**Comment by mnot** [comment]
All of the parsing algorithms seem to have checks for the range of characters they allow; closing with no action.

**Comment by mikewest** [comment]
For my own clarity: what do you expect callers of this algorithm to do? The text Kari points out does give me the impression that you require ASCII encoding, which doesn't match the expectations that Fetch has for header values. In particular, the algorithms in https://fetch.spec.whatwg.org/#terminology-headers do not make any assumptions about the character set.

Should we be checking whether the string we're passing into the parsing algorithm is ASCII before doing so?

(See the conversation in https://github.com/whatwg/html/issues/4175#issuecomment-503991995 for context).

**Comment by annevk** [comment]
Yeah, note that this can lead to vastly different results for quoted strings. I think it would be preferable if these parser algorithms operated on a byte sequence (or the result of https://infra.spec.whatwg.org/#isomorphic-decode).

**Comment by mnot** [comment]
We can add a step to convert a byte stream to characters on parsing (and vice versa for serialisation) if it makes things easier for you.

We could add an explicit step to check that the input is ASCII, but like I said above, that would be an optimisation; the terminal types all check their input.

**Comment by annevk** [comment]
What is a terminal type?

I think @mikewest and I have been looking at https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-10#section-4.2 which assumes an ASCII string as input.

(As an aside, I wonder what the eventual specification contract should look like here. I guess a "header list" should be able to store typed values and there's a typed-value getter that either returns the typed-value for a given header, parses a legacy-value into one if there's no typed-value, or returns none if there's neither, or failure if parsing failed. And if we start setting these values we'd always pass on typed values to the HTTP subsystem which then decides based the connection how to serialize these.)

**Comment by mnot** [comment]
terminal types are items; i.e., something that isn't a container.

**Comment by mnot** [comment]
WRT 4.2, we can be more explicit there; will do a PR.

**Comment by mnot** [comment]
PTAL at the commit above.

**Comment by mnot** [comment]
Closing; if that's not what you needed, please complain and will reopen.

**Comment by annevk** [comment]
Okay, so if there's a byte in the range 0x80-0xFF, inclusive, anywhere for a particular header, it'll fail parsing. That seems fine.

HTTP still needs to define this interface where it accepts a header list where the header values can be typed values, but I guess that'll take a while.
