### ISSUE TITLE
Consider aligning Structured Headers terminology with Infra

### ISSUE THREAD

**Issue by jyasskin** [httpwg/http-extensions#671]
https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#parse-binary talks about returning "binary content" where Infra would say "[byte sequence](https://infra.spec.whatwg.org/#byte-sequence)". I think this is the only one where pedantic readers might wonder whether there's a semantic difference.

https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#string uses "String" where Infra would use "[ASCII string](https://infra.spec.whatwg.org/#ascii-string)".

Adopting #659 would match Infra's [ordered maps](https://infra.spec.whatwg.org/#maps), but I'm happy to keep the semantic argument out of this issue. :smiley:

**Comment by mnot** [comment]
Seems reasonable; will have a deeper look when I get a chance. Thanks!
