### ISSUE TITLE
IANA registry for Variant-able Content Negotiation Mechanisms

### ISSUE THREAD

**Issue by jyasskin** [httpwg/http-extensions#681]
https://tools.ietf.org/html/draft-ietf-httpbis-variants-03 should define a registry to specify which content negotiation mechanisms are usable with `Variants`.

https://tools.ietf.org/html/draft-ietf-httpbis-variants-03#section-6 has most of the requirements for putting something in that registry, and https://tools.ietf.org/html/draft-ietf-httpbis-variants-03#appendix-A has the initial entries.

**Comment by mnot** [comment]
Hi Jeffrey,

My initial reaction is that we don't really use registries like this; they're for managing a name space, not just for convenience like that (that's more like developer documentation, blog entries, etc.).

Let met talk to a few grey beards and see what they think.

**Comment by mnot** [comment]
Discussed in Bangkok. The sense of the room was that recording this elsewhere -- e.g., a wiki -- was sufficient.

**Comment by jyasskin** [comment]
Thanks. I'm concerned about how folks find that wiki page when they're starting from either Variants or the other header's definition, but it'll probably work out.
