### ISSUE TITLE
Strictness for multi-party headers

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#684]
currently:

> If parsing fails – including when calling another algorithm – the entire header field’s value MUST be discarded. This is intentionally strict, to improve interoperability and safety, and specifications referencing this document cannot loosen this requirement.

This might not be setting up the right incentive structure for cases where multiple parties are adding to a single header field value. The right thing to do in that case might be to discard the offending value (or replace it with an empty value, to preserve cardinality) while preserving others.

**Comment by martinthomson** [comment]
This depends on how header fields are consumed.  If you have a process that parses each as it arrives, adding to a list of multiple header fields are encountered, that will work fine.

On the other hand, isn't it possible to join multiple values with a comma and then parse?  This would have the effect of prohibiting that style of API.

**Comment by phluid61** [comment]
If there's a 7230-compatible (but not SH-compatible) thing in the middle, it could concatenate them naively.  Which means the burden has to be on the final recipient.  No matter what, I can't think of a particularly graceful way to deal with something like this:

~~~
my-list-header: "hop1"
my-list-header: "buggy-hop
my-list-header: "hop3"
~~~

**Comment by mnot** [comment]
I wonder if it's worth specifying that for list headers, each individual header field MUST contain one or more valid values; if not, it's discarded rather than raising an error.

The problem is that even then, you could get in situations where the missing information is important. 

The motivation for this was the `CDN-Loop` header. I'm not sure it's a particularly good example for SH...

**Comment by mnot** [comment]
Discussed in Bangkok. Seemed to be agreement that there's not much we can do here beyond documenting the issue.
