### ISSUE TITLE
Point out blank header special case in an example

### ISSUE THREAD

**Issue by annevk** [httpwg/http-extensions#686]
We should point out that if there are multiple headers of the same name, any blank header among them will be ignored.

I should really add some API tests for this as well as I kinda doubt this is how they work...

**Comment by annevk** [comment]
I now actually think there may be an issue here.
```
SH: "start
SH: 
SH: end"
```
needs to become `SH: "start, , end"` and then parsing should start. If empty/whitespace values were to be removed when combining you'd end up with different strings due to ignorant intermediaries. That doesn't seem acceptable.

https://github.com/httpwg/http-core/issues/148 has some on this as well.

**Comment by mnot** [comment]
I suspect what we'll need to say is that splitting values across headers will lead to unpredictable results, depending on who combines them where.

Probably in 4.2. Parsing HTTP/1 Header Fields into Structured Headers.

**Comment by annevk** [comment]
Yeah, that seems fine, though for browsers I'd want to specifically mandate combining (without omitting empties) before parsing. I guess Fetch would have to define that then.
