### ISSUE TITLE
Refer to HTTP method registry

### ISSUE THREAD

**Issue by DanilSuits** [httpwg/http-extensions#691]
The HTTP Methods section (4.5) requires that an application use registered http methods.  The HTTP Method Registry, defined by [RFC 7231](https://tools.ietf.org/html/rfc7231#section-8.1), is not mentioned as a source for candidate methods.

The second paragraph of the section includes the following text 
> they are required to be registered with IETF Review 

which I had expected to see linked to RFC 7231; but the actual link in the text is to RFC 7232.

I suspect this is a spelling error.

**Comment by mnot** [comment]
Thanks!
