### ISSUE TITLE
Picking up Linked Cache Invalidation

### ISSUE THREAD

**Issue by evert** [httpwg/http-extensions#692]
Hi everyone,

I have an interest in this draft:

https://tools.ietf.org/html/draft-nottingham-linked-cache-inv-04

Unfortunately it seems abandoned. Is there something I might be able to do to revive this? I think it's still a very useful specification. I'm happy to put the work in to revive in, but I'm not entirely sure how to go about this.

**Comment by mnot** [comment]
Hi Evert. I'm planning on doing something similar, but starting a fresh spec, to integrate the current "Cache-Tag" / "Surrogate-Key" headers used by CDNs. Shouldn't be long.

BTW - Best place to ask this sort of thing is on-list.

**Comment by evert** [comment]
Thank you, will ask on the list in the future
