### ISSUE TITLE
Relationship between `sizes` and `Width` could be explained

### ISSUE THREAD

**Issue by eeeps** [httpwg/http-extensions#698]
`sizes` isn’t mentioned in the spec, and many people dealing in Client Hints from within HTML do not know that it is required in order for clients to send a `Width` hint.

I've seen a lot of [confusion](https://github.com/ojanvafai/intrinsicsize-attribute/issues/7#issuecomment-416764898) about the relationship between the two elements. Is there value to keeping it vague?

**Comment by malchata** [comment]
FWIW, I cover this in a client hints piece for Google Web Fundamentals, but having this in the spec would be a valuable piece of information that I believe would reduce confusion as to how the `Width` hint gets sent to the server.

**Comment by yoavweiss** [comment]
Similarly to #697, this may be better explained closer to HTML and Fetch.

**Comment by igrigorik** [comment]
Closing, this logic has been moved to HTML+Fetch.

Ref: https://github.com/yoavweiss/client-hints-infrastructure/blob/master/specification_situation.md
