### ISSUE TITLE
CH deletion wording

### ISSUE THREAD

**Issue by thiemonagel** [httpwg/http-extensions#699]
> Implementers [...] MUST clear persisted opt-in preferences when site data, browsing history, browsing cache, or similar, are cleared.

@igrigorik I think that sentence can be read in two ways: "opt-ins must be deleted whenever any of [site data, browsing history, browsing cache, or similar] are cleared" or "there must be at least one out of [site data, browsing history, browsing cache, or similar] whose deletion also triggers the deletion of CH opt-ins". Could you please clarify?

**Comment by igrigorik** [comment]
> when any one of site data, browsing...

Would that do the trick?

**Comment by thiemonagel** [comment]
In my opinion, yes. Thank you!
