### ISSUE TITLE
Consider adding Downlink-Max as a client hint header?

### ISSUE THREAD

**Issue by malchata** [httpwg/http-extensions#701]
Pretty much all of what's available in [netinfo](https://wicg.github.io/netinfo/) has been brought into client hints, _except_ for the `downlinkMax` attribute. Is this a reason this hasn't occurred? Is it targeted for eventual removal in netinfo? If not, it may be worth bringing this hint into client hints as `Downlink-Max` so we can determine on the server side what the fastest recorded downlink speed is for that page load cycle.

**Comment by malchata** [comment]
> `downlinkMax` predated the more recent `downlink`, `rtt` and `ect`

Good to have that context. Thanks!

The only case I can make for `downlinkMax` might be that it would be useful for knowing when downstream conditions improve for the client. Such as a client starts off with a low downstream speed on the navigation request, but subsequent resource requests show an improvement in `downlink` values. But in all honesty, if pressed to defend `downlinkMax` (or `Downlink-Max` as I've suggested here), applications can track `downlink` values across all resource requests and figure that out on their own.

A better title for this issue might be "Consider making network-related client hints congruent with netinfo", since congruency between the two would reduce confusion and allow spec readers to draw a 1:1 relationship between hints available in netinfo and network hints available in CH.

**Comment by tarunban** [comment]
I remember there were even discussions around removing `downlinkMax`. It's also not supported on any of the desktop platforms.

**Comment by malchata** [comment]
Can you clarify what you mean by that, @tarunban? I can access `navigator.connection.downlinkMax` in my desktop version of Chrome on High Sierra (though it populates with `Infinity`).

**Comment by tarunban** [comment]
Yeah, that's what I meant, on desktop platforms it returns `Infinity` in all cases (regardless of actual capacity of the last hop WiFi or ethernet connection).

**Comment by malchata** [comment]
Thanks for clarifying, @tarunban! I had wondered why that was the case (and now I know).

**Comment by tarunban** [comment]
The relevant code is here: https://cs.chromium.org/chromium/src/content/child/runtime_features.cc?rcl=01bde77cb05eaab1ce10ec5dbf797fca2d2c333c&l=76

I believe part of the reasoning is that there were (are?) not enough APIs exposed by operating systems (Windows, Mac OS etc.) for the Chrome to determine the capacity of the last hop.

**Comment by igrigorik** [comment]
As a brief aside.. Can we move this discussion to https://github.com/WICG/netinfo/issues? If we want to define the header, we should be doing so in NetInfo spec, same as others.

**Comment by malchata** [comment]
Got it, @igrigorik! I'm still figuring out how the different parts of CH are structured and didn't think to put it there. Feel free to close this if you want.

**Comment by igrigorik** [comment]
sg, closing, let's continue this on netinfo repo.
