### ISSUE TITLE
better to Use Example Domain

### ISSUE THREAD

**Issue by Jxck** [httpwg/http-extensions#706]
> Consider the scenario in which a user reads their email at MegaCorp Inc's webmail provider https://example.com/. They might expect that clicking on an emailed link to https://projects.com/secret/project would show them the secret project that they're authorized to see, but if projects.com has marked their session cookies as SameSite, then this cross-site navigation won't send them along with the request. projects.com will render a 404 error to avoid leaking secret information, and the user will be quite confused.

`projects.com` is real domain. (currently not owned)
seems better to use example domain in rfc.

**Comment by johnwilander** [comment]
Should we use the .example TLD or stay with example.com? It's easier to contextualize with .example, in this case webmail.example and projects.example.

**Comment by Jxck** [comment]
SGTM in projects.example, webmail.example etc
also projects.example.com/net/org are fine too.
