### ISSUE TITLE
! seems like a poor choice for Boolean

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#719]
I think either @phluid61 or @LPardue suggested `?`, since `!` will be read as "NOT" by many, and therefore confuse...

**Comment by mnot** [comment]
@jyasskin / @irori will changing this cause trouble for you?

**Comment by mnot** [comment]
Thx.

**Comment by mnot** [comment]
Pinging @mikewest just to make sure this won't cause any pain, and FYI.

**Comment by mikewest** [comment]
I was also surprised at `!` in the doc. `?` is fine, and maybe possibly more semantic if I squint?

**Comment by LPardue** [comment]
I don't recall making any complaints. However you resolved this SGTM
