### ISSUE TITLE
"Identifier"

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#725]
A bit of an unwieldy name. Perhaps:

* Token
* Word
* ???

**Comment by mnot** [comment]
@phluid61 says (on a commit):

> Speaking as a computer scientist, "token" is a worse name than "identifier". Any atomic element is a lexical token (identifiers, integers, commas, etc.).

> The only things I could think of that were as applicable as "identifier" were "bareword" and "symbol", which is why I didn't suggest them

**Comment by mnot** [comment]
My main problem with `Identifier` is how many syllables it has -- which is not a deal killer.

Going from [definitions](https://en.wikipedia.org/wiki/Lexical_analysis), I agree that `token` is not terribly apt (although we're not conveying semantics here, so...).

However, HTTP already uses `token` in a [similar way as here](https://httpwg.org/specs/rfc7230.html#rule.token.separators). 

I could see an argument that using `token` in a different way to HTTP "core" might be confusing -- on balance, my inclination was that the term would always be used in the context of structured headers, so would not be ambiguous.

I'm happy to keep it at `token`, move back to `identifier` or choose something else -- @phluid61 does the above change your thinking? If not, let's move back to `identifier`.

And yes, this issue probably deserves a `bike shed` label...

**Comment by phluid61** [comment]
> does the above change your thinking?

It expands my thinking, certainly.  I think as long as `sh-token` and (RFC7230) `token` are always clearly distinct there's no problem.  There's precedent, since `sh-string` and `quoted-string` have a similar kind of overlap.  It's just a bit weird that we're drifting away from the "normal" meaning of the word.

┬─┬ノ( º - ºノ)

*(unflipped table)*
