### ISSUE TITLE
Integer limits

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#737]
Working on evert/structured-headers, @evert [noticed](https://github.com/httpwg/structured-header-tests/issues/9) that representing the full range of SH integers is [hard](http://2ality.com/2013/10/safe-integers.html), and going beyond it can cause [problems](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

Given JS's place in the Web ecosystem and the relative rarity of headers that need integers that big (as well as the availability of floats), should we consider limiting the range of integer to match JS?

**Comment by phluid61** [comment]
Wait, what problem is this proposal actually fixing? Which JS code in particular is affected, in what way?

**Comment by bsdphk** [comment]
Way back I limited Floats, or "Numbers" as I think I called them,
to 15 digits so they would fit in ieee64 floting point types, this
became our "Float" type, which still has that restriction.

Integers were added, I thought, precisely to give the full
64 bit integer range without that limitation ?

If we want to go back and cater to JS implementations, we should
remove Integers again, rename Float back to Number, add the
"15DIGIT" variant back and leave it to people to specify "Number
without fraction" in their usage of SH.

It's early in the morning and I fought a server all night, so subject
to me waking up I think my preference probably is to make it a
mandatory parsing error if an Integer cannot be represented precisly
in the target environment, with a pointed caution/footnote about JS ?

**Comment by mnot** [comment]
For most other types, we guarantee supported lengths / sizes of types by saying "implementations must support at least..."

What if we said that implementations MUST support at least a range of -2^53 to 2^53, and MUST fail dependably if they don't support numbers outside that range? 

That would give us JS interoperability, as well as ability to support larger numbers for cases that need it, with dependable failure by individual implementations.

**Comment by kazuho** [comment]
> For most other types, we guarantee supported lengths / sizes of types by saying "implementations must support at least..."
> 
> What if we said that implementations MUST support at least a range of -2^53 to 2^53, and MUST fail dependably if they don't support numbers outside that range?

I assume you meant "MUST fail dependably if they receive a number outside the supported range"?

**Comment by mnot** [comment]
s/the/their/, but yes.

**Comment by kazuho** [comment]
Thanks. SGTM (I've always preferred having no fixed upper-bound in the spec).

**Comment by martinthomson** [comment]
What does it mean to fail dependably?  I assume that this is just the "fail parsing" clause.

**Comment by mnot** [comment]
yes.

**Comment by bsdphk** [comment]
The only integers I personally know larger than 53 bits are memory addresses (which should *never* get near JS, but could be blobs) and cryptographic data (which should be blobs) and nonces like CC numbers, SKU numbers, transaction IDs (which {c|sh}ould either be strings or blobs).

In other words: People have sound alternatives.

Making it parsing error to fail to "capture the exact numerical value" would raise the question why we don't also have that note for Numbers, which runs into the binary floating point vs. decimal numbers thing.

In all likelihood what will happen is that people won't read what we write anyway, and any 53+ bit integers will simply loose resolution in JS, *just like they would* if they came into JS *any other way*.

So all in all:  I think we should just close this issue.

At most, we can add a footnote reminding people that JS does not have a native 64 bit integer type.

**Comment by kazuho** [comment]
FWIW, https://tools.ietf.org/html/draft-ietf-httpbis-rand-access-live-03 has the following in the Security Considerations:
> One potential issue with this recommendation is related to the use of very-large last-byte-pos values. Some client and server implementations may not be prepared to deal with byte position values of 2^63 and beyond. So in applications where there's no expectation that the representation will ever exceed 2^63, a value smaller than this value should be used as the very large last-byte-pos in a byte-seek request or content-range response. Also, some implementations (e.g. JavaScript-based clients and servers) are not able to represent all values beyond 2^53. So similarly, if there's no expectation that a representation will ever exceed 2^53 bytes, values smaller than this limit should be used for the last-byte-pos in byte-range requests.

I think that the decision we make here should be aligned to this.

**Comment by mnot** [comment]
@kazuho I'm not sure what the practical impact of that is; `Range` and `Content-Range` do not use structured headers. Of course, if they're ever adapted to do so (e.g., with replacement headers whose use is negotiated), that would need to be accounted for, but the proposal above doesn't preclude an approach such as that taken in the current rand-access draft, AFAICT.

**Comment by mnot** [comment]
@bsdphk:

> Making it parsing error to fail to "capture the exact numerical value" would raise the question why we don't also have that note for Numbers, which runs into the binary floating point vs. decimal numbers thing.

We're already there; we have such requirements for other types. I think the way out might be to note that float precision is implementation-dependant. 

> In all likelihood what will happen is that people won't read what we write anyway, and any 53+ bit integers will simply loose resolution in JS, just like they would if they came into JS any other way.

I agree it's hard to reflect that requirement in the unified test suite, but the fact that our first JS implementer brought this up and asked for help tells me that we should say something; they appear to be listening.

**Comment by phluid61** [comment]
How do current JS libraries deal with pathological values? (Can I crash a node script by sending an evil `range` or `content-length` header?)

**Comment by mnot** [comment]
For examples, see:
  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by phluid61** [comment]
Oh, right, MAX_VALUE is different.

**Comment by evert** [comment]
Not sure if this is interesting, but if unsafe integers appear in JSON documents, `JSON.parse()` will simply lose precision.

Example:

```
> JSON.parse('9223372036854775807');
9223372036854776000
```

Perhaps the recommendation for (javascript) implementations is to do the same, and leave it up to end-users to use strings if there is risk of overflow.

**Comment by evert** [comment]
Prior art for the JSON specification:

> Note that when such software is used, numbers that are integers and
   are in the range [-(2\*\*53)+1, (2\*\*53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.

https://tools.ietf.org/html/rfc8259#section-6

Basically the JSON spec defines a safe range but doesn't forbid larger numbers. It might be interesting to do the same thing here. If defining a safe range is still too aggressive for folks, it could simply be stated as a potential risk that certain implementations may lose precision for larger numbers.

**Comment by kazuho** [comment]
@evert Losing precision is a nightmare for header fields, because it can lead to vulnerabilities (consider the case of content-length (using structured headers) being rounded in HTTP/1; that can be used to mount a response splitting attack).

I think the "MUST fail dependably if outside of supported range" is a must-have, regardless of if we agree on having a safe range.

**Comment by kazuho** [comment]
+1 to requiring support for numbers between -2<sup>53</sup>+1 to 2<sup>53</sup>-1. JavaScript is not the only programming language that relies on IEEE 754.

**Comment by martinthomson** [comment]
> -2^53 to 2^53

> -2<sup>53</sup>+1 to 2<sup>53</sup>-1

Please get the numbers right.  I think that @kazuho got the real limits right based on there being a 53-bit modulus, though I would observe that it's 2<sup>53</sup> is faithfully represented and it's only n + n*2<sup>-53</sup> that can't be represented.  So either range works, though the smaller range is perhaps easier.

**Comment by martinthomson** [comment]
The significand is 52 bits, which produces 0b1.1{52} (i.e., 52 ones), as a maximum value, with an exponent of 52, producing 2<sup>53</sup>-1 as you say.  But 0b1.0{52} (52 zeroes) and an exponent of 53 produces 2<sup>53</sup> precisely as well.

**Comment by kazuho** [comment]
That's true, and so does 2<sup>53</sup>+2. But I think we should better refrain from listing all the integers that can be represented using IEEE 754.

**Comment by wtarreau** [comment]
Well, I'd personally vote for a range that can be tested with a single AND mask :-)  I.e. I'd like that we can check that (value & 0b011111111110000...000) == 0. This would indeed rule out the extremities hence +/-2^53, but would limit confusion and off-by-one errors. It would also avoid surprises when representing scaled down values in lower bits.

**Comment by martinthomson** [comment]
Unfortunately, the test is always going to more complicated than a mask.  A straight integer representation will need a test like `e = (int)((value >> 53) & 0x7ff) - 1023, e > -52 && e < 53`.  You might also need to test that it is an integer by looking at the low bits of the significand, though that test might be avoided with a guarantee that there is no decimal point.  Floating point is just tricky.

**Comment by bsdphk** [comment]
Mark, I'm -1 on your PR, because the same effect can be had by taking the sh-integer type out behind the barn.

We introduced sh-integer precisely to escape the 53 bit limitation of IEEE754::64bin and JS, and if we are going to put that restriction also on sh-integer, it serves no purpose any longer and should be removed.

Collapsing sh-integer and sh-number will actually simplify the spec a fair bit, for instance the "Parsing a Number from Text" algo, and some old french dude says that gets us closer to perfection than if we add more text.

**Comment by bsdphk** [comment]
I have attempted created PR #755.

**Comment by mnot** [comment]
Poul-Henning - remember that the goal here is make headers easier / less error-prone; most headers need an integer type, and forcing them to specify the error conditions if it's not an integer-carried-in-a-float is going to hurt that. 

Additionally, it's extremely convenient to map existing headers into SH -- one of the reasons we have separate String and Token types. many headers wouldn't be mappable into SH if we didn't have an explicit Integer type.

In other words -- while your spec might simplify the *spec* and even *implementations* a bit, it's making the job of people using the spec harder -- and making that job easier is the whole point of this exercise.

**Comment by bsdphk** [comment]
Make the abstract value space 15 digits:  -999,999,999,999,999...+999,999,999,999,999

**Comment by phluid61** [comment]
So we want to have integers for people who can store them in integers, but we want to limit them to what fits in a float for people who have to store them in floats. And write syntax & parsing rules for people who de/serialise them in HTTP/1 (or /2), which can distinguish the two cases.

My biggest concern through all of this is what happens when "fail parsing". There's no signal, so how do you tell someone you're ignoring the super-important integer header they sent you which is close to 64-bits wide because you're trying to store it in a float and have detected a precision drop?  The whole "you can send bigger numbers but they might fail silently" thing is bad.  (This is also true for other types, but is surfacing here now.)

**Comment by mnot** [comment]
It is true for other types; e.g., if you create a list with more than 1024 members. We came up with the "implementations must support at least..." pattern to balance a need for interop on a defined range of values with the need for more extreme values in some (hopefully limited) use cases.

Effectively, when you go beyond the required range for *any* type, you're outside the guide rails; if your header needs to convey a value like that, you need to be prepared for a failure.

The difference here, I think, is that most of the other advertised minimums are typically going to blow out the size of a single header so much that other limits will be seen first, whereas a (say) 62-bit integer will tickle this well inside the size of a "normal" header.

**Comment by martinthomson** [comment]
A lot of this design is predicated on the notion that these header fields are going to be ignored by peers that don't understand the basic header field.  I think that ignoring the value that goes out of range is fine.  

The risk, now that I think about it is in responses: client says "X", server supports X and responds with an "X" with a too-large value.  That creates a situation where the client might think that X is not supported and so it acts as though it were not, when it was.

The fix is to say that servers need to be more conservative about the values they send.  Without a signal that a client supports things outside of the envelope that this spec guarantees, they can't.  That would be general advice, because maybe the consequences aren't that bad for some values of X.

Does that need text?

(Otherwise, I agree with @mnot here.)

**Comment by bsdphk** [comment]
> That's smaller than the range we've discussed as desirable; a bit smaller than -2^50 to 2^50. We already say:
> 
> > Integers have a range of −9,223,372,036,854,775,808 to 9,223,372,036,854,775,807 inclusive (i.e., a 64-bit signed integer).
> > The ABNF for integers in HTTP/1 headers is:
> > sh-integer = ["-"] 1*19DIGIT

It is much easier for to spec and for people to get 15 digits right, than it is to get some strange power of two right, and in terms of range, both values are equally arbitrary.

**Comment by mnot** [comment]
@bsdphk AIUI you're saying that this approach:

1. Count the digits (ignoring the sign) to see if they violate a length limit
2. Parse as an integer

is easier to get right than:

1. Parse as an integer
2. Check the integer to see if it's in a pre-defined range

Correct? If so, can folks weigh in?

**Comment by evert** [comment]
Agreed

**Comment by bsdphk** [comment]
@mnot 

Yes.  Counting 15 digits is much easier than looking up what 1<<53 is.

**Comment by kazuho** [comment]
Considering that this is about minimum maximum, I tend to agree that 15 digits is better.

We want people to implement the boundary checks, and it's beneficial to define it as something that can be implemented easily (e.g., by using regular expression).

**Comment by wtarreau** [comment]
On Wed, Feb 13, 2019 at 04:12:21AM -0800, Kazuho Oku wrote:
> We want people to implement the boundary checks, and it's beneficial to
> define it as something that can be implemented easily (e.g., by using regular
> expression).

While I find it a bit sad to lose 3 more bits, I tend to agree on the ease
of applying length checks when parsing.

It's a bit sad that after removing so many bits we don't have enough anymore
to transport a timespec (32+20 bits) though, but I guess it might not be used
that much anyway.

Maybe we could extend the range a bit by covering -4999999999999999 to
+4999999999999999, which are not significantly harder to check especially
using regex, and cover a bit more than 52 bits ?

**Comment by kazuho** [comment]
> It's a bit sad that after removing so many bits we don't have enough anymore to transport a timespec (32+20 bits) though, but I guess it might not be used that much anyway.

I think you meant timeval (microsecond granularity ~ 20 bits) rather than timespec (nanosecond granularity ~30 bits). Anyways, my understanding is that POSIX is obsoleting timeval in favor of timespec. (Un)fortunately, timespec cannot be represented as a IEEE 754 double precision number.

**Comment by wtarreau** [comment]
On Wed, Feb 13, 2019 at 01:47:31PM +0000, Kazuho Oku wrote:
> I think you meant timeval (microsecond granularity ~ 20 bits) rather than
> timespec (nanosecond granularity ~30 bits).

In fact I initially thought about timespec and gave the numbers for timeval!
So I mixed them.

> Anyways, my understanding is that
> POSIX is obsoleting timeval in favor of timespec. (Un)fortunately, timespec
> cannot be represented as a IEEE 754 double precision number.

Yep indeed.

**Comment by bsdphk** [comment]
>  (Un)fortunately, timespec cannot be represented as a IEEE 754 double precision number.

You absolutely can, but you only get about ¼ microsecond resolution until 2038, and then only ½ microsecond resolution.  It is surprisingly hard to make that loss of precision matter (said the first person to ever wrangle a UNIX-style kernel at the nanosecond level :-)

**Comment by wtarreau** [comment]
On Thu, Feb 14, 2019 at 12:01:55AM -0800, Poul-Henning Kamp wrote:
> It is surprisingly hard to make that loss of precision matter

It just depends if you use it for estimation (sort by date) or to transport
exact information (file timestamp) needed to be retrieved unaltered at
another point in time (as a complement to make a unique key for example).

As an example, I've had a WiFi camera which used to take snapshots, and
I noticed that certain random files were listed but impossible to retrieve,
returning 404. They were all indexed by date, and I suspected that their
reported dates were inaccurate and didn't match the value presented in the
link. The problem was likely deeper as only second-resolution was involved
but that was to give an example use case.

**Comment by mnot** [comment]
@bsdphk:

> Counting 15 digits is much easier than looking up what 1<<53 is.

Sorry to belabour the point, but I want to understand your motivation here.

Are you saying:

1) It's easier/less error prone for people to enforce a limit at a base10 boundary because that's how most people think
2) It's easier/less error prone to count digits and then parse, rather than parse and enforce a limit after the fact
3) Something else?

My thinking:

(1) may be true, but it seems like a very weak motivation (people can cut and paste the boundary values from the spec, and we have a test suite), especially if it loses us some capability. If this is really just about saving an implementer a small amount of *effort*, I'm firmly on the side of giving users the most range we reasonably can.

(2) will catch cases when a parser can process a string that contains a value that's not within bounds, but then somehow ends up with something that is. There are cases where that's demonstrably true (e.g., `3e5`), but we can catch those with a combination of further pre-processing steps (e.g., "if the string contains anything but a digit, fail parsing") and tests.

Is there a case where invalid input will evade those pre-processing steps and still produce a valid output? My understanding that excessive values can cause imprecision once you exceed a threshold, but the returned value is never below that threshold (in the case of JS above 2^53).

**Comment by bsdphk** [comment]
@mnot:

I'm saying:  If we are to have an arbitrary limit, we should pick the most convenient one, since the precise value does not matter.

1: Yes, absolutely.

Strictly speaking, loosing the ability to communicate numbers in the ± [1000000000000000:9007199254740991] ranges is a "loss of some capability" but compared to a simpler specification you can validate by eyeball, it doesn't matter.

2: Yes, if you prefer to do it that way.

3: It is a much easier rule to remember and implement, exactly because it does _not_ happen right on the edge of what an ieee754 double can represent faithfully.

**Comment by mnot** [comment]
The other aspect here is that the PR still allows up to 19 digits -- so the range being potentially lost is actually [10,00,000,000,000,000:9,223,372,036,854,775,807] -- if the implementation chooses to support more than the minimum required.

Folks who need numbers in those ranges would benefit from SH more than small ones, so I suspect rather than serialising them in strings, we'll need to add a BigNum type to SH. 

I'm OK waiting to do that. Mostly, I want to make sure we all understand and agree to what we're doing here.

**Comment by mnot** [comment]
PTAL at the commit above.

**Comment by bsdphk** [comment]
Works for me.

**Comment by wtarreau** [comment]
OK as well
