### ISSUE TITLE
Alt-Svc:  Alternates of alternates

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#74]
When the origin delegates to an alternate for 30 seconds, and the alternate delegates somewhere else (or to itself) for 7 days, how long does the client keep it?  30 seconds because that’s what the origin said, or 7 days because the alternate is supposed to be equivalent in authority to the origin?

I'm inclined toward the second, since the alternate is supposed to be fully authoritative and since it enables use of an alternate to be persistent so long as you regularly visit the origin.  It feels odd to let a delegate grant itself more power than the delegation originally gave it, though....

**Comment by martinthomson** [comment]
I agree that it's the latter.  The alternative service is an alternative with full rights.  Those rights are based on the authentication credentials it presents, not the Alt-Svc delegation.

**Comment by mnot** [comment]
This was discussed some pre-WG and IIRC we came to the same conclusion, but it'd be good to have the discussion play out on list.

**Comment by mnot** [comment]
Discussed in Prague; second reading is correct. May need to clarify in document.

**Comment by mnot** [comment]
Do we need someone to suggest text?

**Comment by reschke** [comment]
yes

**Comment by reschke** [comment]
See https://github.com/httpwg/http-extensions/commit/7f320202815c431df89a63cfa66ebb0623ed8883
