### ISSUE TITLE
Alt-Svc header with 421 status

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#75]
Why does the spec explicitly allow the alternate to simultaneously send you an alternate list (which we trust, because the alternate is authoritative for this origin) and a status code telling us this host is not authoritative for this origin?

It seems like 421 should automatically remove the alternate (as stated) and cause the user agent to fall back to the origin server.  While one can also envision a scenario where the server says "I'm not authoritative, but I know who might be....", that way lies loops.

**Comment by mnot** [comment]
Discussed in Prague; an alt-svc header in a 421 response MUST be ignored.
