### ISSUE TITLE
HTTP/2 dependency tree is racy

### ISSUE THREAD

**Issue by pmeenan** [httpwg/http-extensions#751]
The way HTTP/2 dependencies work requires the client and server to maintain dependency trees that are (at least somewhat) in sync.

When the client starts a new stream as a child of an existing stream it provides the parent stream ID. If the parent stream ID is unknown to the server then the dependency information is [thrown away and the stream is given a default priority](https://tools.ietf.org/html/rfc7540#section-5.3.1).

In practice this is causing racy issues with Chrome's dependency tree and some server implementations. Chrome attempts to build a linear list of streams with each stream exclusively dependent on the stream before it. Higher priority streams are placed in the list ahead of lower priority streams. Each stream is also assigned a weight that maps to Chrome's internal "priority" though the weight is largely inconsequential when the dependency ordering is working because each request is always exclusively dependent on the parent in a list.

![start](https://user-images.githubusercontent.com/444165/50975374-6f48e980-14bb-11e9-85fe-5c17e848f6ff.png)

When a new stream is initiated that is a higher priority than the end of the list it is attached as an exclusive dependent of the last stream in the list with a higher priority (inserting it into the ordered priority list):

![insert](https://user-images.githubusercontent.com/444165/50975460-a7e8c300-14bb-11e9-9d0b-3cb4af50b687.png)

This is where things get racy. If the server has already sent the last part of the new parent stream but the bytes are in-flight and the client doesn't know the stream has closed yet it is possible that the server no longer knows about the parent stream that the new stream is trying to attach to. When that happens, the new stream is given a default priority (weight 16 and attached to the root).

![after](https://user-images.githubusercontent.com/444165/50975592-f6965d00-14bb-11e9-91c3-797a0f9b9fe8.png)

At this point, what was supposed to be a high-priority stream inserted ahead of streams 5-9 is now a parallel stream with a MUCH lower weight, effectively starving it and largely delaying it until all of the requests in the original list complete.

This issue was exposed with my initial [HTTP/2 prioritization test](https://github.com/pmeenan/http2priorities) which flagged both Google's and h2o's HTTP/2 implementations as not working because the race condition was being triggered. I don't know how often it happens in the wild.

h2o has mitigated the issues somewhat by remembering a set number of completed streams, reducing the likelihood that a completed stream will be needed as a parent but it is still possible to trigger depending on the size of in-flight buffers and the size of the high-priority requests (a lot of small streams and large buffers can still exhaust the dead-stream list).

Adding support for something like a FIN ACK from the client when a stream completes and only deleting streams on the server when ACK'd should at least make it deterministic.

As the HTTP/3 spec is being finalized, it might be worth considering if a stateful dependency tree is really needed or if a stateless prioritization scheme more similar to what SPDY originally used might be easier (both for servers and browsers).

**Comment by pmeenan** [comment]
btw, huge thanks to the Fastly dev team for identifying the root cause of the prioritization issues in h2o. I'm largely just documenting their findings for the working group.

**Comment by MikeBishop** [comment]
Write an I-D, send it to the HTTPbis list.  (HTTPbis will own extensions to HTTP/3 after publication, so they're probably the right venue.)

In your example, B currently depends on A, and the following two instructions are in flight:
- On stream C:  C depends on A
- On control stream:  B depends on C

The end state of these is the same, regardless of the order in which they're applied.  It's true that there could be an intermediate state in which B depends on C which depends on the root of the tree -- what we concluded was that the requirement was eventually reaching the same state, and that transient differences were tolerable.

(Repeating Stream C's prioritization on the control stream before the prioritization of B would ensure this cannot happen, if the client cares.)

**Comment by mnot** [comment]
Closing, as this is not about a currently in-progress HTTP extension spec. Please do continue discussion on-list and/or write a draft.
