### ISSUE TITLE
Refactor?

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#766]
_From Alex R on list:_

If we are to standardize X-Cache, then we should be mindful of the trap
created by early implementations that thought a single action value can
adequately relay what has happened at the proxy:

1. The obvious HIT and MISS actions came first.

2. Then we quickly discovered that a "we found it in the cache" HIT
action is often followed by a REFRESH action (and a resulting MISS from
the proxy-server traffic point of view). HIT_REFRESH... concatenations
were used to combat this.

3. Realizing that even fresh cache HITs may become misses due to various
protocol requirements and internal problems, some added X-Cache-Lookup
that was dedicated to the first (and often critical for triage) cache
lookup, depicting what happened to that HIT later in X-Cache.

4. Then flash crowds and collapsed forwarding solutions came along. Now,
a single client HIT or MISS request could cause even more transactions,
some of which could be cache hits, some could be revalidations or even
errors. Some added COLLAPSED_HIT_REFRESH... and/or other variants. This
concatenation approach still loses a lot of info, but it highlights the
fact that a lot of info could be lost by including the COLLAPSED tag.

If the goal here is to standardize the current status quo, then the
document should cover Cache-Lookup and COLLAPSED tags (and/or their
variations).

If the goal here is to standardize a scalable solution based on the
current experience, then we should combine Cache-Lookup and Cache while
enumerating individual cache actions as separate same-node entries
(instead of trying to merge them into a single FOO_BAR_BAZ super-action
summary for one node).

**Comment by mnot** [comment]
It's a good question, I think. So far we've been trying to "pave the cowpath" of existing practice. If we were to refactor the specification, I think we'd need a number of flags / fields, e.g., something along the lines of (ignore syntax issues for now):

- `uri-stored` - was there any stored response that matched the request URL?
- `variant-stored` - was the cache able to select one (or more) stored responses based upon `Vary` / `Variants` / local config?
- `server-fresh` - was the selected response fresh, according to its response freshness controls?
- `client-fresh` - was the selected response fresh, according to its request freshness controls (if the cache is paying attention to them)?
- `went-forward` - did the request go forward to an origin server (validating or not)?
- `request-collapsed` - was the request collapsed with one or more other forward requests?
- `forward-validating` - was the forward request a validating request?
- `forward-not-modified` - was the forward response a 304?

What do folks (especially cache implementers!) think?

**Comment by mnot** [comment]
Feedback from Jozef - HIT_PASS / NEGATIVE_HIT needs something explicit.

**Comment by thpts** [comment]
I had many months ago [written up a fair deal about existing public implementations](https://gist.github.com/thpts/76530c47609293f5d9a2809c3aa4d2af) and I have concluded a few points:
* Very few cache implementors either have, or expose anything more complicated than "`HIT`" or "`MISS`".
* Non-public implementations (e.g. CDNs) that I have observed appear to have no consistent caching behaviour, particularly as they are almost always multi-tiered operations - and this specification as I read it does not lend itself towards those.
* It is not clear to me how in 5-10 years time what caching systems may look like with regards to the state automata they operate.

I understand @mnot you also had some some analysis, is it worth sharing it here to compare?

To me it makes more sense to define less cache actions and extend the specification to allow for cache implementors to implement additional actions that allow them to better describe their own systems. How this might be expressed in specification I'm unsure presently but might come up with a pull request.

**Comment by mnot** [comment]
> Very few cache implementors either have, or expose anything more complicated than "HIT" or "MISS".

Oh, I disagree; ATS is quite nuanced, and Squid offers a fair amount of state. Nothing documented in the spec right now is really new; it's all exposed by implementations, often more than one.

>  Non-public implementations (e.g. CDNs) that I have observed appear to have no consistent caching behaviour, particularly as they are almost always multi-tiered operations - and this specification as I read it does not lend itself towards those.

It allows multiple hops to add values, so you can see what different caches in the hierarchy have done -- if the CDN wants to expose that information.

> It is not clear to me how in 5-10 years time what caching systems may look like with regards to the state automata they operate.

Given how little it's changed in the last twenty years, at the core, I'm not too concerned about this; we can always extend or add a new header.
