### ISSUE TITLE
Data motivating CH?

### ISSUE THREAD

**Issue by snyderp** [httpwg/http-extensions#768]
From PING:

Related but distinct from https://github.com/httpwg/http-extensions/issues/767, PING is interested in what data has been gathered / exists to motivate this change.  Given that the spec increases the risk of privacy-loss (there is a subsection of the spec for this purpose), we're interested in what data exists to show that this risk would be counter balanced by benefit to:
1) A significant portion of web users,
2) On a significant portion of web sites

Does any such data exist?  Any relevant information would be extremely useful as we continue considering the proposal.

**Comment by mnot** [comment]
HI, this isn't an issue with the spec; please engage with the authors or the WG mailing list directly.

**Comment by snyderp** [comment]
PING as been asked to consider the CH proposal, and was told GH issues was the best place to do.

If that is not correct, please kindly point us to where the best place would be to follow up.  ietf-http-wg@w3.org ?

**Comment by mnot** [comment]
Yes, that's fine.

**Comment by colinbendell** [comment]
@snyderp I published data here: https://cloudinary.com/blog/client_hints_and_responsive_images_what_changed_in_chrome_67

**Comment by snyderp** [comment]
Hi @colinbendell 

Thanks for the link!  After reading through the document though, it wasn't clear to me, which of these improvements would you have *not* been able to make through a combination of `<picture>` and CSS media queries?  Does CH make it more convenient, or is there something unique about CH that enables these optimizations (and if so, do you have a sense of what % of the improvement could have been captured with `<picture>` + `CSS` alone)?

Thanks much for any thoughts you could share!

**Comment by colinbendell** [comment]
I'll reply on the ietf-http-wg@w3.org thread and move it out of this closed issue
