### ISSUE TITLE
Clarify SameSite behavior for non-HTTP API

### ISSUE THREAD

**Issue by ericlaw1979** [httpwg/http-extensions#769]
In Firefox and Safari, |document.cookie| matches the |Cookie| header. 
In Chrome and Edge, samesite=strict cookies are omitted from the |Cookie| header but included in the |document.cookies| collection following a cross-origin navigation.

Test: https://debugtheweb.com/test/cookie/samesite/
Chrome Issue Tracker: https://crbug.com/925311

**Comment by tbroyer** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1530995 (contrary to the test and Chrome issue linked above, the cookie here is set in the response after the navigation; it's still related to how to build a cookie-string for non-HTTP API and whether SameSite cookies should be returned or not)

**Comment by annevk** [comment]
See also https://github.com/whatwg/html/issues/804 and #1073.

**Comment by chlily1** [comment]
Currently, Firefox and Chrome both allow access to SameSite=Strict cookies (and Lax cookies) via `document.cookie` following a cross-site navigation. Safari omits SameSite=Strict cookies.

In Firefox and Chrome, for `document.cookie`, the same-site vs cross-site distinction only depends on the frame hierarchy of the document, which always includes all SameSite cookies (if same-site) or only includes SameSite=None cookies (if cross-site).

**Comment by chlily1** [comment]
I believe #1428 addresses this adequately.
