### ISSUE TITLE
Clarify "append" in CDN-loop

### ISSUE THREAD

**Issue by zwoop** [httpwg/http-extensions#771]
It may be obvious, but I think clarifying that when a conforming CDN "adds" to the header, it must be an append. E.g.

```
As with all HTTP header fields defined using the "#" rule, the CDN-
Loop header field can be **appended** to by comma-separating values, or by
creating a new header field with the desired value.
```

(emphasis mine, s/added/appended/. it certainly wouldn't hurt to have such a clarification IMO :).

**Comment by mnot** [comment]
OBE
