### ISSUE TITLE
Correct behaviour for a POST-redirect-GET when using SameSite=Lax

### ISSUE THREAD

**Issue by pmhsfelix** [httpwg/http-extensions#773]
In the context of <https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-02>, 
I would like to clarity what is the intended behaviour for the `GET` request in the following scenario, when using a cookie with `SameSite=Lax`:
- `POST` to `https://example.com/path-1` triggered by a cross-site document.
- Response to the `POST` is a redirect status code to `https://example.com/path-2`.
- `GET` to `https://example.com/path-2`.

When using `SameSite=Lax` it is rather clear that the first request (`POST`) will not contain the cookie, since it is using a non-safe method.
However, the behaviour for the `GET` is not completely clear because:
- It is a safe method.
- However, it was triggered by a non-safe cross-site request.

I've tested it with two different browsers and obtained two distinct behaviours:
- Safari (macOS Mojave) - the cookie is not sent on the `GET` request.
- Firefox (`65.0.1`) - the cookie is sent on the `GET` request.

**Comment by chlily1** [comment]
There's now a sentence in the spec clarifying this issue. (Still needs WPT coverage.)

In the above scenario, the Lax cookie should be sent on the `GET` request. I believe Chrome sends the cookie (tested on Chrome 86), and Safari does as well (tested on 13.1.3).

**Comment by chlily1** [comment]
@mnot Since we have clarified this in the spec and have alignment between Chrome, Firefox, and Safari, can we close this issue?

**Comment by mnot** [comment]
Yes (see [our working procedures](https://httpwg.org/CONTRIBUTING.html#resolving-issues) for details).

**Comment by miketaylr** [comment]
@mnot Can @chlily1 (and @englehardt) be added as collaborators to the repo so they can close issues (in accordance with working procedures)?
