### ISSUE TITLE
Variant-Key needs justification

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-extensions#783]
As mentioned in Prague, I don't see why the origin server is sending duplicate metadata in the Variant-Key field when the data should already be present in content metadata fields. This is true for all of the examples in the spec, but perhaps you have other examples in mind for which that would not be the case?

I know it is simpler for caches to not have to look at every field, but they can determine this from the metadata during the post-store non-critical path. In general, I don't think we should send redundant data on the wire unless absolutely necessary. It also runs the risk of reality distortion if the key (mistakenly) contradicts the metadata.

**Comment by wimleers** [comment]
I _think_ @mnot chose this approach to signal that a single response variant can satisfy multiple possible requests. i.e. this bit in the text:

> If the response can be used to satisfy more than one request, they can be listed in additional members. For example:
> ```
> Variants: Accept-Encoding;gzip;br, Accept-Language;en ;fr
> Variant-Key: gzip;fr, "identity";fr
> ```
> indicates that this response can be used for requests whose Accept-Encoding algorithm selects “gzip” or “identity”, as long as the Accept-Language algorithm selects “fr” – **perhaps because there is no gzip-compressed French representation.**

(Emphasis mine.)

But I also struggle to see how widely useful this would be. The emphasized sentence in the quote is not a particularly widespread use case, and hence not very convincing.

Perhaps @mnot has concrete use cases in mind for less common request/response headers?

**Comment by mnot** [comment]
Yes; I've seen cases where this (having multiple possible cache keys) quite a lot.

Also, for header compression, the Variants information is less likely to change from representation to representation, and so it compresses better when it's separated out. See [this](https://www.mnot.net/blog/2018/11/27/header_compression).

**Comment by MikeBishop** [comment]
+1.  Envision this as a Karnaugh map minimization.  The Variants header tells you what all the possible inputs are, but the Variant-Key header enables you to do the minimization step, circling multiple outputs and marking them as a single outcome.

A more convincing case for me, though probably not something we want to explicitly encourage, is this:

    Variants:  Sec-CH-UA;"Chrome 77";"Chrome 76";"Chrome 75";"Firefox 68";"Firefox 67"
    Variant-Key:  "Chrome 77", "Firefox 68"

That is, "I would have served this content to the most recent versions of Firefox or Chrome, but would have served different content to an older browser."  Without this, resources would be separately cached for each possible value of Sec-CH-UA.

**Comment by mnot** [comment]
See also the cookie example I've roughed into the current editor's draft.
