### ISSUE TITLE
Boolean type character choice

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#784]
This is going to sound like a bikeshed comment, but it's probably worth thinking about:

The current syntax uses `?T` and `?F`.  In sitting through a presentation today, I realized that, from a distance, these two strings are hard to distinguish if the text is small enough.  Looking at the QPACK table, I observe that existing header fields often use `1` to mean "true".

I propose that the syntax be changed to `?0` and `?1`.

**Comment by martinthomson** [comment]
Some feedback on this suggestion:
> Mike West   I suspect that `Sec-Fetch-User` is going to be the first boolean header hitting the wire. So. Hammer it out quickly, please (@mnot).
> Mike West   Ideally shipping in Chrome 75, which branches on the 18th.

**Comment by bsdphk** [comment]
No opinion.

**Comment by mnot** [comment]
I think the benefits aren't significant enough to change, given that it's already in use by some. Practically speaking, if you project HTTP headers that small, you're going to have lots of other problems too.

**Comment by wtarreau** [comment]
On Wed, Apr 03, 2019 at 05:39:55AM -0700, Martin Thomson wrote:
> I propose that the syntax be changed to `?0` and `?1`.

I'm used to 0 and 1 as well in general and I didn't first get this
?T/?F to be honest :-)

Willy

**Comment by mnot** [comment]
The non-english interpretation (of lack thereof) is persuasive here. @mikewest @jyasskin will changing this now cause any significant pain? Anyone else?

**Comment by jyasskin** [comment]
Signed Exchanges don't have any Boolean fields, and they're versioned anyway so we could change the parsing.

**Comment by mikewest** [comment]
I'm happy for `Sec-Fetch-User` to serialize however you'd like. Pick something, tell me what it is, and I'll do it. Assuming it'll be `?1`, I filed https://bugs.chromium.org/p/chromium/issues/detail?id=949894 and put up https://chromium-review.googlesource.com/c/chromium/src/+/1554484.

**Comment by bsdphk** [comment]
Still no opinion :-)

**Comment by mnot** [comment]
Let's do `0` / `1`

**Comment by mikewest** [comment]
With the `?` prefix, though (`?0`/`?1`), right?

**Comment by mnot** [comment]
?1

**Comment by mikewest** [comment]
(Maybe we can use :+1: and :-1: instead?)

**Comment by mikewest** [comment]
(That was a joke, just in case it wasn't clear. `?1` is just as great as `?T`, and I'll aim to land https://chromium-review.googlesource.com/c/chromium/src/+/1554484 to lock that into Chrome's implementation shortly.)

**Comment by arturjanc** [comment]
The root cause here seems to be interplay between the similar visual appearance of the Greek digamma (`Ϝ`) and tau (`Τ`) which became a problem during the introduction of the West Saxon _triewe_ and _false_ to mean opposing values of truthiness (both introduced in the Old English revision, ca. AD 1200). 

Rather than work around this legacy problem with the use of numerals, I would recommend reverting to the last character notation that didn't exhibit the problem -- Phoenician could be fine, though we might have to go as far back as Ugaritic.

**Comment by mikewest** [comment]
@arturjanc: I am not changing Chrome to support Ugaritic. Or Phoenician. :)
