### ISSUE TITLE
Consider adding `None` to the list of values for the `SameSite` attribute.

### ISSUE THREAD

**Issue by mikewest** [httpwg/http-extensions#788]
Giving developers an explicit keyword that asserts non-`SameSite`ness  seems like it's both helpful from an explanatory perspective, and could open paths towards tightening cookie behavior in the future. Perhaps something like `SameSite=None` to represent the status quo default behavior. That is, the following two `Set-Cookie` header values would produce the same cookie today:

```
name=value
```

```
name=value; SameSite=None
```

**Comment by orvillelawrence72** [comment]
We're is my stimulus check and child tax credit it was suppose 2 been here in September of 2022
