### ISSUE TITLE
Structured headers: serialise / serialize

### ISSUE THREAD

**Issue by evert** [httpwg/http-extensions#791]
The structured headers draft heavily uses the spelling 'serialise'.

I have no stake in this. I was raised in the Netherlands, learned UK-English and now live in Canada. I enjoy the subtle differences and cultural expression.

There is one instance in the draft though that specifically suggest calling a function 'serialise':

https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-10#section-3.9

> A generic implementation should expose the top-level parse
   (Section 4.2) and serialise (Section 4.1) functions.

This I am less comfortable with. Many (if not most) popular programming languages will use 'serialize' in their spelling. I feel that it would be slightly better to stick to this.

I might also just rename my `serialise` function to `stringify` because it's more consistent with typical Javascript api's such as `JSON.stringify`.

**Comment by mnot** [comment]
Usually I let the RFC Editor sort this out, but that's a good point. Will adjust.
