### ISSUE TITLE
Structured headers: merge List and Parameterized List

### ISSUE THREAD

**Issue by evert** [httpwg/http-extensions#794]
I wanted to bring this up as a suggestion, I hope it's not too late in the development in the draft.

I intended to use the structured headers format for a draft I'm working on: [Prefer-Push](https://tools.ietf.org/html/draft-pot-prefer-push-00).

The specific format I'm using right now is a list:

    Prefer-Push: rel1, rel2, "rel3"

It occurred to me that it might be a good idea to keep a door open to future extensions. If I tell folks from Day 1 that the value _must_ be parsed as a parameterized list, it allows this to be extended further down the line despite that there's no parameters defined right now.

This led me to wonder... well, is this even a good idea? It seems reasonable to try and keep things open for future extension.

This led me to my second thought: is there ever a point to *not* parse lists as if they were parameterized lists. The implication is that any of these headers can always be more easily extended.

**Comment by phluid61** [comment]
Well, if the quotation marks actually matter, `rel1, rel2, "rel3"` isn't a valid parameterised list, because the primary identifier of each list element has to be a token. (In the same vein you can't parameterise a list of numbers, or certain URL references)

If you're asking why that's the case, uhm... I think it grew out of #443.

**Comment by evert** [comment]
I see, that makes sense.

I guess really my question then becomes, why not define a more broader syntax and leave it up to specific headers to to specify what subset they require, but I think that ship may have sailed.
