### ISSUE TITLE
Update abstract to reflect the current document scope

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-extensions#799]
The current (draft 10) abstract says

> This document describes a set of data types and algorithms associated with them that are intended to make it easier and safer to define and handle HTTP header fields. It is intended for use by new specifications of HTTP header fields as well as revisions of existing header field specifications when doing so does not cause interoperability issues.

whereas the editors are currently working on something more like

   - This document describes a set of data types and associated algorithms for easier definition and processing of HTTP header fields that are known to have values limited to those types. It is intended for use by specifications of new HTTP header fields that wish to use a common syntax that is more limited than traditional HTTP/1.x field values.

**Comment by phluid61** [comment]
I like the current first sentence and the new second one.

> This document describes a set of data types and associated algorithms associated with them that are intended to make it easier and safer to define and handle HTTP header fields. It is intended for use by specifications of new HTTP header fields that wish to use a common syntax that is more restrictive than traditional HTTP/1.x field values.

"Easy and safe" implies "restricted"; no need to say 'limited' twice in as many sentences. (Sounds a bit.. judgmental.) And it fits the mental model I've built up.
