### ISSUE TITLE
Distinguishing intermediaries from origins

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#80]
In the current draft, 451 is used both to indicate when the origin server has the legal demands placed upon it, and when an intervening intermediary is enforcing such a demand.

In discussion, some have wondered whether it would be useful to be able to distinguish them in a machine-readable way; e.g., using a different status code (452?) or a response header.

**Comment by wseltzer** [comment]
Yes, I think it would be useful to distinguish.

**Comment by mnot** [comment]
Discussed in Prague; sense in the room was that it is worth distinguishing, but no strong opinions about how to express it (except @mnot).

**Comment by reschke** [comment]
In the meantime, draft 02 defines a "blocked-by" link relation.

**Comment by mnot** [comment]
LGTM; I think we just need to put a template registering 'blocked-by' in IANA considerations, as per http://tools.ietf.org/html/rfc5988#section-6.2.1

**Comment by mnot** [comment]
In WGLC, but the template can be taken care of in the next version.

**Comment by timbray** [comment]
Added in -03
