### ISSUE TITLE
Add a subsection on limitations

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-extensions#801]
If the proposed syntax is intended to exclude many existing field values defined by HTTP in practice, then the document should clearly state that up front and as an essential design criteria (e.g., a new section 1.1 on field value limitations) before strict processing.

The reader shouldn't have to figure out from the ABNF that this syntax is incapable of handling empty field values, links with parameters, empty lists, or heterogeneous lists. It should also make some mention of motivations, such as avoiding the hell of Cookie syntax and failures in handling Set-Cookie in list form.

**Comment by mnot** [comment]
The document already clearly states that it's not to be used for existing values. 

If you have a proposal for text here I'm happy to look at it, but I don't really know where you're going with this.

**Comment by mnot** [comment]
As per discussion in Montreal, closing.
