### ISSUE TITLE
Proxy-Status: add Proxy Internal Response.

### ISSUE THREAD

**Issue by PiotrSikora** [httpwg/http-extensions#807]
This is proposal to add `Proxy Internal Response` type that could be used to indicate that the response was generated by the intermediary (since we don't have any type that could be used in such case).

* Name: proxy_internal_response
* Description: The intermediary generated the response locally, without attempting to connect to the next hop (e.g. in response to a request to a debug endpoint terminated at the intermediary).
* Extra Parameters: None.
* Recommended HTTP status code:

PR: #806 

cc @mnot

**Comment by mnot** [comment]
We already have `proxy_internal_error`; maybe adjust that one to suit?

**Comment by PiotrSikora** [comment]
Erm, those 2 have quite different purpose:

`proxy_internal_error` is `Proxy-Status` equivalent of `500 Internal Server Error`, i.e. something is terribly broken and proxy couldn't handle the received request.

`proxy_internal_response` is supposed to indicate successful response generated by the proxy itself (e.g. in response to a request to a special debug URL like https://www.cloudflare.com/cdn-cgi/trace).

cc @alyssawilk

**Comment by mnot** [comment]
Got it. Merging, but we might want to look at the entire set and make sure we have enough context / prose around all of them (including this one) to make sure people understand the appropriate uses of them.
