### ISSUE TITLE
Proxy-Status: detailed types for HTTP request errors.

### ISSUE THREAD

**Issue by PiotrSikora** [httpwg/http-extensions#808]
Currently, `Proxy-Status` draft defines only a single catch-all `http_request_error` error type for all issues with HTTP requests, and piggy-backs on the `4xx` status codes (`400`, `403`, `405`, `406`, `408`, `411`, `413`, `414`, `415`, `416`, `417`, `429`) for the exact reason as to why the request failed.

This is a bit inconsistent with the detailed error types it defines for issues with HTTP responses (`http_response_incomplete`, `http_protocol_error`, `http_response_header_block_size`, `http_response_header_size`, `http_response_body_size`, `http_response_transfer_coding`, `http_response_content_coding`, `http_response_timeout`).

But more importantly, it means that the `Proxy-Status` header isn't self-contained and it forces recipients to look in 2 places (`Proxy-Status` header and status code) to get the reason of the failure, and to take any action (log the error, etc.).

While duplicating the information between `4xx` status codes and `Proxy-Status` type isn't ideal, the self-contained header seems to be worth it, IMHO.

Current draft:
```
HTTP/1.1 411 Length Required
Proxy-Status: http_request_error
```

This proposal:
```
HTTP/1.1 411 Length Required
Proxy-Status: http_request_length_required
```

Thoughts?

cc @alyssawilk @mnot

**Comment by mnot** [comment]
Besides the bloat issues in the spec (we'll manage ;), I'm concerned here that we're creating a lot of corner cases due to misalignment; if the response status code and the proxy-status type are misaligned, what will happen? In particular, if some software isn't aware of proxy-status, it will act on the status code, whereas other software on the same path that is aware of it will act differently.

**Comment by alyssawilk** [comment]
Just weighing in here, if we don't split out these as their own status codes, I suspect folks will end up shoving the redundant information into the details section.  If the goal of proxy status is to have consistent standardized error diagnoses across various proxies I think it's worth the bloat because otherwise the information will be not be delivered and/or communicated consistently

**Comment by mnot** [comment]
Alyssa do you mean s/status codes/error types/?

**Comment by PiotrSikora** [comment]
Isn't misalignment an issue already, since it can happen for response errors as well (even more so, since we use only a few 5xx response codes)? e.g. `http_response_body_size` vs `502 Bad Gateway`.

**Comment by mnot** [comment]
What if we just had a parameter `status_code` whose value was the status code in question?

**Comment by PiotrSikora** [comment]
`status_code` param would make the headers self-contained, yes, but if we want to have an easy-to-extend registry of valid status types, then we probably shouldn't piggy-back on the harder-to-extend(?) list of existing HTTP status codes. It also doesn't address the inconsistency problem.

**Comment by mnot** [comment]
@PiotrSikora I've just committed a start at this; it doesn't include all of the status codes (right now, only 4xx; I think we'd need to include at least 2xx and 3xx, and possibly 5xx and 1xx too).

PTAL. I know I was OK with this when we talked on Friday, but going through this has made me question that; it's really a lot of duplicated information, and it requires a lookup table to find the right type (along with the errors that might happen there). I think we might get some pushback from the group as a result.

I'm happy to go to them to see what they think, but if we choose to go with at `status_code` approach, I think what we'd do is to say "use this if there's a specific status code that covers your situation; if not, create a new type that does."

Tell me what you think.

**Comment by mnot** [comment]
@PiotrSikora ping

**Comment by ioggstream** [comment]
Questions:

- will implementors end checking both the proxy-status and the status code?
- which are the probability for misalignment?

A note:

- as the status message (eg. "bad_request") may change in time (see https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#status.422) I won't use it.

**Comment by tfpauly** [comment]
In Singapore, discussed not enumerating all cases as new errors. Discussion landed on only transmitting the error code as the value.
