### ISSUE TITLE
Cookies: mismatch between specification and test

### ISSUE THREAD

**Issue by annevk** [httpwg/http-extensions#814]
As far as @bakulf and I can tell, https://github.com/web-platform-tests/wpt/blob/master/cookies/samesite/form-get-blank.html attempts to set SameSite cookies cross-site, in particular line `create_test(CROSS_SITE_ORIGIN, CROSS_SITE_ORIGIN, SameSiteStatus.LAX, "Cross-site top-level form GETs are laxly same-site");`.

This seems counter to step 14 of https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-5.4.

Yet Chrome passes this test.

cc @mikewest

**Comment by mikewest** [comment]
The editor's draft is more up to date: https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#storage-model. https://github.com/httpwg/http-extensions/issues/594 and https://github.com/httpwg/http-extensions/pull/800 capture the conversation around that change. In a nutshell, no one matched the spec. Chrome tried to, and immediately broke some OAuth endpoints.

**Comment by mikewest** [comment]
Should have closed this earlier; closing it now. Both the spec and the tests are, I think, the behavior we want here.
