### ISSUE TITLE
bcp56bis refers to PATCH method

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#815]
## I expect

This bcp56bis to refer to methods properly defined in  httpbis-semantics

https://github.com/httpwg/http-extensions/blame/master/draft-ietf-httpbis-bcp56bis.md#L420

## Instead

 `PATCH`  is still entangled with entity, entity-header & co

## Note

- is that an issue?
- should we introduce PATCH in httpbis-semantics ?
- should we add an httpbis-patch ?

**Comment by reschke** [comment]
This is not an issue for bcp56bis.

It might be a work item for http-core. Personally I would recommend keeping it a separate document.

**Comment by mnot** [comment]
Agreed.
