### ISSUE TITLE
Alt-Svc Header - hop by hop

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#83]
Amos pointed out that we should consider making the header field explicitly hop-by-hop, to match the semantics of the frame.

**Comment by mnot** [comment]
Discussed in Prague; end-to-end header is useful in the OppSec use case, and it doesn't need to be consistent with the frame. Feeling in room was to close with no action.

**Comment by reschke** [comment]
see https://lists.w3.org/Archives/Public/ietf-http-wg/2015JulSep/0369.html

**Comment by mnot** [comment]
Closing due to lack of further input.
