### ISSUE TITLE
Digest: unused references

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#831]
- [x] Warning: no \<xref> in \<rfc> targets \<reference anchor='RFC7233'>
- [x] Warning: no \<xref> in \<rfc> targets \<reference anchor='FIPS180-4'>
- [x] Warning: no \<xref> in \<rfc> targets \<reference anchor='RFC2818'>
- [x] Warning: no \<xref> in \<rfc> targets \<reference anchor='RFC5788'>
- [x] Warning: no \<xref> in \<rfc> targets \<reference anchor='RFC6962'>

**Comment by ioggstream** [comment]
Fixed in #833
