### ISSUE TITLE
properly cite definition of ABNF

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#84]
"The ABNF (Augmented Backus-Naur Form) syntax for the ALPN header field is given below. It is based on the Generic Grammar defined in Section 2 of [RFC7230]."

This needs to say something like

"The ABNF (Augmented Backus-Naur Form) syntax for the ALPN header field value is given below. It uses the syntax defined in Section 1.2 of [RFC7230]."

**Comment by martinthomson** [comment]
I think that you have commit access.  If it is my permission that you need, you have it.
