### ISSUE TITLE
Talk about freshness

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#840]
Some people find it surprising that a cache can return a stale response (e.g., when disconnected from the origin server). It would be good to talk about:

* [ ] Advice to clients regarding examining the freshness of returned responses
* [ ] Advice to servers about setting appropriate cache-control for corner cases (e.g., `must-revalidate`)
* [ ] Advice to spec authors when they're writing requirements for both

**Comment by richsalz** [comment]
This has come up in a proposed errata for RFC 8555, https://www.rfc-editor.org/errata_search.php?rfc=8555&eid=5771
