### ISSUE TITLE
Dictionary of a dictionary

### ISSUE THREAD

**Issue by kazuho** [httpwg/http-extensions#842]
Now that we are generalizing how the types are used, I think it might be a good idea to allow a dictionary value to be a mapping (i.e., a list of parameters).

This would be a generalization. At the moment, top level elements can contain scalars, lists, or dictionaries. However, it is at the moment impossible to use a dictionary at the second level even though scalars and lists are permitted.

In terms of use-case, the proposed change would allow for example something like a cache-control directive to take a mapping as an argument (see https://github.com/httpwg/http-extensions/pull/824#discussion_r300230506).

Logic-wise, I assume that the added complexity would not be significant, as we can reuse the definition for the parameters of a parameterised list.

**Comment by mnot** [comment]
@kazuho are you just asking for parameters on dictionary values, in a manner that's equivalent to list values?

**Comment by kazuho** [comment]
@mnot Sorry for the belated response.

Yes. I'd be fine with member-value being exactly list-member.
