### ISSUE TITLE
* in parameter names

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#844]
RFC5987 encoding uses `*` in parameter names. Should we allow this? Would require modifying `key`.

**Comment by reschke** [comment]
RFC 8187.

That said, good catch. But also opens the can of worms about non-ASCII.

**Comment by mnot** [comment]
@bsdphk nudged me into remembering it. I agree WRT the can-of-ASCII-worms, but in this case, our current design has the effect that it's not possible to port a 8187-encoded header into SH without performing some pretty nasty tricks (because we'd need a _different_ sigil to indicate the encoded parameter, and we really don't have any available).

That may be a perfectly fine outcome; it could be that we don't want to port `Content-Disposition` (others?) into SH. 

The charm of the current design that it's easy to represent in common programming languages, e.g., as a property of an object. Not sure how important that really is, though.

**Comment by martinthomson** [comment]
Is there a path toward including Unicode directly?  I mean, there's not even a shadow of a hope of just putting Unicode between quotes and calling it a day when it comes to existing header fields, I assume.  But what would it take to get there?  Sadly, I don't think that a new serialization is what gets you there, at least not directly, but it does suggest that there are possibilities.

**Comment by mnot** [comment]
The path to unicode is -- for the current, textual serialisation -- to encode it somehow into ASCII. 8187 is one way to do that, but it's important to remember that it's *just* for parameter values that use a special convention, and have a fallback parameter value that's pure ASCII. 

I.e., it's a very specific model, not a general approach to unicode in headers. If we accommodate `*` in keys, we could say that it's reserved for this use, and have an alternative encoding of the value in a new serialisation.

**Comment by martinthomson** [comment]
That's not a path, that's a hack.  Reserving `*` for that hack might be reasonable, but I'm looking at the bigger problem space.

If you accept that header field values are sequences of bytes (not ASCII), then you do have some leeway.  The problem being that I suspect that the reason we have the hack is that we don't have 8-bit clean paths through everywhere.  But if there is some incentive associated with making these 8-bit clean for some other purpose (like alternative serialization), then there is hope for that.  Once there, the semantics of `Header: "🖲🔥"` are ours to define.

Too optimistic?

**Comment by mnot** [comment]
I think so. But really this is #537.

**Comment by martinthomson** [comment]
OK, then I'll add my support to Roy's comments there, acknowledging that that might be a little optimistic.

**Comment by reschke** [comment]
"Link", too, not only "Content-Disposition".

If we don't get non-ASCII in strings, reserving "*" for RFC 8187 encoding might be the next best approach. Not having something will cause people to invent new stuff, which seems to be a bad outcome.

**Comment by evert** [comment]
If UTF-8 is definitely out of scope, I also hope that `*` can be reserved for RFC 8187 encoding. At least it keeps a door open to merging these formats one day.

That said I really would *love* RFC8187 encoding in structured headers. I realize that this topic has been beaten to death already though.

**Comment by phluid61** [comment]
Does it conflict in serialisation with binary data? I can't keep track of where we're up to.

**Comment by mnot** [comment]
No.

**Comment by mnot** [comment]
My sense after discussion in Montreal is that specifying the use of 8187 in SH is too much complexity for the benefit. However, it seems like we can allow `*` in key names without too much trouble, enabling those use cases if folks want to specify how to do it.
