### ISSUE TITLE
Serializing sh-float is hard

### ISSUE THREAD

**Issue by bsdphk** [httpwg/http-extensions#848]
The current definition of sh-float is surprisingly hard to serialize correctly, the best C-code I could come up with is:

        int
        serialize_sh_float(char buf[18], double d)
        {
                int p = 0, l, dig;

                buf[0] = '*';
                buf[1] = '\0';
                if (isnan(d))
                        return (-1);
                if (fabs(d) >= 99999999999999.95)
                        return (-1);

                if (d < 0) {
                        buf[p++] = '-';
                        d = -d;
                        l = 18;
                } else {
                        l = 17;
                }
                dig = trunc(log10(d));
                p += snprintf(buf + p, l - p, "%.*f", 15-dig, d);
                while (buf[p-2] == '0') {
                        buf[p-1] = '\0';
                        p--;
                }
                return (p);
        }

And that is horrible in severale levels.

If we insist instead that sh-float can have maximum six digits after the decimal point, people can rely on the default "6 decimals" behaviour of "%f" formatters, and use the simpler:

        int
        serialize_sh_float(char buf[18], double d)
        {
                int p = 0, l, dig;

                if (isnan(d))
                        return (-1);
                if (fabs(d) >= 99999999999999.95)
                        return (-1);

                if (d < 0) {
                        buf[p++] = '-';
                        d = -d;
                }
                p += snprintf(buf + p, 18 - p, "%-16f", d);
                while (buf[p-1] == ' ')
                        p -= 1;
                buf[p] = '\0';
                return (p);
        }

**Comment by mnot** [comment]
+1 from me, our primary focus should be on data types that will have good interop. That level of precision isn't necessary for any current use of HTTP headers I'm aware of, off the top of my head.

**Comment by martinthomson** [comment]
Proposal:

1. Call these **decimal**.
2. Allow a maximum of 9 digits on the left of the decimal place and 6 after.  This matches the definition for int and allows storing this in the same sized slot with a `*1e6` or `/1e6` conversion factor.

**Comment by martinthomson** [comment]
ABNF gets much simpler.
```
sh-decimal = ["-"] 1*9DIGIT "." 1*6DIGIT
```

**Comment by bsdphk** [comment]
@martinthomson That would probably curtail the range too much.

I think it is desirable to be able to move posix time_t timestamps in these.

**Comment by reschke** [comment]
If this really is an integer with fixed point semantics, why do we need it at all?

**Comment by phluid61** [comment]
> If this really is an integer with fixed point semantics, why do we need it at all?

Because it's easier than making people specify "divide the number by a million to get its real value"?

That said, I agree that 9 digits to the left of the point is probably not enough, so a floating point representation is more useful.

This is the ABNF equivalent of @bsdphk's C code, yeah?:

```
sh-float    = ["-"] (
           1*9DIGIT "." 1*6DIGIT /
            10DIGIT "." 1*5DIGIT /
            11DIGIT "." 1*4DIGIT /
            12DIGIT "." 1*3DIGIT /
            13DIGIT "." 1*2DIGIT /
            14DIGIT "." 1DIGIT )
```

That easily gets us a current 32-bit time_t plus microseconds, and a whole range of other values besides.

**Comment by martinthomson** [comment]
Why do the arguments about size of integers not also apply here?  `time_t` is 64-bit on my system, which doesn't fit in the sh-integer definition either.

**Comment by phluid61** [comment]
The current time is `1564367600`ish. You don't need to prefix it with 30 bits worth of zeroes.

**Comment by phluid61** [comment]
I've read the IETF105 minutes, and thought about the fixed-point discussion.  All the uses for "decimal number with fractional part" I can think of\* would reasonably served by at least 10 digits to the left\*\* and at least 3 to the right of the point.  So I would support any fixed- or floating-point representation that supports that range of values.

\* that's all that matters, right?

\*\* a ten-decimal-digit time_t gives us until November 20, 2286

**Comment by bsdphk** [comment]
Using the max-six-decimal definition, and allowing 15 digits with no period or decimals, this C-code will do the job:

        static char *
        sh_float(double d)
        {
                static char buf[40];
                int n;

                if (fabs(d) < 1000000000) {
                        n = snprintf(buf, sizeof(buf), "%f", d);
                        while (buf[--n] == '0')
                                buf[n] = '\0';
                        if (buf[n] == '.')
                                buf[n] = '\0';
                } else {
                        n = snprintf(buf, sizeof(buf), "%.15g", d);
                }
                return (buf);
        }

**Comment by bsdphk** [comment]
Sorry, wrong button.

**Comment by martinthomson** [comment]
If I take #893, then I can *almost* represent that in a JS float in the most horrific way imaginable:

```js
let dot = s.indexOf(".");
if (dot > 0) {
  m = s.length - dot - 1;
  s = s.slice(0, dot) + s.slice(dot+1);
} else if (dot == 0) {
  throw "bad";
}
const stored = parseInt(s) + m * Math.pow(10, 15);
```

But that doesn't quite fit.  69999999999999999 doesn't fit into a double.  If you want to remember the number of additional decimal places so that you don't lose any precision on those trailing decimal places (things like 0.3 are surprisingly tricky to re-encode), you are left with supplementary values.  Can someone make a better case for any more than 10^10 values here?  I couldn't see a good one.  You can fit a 32-bit value in that.

If you really think that time_t is valuable, which I'm totally not convinced of, then fewer steps might be acceptable.  I can pack this:
```
sh-float    = ["-"] (1*9DIGIT "." 1*6DIGIT / 12DIGIT "." 1*3DIGIT)
```

**Comment by mnot** [comment]
PR updated. Any further comments, or ready to merge?
