### ISSUE TITLE
Using Digest in signatures

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#851]
## I expect

To better detail the usage of `Digest` in signatures, including:

- [x] you need a transport-layer integrity mechanism for the whole message;
- [x] what should be included in signature for integrity (representation metadata affecting digest-algorithms)
- [ ] issues with signing partial representations (eg. Range-Request, PATCH, ..)
- [x] using strong crypto algorithms

This should be done:

- [x] respecting the dependency model is that a signature doesn't need to include a digest but it can;
- [x] don't explain too much of signature risks inverting the dependency;
- [x] add useful guidance that is relevant to Digest and expected usages but without also defining the expected usages completely.

## Questions

- consider signing `Content-Length` too ([it's a representation-metadata in http-core](https://tools.ietf.org/html/draft-ietf-httpbis-semantics-04#section-6.2)), though it would eliminate the ability to do things like chunked transfer-encoding, which is quite common. @dlongley

## Previous discussions

What we have today is probably sufficient but we're open to compelling reasons on what would be really helpful to define in this document.

The followings may be out-of-scope:

  - [length-extension attack on the signature](https://en.wikipedia.org/wiki/Length_extension_attack): Digest should not be subject to length extension attacks because **it doesn't provide a proof of origin**;
  - which other signature data unrelated to `Digest` (eg. timestamp, method & co)

**Comment by LPardue** [comment]
What does it take to close this issue?

Since we opened it, the HTTP WG has adopted a signautes draft. Does that move the needle on any questions we have?  Can we spin out anything or makr them as won't do?

**Comment by ioggstream** [comment]
"Usage in signatures" covers the goals enough.

https://github.com/httpwg/http-extensions/blame/master/draft-ietf-httpbis-digest-headers.md#L1012

- we provide considerations but won't specify what other headers should be signed (eg. content-length);
- as https://github.com/httpwg/http-extensions/blob/master/draft-ietf-httpbis-message-signatures.md should be independent from Digest, the best we can do is to write a BCP on Digest and Signatures.

This is the repository placeholder https://github.com/ioggstream/draft-polli-digest-signatures (still not edited).

@richanna @jyasskin @jricher  WDYT? 
@LPardue feel free to close if you agree.

**Comment by ioggstream** [comment]
Last considerations integrated via #1334 

The point on partial representations is related on HTTP semantics and cannot be addressed by this spec.

**Comment by ioggstream** [comment]
Last considerations integrated via #1334 

The point on partial representations is related on HTTP semantics and cannot be addressed by this spec.
