### ISSUE TITLE
Digest should use http-core or rfc 723x?

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#854]
## Task

Should we base on 723x or [http-core](https://github.com/httpwg/http-core) ?
Are there changes in http-core that modify or improve Digest definition (eg. terminology, ...)?

**Comment by reschke** [comment]
Depends on publication timing.

I don't expect -core to change anything that would effect this spec.

**Comment by ioggstream** [comment]
digest references moved to http-core. #1140
