### ISSUE TITLE
Shall we use sh-binary serialization for `id-sha` digest-algoritms?

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#855]
## Hypothesis
Considering that:

1- every digest-algorithm define his own serialization method (eg. you don't need to use just b64)

2- Structured headers allow to [serialize byte-sequences](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#binary) like the following:

```
sh-binary = "*" *(base64) "*"
base64    = ALPHA / DIGIT / "+" / "/" / "="
``` 

3- the newly defined digest-algorithms `id-sha-256` and `id-sha-512` do not have a 
    predefined encoding format, so that we can chose which one to use.

We could:

- use for `id-sha-256|512` the `sh-binary` serialization

## Notes

Pro:
- compatibility with structured headers

Cons:
- syntax will be different from the (previous) sha-xxx

**Comment by martinthomson** [comment]
I think that it would be best to consider digests as octet sequences.  You can encode all sorts of stuff into one of those.

**Comment by LPardue** [comment]
I'm not sure that answers @ioggstream original question as intended. If we rephrase the question to be:

Spec says "The encoded digest output uses the encoding format defined for the specific digest-algorithm.". Presently, SHA based algorithms encode using base64 and Unixsum uses ASCII decimal-digit string. `id-sha-256` and `id-sha-512` are new digest-algorithms added in this update but presently have no defined encoding format; should they also be base64 encoded or something else?

@martinthomson are you suggesting that the encoding format be octects?

**Comment by martinthomson** [comment]
Yes, in that every digest algorithm produce a single output that is a sequence of octets and that the new SH be used to encode that.  I know that this doesn't fit with existing code, but you could carve out exceptions for legacy identifiers (and then discourage their use).

**Comment by dlongley** [comment]
It would be great to consider [Multibase](https://tools.ietf.org/html/draft-multiformats-multibase-01) (see also: https://github.com/multiformats/multibase) to solve this problem for current and future algorithms.

**Comment by LPardue** [comment]
My inner pragmatist leans toward simply using base64 encoded for id-sha-256|512. This is partly driven by the possibility of endpoints generating digests `id-sha-256` and `sha-256` with associated `content-encoding: identity`. Having different encoding formats for effectively the same thing seems weird.

**Comment by ioggstream** [comment]
@dlongley I will propose a PR to multibase so that it will add an algorithm to the iana digest-algorithm table 

In this way as soon as multihash becomes an RFC multihash will be supported for digest.

Just give me some days to write it (I'm at europython until Sunday)

**Comment by LPardue** [comment]
Extensibility options are interesting, thanks for sharing @dlongley.  The way digest algorithm currently works for encoding is clunky with each algorithm defining their base-encoding format but it sort of skirts the issue that Multibase appears to solve.

I think the extensibility story is more interesting where a future multihash digest algorithm specifies the multibase encoding. That gives people a choice of using a more flexible tool in future, or falling back to the explicit clunkiness we have today.

**Comment by ioggstream** [comment]
> Having different encoding formats for effectively the same thing seems weird.
Lucas is definitely right. I'm closing this, while we should write something in the algorithm-agility section.
