### ISSUE TITLE
alt-svc response header field in HTTP/2 frame

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#87]
Should we say what an alt-svc header field means when received over HTTP/2? Does it mean anything? Does it override a previously received alt-svc frame?

**Comment by mnot** [comment]
Discussed in Prague; no special handling, they're still valid. Clarify in document if necessary.

**Comment by reschke** [comment]
I originally raised this because of https://github.com/httpwg/http-extensions/issues/16 which talked about multiple sets of information that could be independently updates or invalidated. Now that we don't have this anymore this issue is less important.
