### ISSUE TITLE
Privacy considerations for client-requested server certificates

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-extensions#870]
If a malicious server claims support for a variety of common hostnames for which it doesn't actually possess certificates, browser clients with a long-lived connection to the attacker will probe for certificates when the user attempts to access those sites.  This allows the server to monitor user behavior during the lifetime of the connection, even without valid certificates.

One obvious strategy is to probe everything "interesting" ASAP after the ORIGIN frame, but that obviously leaks what the client considers interesting, which is its own privacy leak.

Note that a DNS lookup of claimed hostnames prior to requesting the cert prevents this attack.  Should probably recommend that clients which omit the DNS lookup never solicit secondary server certificates, but probably don't need to mandate anything.

**Comment by davidben** [comment]
In addition to monitoring user behavior, depending on client behavior (do you race two connections? fallback on error?), the malicious server could also deny access to other hostname or degrade performance.
