### ISSUE TITLE
Request `Digest` validation

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#874]
## Considering that

- Digest specs allows the receiver to skip digest validation

## We could

- Provide some method to mandate digest validation. Clearly the receiver may cheat :P 

A discussion on the subject happened here:

https://github.com/fcrepo/fcrepo-specification/issues/373#issuecomment-391833541

**Comment by LPardue** [comment]
Thanks for sharing. I only skimmed the thread but my initial opinion is that we want to define this as out of scope for the Digest refactor, but ensure that we don't prevent other from supporting their use case with some other proposal in a separate doc.

**Comment by ioggstream** [comment]
Agree.
