### ISSUE TITLE
Examples for id-sha-256 and id-sha-512

### ISSUE THREAD

**Issue by manger** [httpwg/http-extensions#880]
draft-ietf-httpbis-digest-headers includes examples of sha-256 in the Digest header value, but no examples of the two new algorithms it introduces: id-sha-256 and id-sha-512.

Examples would be extremely useful to illustrate the difference between sha-256 and id-sha-256.

**Comment by LPardue** [comment]
That sounds reasonable to me.

**Comment by ioggstream** [comment]
@manger WDYT? #883
