### ISSUE TITLE
Editorial: in structured headers rename "Strings" to "ASCII Strings"

### ISSUE THREAD

**Issue by annevk** [httpwg/http-extensions#905]
This makes it more immediately apparent that this is far more limited than strings of modern programming languages and you likely want to use a (UTF-8) Byte Sequence for representing those.

**Comment by mnot** [comment]
We already use the phrase "ASCII string" to indicate the type of many of the algorithms, so I'm afraid that this will cause some confusion.

Do you have an alternative suggestion? Or, would it be sufficient to emphasise their nature in their definition?

**Comment by annevk** [comment]
You also use "string" for a number of things that are not "String". And similar for "float" or "integer", so that's not particularly persuasive.

**Comment by phluid61** [comment]
It's not even ASCII. Quite a few of the 128 ASCII characters can't be sent in an sh-string.

**Comment by annevk** [comment]
Yes.

**Comment by mnot** [comment]
I'm not inclined to change this; we already subset integers and floats, but we don't call them e.g., "integers up to 15 digits."
