### ISSUE TITLE
[SH] Allow parameterized inner-list values.

### ISSUE THREAD

**Issue by mikewest** [httpwg/http-extensions#907]
As discussed around https://github.com/httpwg/http-extensions/issues/839#issuecomment-508367966, it would be lovely if we could address the use case raised in https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#structured-headers-dont-fit-my-data by allowing list items themselves to contain parameters. This would allow the example in the specification:

```
Example-Thing: name="Widget", cost=89.2, descriptions=(foo bar)
Example-Description: foo; url="https://example.net"; context=123,
                     bar; url="https://example.org"; context=456
```

to be written as:

```
Example-Thing:
    name="Widget",
    cost=89.2,
    descriptions=(foo;url="https://example.net";context=123
                  bar;url="https://example.org";context=456)
```

**Comment by mnot** [comment]
Hm. We put parameters on (item or inner-list), where maybe we should have just put them on item; I suspect your use case is more common than the one that's currently enabled.

Would you be against making that change (i.e., moving parameters "inside" the list, as opposed to enabling them both on the list as a whole and individual items)?

**Comment by mikewest** [comment]
> Would you be against making that change (i.e., moving parameters "inside" the list, as opposed to enabling them both on the list as a whole and individual items)?

That sounds fine to me. I, personally, don't yet have a use for parameterizing the `inner-list` itself, but I would quite appreciate being able to add parameters to the items an `inner-list` contains.

**Comment by mnot** [comment]
@bsdphk @phluid61 any concern about trying the above change?

**Comment by bsdphk** [comment]
If we keep this up, I can dust of my original proposal which had recursion :-)

As long as we can pick it apart consistently, I'm fine.

**Comment by mikewest** [comment]
> If we keep this up, I can dust of my original proposal which had recursion :-)

I'm fine with recursion, FWIW. More complexity === better. ;)

**Comment by mnot** [comment]
So to summarise, I think the proposal is:

* Allow parameters on Item
* Allow parameters on inner-list

This removes the need to make parameters specific to Dictionaries and lists, and effectively allows parameters "everywhere". This is probably a very good story for extensibility, if we document it right.

The only downside that I see is that implementations will no longer map "simple" types (e.g., integers, strings) to their analogies in-language; it'll all need to be objects, to accommodate parameters.

I think that's acceptable -- especially given the token/string schism -- but wanted to make sure everyone understood this. 

For the test suite, it means that the JSON representation of an item will probably be something like:

~~~ json
{
  "value": 12335,
  "parameters": {
    "foo": 456.78
}
~~~

and with an inner-list:

~~~ json
{
  "value": [
    {
      "value": "a",
      "parameters": {
        "foo": true
      }
    },
    {
      "value": "b"
    }
  ],
  "parameters": {
    "foo": "bar"
}
~~~

This is _verbose_, but fairly straightforward. And of course APIs can make this a lot easier with various methods (e.g., `getParameters` and the like).

What do people think? This is not a small change, so I'm likely to do it in an isolated draft version. There aren't *that* many implementations yet, so if we're going to do this, now is the time.

**Comment by phluid61** [comment]
Except that 'serializing an item' is used by param values. But that can be unpicked.

**Comment by mikewest** [comment]
SGTM.

**Comment by clelland** [comment]
I'm quite happy with that proposal -- it solves the use case that we've had with reporting, where both inner and outer list items may require parameters.

Even if reporting ends up not needing to use both levels of parameters at the same time, I'm fairly certain that parameters on either inner or outer list items will be used separately by different headers, and it should make both parsing and serialization more straightforward to describe and implement if both are allowed in the same structure.

**Comment by bsdphk** [comment]
no opinion.

**Comment by mnot** [comment]
I've created a PR #954; would very much appreciate a close review from multiple people, as it's fairly intrusive. Having said that, I think I like it.

The diff is useful, but you can also see the HTML here:
  https://httpwg.org/http-extensions/mnot-907/draft-ietf-httpbis-header-structure.html

I haven't yet updated the tests or my implementation.

**Comment by mnot** [comment]
(BTW, as I did this I noticed a number of small-ish stylistic issues in the spec; I'll address those separately)

**Comment by phluid61** [comment]
At a first (quick) read-through it looks pretty good. I'll have to find time to mash it into code to see if I notice any issues.

High level question: the combined ABNF for dictionary says:

```
dict-member    = member-name "=" member-value *parameter
member-value   = sh-item / inner-list
sh-item        = bare-item *parameter
inner-list     = "(" OWS [ sh-item *( SP sh-item ) OWS ] ")" *parameter
```

Obviously it's easy to remove `*parameter` from `dict-member`, but does that change the semantics?  Does anyone currently use it as ((key,value),params) rather than (key,(value,params)) ?

**Comment by mnot** [comment]
Ah, good catch; that `*parameter` shouldn't be there.

I don't *think* it changes the semantics; keys can't be duplicated, so there shouldn't be any conflicts, and an implementation can choose how it surfaces things.

**Comment by phluid61** [comment]
I was playing around with a regular expression parser to check the ABNF, and noticed this:

```
parameter     = OWS ";" OWS param-name [ "=" param-value ]
param-value   = sh-item
sh-item   = bare-item *parameter
```

`param-value` should be a `bare-item`

**Comment by mnot** [comment]
Merged; should be out in a new draft in the next day or two. I still need to update my implementation; @phluid61 has a PR for updates to the tests.

**Comment by CxRes** [comment]
In 2024, I have been groking the sfbis-05 draft, and it is unclear to me how recursion would work. Specifically, dictionary values can be items or inner lists (text refers to them as "array of items" which though correct is not specific), while item parameters (which are essentially a dictionary specific to the item except that they) allow only "bare" items. Inner lists themselves only allow items, so that does not nest either.

I am asking this as I have a real world use case for this with PREP. Specifically, I want to reuse existing HTTP headers as parameters for negotiating the notification content (to avoid defining new ones), which themselves might have parameters, thus my need for parameters of parameters!
