### ISSUE TITLE
alt-svc from https (1.1) to https (1.1)

### ISSUE THREAD

**Issue by reschke** [httpwg/http-extensions#91]
See <https://lists.w3.org/Archives/Public/ietf-http-wg/2015JulSep/0193.html>:

"Alternative Services MUST NOT be advertised for a protocol that is not designed to carry the scheme. In particular, HTTP/1.1 over TLS cannot carry safely requests for http resources."

...which refers to the :scheme pseudo header field in HTTP/2 (<http://greenbytes.de/tech/webdav/rfc7540.html#HttpRequest>).

As far as I recall the intention of the statement above is to avoid that when alt-svc is used to move http traffic to a TLSsy port such as 443, the alternative server gets confused about whether it's serving HTTP or HTTPS.

The clause seems to be less relevant when alt-svc is used to load-balance HTTP/1.1 http*s* traffic.

**Comment by mnot** [comment]
I think this is editorial.

**Comment by reschke** [comment]
Like that?

"Special care is needed when the use of an alternative service causes a change in the URI scheme of the transport (e.g., when HTTP traffic is transferred over an HTTPS connection). In cases like these, alternative services MUST NOT be advertised for a protocol that is not designed to carry the scheme. In particular, HTTP/1.1 over TLS cannot carry safely requests for http resources.").

**Comment by icing** [comment]
Or:
"Alternative Services MUST NOT be advertised for a protocol that is not designed to carry the scheme, for resources whose scheme differs from the Alternate Service one. In particular, HTTP/1.1 over TLS cannot carry safely requests for http resources."

**Comment by martinthomson** [comment]
I think that both could be a little problematic in the sense that they confuse scheme with protocol.  How about:

> Alternative services MUST NOT be advertised or used if the protocol for the alternative is not designed to carry the scheme. In particular, HTTP/1.1 over TLS cannot ...

**Comment by reschke** [comment]
...but that doesn't address the problem this ticket is about...

**Comment by MikeBishop** [comment]
Maybe
> ...not designed to carry the scheme, unless the alternate uses the same protocol implied by the scheme.

**Comment by reschke** [comment]
proposal from @mnot in https://github.com/httpwg/http-extensions/issues/92#issuecomment-156880299 would address this issue as well
