### ISSUE TITLE
Improve references

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#911]
## I expect

That the following references contain Section

- [ ] https://github.com/httpwg/http-extensions/blame/master/draft-ietf-httpbis-bcp56bis.md#L187 as this is quite a different approach respect to the widely used OpenAPI one.

**Comment by LPardue** [comment]
Mistakenly assumed this was related to Digest headers. What document are you raising this issue against?

**Comment by ioggstream** [comment]
@LPardue the issue is open on BCP56bis :)

**Comment by mnot** [comment]
@ioggstream this is specifically about standard APIs, not single-origin APIs.
