### ISSUE TITLE
Structured Headers and JavaScript

### ISSUE THREAD

**Issue by annevk** [httpwg/http-extensions#913]
For https://github.com/whatwg/fetch/issues/930 I was trying to think of a natural mapping and I see a potential problem with String and Token. A natural way to do this in JavaScript would be to treat both as a JavaScript string and depending on the content serialize as one or the other. However, this would mean that if something takes a String that could also be represented as a Token, it gets a Token. And unless consumers are always required to support that, there's a problem.

An alternative here is that we do something less ergonomic, but that'll likely end up favoring one of these over the other.

(Depending on the outcome of #907 for the getter side we might need a wrapper Item object of sorts that could indicate whether something is a string or token and you could use the same on the setter side, but passing a string when setting should probably work as well.)

**Comment by reschke** [comment]
> However, this would mean that if something takes a String that could also be represented as a Token, it gets a Token. And unless consumers are always required to support that, there's a problem.

I think we should required consumers to support that.

**Comment by mnot** [comment]
This was already discussed; see #790. 

Basically, you'll need to wrap Token with some sort of object to distinguish it from string.

@reschke this is not ABNF-defined headers, it's new. There are use cases where the difference is semantic.

**Comment by reschke** [comment]
Well. It's still ABNF, but I understand that you're referring to the conventions wrt token/quoted-string.

What I wanted to say is that this is a good convention, and it doesn't seem to be a good idea not to use it here as well.

In which cases would there be a semantic difference?

**Comment by mnot** [comment]
How would you feel if we had a term of art that indicated that they were isomorphic?

**Comment by reschke** [comment]
"token" and "quoted-string" isomorphic? Sounds good to me.

**Comment by mnot** [comment]
To be clear -- do not specify them as isomorphic, but define language that can be referenced easily by specifications that want to make them so.

**Comment by reschke** [comment]
Could you explain why this can't be the default?

**Comment by mnot** [comment]
We've talked about this a lot, Julian. E.g., Cache-Control directives, remember that? There are many examples of headers that depend on one for or another, and the intent of SH is to make it possible to back-port some existing headers optimistically.

Allowing specifications to nominate values as token-or-string is a good compromise position, I think.

**Comment by reschke** [comment]
Cache-Control has a related issue, and we haven't resolved it yet.

I'm kind if surprised that backporting for existing field values suddenly is a goal again, though.

**Comment by phluid61** [comment]
re: isomorphism

Do you mean like defining an ABNF rule and/or "virtual" type that can be either string or token?

**Comment by mnot** [comment]
yep

**Comment by phluid61** [comment]
Feels a bit like "you shouldn't do this, but we know you will, so here's how".

Immature thought: is it time to rethink strings so the hierarchy goes Binary>String>Token, and you can freely transform up, but only down if the subset constraints match? (I know that Binary is a byte sequence, not a string, and :something something: character encoding...)

**Comment by mnot** [comment]
I think there are valid cases for it; indeed, I came across one the other day in an SH-using spec.

Re: hierarchy -- I'd really rather not rework things to that extent now, unless there are significant benefits.

**Comment by phluid61** [comment]
How important is it to actually document this pairing here, now?  We aren't providing a schema specification (beyond top-level data types).  Like, we aren't making it easy to say "a list of all integers", or "a list of lists of all strings", or "a parameterised item where for any parameter with param-name of `q` the param-value should be a `float`"; so do we need to make it easier to say "string-or-token" in similar places?

Is that the only pairing that needs special treatment?  Does nobody care about integer-or-float?

Also, which header specs require it? The push so far _seems_ to be driven from implementations.

**Comment by mnot** [comment]
I'm thinking about something that's just a documentation convention, not something that would change a typical SH implementation (unless it specifically wanted to present an abstraction for it). This is more for convenience of spec authors.

**Comment by phluid61** [comment]
Me too, that's why I'm wondering where it's actually come up.

**Comment by annevk** [comment]
It came up in how to design the JavaScript API as it'll likely favor one over the other. And I think you're right that this also applies to serializing integers and floats (unless we require BigNum for the former and Number for the latter, but that seems to be unlikely the API that folks want).

**Comment by phluid61** [comment]
As long as someone is allowed to say "must be a Token" in one place, and someone is allowed to say "must be a String" in another, there's not really anything that can be done.

**Comment by annevk** [comment]
Yeah, that'll lead to favoring one type over another or an extremely awkward to use API. Having the types be isomorphic would be much better. For integers and floats it'd also seem better if we ended up with JSON's way of dealing with that.

**Comment by phluid61** [comment]
Or you could use Ruby ;)

**Comment by phluid61** [comment]
I think it's enough to say that JavaScript doesn't have a native type that corresponds with token, so there's no natural mapping from something like a js string.

**Comment by mnot** [comment]
If #907 goes forward (and it looks like it will), I think this will be overcome by events, since that will effectively require implementations to move away from a direct mapping to "simple" types in favour of something like objects.

**Comment by mnot** [comment]
#907 did indeed happen, so I think this is OBE.
