### ISSUE TITLE
Header for considering the request body as part of the cache key

### ISSUE THREAD

**Issue by asbjornu** [httpwg/http-extensions#942]
As requested by @reschke in httpwg/http-core#250, I'm creating an issue for the specification of a header that signifies to cache intermediaries that the request body should be a part of the cache key so the response from a `POST` request can be cached safely.

As I discussed in the HTTP Workshop in May, `GET` with a body is in use by large vendors such as Elasticsearch (see elastic/elasticsearch#16024) and their interpretation of the spec being that this is "just fine" (see https://github.com/elastic/elasticsearch-php/issues/737#issuecomment-378590773). Language is hopefully being added to the spec that makes this not seem "just fine" anymore, but I think we also need to provide a solution to the specific problem of not wanting to jam JSON into a URL to be able to use the `GET` keyword. `POST` should therefore be usable with search-like semantics without sacrificing caching.

**Comment by mnot** [comment]
This is overcome by events, thanks to the adoption of safe-method-with0body.

**Comment by mitar** [comment]
I think this is the reference @mnot is making: https://datatracker.ietf.org/doc/draft-ietf-httpbis-safe-method-w-body/
