### ISSUE TITLE
SEARCH method

### ISSUE THREAD

**Issue by asbjornu** [httpwg/http-extensions#943]
As requested by @reschke in httpwg/http-core#250, I'm creating an issue for the specification of the `SEARCH` method as an alternative to `POST`, making search requests safe, idempotent and cacheable.

As discussed in the HTTP Workshop in May, `GET` requests with a body is in use by large vendors such as Elasticsearch (see elastic/elasticsearch#16024) and their interpretation of the spec being that this is "just fine" (see https://github.com/elastic/elasticsearch-php/issues/737#issuecomment-378590773). Language is hopefully being added to the spec that makes this not seem "just fine" anymore, but I think we also need to provide a solution to the specific problem of not wanting to jam JSON into a URL to be able to use the `GET` keyword.

While `POST` with the header defined in #942 would help, `POST` is still an unsafe method that poorly reflects the safe, idempotent semantics of search-like operations. I therefore argue that a a `SEARCH` method is needed to have a safe, idempotent method with explicit caching support, in opposition to `POST` which explicitly is **not cacheable**.

The [current draft](https://tools.ietf.org/html/draft-snell-search-method-01) for `SEARCH` is written by @jasnell, but I hope he would be willing to hand over the spec to someone else.

**Comment by MikeBishop** [comment]
I'm not sure that an issue is the right way to track this, because this would be a substantial new addition to a draft that's not actually supposed to define anything new.  I would think the right venue for this is reviving the draft and/or writing a new one that succeeds it, then taking it to the working group for potential adoption.

**Comment by jasnell** [comment]
Absolutely willing to hand it over! Would love to see this move forward, just don't have any time to move it forward myself.

**Comment by asbjornu** [comment]
@MikeBishop, this issue got a reply from both you and @jasnell, so I'd say its creation is an absolute success so far! 🎉 😄 I agree it needs proper stewardship, though, so now that James has agreed to hand it over, we "just" need someone who knows how to write an I-D to take it and to do exactly as you suggest and revive/rewrite the draft.

**Comment by mitar** [comment]
I think `SEARCH` is to specific. What about `FETCH` or `RETRIEVE`?

**Comment by mnot** [comment]
See https://github.com/httpwg/admin/issues/2.
