### ISSUE TITLE
EU Cookie Law: Mechanisms enabling user agents to aid in compliance absent

### ISSUE THREAD

**Issue by ttacker** [httpwg/http-extensions#945]
A European Union (EU) [directive](https://en.wikipedia.org/wiki/Directive_(European_Union)) requires member states to achieve a result, without dictating specific means. In contrast, EU [regulations](https://en.wikipedia.org/wiki/EPrivacy_Regulation_(European_Union)) are binding law in all member states. Recital 25 of the Preamble and Article 5(3) of the [ePrivacy Directive](https://en.wikipedia.org/wiki/Privacy_and_Electronic_Communications_Directive_2002) (ePD)--often referred to as the EU Cookie Law--regulate the use of cookies. The [ePrivacy Regulation](https://en.wikipedia.org/wiki/EPrivacy_Regulation_(European_Union)) (ePR) is expected to repeal and replace the ePD in 2019, but it's expected the ePR will regulate the use of cookies in substantially the same manner as the ePD.

To paraphrase [one summary](https://www.iubenda.com/en/help/5525-cookies-gdpr-requirements), the EU Cookie Law requires the following:

- Unless an exempt type of cookie, informed consent, based on explicit affirmative action, before storing a cookie on the user's device.
- Conspicuously providing the option for obtaining informed consent.
- A means for withdrawal of consent.
- Ability to prove consent occurred, even if subsequently withdrawn.
- A guarantee, via prior blocking, no tracking performed before consent.
- Informing users of the use of third-party cookies.
- Stating the category and purpose of third-party cookies, even if not listed individually.
- Linking to relevant third-party privacy/cookie policies.

[RFC 6265](https://www.rfc-editor.org/info/rfc6265) doesn't include mechanisms enabling user agents to aid in compliance with the above requirements, and this has resulted in presentation of inconsistently placed, and inconsistently formatted, cookie banners worldwide. Such inconsistency degrades user experience, works against conspicuousness, and is annoying to the point that some have attempted to create [workarounds](https://cookiesok.com/) to address the lack of desired user agent functionality. Internet Draft (I-D) [draft-ietf-httpbis-rfc6265bis](https://datatracker.ietf.org/doc/draft-ietf-httpbis-rfc6265bis/) proposes to obsolete RFC 6265; however, it also fails to address the issues raised above.

Attributes, such as the following, could be added to the Set-Cookie Header:

- Category (Allows grouping for purpose of category consent.)
- Purpose (Provides information to ensure consent is informed.)
- Exempt (Informs user agent not to prompt for consent.)
- Third-Party (Informs user agent to label cookie as third-party.)
- Policy (Allows linking to third-party privacy/cookie policy.)

Each user agent could then prompt users for consent in a consistent manner across all servers that implement the standard. Consent could be requested individually, for all cookies all at the same time, or selectively (depending on capabilities of the user agent.)

If permissible, such attributes may eventually enable user agents to allow users to provide advance consent, via settings, for selected categories of cookies, for selected purposes, on selected domains. A list of allowable categories and purposes may also need to be standardized before anything other than the ability to accept all cookies for selected domains would be feasible.

Due to the requirement that servers be able to prove consent occurred, user agents would need to be required to provide a response to that effect, and servers would need to be able to reliably assume requested cookies were not stored if no such response is received. Servers would need a mechanism to ensure older user agents don't automatically store the cookies without prompting for consent, as the existing Set-Cookie Header would be used.

I'm not yet sure what withdrawal of consent might look like.

**Comment by mnot** [comment]
Hi Timothy,

Thanks for writing that up (and welcome to the group). Personally, I agree very much and have been talking to some folks about doing something like this as an extension to cookies. 

However, while there is an emerging set of values that are commonly used on sites -- which is great -- they won't be effective unless they're closely tied into the relevant legislation, and that means a fair amount of work, and engagement with all of the relevant parties.

Previous experience (e.g., P3P, DNT) has shown that doing so takes a considerable amount of time, and has a non-trivial amount of associated risk. Getting buy-in to this approach from the legislative bodies / regulators beforehand can lend considerable weight (which was lacking in both of those examples), so personally my focus is on educating those folks that this is possible, before actually specifying it.

Beyond all that, the scope of work for 6265bis was pretty tightly constrained when we started it; we nominated a set of drafts (linked to [here](https://github.com/httpwg/http-extensions#rfc6265bis)) that were to be included, along with various errata and bug fixes. As such, this is out of scope for this draft. 

On top of that, we've been having trouble meeting those more modest goals, and I'm concerned that adding a significant new feature like this would put the document's delivery at yet more risk.

So, I'm closing this issue as out of scope for _this_ draft. That doesn't mean we might not try to tackle it in a different document, under the right conditions. 

Thanks for raising it.
