### ISSUE TITLE
Digest and Caching

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#949]
## I expect

To clarify relations between Digest and Caching.

- [x] #936 
- [x] #940 

Moreover address  Digest behavior with:

- [x]  `If-Modified-Since` and `304` with an empty body: do we have all the relevant metadata to compute and reply with the digest?
- [ ] Intermediary caches

**Comment by ioggstream** [comment]
@mnot WDYT ^

**Comment by mnot** [comment]
I need to catch up with this spec -- will comment before Singapore (I hope).

**Comment by LPardue** [comment]
@mnot friendly ping

**Comment by mnot** [comment]
Regarding #936, this text is very odd:

> The resource is specified by the effective request URI and any validator field contained in the message.

I _think_ [this text](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#identifying.payload) might help. I.e., you want to say that Digest applies to the selected representation [ref] of the resource corresponding [ref] to the message it occurs within.

**Comment by ioggstream** [comment]
@reschke  question: imho if  a server returns  Digest in a "304 not modified" response, it must explicit all necessary representation metadata (eg. content-type, content-encoding) used to compute the Digest value. Does it sound reasonable to you? Do we have to state it in the spec?

**Comment by mnot** [comment]
_Please_ avoid re-specifying how other parts of HTTP work -- it only introduces errors.
