### ISSUE TITLE
Not maximum lifetime for server opt-in preferences specified

### ISSUE THREAD

**Issue by amtunlimited** [httpwg/http-extensions#957]
The client hint spec does not seem to specify if there's a maximum lifetime for the origin opt-in preferences. There seem to be spec that the data should be cleared when site data, cookies, cache, etc. are cleared, but barring that should there be some sort of reasonable limit?

**Comment by amtunlimited** [comment]
I'm new to this process; I'm not sure how to add the "client-hints" label

**Comment by yoavweiss** [comment]
@martinthomson thoughts? You were the one pushing for an implicit lifetime. Do we want to cap it?

**Comment by martinthomson** [comment]
I think that what you should say is that the browser can discard this state, but it should do so only when it drops all other state for the origin (e.g., when clearing cookies).  Modeling this as part of origin-bound state like that is far easier to reason about and more reliable for sites.

**Comment by yoavweiss** [comment]
We already have "Implementers SHOULD support Client Hints opt-in mechanisms and MUST clear persisted opt-in preferences when any one of site data, browsing history, browsing cache, or similar, are cleared."

Do we need to also add something around origin-bound state to that?

**Comment by snyderp** [comment]
As Safari is already capping script-set storage lifetime to 7 days (Brave does w/ cookies, plans to do for all storage too), and some other vendors have hinted at the same, I suggest a max lifetime of 7 days.

Especially given the possibility that these values can be tracking vectors (discussed in the fingerprinting conversation).

**Comment by yoavweiss** [comment]
The text above means that browsers that choose to set max lifetime to storage/cookies will MUST do the same for Client Hints. I don't think we need to bake in the specific max age that some UAs chose into an IETF draft.

**Comment by snyderp** [comment]
I hear what you're saying, but the purpose of a standard is not to say "some people will act X and some folks will act Y", its to bring X and Y as close as possible.  What is the use case for a lifetime of > 7 days?  Like any cache value, its perf utility decreases as life time increases, but the privacy risk stays constant.

Put differently, what is the concern w/ a maximum value, to at least partially constrain the privacy risk?

**Comment by yoavweiss** [comment]
Sounds like the restriction you're talking about is of larger scope than Client Hints, and applies the origin storage in general. I suggest you'd try to enforce those specific values e.g. on session cookies, and Client Hints will follow out of that.

At the same time, I was under the impressions that when we [removed the explicit lifetime](https://github.com/httpwg/http-extensions/pull/878), we tied the lifetime of Client-Hints persistence to session cookies, but looks like we did not. I'll submit a PR on that front.
