### ISSUE TITLE
Specific hints might not be useful on all requests

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#963]
Client hints might be most useful in some types of requests and not others.  Clients might choose to limit which hints are sent with requests based on contextual information.

For instance, hints that apply to presentation like DPR are less applicable to resource loads for javascript or json objects.  Though I'm sure that someone can come up with a use case for almost anything in almost any context, the cost (#962), small as it might be, is probably not always justified in the aggregate.  So the draft should probably say that *for a given hint* opting in to clients hints might be either:

1. constrained by the UA to apply only to similar requests to the one where the hint has been requested, or 

2. only sent for requests made from a specific application context.

For (1), this is something that can be applied generically in specifications (like the fetch spec).

For (2), the definition of each client hint might provide suggestions.

This is probably something that the fetch specification changes need to consider more carefully, but this specification might lay some groundwork for that.

**Comment by yoavweiss** [comment]
> 1. constrained by the UA to apply only to similar requests to the one where the hint has been requested, or

Client Hint opt-ins are only applicable on top-level navigation responses, (due to privacy and simplicity considerations), so that doesn't seem feasible.



> For (2), the definition of each client hint might provide suggestions.

That makes sense, and we can add some text to this draft to indicate that they can. (and as you say, have some Fetch flag that enables features to enable/disable CH for certain request destinations)

**Comment by eeeps** [comment]
Re: adding destination/context to the opt-in model...

Should this be something that the...

1. ...definition of the hint decides (e.g., the DPR hint definition would mandate that it is only sent for fetches whose destination is "image" or "video")
2. ...UA decides, contextually
3. ...author decides, as a part of their opt-in

?

I'd argue for a set of specified defaults (1), which authors can override to meet their edge cases, if need be (3). I'm having a hard time thinking through how the UA would make this decision on its own (2).

**Comment by yoavweiss** [comment]
@eeeps - I don't think that we need to dive into those details in the IETF draft, but I imagined something along the line of (1). (3) seems to throw complexity on the syntax/user, so I'd love to see concrete use cases before we go that route.

This was closed by https://github.com/httpwg/http-extensions/pull/985, but I don't have permissions to actually close it... @igrigorik - can you click the button?

**Comment by igrigorik** [comment]
Yep, resolving.
