### ISSUE TITLE
A client requests an unsupported Digest, the server MAY reply with a 400

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#968]
I think this example demonstrates the under specification of the Want-Digest header. Does it work as 

1. A discovery mechanism that allows the client to probe the server for the set of digests it supports (client and server specifically)
2. A unilateral advertisement of the algorithms supported by the sending endpoint

But to try and understand if it is 1) or 2) I see nothing in RFC 3230 that prescribes behaviour like this but I may well have missed it. Either way I don't think we should be putting normative text (MAY reply) in the section header. 

So lets decouple things.

I'm assuming in this example case that we operate under the model that server is allowed to respond with a 4xx under any circumstance. But specifically in this case the server is unwilling to accept requests with `sha` algorithm.

Then next it advertises the list of algorithms it can generate? In which case, a header names Want-Digest is not very inutuitive. It seems to act asymmetrically, while we are expending a lot of effort to understand and describe how Digest can be used in Request and Response.

**Comment by ioggstream** [comment]
> I don't think we should be putting normative text (MAY reply) in the section header.

agree, will fix it after IETF106.

> I see nothing in RFC 3230 that prescribes behaviour like this

it's not a prescribed behavior, as rfc3230 is not very rigid.
imho it's a possibility which we have in rfc3230 that we may use to implement some sort of negotiation. 

the alternative would be that the server responds with a sha-256 digest 
that the client won't be able to process, as cited in rfc3230#4.3.2

> A sender MAY send an instance-digest using a digest-algorithm without
   knowing whether the recipient supports the digest-algorithm, or even
   knowing that the recipient will ignore it

**Comment by LPardue** [comment]
> imho it's a possibility which we have in rfc3230 that we may use to implement some sort of negotiation.

Our job with this draft is to update the status quo. So we need to be really careful not create new modes or capabilities, especially if they end up being somehow incompatible with how people actually use Want-Digest today. So my problem is that this example is quite suggestive of a protocol design aspect but has no useful text. And trying to write up negotiation is likely to hit barriers or just be ignored in extant deployments.  

I'd be happier with a separate example that shows a 4xx response that includes the digest of the error body (i.e. the returned error page). I'd be happy with a stand alone example that shows a request with Want-Digest and a response that includes no Digest and no Want-Digest  because of the algorithm mismatch. 

Given the timeframes lets punt this to IETF 106.

**Comment by LPardue** [comment]
This also relates to 

> 6. What changes in `Want-Digest`?

>   We allow to use the `Want-Digest` in responses to advertise the supported digest-algorithms
   and the inability to accept requests with unsupported digest-algorithms.

**Comment by ioggstream** [comment]
The current situation on this thread:

- we did not add further normative parts on want-digest

> a stand alone example that shows a request with Want-Digest and a response that includes no Digest and no Want-Digest because of the algorithm mismatch.

- we have examples showing two legitimate ways of managing unsupported algorithms in a way which is similar to the [Negotiation of Content-MD5](https://tools.ietf.org/html/rfc3230#section-5) proposed in RFC3230: 
   * one ignoring Want-Digest and returning 200 + Digest (WRT the client, this is exactly the same of returning no Digest), 
   * one returning the supported Want-Digest algorithms with a 400 error


> I'd be happier with a separate example that shows a 4xx response that includes the digest of the error body (i.e. the returned error page). 

- we have another example showing that Digest of error responses refers to the error payload

About what changes in Want-Digest: probably the only thing is the deprecation of contentMD5, because all the examples describe behaviors which are legitimante under RFC3230

**Comment by LPardue** [comment]
> About what changes in Want-Digest: probably the only thing is the deprecation of contentMD5, because all the examples describe behaviors which are legitimante under RFC3230

IIUC all we need to do is update the example `Want-Digest: SHA-512;q=0.3, sha-256;q=1, md5;q=0` to remove/replace the `md5` algorithm. I don't think we need to explicitly mention this because the example is non-normative, and the deprecation of MD5 is already covered. Or maybe I'm misunderstanding?

**Comment by ioggstream** [comment]
I just added that `md5;q=0` to express that the sender does not want md5, but if this creates confusion we can remove it.

Feel free to edit the PR @LPardue
