### ISSUE TITLE
Computing Digest in requests

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#970]
## Uniform digest request semantic

While discussing #923 @reschke made the following consideration

> I just don't think that it would be a good idea to vary the semantics based on the request method. 

In this issue we will gather some examples and considerations so to investigate whether  
digest in requests should be computed on the request body.

**Comment by LPardue** [comment]
Does this need fixing, or can we close with no action?

**Comment by ioggstream** [comment]
I'll add a FAQ and close.

**Comment by ioggstream** [comment]
IMHO: we should find a better name for this issue.

- the digest semantic is always the same: digest is computed on the selected resource representation data;
- digest computation depends on method and headers, because they alter the meaning of the payload body (eg. with partial representations).

**Comment by ioggstream** [comment]
Me and Julian @reschke exchanged some email but the point is still open.

Julian suggests that in requests, Digest should always be computed on the payload-data, independently of the request semantic (eg. even if the request contains a partial representation). This would make it easy its implementation.

I understand this position, but I think that it is not aligned with RFC3230 which introduces Digest because Content-MD5 definition was inconsistent respect to partial representations. Note that this I-D defines `representation-data-digest` which is potentially unrelated to the `payload-data`.

If HTTP forbids partial representations in requests though, we will get @reschke behavior without the need of changing the specification; otherwise we really need @mnot / chair support.

**Comment by ioggstream** [comment]
@LPardue about a new method accepting Content-Range in requests  https://github.com/httpwg/http-core/pull/620/files

**Comment by LPardue** [comment]
Discussion at the last interim seemed to indicate that a "Content-Digest" would go some way to unblocking this issue, a PR will come later this week.

**Comment by ioggstream** [comment]
fixed via #1543
