### ISSUE TITLE
Add capability for sending HTTP metadata (trailer fields) in mid-stream

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-extensions#986]
For a very long time (since early 1995) there have been various attempts to send metadata in parallel with the request or response bodies. The use cases have ranged from group chat to chained digital signatures to performance metrics to long download checkpoints to a heck of a lot of other things that I pretend to no longer remember for sanity purposes.

Fixing that in HTTP/1.1 was only possible within chunked extensions. For a variety of reasons that had nothing to do with the use cases, chunked extensions didn't work well over intermediaries and the chicken never hatched. Nevertheless, they did work over HTTP/1.1 when the applications had control over both sides of a connection. I vaguely recall such metadata being present in HTTPng as well.

I would like for HTTP/2 to have a mechanism for communicating metadata (like trailers) in mid-stream, both for requests (e.g., priority) and responses (e.g., chained sigs).

I believe that this can be done with an extension frame type that carries trailer data, just like HEADERS, but that doesn't imply the end of DATA. However, I don't really have an opinion on what is the right way to do this in HTTP/2. I'd appreciate if people more familiar with HTTP/2 extensions could choose the best specific syntax.

This is not a semantics change for HTTP because the fields are just optional trailers that arrive early. A recipient that is not prepared to handle these fields, for whatever reason, can discard them in the same way as trailers, as specified in http-core [Semantics](/httpwg/http-core/draft-ietf-httpbis-semantics-latest.html).

Related to quicwg/base-drafts#3265

**Comment by royfielding** [comment]
Use cases:

- [progress meter](https://datatracker.ietf.org/doc/draft-lnageleisen-http-chunked-progress)
- midstream timing, like [server timing](https://www.fastly.com/blog/supercharging-server-timing-http-trailers)
- priority updates
- non-critical-path metadata (reduced latency vs headers)
   - [alternates](https://tools.ietf.org/html/draft-ietf-http-alternates-01) (reactive content negotiation)
   - [link preload nopush](https://www.w3.org/TR/preload/#server-push-http-2)
   - metadata determined while sending body
- long poll metadata
     - chained signatures
     - related resource notifications
     - changed-while-sending notifications
     - "typing..." notifications
     - application-level backpressure

**Comment by PiotrSikora** [comment]
There is the [HTTP/2 METADATA draft](https://docs.google.com/document/d/1DsPjl6qWxhcF28vzJey0xQJ2O2eRKHv7CBXt3EZyDjc/edit#heading=h.49cyuw1fzpul), which is implemented in Envoy (see: https://github.com/envoyproxy/envoy/issues/2394), but I'm not sure what's the status of standardizing it. cc @birenroy @soya3129

**Comment by royfielding** [comment]
Oh, cool, that is exactly what I was thinking of (even the same frame type name). The only thing we would need to add is the semantic model of being equivalent to trailers.

**Comment by LPardue** [comment]
Thanks for sharing @PiotrSikora this is pretty interesting. 

> The payload contains a block of key-value pairs, encoded using the HPACK Literal Header Field Never Indexed representation. 

This is the first instance that I've seen that constrains the behaviour of a HPACK-related frame, I really like that! It would be interesting to understand the motivation behind the constraint, in order to understand how HTTP/3 METADATA would map to QPACK .

On a completely different topic, the document says

> A METADATA frame with a stream ID of 0 represents connection-level metadata.

I'm curious what is the definition / use case for connection-level metadata? That seems to be something different than what Roy is asking for.

**Comment by royfielding** [comment]
It is probably for performance metrics applicable to the mesh in general as opposed to a specific request/response stream. It makes sense to spec it that way even if there is no immediate use case.

**Comment by royfielding** [comment]
More like an OPTIONS push.

**Comment by PiotrSikora** [comment]
> This is the first instance that I've seen that constrains the behaviour of a HPACK-related frame, I really like that! It would be interesting to understand the motivation behind the constraint, in order to understand how HTTP/3 METADATA would map to QPACK.

This constraint was added to simplify adding this to the existing implementations (i.e. to avoid messing with the HPACK dynamic table).

> On a completely different topic, the document says
> 
> > A METADATA frame with a stream ID of 0 represents connection-level metadata.
> 
> I'm curious what is the definition / use case for connection-level metadata? That seems to be something different than what Roy is asking for.

This is mostly about endpoint and/or constant metadata (e.g. peer's identity). It would be wasteful to repeat that metadata in each request/stream, so it's bound to a connection and all requests/streams inherit it.

Yes, our use case is slightly different from what Roy is asking for. Notably, our HTTP/2 METADATA is intended to be used to carry metadata within internal infrastructure, and the frame is not forwarded to the client, but we can make it work for both cases.

**Comment by PiotrSikora** [comment]
cc @alyssawilk, FYI

**Comment by vasilvv** [comment]
I have a few questions.

1. What does "semantic model of being equivalent to trailers" mean here?
1. Would the proposed frames require a new form of flow control?
1. Are the proposed frames supposed to be associated with a specific position in HTTP response body?
1. How would this interact with caching?

**Comment by mnot** [comment]
Closed in favour of https://github.com/httpwg/http-core/issues/313
