### ISSUE TITLE
The best use for `*`

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#991]
I'm running my SH implementation against the HTTP Archive dumps (400,000,000+ HTTP requests) to see how the [Directly Represented Fields](https://mnot.github.io/I-D/binary-structured-headers/#direct) from BSH parse in something like the real world.

It looks like some headers are failing because `*` is commonly used in things that are parsed as tokens; e.g., the `Accept*` headers, and `Access-Control-Allow-Origin`. 

If we were to use a different character to delimit Byte Sequences, we could include `*` in Token (necessarily as a first character, as well as in the rest, I assume).

Worthwhile? If so, what should we use for Byte Sequences?

**Comment by martinthomson** [comment]
`token` (via `tchar`) already allows `*`, but not as a first character.

'%' is short in HPACK and unlikely to trigger funny handling, but maybe it will conflict with pct-encoding to start.

'=' has the virtue of being already allowed.  It has the drawback of causing byte array parameters to look funny (`x==AA===` for instance).  Interestingly, it makes removal of padding easier (base64 padding is silly).

**Comment by mnot** [comment]
How about `:`? I don't' think `=` is a good idea; if an implementation enforces padding (which we caution against, but do not prohibit), it's confusing.

**Comment by mnot** [comment]
Checking with @mikewest @jyasskin - any issues changing byte sequence delimiters from `*` to `:`?

**Comment by mnot** [comment]
(the only conflicting use that comes to mind ATM for `:` is that if someone wants to refer to H2 pseudo-headers like `:scheme` in a field that uses tokens, they'll be out of luck. I think that's OK, because _existing_ fields that take header names as a list-of-tokens don't refer to pseudo-headers, and new fields can be defined as lists of tokens-or-strings.

**Comment by phluid61** [comment]
🎨🖌️ `$ABC=$` is free
