### ISSUE TITLE
Optional Dictionary values

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#992]
I'm running my SH implementation against the HTTP Archive dumps (400,000,000+ HTTP requests) to see how the [Directly Represented Fields](https://mnot.github.io/I-D/binary-structured-headers/#direct) from BSH parse in something like the real world.

A number of headers are failing because they have valueless dictionary members; e.g., `Cache-Control`, `Pragma`, `Surrogate-Control`.

It should be pretty easy to accommodate these, as we already have optional values on parameters.

**Comment by mnot** [comment]
PTAL at the PR, especially the note about using True for missing parameter values.

**Comment by mnot** [comment]
Ping @bsdphk @phluid61

**Comment by phluid61** [comment]
Seems like a reasonable change. I'm happy to remove the 'null' from parameters too.

**Comment by bsdphk** [comment]
(already OK'ed in the PR)
