### ISSUE TITLE
Tabs?

### ISSUE THREAD

**Issue by mnot** [httpwg/http-extensions#998]
Right now we use OWS, and #983 suggests moving from SP to RWS for inner list separation.

Should we allow tabs in SH? Error on them? 

If we want to allow them, 983 makes sense, as it's more consistent. However, we'll need to test for tabs...

**Comment by phluid61** [comment]
What's the reason to allow tabs? Compatibility with current headers? Do actual tab characters show up in the wild that often?

**Comment by mnot** [comment]
We had them in there because we were reusing OWS, not purposefully. AFAICT they don't appear in the wild much at all. So +1 for #1002.
